### ISSUE TITLE
Update build not to be hard-coded to require brew on linux

### ISSUE THREAD

**Issue by hengestone** [YugaByte/yugabyte-db#1]
Use cmake to detect library dependencies  and fail if not found.

**Comment by mbautin** [comment]
@hengestone Great point, we'll definitely look into this! The reason to introduce Linuxbrew was that CentOS is our primary target production platform, but the default toolchain on CentOS 7 is quite outdated. And it turns out that Linuxbrew has a pretty recent Boost version as well. Building without Linuxbrew on CentOS might still be challenging, but we might be able to build without it e.g. on a recent version of Ubuntu. What platform are you trying to build on, and what does your toolchain look like, by the way?

**Comment by hengestone** [comment]
Totally understood - there just should be an alternative for environments that are more up to date and able to install newer packages. I'm on Ubuntu (17.10), which is used by a large majority of cloud platforms. See e.g. [zdnet](http://www.zdnet.com/article/ubuntu-linux-continues-to-rule-the-cloud/)

**Comment by mbautin** [comment]
@hengestone We have made changes to our build script and YugaByte DB should now build on Ubuntu 17.10. Please give it a try when you have a chance and let us know how it goes! By the way, at this point, we're still doing all of our official testing and releases on CentOS, but the resulting Linux package works on both CentOS and Ubuntu.

**Comment by hengestone** [comment]
Thanks!

The build process gets a lot further now. I'll file a separate bug for the compile failure.
