### ISSUE TITLE
[docsdb] Table level TTL not re-claiming disk space.

### ISSUE THREAD

**Issue by mheer9** [yugabyte/yugabyte-db#10012]
Rows not being purged permanently when they expire via table level TTL. Even after compaction.

The test I ran in YCQL

Create a table with table level TTL
Insert rows periodically (400k)
Wait fr rows to expire - approx 200K expired as expected, as no longer returned via SELECT statements.
Ran a flush table, then compact table, but table size remained the same.
I then altered the table to have a longer TTL
The previous rows that expired, where visible again via SELECT statements.

**Comment by kmuthukk** [comment]
If the compaction is done too soon - within this setting (15 mins / 900 secs by default) then the above behavior is not surprising since we keeping older versions of rows for 15 mins (for MVCC and to support long-running transactions).

```
$ git grep timestamp_history_retention_interval_sec | grep DEFINE
src/yb/tablet/tablet_retention_policy.cc:DEFINE_int32(timestamp_history_retention_interval_sec, 900,
```
Can you try doing the yb-admin compact one more time (after 15 mins) to see if the rows are still around?

**Comment by mheer9** [comment]
This issue can be closed, I tested again, waiting at least "timestamp_history_retention_interval_sec" after the rows expired before flushing the table and running a compaction.
In my case this was 900 secs (15 mins).
Space was re-claimed and all rows purged.

I will relay this to the customer.
