### ISSUE TITLE
ALTER TABLE ADD CONSTRAINT UNIQUE for temporary table fails

### ISSUE THREAD

**Issue by qvad** [yugabyte/yugabyte-db#10098]
```
CREATE TEMP TABLE IF NOT EXISTS t3(c0 inet  DEFAULT ('206.37.67.253') UNIQUE NOT NULL, c1 money ) ON COMMIT DELETE ROWS ;
ALTER TABLE  ONLY t3 ADD CONSTRAINT q UNIQUE(c0);
```

will fail with 
```
[XX000] ERROR: access method "lsm" only supported for indexes using Yugabyte storage
```

**Comment by tedyu** [comment]
I have a tentative patch. Will publish after sync'ing with Jason.

**Comment by jaki** [comment]
In upstream postgres, I believe table always uses btree (since there doesn't seem to be any option to change the access method).  Therefore, unique constraint can also assume to be btree.

For Yugabyte, table can be btree (temp table) or lsm (otherwise).  The logical fix is to use the table's access method when creating the unique constraint index.

From the grammar perspective, I see no way to specify access method for unique constraint using ALTER TABLE, but there is a way if creating an exclude constraint: `EXCLUDE [ USING index_method ]`.  However, one hack that might work is creating a unique index with the proper access method then adding altering table to add that index as constraint:

```
CREATE TEMP TABLE IF NOT EXISTS t3(c0 inet  DEFAULT ('206.37.67.253') UNIQUE NOT NULL, c1 money ) ON COMMIT DELETE ROWS ;
CREATE UNIQUE INDEX myidx ON t3 (c0); -- uses btree by default since it's temp index
ALTER TABLE ONLY t3 ADD CONSTRAINT q UNIQUE USING INDEX myidx;
```

That's the workaround while a proper fix is made.
