### ISSUE TITLE
[docdb] Update DocDBCompaction filter with respect to tablet key bounds and special records

### ISSUE THREAD

**Issue by ttyusupov** [yugabyte/yugabyte-db#10162]
We now have special “apply state records” in regular RocksDB.
These records will be filtered out from post-split tablets by compaction filter: https://github.com/yugabyte/yugabyte-db/blob/0afb884bca157603a8708d9cc41209f945d70071/src/yb/docdb/docdb_compaction_filter.cc#L83

We use these special records only for committed transactions and remove these records would cause silent loosing of all unapplied data for affected transactions.

It will happen only in case of tablet restart, but it could be the case for the splitting since we could start child tablets during apply of a large transaction.

We need to update docdb compaction filter to keep those records for split child tablets.

**Comment by bmatican** [comment]
Was talking to Rob on Slack, he felt this should be pretty quick to fix + add a test for, so he's giving that a go. cc @rthallamko3

**Comment by robertsami** [comment]
@rthallamko3 passing back to you, with some notes about one specific problematic situation to consider:

1. client issues "commit" of a large transaction to coordinator
2. coordinator asynchronously issues TransactionStatus::APPLYING operation to involved tablets
2. participating tablet calls `Tablet::ApplyIntents` which calls `PrepareApplyIntentsBatch`
3. `PrepareApplyIntentsBatch` finds that it needs to prepare more than `FLAGS_txn_max_apply_batch_records` for this transaction https://github.com/yugabyte/yugabyte-db/blob/master/src/yb/docdb/docdb.cc#L1257
4. docdb applies the current batch of intents to regular_db along with a special `ApplyTransactionStatePB` record which tracks apply progress
5. background `ApplyIntentsTask` is registered to write a new batch of intents every `FLAGS_apply_intents_task_injected_delay_ms` millis

if we've applied some but not all batches of a transaction, and then we split a tablet, the post split compaction will wipe `ApplyTransactionStatePB` records. in practice, when a tablet is bootstrapped, we should eventually register `ApplyIntentsTask` instances for each incomplete `ApplyTransactionStatePB` found in the bootstrapped regular_db_ (see `TransactionParticipant::LoadFinished` which is called by `TransactionLoader`). so i think one way we see this issue cause data loss is if:
1. on tablet split, we bootstrap the new tablet and register a new`ApplyIntentsTask` for the ongoing transaction on the child subtablet
2. post split compaction runs and wipes the `ApplyTransactionStatePB` from `regular_db_`
3. before the ongoing transaction is complete, the node crashes
4. on subsequent bootstrap of this tablet, we will *not* find a `ApplyTransactionStatePB` for the previously ongoing transaction since it has been compacted away, and we will incorrectly fail to apply the remaining transaction's intents
