### ISSUE TITLE
[docdb] PITR-YSQL support for Sequences

### ISSUE THREAD

**Issue by kripasreenivasan** [yugabyte/yugabyte-db#10249]
Jira Link: [DB-635](https://yugabyte.atlassian.net/browse/DB-635)
As of today, Sequences don't work with PITR - If we drop a sequence on a column and then restore to a time before the drop, the sequence isn't restored properly.

**Comment by sanketkedia** [comment]
Did some testing on where we stand currently wrt Sequences:

- If you restore to a state before the sequence table was created/dropped then it doesn't work. PG Catalog metadata changes seem to be in order so I am guessing that it is because of the extra things that we do for supporting sequences (that Postgres doesn't). Who can help me with understanding this?
- If you just restore rows of a table containing SERIAL columns and/or other columns linked to a sequence then it works.
