### ISSUE TITLE
'FOR UPDATE' lock acquired even after the same row being locked using 'FOR UPDATE' in different transaction.

### ISSUE THREAD

**Issue by shubh1608** [yugabyte/yugabyte-db#10250]
Jira Link: [DB-995](https://yugabyte.atlassian.net/browse/DB-995)
Created a table to perform the testing and insert a dummy record:
1. CREATE TABLE t(k int, v int);
2. INSERT INTO t VALUES(1, 1);

Open 2 sessions Session1 and Session2

Start a TXN1 in Session1:
1. BEGIN;
2. SELECT * FROM t WHERE k=1 FOR UPDATE;
***wait***

In Session2 run:
1. SELECT * FROM t WHERE k=1 FOR UPDATE;

Expected behavior: Request for lock in Session2 should not be allowed and an error should be thrown.
Observed behavior: Lock successfully acquired and TXN1 failed.

Refer below screenshot for the result, steps are highlighted:
![image](https://user-images.githubusercontent.com/8343393/136839995-4d71aefc-1316-40e5-b2f2-343210dff545.png)

YugabyteDB version used: 2.9.0.0

**Comment by pkj415** [comment]
@ddorian this is expected behaviour when we use optimistic locking with our REPEATABLE READ and SERIALIZABLE isolation levels. Transactions are assigned priorities randomly and the following 2 possibilities can occur -
1. T1 starts first and takes a lock. T2 then attempts to take the same lock and has a higher priority than T1. In this case, it will abort T1 and take the lock. T1 will see the error when it attempts the next query.
2. T1 starts first and takes a lock. T2 then attempts to take the same lock and has a lower priority than T1. In this case, it will abort itself. If T2 is facing the conflict in the first query of the transaction, it will restart the transaction and retry internally for a configurable number of times with exponential backoff without surfacing the error the the client. Note that the restarted transactions will preserve the same priority which would still be lower than T1's priority -- so the backend is essentially waiting for T1 to complete.
