### ISSUE TITLE
[Docs] Add deployment guides for OCI and DigitalOcean

### ISSUE THREAD

**Issue by polarweasel** [yugabyte/yugabyte-db#10373]
### Description

We would like to create Deployment guides for Oracle Cloud (OCI) and Digital Ocean similar to the ones found here:

<https://docs.yugabyte.com/latest/deploy/public-clouds/>

Both of these deployment guides would have "Terraform" and "Manual" installation paths available under them. 

**Richard Lewis** is the point of contact for this effort.

The Partner team is executing programs to make our software available in these clouds.

**Comment by lizayugabyte** [comment]
There was a similar/duplicate ticket opened in jira for Platform docs. Yogesh asked to close it because there's nothing to document ("there is no native support for OCI and Digital Ocean... We can close this ticket. when we add the product support we will add the documentation as part of the feature completion. / We should track this as a feature request, since it needs to go through the dev/qa/release process and once it is certified we will create a sub ticket for the documentation")
