### ISSUE TITLE
[DocDB] Reset master proxy on request timeout

### ISSUE THREAD

**Issue by spolitov** [yugabyte/yugabyte-db#10519]
### Description

Suppose the following scenario.
Meta cache needs to lookup table locations.
It sends RPC to the master leader, and this RPC deadline matches the lookup deadline.
But this master leader was removed from the cluster and just drop all incoming packets.
Call times out, but since we cannot retry lookup, meta cache does NOT reset master leader.
So we could end up in a situation where we query this bad master again and again and fail all lookups.

**Comment by bmatican** [comment]
More notes, this came up as a 2.8 release blocker, because backup/restore was failing, during a full move.

A full move is classified as moving the whole cluster, from say an old set of 3 nodes, ABC, to a new set of 3 nodes, DEF. Due to having masters involved, we need the new set of nodes to start off with the full list of all possible masters, including the transition, so ABCDEF. However, once the transition is done, the final set will only be DEF.

However, we try not to restart processes, so the new masters and tservers are initially started with the ABCDEF master addresses, in memory and on disk, then after the transition, we change the file on disk and update the gflags in memory. However, the YSQL PG process does not reflect the in-memory changes, as we do not propagate in-memory gflag changes to PG yet.

**This leads to any new YSQL connection potentially trying to reach out to 3 dead masters, leading to the timeout issue that Sergei uncovered here.**
