### ISSUE TITLE
Master UI of /tablet-servers page: Show only running and bootstrapping tablets

### ISSUE THREAD

**Issue by bmatican** [YugaByte/yugabyte-db#1055]
Follow-up on this, 909341602f5a4e52b8b353fc9be40c020ebe2dd6 also had two unintended side-effects we should address:
- the tablet columns used to get data displayed from the `TSDescriptor`, which was based on the `TSTabletManager::GetNumLiveTablets`, which would account for `RUNNING` and `BOOTSTRAPPING` state only (something we would often use to figure out how fast a TS was coming back to full serving ability), as opposed to just being a member of the quorum
- ~~@kmuthukk pointed out that the `User` vs `System` table split makes the `User` column only show explicitly user created tables and not include secondary indexes, which are arguably still a user table (done through some `CREATE INDEX` statement) cc @schoudhury~~

**Comment by kmuthukk** [comment]
@bmatican - I was referring to the /tablet-servers view where we show running tablets. 

For tablet counts shown  - I think index & table tablets can be shown unified. 

For UI pages where we display objects - separating tables, indexes, and system tables (like pg catalog tables), etc. makes sense.

**Comment by ndeodhar** [comment]
Dug into this. Here's the problem:
During heartbeat, tserver sends master a list of all its tablets, their raft groups and tablet status. Master only records this information if the tablet status is running and/or raft groups differ from what the master has.
We use information from master to populate "tablet count" for every tserver in Master UI's /tablet-server page. Because the master does not consider tablet status other than "running", when a tserver that was down is brought back up, the tablet count on the UI page incorrectly reflects the old tablet count. This should actually be 0 when tserver first starts up and then gradually keep increasing as the tablets are bootstrapped.

To fix:
Master should also consider the tablet status that is sent by tserver during heartbeat and update the catalog if there's a difference.
