### ISSUE TITLE
[YSQL] COPY for partitioned table writes to parent instead of child nodes

### ISSUE THREAD

**Issue by m-iancu** [yugabyte/yugabyte-db#10591]
Jira Link: [DB-856](https://yugabyte.atlassian.net/browse/DB-856)
We need to confirm the diagnosis, and also whether it only affects PARTITION BY HASH.
Superficially appears like COPY succeeds and the table is empty.
However, if the we re-run the COPY we get an unique constraint violation on the parent table pkey (so it appears the rows might get inserted there).

To repro:
### Set up tables
```
CREATE TABLE test(h1 int NOT NULL, 
                  h2 int NOT NULL, 
                  h3 int NOT NULL, 
                  v1 int, 
                  primary key(h1, h2, h3))
PARTITION BY HASH(h1);

CREATE TABLE test_1 PARTITION of test FOR VALUES WITH (modulus 2, remainder 0);
CREATE TABLE test_2 PARTITION of test FOR VALUES WITH (modulus 2, remainder 1);
````
### Run initial copy -- succeeds but table appears empty
```
\copy test from 'test.csv' WITH (DELIMITER ',');
```
```
COPY 6
```
Appears to succeed -- now verify the table data.
```
SELECT * FROM test;
```
```
 h1 | h2 | h3 | v1
----+----+----+----
(0 rows)
```
To confirm, EXPLAIN shows the select does the right thing (goes through all children/partitions):
```
EXPLAIN SELECT * FROM test;
```
```
                            QUERY PLAN
------------------------------------------------------------------
 Append  (cost=0.00..210.00 rows=2000 width=16)
   ->  Seq Scan on test_1  (cost=0.00..100.00 rows=1000 width=16)
   ->  Seq Scan on test_2  (cost=0.00..100.00 rows=1000 width=16)
(3 rows)
```

### Re-run copy -- will get unique constraint violation
```
\copy test from 'test.csv' WITH (DELIMITER ',');
```
```
ERROR:  duplicate key value violates unique constraint "test_pkey"
```

**Comment by deeps1991** [comment]
Some additional notes:

1. On setting set yb_debug_log_docdb_requests = true; I can see that the PGSQL_WRITE requests are made to the parent partitioned table. This results in the copied rows being stored in the tablets of the parent partitioned table. All rows pertaining to the partitioned table must only be stored in the children, so the above is unexpected behavior. The data stored in the parent partitioned table is "lost" as the YSQL layer only expects to see rows in the tablets of the child partitions.
2. I could reproduce the same behavior with RANGE, LIST and HASH. So this issue is not specific to HASH partitioning.
