### ISSUE TITLE
🐞❓ [YCQL] `describe index` should not include auto-included columns for primary key

### ISSUE THREAD

**Issue by BevanR** [YugaByte/yugabyte-db#1073]
## Steps to reproduce

1. Create a table
1. Add a unique index; `CREATE UNIQUE INDEX myindex...`
1. `desc index myindex`
1. drop the index
1. Copy-paste the output of `desc index` to recreate the index
1. Fails because the command has the `INCLUDE` section that is autogenerated by YB and duplicates primary key columns;

```
InvalidRequest: Error from server: code=2200 [Invalid query] message="Query error: Duplicate Column
```

Related; https://github.com/YugaByte/yugabyte-db/issues/1072

**Comment by kmuthukk** [comment]
@ndeodhar - could you take an initial look at this one?

**Comment by ndeodhar** [comment]
While creating an index, we implicitly add primary key columns from the indexed table to the index. That's why we see an error when the user query explicitly contains the primary key column in the INCLUDE clause.

We'll fix this so that we don't error out when the user supplied INCLUDE clause contains primary key and also update the docs to explain this behavior better.

**Comment by ndeodhar** [comment]
Fixed in https://github.com/YugaByte/yugabyte-db/commit/d9b77deefea23958dbcb0aebe6b0b8abc707577f
