### ISSUE TITLE
[DocDB] Automate Changing Database Ownership When Migrating to a New Yugabyte Database

### ISSUE THREAD

**Issue by mrajcevic01** [yugabyte/yugabyte-db#10773]
### Description

[Link to Internal Slack Conversation](https://yugabyte.slack.com/archives/C02GQC96NH4/p1637693861055800)

Running into issue for clusters successfully restored into GA where the admin user does not have access to the restored tables due to the owner of the tables being the yugabyte user (first screenshot). Due to this the user cannot change the owner of the table either.

**Comment by sushantrmishra** [comment]
In cloud the if  restore should be done as admin user (customer's user) .  Problem arises since  restore is done as superuser (`yugabyte`) but customer is accessing using `yb_superuser` which not a actual superuser.

https://docs.google.com/document/d/1RFp3G0Mw_eLcqS_hc6sOGkOJktvuKiAYdocUAnkMVGE/edit#heading=h.846ve86z74lw
