### ISSUE TITLE
[Docs] Version picker behaves inconsistently

### ISSUE THREAD

**Issue by chrisckchang** [yugabyte/yugabyte-db#10790]
### Description

If you explicitly pick a version from the drop down menu, the version picker does not stay consistent as you click through the docs.

A quick way to repro:
1. Pick version 2.8
2. Click on Integrations, FAQ, or Misc and the version will change to 2.11

**Comment by polarweasel** [comment]
Also true for Cloud and a couple of others that we do not want to be tied to a particular version. We're thinking about how to make the separation cleaner.

**Comment by ymahajan** [comment]
cc: @yb-andrew

**Comment by polarweasel** [comment]
Hey @ymahajan rather than calling this a high priority, I'd suggest we look at the two that reference this one: #10877 addresses bad behaviour, and should happen first; and #10876 is what needs to happen to do things like hide the version display when the page you're on is unversioned (and is a lot more work).

**Comment by polarweasel** [comment]
Fixed in the last little while.
