### ISSUE TITLE
yb-admin list_tablets does not work for YSQL tables

### ISSUE THREAD

**Issue by ndeodhar** [yugabyte/yugabyte-db#1080]
```
yb-admin list_tablets postgres foo
I0326 12:51:31.168517 2472186752 mem_tracker.cc:240] MemTracker: hard memory limit is 13.600000 GB
I0326 12:51:31.169183 2472186752 mem_tracker.cc:242] MemTracker: soft memory limit is 11.560000 GB
W0326 12:51:31.176200 153608192 proxy.cc:243] Peer address 'localhost:7100' resolves to [127.0.0.1:7100, [::1]:7100] different addresses. Using 127.0.0.1:7100
Error: Not found (yb/master/catalog_manager.cc:6477): Unable to list tablets of table postgres.foo: The object does not exist
```

**Comment by mbautin** [comment]
I think this might be related to the fact that YSQL tables are missing from the (namespace, table_name) -> table_uuid map in the master, because we also need the schema id there.

@ndeodhar what is the use case for this? Is this mostly for completeness?
@robertpang any thoughts about how this should work best?

**Comment by ndeodhar** [comment]
Yes, it's for completeness. Not high priority, but something that we should look into.

**Comment by d-uspenskiy** [comment]
CatalogManager doesn't allow to find YSQL namespace by name. This is designed behavior. YSQL namespaces are not stored in internal map to avoid namespace name collision (different namespaces in different database_type with same name)

**Comment by jaki** [comment]
Closing due to commit e6318c0b3711bbacc7c1503029e28fd776c3b30b.
