### ISSUE TITLE
[DocDB] Table splitting: disable splitting for TTL-enabled tables until we have proper integration

### ISSUE THREAD

**Issue by ttyusupov** [yugabyte/yugabyte-db#10837]
### Description

We need to enable back after implementing https://github.com/yugabyte/yugabyte-db/issues/10515.

**Comment by bmatican** [comment]
Had some discussion with @jmeehan16 and @SrivastavaAnubhav yesterday and I think we might have a not-so-expensive way of getting this done, in an easy to undo way in the future.

The challenge is that the master is responsible for triggering splits, but we'd need to disable it based on a TS-only gflag being enabled or not (`rocksdb_max_file_size_for_compaction`) and we do not flow that information to the master right now.

So instead, we could do the following
- On the TS side, we make the split command fail, if `rocksdb_max_file_size_for_compaction` is set AND the table this tablet belongs to has table level TTL. This can be a very specific error, that we can account for.
  - There's actually 2 TS APIs that we could use: GetMiddleKey and SplitTablet. We should probably wire it to the GetMiddleKey, due to the master implication here. By the time we call SplitTablet, the master would have already deemed that this split should happen, and create 2 children as master-side metadata. That's undesirable!
- On the master side, we will soon have a standalone component triggering splits, every 1s. If we get the specific error above, then we can mark this table as not needing to do splits for in the future.
  - Ideally, we wouldn't mark the table as permanently disabled, but rather disabled for N amount of seconds. This would make our life easier in the future, if say, `rocksdb_max_file_size_for_compaction` gets disabled, or when we do a software upgrade on the TS and we now support splits. The main drawback here would be that every N seconds, we could try this table again. Since the RPC will fail trivially, that seems like minimal overhead.
