### ISSUE TITLE
  [YSQL] Yugabyte IndexScan needs optimization similar to BitmapOr

### ISSUE THREAD

**Issue by nocaway** [yugabyte/yugabyte-db#10848]
Jira Link: [DB-695](https://yugabyte.atlassian.net/browse/DB-695)
### Description

Postgres's plan for Bitmap scan provides optimization for simple OR operator, but Yugabyte Index scan does not.

Postgres's scan plan.
```
postgres=# create table tab(i int primary key, j int);
CREATE TABLE
postgres=# create index jdx on tab(j);
CREATE INDEX
postgres=# explain select * from tab where i = 1 or j = 1;
                                 QUERY PLAN                                  
-----------------------------------------------------------------------------
 Bitmap Heap Scan on tab  (cost=8.41..19.12 rows=12 width=8)
   Recheck Cond: ((i = 1) OR (j = 1))
   ->  BitmapOr  (cost=8.41..8.41 rows=12 width=0)
         ->  Bitmap Index Scan on tab_pkey  (cost=0.00..4.16 rows=1 width=0)
               Index Cond: (i = 1)
         ->  Bitmap Index Scan on jdx  (cost=0.00..4.24 rows=11 width=0)
               Index Cond: (j = 1)
(7 rows)
```

Yugabyte's index scan plan.
```
postgres=# create table tab(i int primary key, j int);
CREATE TABLE
postgres=# create index jdx on tab(j);
CREATE INDEX
postgres=# explain select * from tab where i = 1 or j = 1;
                       QUERY PLAN                       
--------------------------------------------------------
 Seq Scan on tab  (cost=0.00..105.00 rows=1000 width=8)
   Filter: ((i = 1) OR (j = 1))
(2 rows)
```

**Comment by m-iancu** [comment]
This is still in the roadmap, but as a temporary workaround, some of these cases can be optimized using UNION or UNION ALL.
For example, for the `OR` query above, we can rewrite it as:
```
yugabyte=# explain select * from tab where i = 1 UNION ALL select * from tab where j = 1;
                                 QUERY PLAN
----------------------------------------------------------------------------
 Append  (cost=0.00..9.50 rows=11 width=8)
   ->  Index Scan using tab_pkey on tab  (cost=0.00..4.11 rows=1 width=8)
         Index Cond: (i = 1)
   ->  Index Scan using jdx on tab tab_1  (cost=0.00..5.22 rows=10 width=8)
         Index Cond: (j = 1)
(5 rows)
```

or 
```
yugabyte=# explain select * from tab where i = 1 UNION select * from tab where j = 1;
                                    QUERY PLAN
----------------------------------------------------------------------------------
 HashAggregate  (cost=9.56..9.67 rows=11 width=8)
   Group Key: tab.i, tab.j
   ->  Append  (cost=0.00..9.50 rows=11 width=8)
         ->  Index Scan using tab_pkey on tab  (cost=0.00..4.11 rows=1 width=8)
               Index Cond: (i = 1)
         ->  Index Scan using jdx on tab tab_1  (cost=0.00..5.22 rows=10 width=8)
               Index Cond: (j = 1)
(7 rows)
```
Both of these do exactly two point-lookups for the respective rows rather than a potentially slow range scan. 
Note that`UNION` (vs `UNION ALL`) additionally goes over the data to remove duplicates -- so that needs to be chosen depending on the use-cases. `UNION` is more optimal if we are sure there's no duplicates or we are ok with them.

Note that this can be extended to multiple OR operators as well as complex combinations of OR and AND operators.
Essentially, each efficient AND'ed group can be executed on it's own and them merged with UNION ALL (or with UNION if that's enough).

**Comment by tanujnay112** [comment]
@m-iancu Note that we can also potentially use `yb_enable_expression_pushdown` once that's also available for index scans.

CC: @andrei-mart

**Comment by wierdvanderhaar** [comment]
@nocaway  @m-iancu 

Regarding this being on the roadmap. Is this already committed for a particular version?

**Comment by sushantrmishra** [comment]
This worked is tracked by https://github.com/yugabyte/yugabyte-db/issues/4634
