### ISSUE TITLE
geo: TS crash when accessing nonlocal data in a local transaction

### ISSUE THREAD

**Issue by es1024** [yugabyte/yugabyte-db#10879]
### Description

Context: #9980

When attempting to access nonlocal data in a local transaction, sometimes the tablet server crashes instead of cleanly aborting the transaction:

```
yugabyte=# begin; insert into testb values(7); end;
BEGIN
server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
The connection to the server was lost. Attempting reset: Failed.
You are currently not connected to a database.
```

**Comment by rthallamko3** [comment]
Segmentation faults that happen due to this issue, can have the following callstack: 
#3  yb::client::YBTransaction::Impl::DoAbort (this=this@entry=0x21a42c0, deadline=..., deadline@entry=..., transaction=std::shared_ptr (count 8, weak 1) 0x219b8a0, status_tablet=...)
    at ../../src/yb/client/transaction.cc:832
#4  0x00007f56c01670cd in yb::client::YBTransaction::Impl::DoAbort (this=this@entry=0x21a42c0, deadline=..., transaction=std::shared_ptr (count 8, weak 1) 0x219b8a0) at ../../src/yb/client/transaction.cc:824
#5  0x00007f56c0167549 in yb::client::YBTransaction::Impl::Prepare(yb::client::internal::InFlightOpsGroupsWithMetadata*, yb::StronglyTypedBool<yb::client::ForceConsistentRead_Tag>, std::chrono::time_point<yb::CoarseMo
noClock, std::chrono::duration<long, std::ratio<1l, 1000000000l> > >, yb::StronglyTypedBool<yb::client::Initial_Tag>, boost::function<void (yb::Status const&)>) (warning: Source file is more recent than executable.
this=this@entry=0x21a42c0,
    ops_info=ops_info@entry=0x1f9e738, force_consistent_read=..., deadline=...,	initial=..., initial@entry=...,	waiter=...) at ../../src/yb/client/transaction.cc:322
#6  0x00007f56c009b871 in yb::client::internal::Batcher::ExecuteOperations (this=0x1f9e690, initial=...) at ../../src/yb/client/batcher.cc:483
#7  0x00007f56c00a018e in yb::client::internal::Batcher::AllLookupsDone (this=this@entry=0x1f9e690) at ../../src/yb/client/batcher.cc:471
---Type <return> to continue, or q <return> to quit---
