### ISSUE TITLE
[Platform] Docker aarch64 image

### ISSUE THREAD

**Issue by robd003** [yugabyte/yugabyte-db#10909]
### Description

It would be great to have a multiarch docker build so that x86_64 and aarch64 images are available.

This would let people use AWS Graviton2 instances to run yugabyte. It would also allow people to test on the new Apple M1 Mac's when using docker.

**Comment by dmagda** [comment]
The lack of support for Apple M1 is becoming more pressing. The number of Apple M1 users keeps growing and I see more reports from the open-source community. 

Users start a node in Docker following this instruction:
https://docs.yugabyte.com/preview/quick-start/create-local-cluster/docker/

`docker run -d --name yugabyte \
         -p7000:7000 -p9000:9000 -p5433:5433 -p9042:9042 \
         -v ~/yb_data:/home/yugabyte/yb_data \
         yugabytedb/yugabyte:latest bin/yugabyted start \
         --base_dir=/home/yugabyte/yb_data --daemon=false`
         
but get the error saying:

``

**Comment by dmagda** [comment]
Regarding the Apple M1 support. The macOS users can use the x86 image with Docker Desktop 4.3+. Docker Desktop for Apple silicon supports multi-platform images, which allows you to build and run images for both x86 and ARM architectures without having to set up a complex cross-compilation development environment. https://docs.docker.com/desktop/mac/apple-silicon/

So, until the aarch64 image for YugabyteDB becomes available, the users can take advantage of Docker Desktop 4.3+.
However, one of the users reported that YugabyteDB processes freeze and become unresponsive from time to time when running the x86 image on Apple silicon. [The root cause is unclear though](https://yugabyte-db.slack.com/archives/CG0KQF0GG/p1650372332515079).

**Comment by robd003** [comment]
I've had the x86_64 yugabyte process lockup on my M1 Mac.

Getting an arm65 build out would be great! Graviton2 is a LOT cheaper than paying the Intel tax on AWS.

**Comment by jannehietamaki** [comment]
Under emulation YugabyteDB is not usable because it's extremely slow. At least file system events / inotify is not working under emulation which may or may not cause this.

**Comment by jannehietamaki** [comment]
Here is a `Dockerfile` for building both arm64 and amd64 images from binary release of YB.

```
FROM centos:centos8
RUN cd /etc/yum.repos.d/
RUN sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-*
RUN sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*
RUN yum upgrade -y
RUN yum install procps-ng wget libatomic python39 -y
RUN alternatives --set python /usr/bin/python3
RUN arch=$(arch | sed s/aarch64/el8-aarch64/ | sed s/x86_64/linux-x86_64/) && wget "https://downloads.yugabyte.com/releases/2.13.0.0/yugabyte-2.13.0.0-b42-${arch}.tar.gz" -O /tmp/yugabyte.tar.gz
RUN tar xvfz /tmp/yugabyte.tar.gz
RUN ln -s /yugabyte-2.13.0.0 /yugabyte
CMD /yugabyte/bin/yugabyted start --daemon=false --ui=false

```

Could be improved, but this seems to be working fine for me on M1.

**Comment by timopulkkinen** [comment]
This seems to still be open. 

Meanwhile, here's a link to a Dockerfile that builds YDB w/ pldebugger.git from source: 

https://github.com/timopulkkinen/yugabytedb-docker/blob/main/Dockerfile

Uses CentOS 8 as base image, and compiles w/ clang11. Currently bound to git commit cd3c1a4, but that is easily changed in script if needed.

**Comment by svarnau** [comment]
DB build on arm64: #14896

**Comment by jharveysmith** [comment]
Hello! We have started releasing dual-arch docker images with `yugabytedb/yugabyte:2.20.0.2-b1`.  Thank you for your patience!
