### ISSUE TITLE
[xCluster] Support Database/Keyspace level replication

### ISSUE THREAD

**Issue by rahuldesirazu** [yugabyte/yugabyte-db#10984]
Jira Link: [DB-778](https://yugabyte.atlassian.net/browse/DB-778)
### Description

This is a tracking issue for setting up replication at the Database/Keyspace scope
Right now, users only have the option to setup replication at the table level. Add functionality for setup replication at the Database/Keyspace level so eventually the YSQL database/YCQL keyspace will automatically replicate any new tables in those groups.

### Phase 1

- Setup replication for all tables in a given database/keyspace 
- Automatically add any new tables to the replication configuration once they are created on the source and target

### Phase 2
- Automatically flow create table DDL from source to target, so that new tables created after setting up replication get automatically created on the target and added to the replication configuration (https://github.com/yugabyte/yugabyte-db/issues/11537)

[DB-778]: https://yugabyte.atlassian.net/browse/DB-778?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by dotyjim-work** [comment]
Would this issue also track the `keyspace` / `schema` level grouping, for YCQL and YSQL respectively. I am wondering it we proposing that  [tablegroup](https://github.com/yugabyte/yugabyte-db/blob/master/architecture/design/ysql-tablegroups.md) be a "privileged" because it neatly maps to a single tablet, or if we really want to map the feature to the same object grouping concepts?
