### ISSUE TITLE
psql: FATAL:  Not found: Error loading table with id 000000010000300080000000000004ec: Not found (yb/master/catalog_manager.cc:3393): The object does not exist: table_id: "000000010000300080000000000004ec"

### ISSUE THREAD

**Issue by Abhirapido** [yugabyte/yugabyte-db#1100]
Error in connecting to db just after installing.

**Comment by jeffreims** [comment]
I had this when I forgot to do one of the steps when setting up YSQL.

`YB_ENABLED_IN_POSTGRES=1 FLAGS_pggate_master_addresses=172.151.17.130:7100,172.151.17.220:7100,172.151.17.140:7100 /home/yugabyte/postgres/bin/initdb -D /tmp/yb_pg_initdb_tmp_data_dir -U postgres`

After running this on one of the nodes it was working for me.

**Comment by kmuthukk** [comment]
Would be nice to make the error message clear if "initdb" step was missed; or maybe if we can just run "initdb" implicitly as part of the cluster creation step - that would be even better.

**Comment by eskuai** [comment]
/help /info

[root@yb-tserver-1 yugabyte]# /home/yugabyte/postgres/bin/initdb -D /tmp/yb_pg_initdb_tmp_data_dir -U postgres
initdb: cannot be run as root
Please log in (using, e.g., "su") as the (unprivileged) user that will
own the server process.

**Comment by kntait** [comment]
I have the same issue, i believe this was supposed to be fixed in version 2.0.0 but that's not the case when using the docker image yugabytedb/yugabyte:2.0.0.0-b16.

The latest docker-compose documentation has also removed the command to enable the YSQL API.

"
Enable the YSQL API by running the following command.

$ docker exec -it yb-master-n1 bash  -c "YB_ENABLED_IN_POSTGRES=1 FLAGS_pggate_master_addresses=yb-master-n1:7100 /home/yugabyte/postgres/bin/initdb -D /tmp/yb_pg_initdb_tmp_data_dir -U postgres"
"
See
 https://docs.yugabyte.com/v1.2/deploy/docker/docker-compose/
vs
https://docs.yugabyte.com/latest/deploy/docker/docker-compose/

**Comment by ndeodhar** [comment]
Hi @kntait @eskuai,

We don't need to run the additional command to enable YSQL anymore. If you notice in the latest doc https://docs.yugabyte.com/latest/deploy/docker/docker-compose/, we are starting yb-master with `--enable_ysql` flag which will take care of initializing YSQL and no separate command is needed.

Please let us know if you still see issues after trying the steps in the latest docs.

**Comment by kntait** [comment]
Thanks @ndeodhar passing flag --enable_ysql on yb-masters works for me.

**Comment by asrulsibaoel** [comment]
Hi, @ndeodhar after adding that flag, i'm still getting this error.

[root@8c43c7fe6e64 bin]# ./ysqlsh --echo-queries
ysqlsh: FATAL:  Aborted: Shutdown connection

**Comment by ddorian** [comment]
Closing because YSQL is enabled by default.
