### ISSUE TITLE
[docs] macOS startup workaround for port(s) in use

### ISSUE THREAD

**Issue by polarweasel** [yugabyte/yugabyte-db#11062]
Slack thread: https://yugabyte.slack.com/archives/CNC26JH3P/p1641928603033600

macOS Monterey turns on AirPlay receiving by default, which listens on port 7000. This conflicts with YugabyteDB and causes `yugabyted start` to partially fail. The workaround is to turn AirPlay receiving off, then start YugabyteDB, and then (optionally) turn AirPlay receiving back on.

Add a note to this effect in the Quick Start, and perhaps also in Troubleshooting.

**Comment by dmagda** [comment]
As a macOS user, I was reluctant to turn on/off AirPlay, use it daily to transfer content between my Apple devices. Plus, what happens if I restart my machine? Should I go through the AirPlay off/on procedure again?

As a second and permanent solution, we can suggest changing the webserver's port number from `7000`. The port can be changed in the `{directory_created_by_yugabytedb}/var/conf/﻿yugabyted.conf` file. Also, we don't mention the existence of that file on our documentation. I would explain how to find that file and what parameters of the database can be changed in it.

**Comment by dmagda** [comment]
@polarweasel got it. Anyway, I would suggest two options. Option 2 is for those who don't want to mess up with the default AirPlay settings.

**Comment by polarweasel** [comment]
Need to add this into Troubleshooting, as well. Yugabyted doesn't fail, but also doesn't show all the output it would on success, and that is going to be confusing when that happens to a new user. Both options (change the config, and turn off AirPlay Sharing) are workable, and both need to be documented. A status of "Running. No leader master yet" indicates you've hit this problem (or a related one?).

**Comment by dmagda** [comment]
I don't remember what was the status. Can double-check if it helps. All I saw is the following error in the logs
`F0126 10:42:39.444931 14702080 master_main.cc:140] Network error (yb/server/webserver.cc:245): Webserver: Could not start on address 0.0.0.0:7000`
