### ISSUE TITLE
[SQLancer][YSQL] It is possible to create a temp table with usually forbidden primary key

### ISSUE THREAD

**Issue by qvad** [yugabyte/yugabyte-db#11144]
### Description

There is a chance to create temp table with `int4range` index field, while they are forbidden for default tables.
Other forbidden types are also affected INT4RANGE, INET, VARBIT, TSVECTOR etc.

```
CREATE TEMP TABLE t0(c0 INT4RANGE, UNIQUE(c0));
-- [2022-01-20 09:25:39] completed in 220 ms

CREATE TABLE t0(c0 INT4RANGE, UNIQUE(c0));
-- [2022-01-20 09:25:39] [0A000] ERROR: INDEX on column of type 'INT4RANGE' not yet supported
```

**Comment by myang2021** [comment]
Temp tables are entirely within Postgres scope and they are not known to YB backend (yb-master or yb-tserver). As a benefit, temp tables allow more features as long as they are supported by Postgres. Because temp tables are strictly "owned" by Postgres, it also follows that they only exist in one node where they are created/manipulated/dropped.

Based on this, I think this is expected and not a bug.
