### ISSUE TITLE
[Phase 3][YSQL][Colocation] Create index is failing with colocation

### ISSUE THREAD

**Issue by Arjun-yb** [yugabyte/yugabyte-db#11194]
Jira Link: [[DB-382]](https://yugabyte.atlassian.net/browse/DB-382)
DB Version: **2.11.2.0-b83**

If user creates indexes with colocated = true or colocated =  false, query fails with 
```
db1=# create index idx1 on t1(name) WITH (colocated = true);
ERROR:  unrecognized parameter "colocated"
db1=# create index idx1 on t1(name) WITH (colocated = false);
ERROR:  unrecognized parameter "colocated" 
```

**Note**: Create index with default colocation is working fine.

**Steps**:
1. create database db1 with colocated = true;
2. \c db1;
3. create table table1(i int primary key, name text);
4. create index idx1 on table1(name) WITH colocated = false;

[DB-382]: https://yugabyte.atlassian.net/browse/DB-382?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by jaki** [comment]
Opt-out of index was never supported in the first place, so this isn't a bug.  The docs `docs/content/latest/api/ysql/the-sql-language/statements/ddl_create_index.md` don't even mention "colocation".

The current behavior is for indexes to follow tables.  If table is colocated, index is also; if table is not colocated, index is not.

Opt-out/in of index was previously not supported mostly due to

- it not seeming like something one would normally do
- grammar/semantics getting complicated (since defaults are different depending on whether the database is colocated or table is colocated) -- tablegroups do support opt-in/out and don't have the same issues

Leaving this issue open as a feature request.

**Comment by frozenspider** [comment]
Confirmed: we have no plans to implement this and no known use case, we're even getting rid of the same semantics in tablegroups (#12503)
If you ever need it, please feel free to reopen or open a new issue.
