### ISSUE TITLE
[DocDB] Tablet Server reports IO error, while no actual IO error probably is happening.

### ISSUE THREAD

**Issue by fritshoogland-yugabyte** [yugabyte/yugabyte-db#11227]
### Description

When stress-testing the tserver by inserting lots of data as efficient as possible, I get the following message after some time:
```
W0126 14:18:06.932065 619152 env.cc:87] Failed to cleanup /mnt/d0/yb-data/tserver/data/rocksdb/table-000033e1000030008000000000004e01/tablet-d2d288985eb6413baa3e1b7783454db1.intents/000102.sst: IO error (yb/rocksdb/util/env_posix
.cc:238): /mnt/d0/yb-data/tserver/data/rocksdb/table-000033e1000030008000000000004e01/tablet-d2d288985eb6413baa3e1b7783454db1.intents/000102.sst: No such file or directory
W0126 14:18:06.932085 619152 env.cc:87] Failed to cleanup /mnt/d0/yb-data/tserver/data/rocksdb/table-000033e1000030008000000000004e01/tablet-d2d288985eb6413baa3e1b7783454db1.intents/000102.sst.sblock.0: IO error (yb/rocksdb/util/
env_posix.cc:238): /mnt/d0/yb-data/tserver/data/rocksdb/table-000033e1000030008000000000004e01/tablet-d2d288985eb6413baa3e1b7783454db1.intents/000102.sst.sblock.0: No such file or directory
```
The inserts are performed with a commit set to 2000 rows.
These are messages pointing at SST files for the intent db. 
I have the impression that the tserver thinks the files are there, whilst in reality they aren't and therefore produces this message.

**Comment by bmatican** [comment]
@fritshoogland-yugabyte unfortunately this is somewhat expected. There is a bg job to clean up intent files at some regularity, but that can race against normal compactions that might have removed the exact same files. The API used to delete them, at the rocksdb level, is not thread safe, so we log this as a WARN, because it's not clear if this was a real problem, or just the race.
