### ISSUE TITLE
[DocDB] Test failures specific to aarch64

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#11244]
### Description

https://detective-gcp.dev.yugabyte.com/job/github-yugabyte-db-centos8-master-clang11-debug-aarch64%2F448%2Fartifact%2Fbuild%2Fdebug-clang11-dynamic-ninja%2Fyb-test-logs%2Ftests-gutil__jenkins-test%2FJenkins_TestHash64.log?class=Jenkins&name=TestHash64

https://detective-gcp.dev.yugabyte.com/job/github-yugabyte-db-centos8-master-clang11-debug-aarch64%2F448%2Fartifact%2Fbuild%2Fdebug-clang11-dynamic-ninja%2Fyb-test-logs%2Ftests-integration-tests__cassandra_cpp_driver-test%2FCppCassandraDriverTest_TestTokenForBigInt.log?class=CppCassandraDriverTest&name=TestTokenForBigInt

https://detective-gcp.dev.yugabyte.com/job/github-yugabyte-db-centos8-master-clang11-debug-aarch64%2F448%2Fartifact%2Fbuild%2Fdebug-clang11-dynamic-ninja%2Fyb-test-logs%2Ftests-integration-tests__cassandra_cpp_driver-test%2FCppCassandraDriverTest_TestTokenForDouble.log?class=CppCassandraDriverTest&name=TestTokenForDouble

https://detective-gcp.dev.yugabyte.com/job/github-yugabyte-db-centos8-master-clang11-debug-aarch64%2F448%2Fartifact%2Fbuild%2Fdebug-clang11-dynamic-ninja%2Fyb-test-logs%2Ftests-integration-tests__cassandra_cpp_driver-test%2FCppCassandraDriverTest_TestTokenForDoubleKey.log?class=CppCassandraDriverTest&name=TestTokenForDoubleKey

https://detective-gcp.dev.yugabyte.com/job/github-yugabyte-db-centos8-master-clang11-debug-aarch64%2F448%2Fartifact%2Fbuild%2Fdebug-clang11-dynamic-ninja%2Fyb-test-logs%2Ftests-util__decimal-test%2FDecimalTest_TestDoubleConversions.log?class=DecimalTest&name=TestDoubleConversions

eg command: `ybd --cxx-test gutil_jenkins-test --gtest_filter Jenkins.TestHash64 --clang11`
cc @mbautin

**Comment by rthallamko3** [comment]
@es1024 , Can you take a look at these test failures? We are trying to understand if this is a test only issue or the underlying aspect has perf implications on the core engine functionality too.

**Comment by bmatican** [comment]
More specifically, I think whatever is breaking the Jenkins.Hash64, is likely also at fault for the Token and "IN clause" test failures.

**Comment by es1024** [comment]
Two bugs here:
1. We attempt to detect whether we are running on ARMv7 and higher, or not, but depend on `__arm__` being defined. This is not defined on aarch64 (`__aarch64__` is defined instead) which results in aarch64 builds being built assuming that we cannot do unaligned reads on 16/32-bit integers. (aarch64 actually supports unaligned read on 64-bit too, so it should use the same branch as x86-64 instead).
2. There is a bug in the fallback path when we have no support for unaligned reads (https://github.com/yugabyte/yugabyte-db/blob/d28d82e8c48bb068b538a3ea0e5165525e46838d/src/yb/gutil/hash/jenkins_lookup2.h#L133) where we assume char is unsigned (since we are casting char directly to uint32/uint64). This would not normally be a problem on ARM, which by default uses unsigned char, but we force char to be signed.

**Comment by es1024** [comment]
Separately, just for Decimal.TestDoubleConversions, https://github.com/yugabyte/yugabyte-db/blob/e88ffbdeac624aa73d37a0b9adfdec283e542a10/src/yb/util/decimal-test.cc#L185-L195 we have a comparison between double and long double. On aarch64, long double is quadruple precision, not extended precision, and this causes the value being compared in the test to (finally) become the wrong value.

**Comment by es1024** [comment]
Fixed with b1f047f and 3a41d2d
