### ISSUE TITLE
[DocDB] Skip system tables for splitting

### ISSUE THREAD

**Issue by SrivastavaAnubhav** [yugabyte/yugabyte-db#11352]
### Description

Automatically tablet splitting is currently enabled for system tables, even though most of these tables are stored on the master. We should limit automatic tablet splitting for system tables to ones that store their data on the tserver.

**Comment by bmatican** [comment]
Another good first issue, to get some exposure to tablet splitting, on the master side.

The main code would likely go into `src/yb/master/tablet_split_manager.cc`, in `TabletSplitManager::ValidateSplitCandidateTable`.

Normally, we'd want to validate via automatic tablet splitting. However, that would require writing some amount of data. Since these are system tables, that could be tricky. Instead, we could try to trigger a manual split, via yb-admin / an RPC in tests. Currently, this should fail on the tserver side, perhaps due to not having enough data to allow a split. After this change, it should fail master side, due to system tables not being allowed.

Can reach out to @SrivastavaAnubhav for more info about the master side TabletSplitManager code + how to add a test for this.
