### ISSUE TITLE
The DCAwareRoundRobinPolicy does not work with Yugabyte's Go Driver for YCQL (gocql)

### ISSUE THREAD

**Issue by ashetkar** [yugabyte/yugabyte-db#11403]
Jira Link: [DB-1111](https://yugabyte.atlassian.net/browse/DB-1111)
### Description

It's been reported that the behaviour of DCAwareRoundRobinPolicy with gocql is not as expected. It returns all nodes irrespective of any dc name passed.
This ticket is filed to confirm the same and provide a fix.

**Comment by ssherwood** [comment]
I may be able to shed some more visibility on this with my recent research.

The `DCAwareRoundRobinPolicy` does not validate the info that is provided in the localDC parameter.  Specifically you can pass any value (or no value).  If the value matches the datacenter label of the node, it puts it into a localDC pool, otherwise they are put into a remoteDC pool.

It isn't obvious to the user how these connections are given priority without digging deeply into the code, so it would be helpful to have more logging in that are to be able to understand the connection topology.  However, this does mean that the application is still connection to every node in the cluster.

The `DataCentreHostFilter` is additionally needed to ensure that connections are not made to "remote" (non-matching) nodes.

```go
cluster.PoolConfig.HostSelectionPolicy = gocql.DCAwareRoundRobinPolicy("datacenter1")
cluster.HostFilter = gocql.DataCentreHostFilter("datacenter1")
```

The documentation and example code could be more clear about this.

**Comment by HarshDaryani896** [comment]
The behaviour of `DCAwareRoundRobinPolicy` in gocql is to pick an active local host in a Round Robin way from all local hosts, if no local host is found active it will pick a host from remote hosts in a Round Robin way. 

Due to which if we gave a dc name which has no hosts in it (even an incorrect dc name), all hosts in the cluster will be remote hosts which will be picked in a Round Robin fashion. 

If one wants to pick only local hosts then they would have to use  `DataCentreHostFilter` as explained above. In this case if no local host is active the application will crash.

I have verified this behaviour on 2.17
