### ISSUE TITLE
[flaky test] BackgroundTaskTest.RunsTaskOnInterval

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#11722]
Jira Link: [DB-1267](https://yugabyte.atlassian.net/browse/DB-1267)
### Description

https://detective-gcp.dev.yugabyte.com/stability/test?branch=master&build_type=all&class=BackgroundTaskTest&name=RunsTaskOnInterval&platform=all

> Bad status: Timed out (yb/util/test_util.cc:287): Operation 'Wait for i-th (2) task run.' didn't complete within 3ms

Maybe something similar to #11010 ?

**Comment by es1024** [comment]
The test is essentially just starting a separate thread, which should wait 10ms between increments of a counter, and checking the value of that counter every 10ms.

It's difficult for me to figure out how to fix this test, since the test only fails on mac builds and I only have a linux machine, but I was able to confirm that running the following on mac:
```
std::atomic<bool> thread_finished{false};
auto thd = std::thread([&thread_finished]() {
  std::this_thread::sleep_for(10ms);
  thread_finished.store(true);
});
std::this_thread::sleep_for(21ms);
ASSERT_EQ(true, thread_finished.load());
```
results in the main thread waiting for at least 21ms, but sometimes failing nevertheless. Notably, the sleep in the main thread was observed (on std::chrono::steady_clock) to take anywhere from 21ms (expected) to 167ms (!), so this likely fails in the opposite case (where the sleep in the other thread takes significantly longer).

Both std::this_thread::sleep_for (used above, and in the main thread in the test case) and std::condition_variable::wait_for (used in the other thread in the test case) may block for longer than the specified time due to things like scheduling delays (the only guarantee is that they wait for _at least_ the specified time), and I suspect what's happening here is that the wait on the condition variable is simply taking significantly longer than the specified 10ms delay to time out -- maybe because we're running other tests in parallel?

**Comment by bmatican** [comment]
Thanks @es1024 ! Last 50 failures:
```
alma8-master-clang12-asan (jenkins history) | 1
alma8-master-gcc9-fastdebug (jenkins history) | 3
mac11.6-master-clang-debug (jenkins history) | 20
mac11.6-master-clang-release (jenkins history) | 26
```
I didn't realize this was mostly mac, for some reason I thought it was alma8 & aarch64.

> maybe because we're running other tests in parallel?

Indeed, for macs, I think we run several tests in parallel, so that could be what's causing this!

**Comment by es1024** [comment]
The alma8 failures I can also see being due to a similar issue (delays from somewhere rarely causing the right sleeps to last long enough to fail the test). Short of making the condition variable sleep very precise (which we probably don't want to do - this would basically be running things in real-time), the test is just fundamentally flawed and only happens to work in practice on our alma8 builds.
