### ISSUE TITLE
[YSQL] SELECT * FROM tab limit 1 very slow on large tables

### ISSUE THREAD

**Issue by kmuthukk** [YugaByte/yugabyte-db#1204]
[This is on 1.2.4]

Irrespective of the size of table, a simple `SELECT * FROM table LIMIT 1;` should return very quickly but that's not the case. On a 50K row table, this is taking about 2-3seconds instead of 1ms or less.

I think we are doing a full-scan even for a LIMIT 1 query; seems like we are not pushing down the LIMIT 1 predicate to DocDB.

```
\timing on

DROP  TABLE sales_records;

CREATE TABLE sales_records
(
  region         text,
  country        text,
  item_type      text,
  sales_channel  text,
  order_priority text,
  order_date     date,
  order_id       int PRIMARY KEY,
  ship_data      date,
  units_sold     int,
  unit_price     real,
  unit_cost      real,
  total_revenue  real,
  total_cost     real,
  total_profit   real
);

-- load 50K rows
COPY sales_records FROM  '/home/centos/notes/SalesRecords.csv' WITH (FORMAT CSV, HEADER);

-- these queries are super slow; take about 2-3seconds; should take 1ms or so.
select * from sales_records limit 1;
select * from sales_records limit 1;
select * from sales_records limit 1;

-- these run 1ms or less
select * from sales_records where order_id = 447897851;
select * from sales_records where order_id = 447897851;
select * from sales_records where order_id = 447897851;

\timing off
```

Relevant output:

```
postgres# select * from sales_records limit 1;
        region         | country  | item_type  | sales_channel | order_priority | order_date | order_id  | ship_data  | units_sold | unit_price | unit_cost | total_revenue | total_cost | total_profit
-----------------------+----------+------------+---------------+----------------+------------+-----------+------------+------------+------------+-----------+---------------+------------+--------------
 Australia and Oceania | Kiribati | Vegetables | Online        | H              | 2015-07-08 | 954815614 | 2015-08-09 |         13 |     154.06 |     90.93 |       2002.78 |    1182.09 |       820.69
(1 row)

Time: 2810.465 ms (00:02.810)
```

and

```
postgres# select * from sales_records where order_id = 447897851;
              region               | country | item_type | sales_channel | order_priority | order_date | order_id  | ship_data  | units_sold | unit_price | unit_cost | total_revenue | total_cost | total_profit
-----------------------------------+---------+-----------+---------------+----------------+------------+-----------+------------+------------+------------+-----------+---------------+------------+--------------
 Central America and the Caribbean | Panama  | Baby Food | Online        | L              | 2016-12-20 | 447897851 | 2017-01-03 |       1782 |     255.28 |    159.42 |        454909 |     284086 |       170823
(1 row)

Time: 0.623 ms
```

**Comment by kmuthukk** [comment]
[SalesRecords.txt](https://github.com/YugaByte/yugabyte-db/files/3075880/SalesRecords.txt)

**Comment by kmuthukk** [comment]
```
postgres=# explain select * from sales_records where order_id=666027534;
                                         QUERY PLAN
---------------------------------------------------------------------------------------------
 Index Scan using sales_records_pkey on sales_records  (cost=0.00..4.01 rows=1000 width=196)
   Index Cond: (order_id = 666027534)
(2 rows)

postgres=# explain select * from sales_records limit 1;
                                  QUERY PLAN
------------------------------------------------------------------------------
 Limit  (cost=0.00..0.10 rows=1 width=196)
   ->  Foreign Scan on sales_records  (cost=0.00..100.00 rows=1000 width=196)
(2 rows)
```

**Comment by nocaway** [comment]
This is due to wrong prefetch limit.
- This default limit needs to be lower to "1024"
- When LIMIT clause is present, the prefetch optimization should be eliminated.
Cranking out features, we haven't gotten chance to fine-tuning our work.

Coding-wise, In file "src/yb/yql/pggate/pg_doc_op.h"
```
  // Public constants.
  static const int64_t kPrefetchLimit = INT32_MAX;
```

**Comment by kmuthukk** [comment]
@nocaway - I am seeing this:
```
% git grep kPrefetchLimit
src/yb/yql/pggate/pg_doc_op.cc:  req->set_limit(kPrefetchLimit);
src/yb/yql/pggate/pg_doc_op.h:  static const int64_t kPrefetchLimit = INT32_MAX;
```

**Comment by kmuthukk** [comment]
This has been partially addressed by https://github.com/YugaByte/yugabyte-db/issues/1206.

But we should push down LIMIT deeper into the system to avoid prefetching too many rows.

**Comment by anshumanvarshney** [comment]
Hi, Can we optimize it soon, This would be great.
`(50 rows)

Time: 72.621 ms`

**Comment by ndeodhar** [comment]
Hi @anshumanvarshney, this is in active development and we hope to have it ready in the next couple of weeks.

**Comment by nocaway** [comment]
This bug has been fixed by commit https://github.com/YugaByte/yugabyte-db/commit/4405799654486b844cfc2251793d9d550c097d1f

In Postgres query plan, the nodes are connected as following.
Limit -> OrderBy -> Aggregate -> Filter (where) -> Scan

- Therefore, LIMIT node is visited first but executed last. When visiting LIMIT node, Postgres would first execute expression and nodes upon which the LIMIT node is dependent.
- To improve performance, LIMIT count and offset are collected at LIMIT node and push down to child nodes.
- When performing scan, the LIMIT count & offset are passed to the storage layer (DocDB) to read only a limited set of rows.
- If OrderBy is present, full-scan is needed, and LIMIT optimization is turned off.
- If Aggregate is present, full-scan is needed, and LIMIT optimization is turned off.
- If Filter is present, full-scan is needed, and LIMIT optimization is turned off.

Example on the ordering of execution for a query:
For the following select.
```
select sum(i), j from test group by j order by j LIMIT 10;
```
the nodes would be executed in the following order.
- Visit LIMIT node.
- Evaluate the LIMIT expression (in this case, 10).
- Visit the OrderBy (sort) node as LIMIT is dependent on this node.
- Visit the Aggregate node (Sorting is dependent on this node).
- Visit the Scan & Filter node ( Needed for aggregate).
- Apply scan and filter
- Apply aggregate on rows that are returned by Scan.
- Apply sort on rows that are returned by Aggregate.
- Apply LIMIT.
