### ISSUE TITLE
[DocDB] MasterLeader does not honor leader blacklist

### ISSUE THREAD

**Issue by hari90** [yugabyte/yugabyte-db#12073]
### Description

If user sets leader_blacklist on a master server then it should not host the master leader.

**Comment by hari90** [comment]
CatalogManager::SysCatalogRespectLeaderAffinity is the function that should perform this check.

**Comment by hari90** [comment]
CatalogManager::SysCatalogRespectLeaderAffinity handled master leader affinity.
l->pb.leader_blacklist() has list of blacklisted nodes.

Tests are in sys_catalog_respect_affinity-test.cc

**Comment by hari90** [comment]
https://docs.yugabyte.com/preview/admin/yb-admin/#change-leader-blacklist

**Comment by druzac** [comment]
Do we have preferences around priority? Looking at CatalogManager::SysCatalogRespectLeaderAffinity, this function checks the leader is currently in a priority group of zones and steps down otherwise. If the current leader is blacklisted but there's no other node in a prioritized zone, what takes precedence? The blacklist setting, or the affinity setting? I.e. should the current leader step down, or not?

**Comment by hari90** [comment]
Blacklist takes precedence over priority. It should move to a non-blacklisted with the most priority.

**Comment by druzac** [comment]
This is fixed in [4cf959a1b1ccc1508abf1aa782bf51994d7157fc](https://github.com/yugabyte/yugabyte-db/commit/4cf959a1b1ccc1508abf1aa782bf51994d7157fc).
