### ISSUE TITLE
[YSQL] Postgresql is built in non-parallel mode

### ISSUE THREAD

**Issue by d-uspenskiy** [YugaByte/yugabyte-db#1235]
In spite of the fact `./python/yb/build_postgres.py` sets correct parallelism level for make command postgres is built in single job mode.

Reason: calling make in format `make -f Makefile -j <parallelism_level>`

Possible solution is to call `make -j <parallelism_level>` instead.
In this case GNUmakefile will be used instead of Makefile. Which is preferable.
Makefile just try to call GNUmakefile but it ignores arguments

```
# The PostgreSQL make files exploit features of GNU make that other
# makes do not have. Because it is a common mistake for users to try
# to build Postgres with a different make, we have this make file
# that, as a service, will look for a GNU make and invoke it, or show
# an error message if none could be found.

# If the user were using GNU make now, this file would not get used
# because GNU make uses a make file named "GNUmakefile" in preference
# to "Makefile" if it exists. PostgreSQL is shipped with a
# "GNUmakefile". If the user hasn't run the configure script yet, the
# GNUmakefile won't exist yet, so we catch that case as well.
```

**Comment by ttyusupov** [comment]
For the case when default `make` is not GNU make we can:
1) move search for GNU make from `Makefile` into `build_postgres.py` and call GNU make if it is found.
2) Update `Makefile` to just report an error that GNU make should be used.
3) Remove `-f Makefile` from make command line arguments passed by `build_postgres.py`.

This way, in this case, it will build concurrently as well instead of silently falling back to single-threaded build.
