### ISSUE TITLE
[DocDB] TabletSplitExternalMiniClusterITest.CrashMasterCheckConsistentPartitionKeys test failures

### ISSUE THREAD

**Issue by ttyusupov** [yugabyte/yugabyte-db#12572]
Jira Link: [[DB-443]](https://yugabyte.atlassian.net/browse/DB-443)
### Description

Need to fix test failures.

Source: https://detective.dev.yugabyte.com/stability?num_commits=50&sort=commit&threshold=10

[DB-443]: https://yugabyte.atlassian.net/browse/DB-443?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rthallamko3** [comment]
Per detective [report](https://detective-gcp.dev.yugabyte.com/stability/test?branch=master&build_type=all&class=TabletSplitExternalMiniClusterITest&fail_tag=all&name=CrashMasterCheckConsistentPartitionKeys&platform=linux) , this test is still failing in master.

**Comment by arybochkin** [comment]
Detected unexpected behaviour fro processing flush request: it exits immediately with OK status without doing anything. This lead to a situation when data is still in memory and no SST files are exist for this particular tablet peer. That's why WaitForAnySSTFiles is timeout from time to time for the particular peer.

> [ts-1] I1027 14:10:43.261771 35199 tablet_service.cc:1518] Processing FlushTablets from 127.0.0.1:40461
> [m-1] I1027 14:10:43.261919 35192 flush_manager.cc:149] Handling Flush Tablets Response from TS {ts1_peer_id}. Status: OK. Flush request id: fad39e61f1aa4491bd9791e5b1335ff2

**Comment by arybochkin** [comment]
Great finding @Huqicheng, thanks!
