### ISSUE TITLE
[DocDB] TabletSplitSingleServerITest.MaxFileSizeTTLTabletOnlyValidForManualSplit

### ISSUE THREAD

**Issue by ttyusupov** [yugabyte/yugabyte-db#12582]
Jira Link: [[DB-453]](https://yugabyte.atlassian.net/browse/DB-453)
### Description

Need to fix.

Source: https://detective.dev.yugabyte.com/stability?num_commits=50&sort=commit&threshold=10

[DB-453]: https://yugabyte.atlassian.net/browse/DB-453?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rthallamko3** [comment]
@Huqicheng , Please work with @jmeehan16 if you want to understand TTL details etc.

**Comment by Huqicheng** [comment]
## Failed part:

TEST_F(TabletSplitSingleServerITest, MaxFileSizeTTLTabletOnlyValidForManualSplit)

../../src/yb/integration-tests/tablet-split-itest.cc:2002
Value of: ts_desc->get_disable_tablet_split_if_default_ttl()
  Actual: false
Expected: true

## Analysis

```
  // If the "max file size for compaction" flag is greater than 0, then tablet splitting should
  // be disabled for tablets with a default TTL.
  metrics->set_disable_tablet_split_if_default_ttl(FLAGS_rocksdb_max_file_size_for_compaction > 0);
```

From the test
```
ANNOTATE_UNPROTECTED_WRITE(FLAGS_rocksdb_max_file_size_for_compaction) = 100_KB;
```

From log:

1. Initially “W0627 03:04:49.097231  6159 tserver_metrics_heartbeat_data_provider.cc:124] FLAGS_rocksdb_max_file_size_for_compaction: 0”

2. Then “W0627 03:04:54.368522  6159 tserver_metrics_heartbeat_data_provider.cc:124] FLAGS_rocksdb_max_file_size_for_compaction: 102400”

In normal case, in step 1, the uptime calculated should be 0, however, if there is a delay before sending the heartbeat, yb-master should set the uptime to greater than 0 into ts-desc. 

To simulate this, let heartbeater sleep 10s before sending heartbeat,

```
I0627 13:58:51.088091 12209 tserver_metrics_heartbeat_data_provider.cc:122] jonathan uptime_seconds 10
I0627 13:58:51.088166 12209 tserver_metrics_heartbeat_data_provider.cc:126] jonathan FLAGS_rocksdb_max_file_size_for_compaction 0
I0627 13:58:51.090945 12178 ts_manager.cc:140] Registered new tablet server { permanent_uuid: "5bcaa763104f4bdd91b98fb2c8cc0597" instance_seqno: 1656338320562334 start_time_us: 1656338320562334 } with Master, full list: [{5bcaa763104f4bdd91b98fb2c8cc0597, 0x0000000005910a18 -> { permanent_uuid: 5bcaa763104f4bdd91b98fb2c8cc0597 registration: common { private_rpc_addresses { host: "127.0.0.2" port: 21727 } http_addresses { host: "127.0.0.2" port: 26762 } cloud_info { placement_cloud: "cloud1" placement_region: "rack1" placement_zone: "zone" } placement_uuid: "" broadcast_addresses { host: "127.0.0.3.ip.yugabyte" port: 21727 } pg_port: 5433 } capabilities: 2189743739 capabilities: 1427296937 capabilities: 2980225056 placement_id: cloud1:rack1:zone }}]
I0627 13:58:51.091225 12154 mini_cluster.cc:625] 1 TS(s) registered with Master after 10.5097s
I0627 13:58:51.091495 12178 ts_descriptor.cc:298] jonathan uptime 10
```

Since the second heartbeat also will wait for 10s, but the uptime is already greater than 0, the test case can resume but disable_tablet_split_if_default_ttl is not correct as expected by the test case.

## Solution

We should modify the test case, not only wait for uptime > 0 but also wait for disable_tablet_split_if_default_ttl to be true.
