### ISSUE TITLE
[YSQL] Force kill PostgreSQL  during restart for stuck backends

### ISSUE THREAD

**Issue by sushantrmishra** [yugabyte/yugabyte-db#12784]
Jira Link: [DB-667](https://yugabyte.atlassian.net/browse/DB-667)
### Description

Sometime PostgreSQL is not able to shutdown due to stuck PostgreSQL backend. Generally from error messages we observe shared_memory segments attached.

From the logs:

2022-01-25 17:56:49.017 UTC [23881] FATAL: pre-existing shared memory block (key 5433001, ID 0) is still in use
2022-01-25 17:56:49.017 UTC [23881] HINT: Terminate any old server processes associated with data directory "/data/pg_data".

In such scenario's we should force kill the Postgres with kill -9.

**Comment by sushantrmishra** [comment]
Can we try out the index-backfill test case and  shutdown the PostgreSQL in middle of index backfill.

**Comment by SteveXiSong** [comment]
Tried to restart the server while index backfill is ongoing. This didn't trigger a hung process or unclean PG shutdown.
Env: mac, debug, clang12.

**Comment by SteveXiSong** [comment]
After an offline discussion with Sushant, our goal for this task is to **mitigate uncleaned PG shutdown scenarios**, which block the new server spawned. With the limited information, it will be hard to reproduce this issue and root-cause it. Under this condition, our intention is **to improve the stability** of our services no matter what happens, since YB's PG layer is "mostly" stateless, which makes it safe to do hard kill.

Will time-box a day or so to root cause it with no guarantee, and implement the mitigation by issuing SIGKILLs to uncleaned PG processes. The consequences of doing this are unclear so far.

**Comment by mbautin** [comment]
@SteveXiSong 
> Tried to restart the server while index backfill is ongoing. This didn't trigger a hung process or unclean PG shutdown.
> Env: mac, debug, clang12.
Please keep in mind that Postgres shutdown details (i.e. the mechanism by which child processes are supposed to automatically terminate) are significantly different between macOS and Linux.

**Comment by SteveXiSong** [comment]
@mbautin thanks for reminding. I investigated how we did during the shutdown after that experiment, and as you said, PG does handle differently in Mac and Linux. I missed it when I did the experiment (for fast validation).
I can definitely try it in Linux to validate the experiment again.
