### ISSUE TITLE
[DocDB] Error running list_tablet_servers: Illegal state (yb/tools/yb-admin_client.cc:1411): Unable to list tablet servers of tablet [...]: Incorrect number of locations 0 for tablet [...].

### ISSUE THREAD

**Issue by def-** [yugabyte/yugabyte-db#12836]
Jira Link: [DB-2602](https://yugabyte.atlassian.net/browse/DB-2602)
### Description

Restoring backup on 2.14.0.0-b34 in testysqlidxbkflcopy-aws-aarch64 (index backfill + copy on arm) system-itest fails:
```
Failed to execute task {"nodeExporterUser":"prometheus","universeUUID":"a199b862-4b93-4ee0-8a10-ca1704fde059","encryptionAtRestConfig":{"encryptionAtRestEnabled":false,"opType":"UNDEFINED","type":"DATA_KEY"},"communicationPorts":{"masterHttpPort":7000,"masterRpcPort":7100,"tserverHttpPort":9000,"tserverRpcPort":9100,"redisServerHttpPort":11000,"redisServerRpcPort":6379,"yqlServerHttpPort":12000,"yqlServerRpcPort":9042,"ysqlServerHttpPort":13000,"ysqlServerRpcPort":5433,"nodeExporterPort":9300},"extraDependencies":{..., hit error:

{"error": "Exception: Command '['ssh', '-o', 'StrictHostKeyChecking=no', '-o', 'UserKnownHostsFile=/dev/null', '-o', 'ControlMaster=auto', '-o', 'ControlPath=~/.ssh/ssh-%r@%h:%p', '-o', 'ControlPersist=1m', '-i', '/opt/yugabyte/yugaware/data/keys/X', '-p', '54422', '-q', 'yugabyte@X', "cd / &&  bash -c '/home/yugabyte/master/bin/yb-admin --master_addresses X list_tablet_servers 4e403e353438494f83abdf0008ec345e'"]' returned non-zero exit status 1."}.
```
Yugaware logs contain more information:
```
YW 2022-06-09T00:23:17.772Z [DEBUG] from ShellProcessHandler in TaskPool-BackupUniverse(d1e4e447-ccd2-40f4-bc45-a52dd87a177c)-0 - 2022-06-09 00:23:17,146 ERROR: Failed to run command [[ ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ControlMaster=auto -o 'ControlPath=~/.ssh/ssh-%r@%h:%p' -o ControlPersist=1m -i /opt/yugabyte/yugaware/data/keys/X -p 54422 -q yugabyte@X 'cd / &&  bash -c '"'"'/home/yugabyte/master/bin/yb-admin --master_addresses X list_tablet_servers 9f4f06f0d2bf4e738a7c7a4f88ead271'"'"'' ]]: code=1 output=Error running list_tablet_servers: Illegal state (yb/tools/yb-admin_client.cc:1411): Unable to list tablet servers of tablet 9f4f06f0d2bf4e738a7c7a4f88ead271: Incorrect number of locations 0 for tablet 9f4f06f0d2bf4e738a7c7a4f88ead271.
```
Same issue happened in rerun, so it looks deterministic or at least happens often. Haven't seen this failure before.

**Comment by def-** [comment]
Happened twice in a row, both times in aarch64, haven’t seen it on x86-64. Waiting for rerun.
Basically what the test does is
1. Create some table, indexes
2. Take a backup
3. COPY TO file, DELETE from table, COPY FROM back from file, drop the table
4. Restore the backup (fails here)

**Comment by kripasreenivasan** [comment]
I have a new automation script with which I'm able to repro this issue 100% of the time.
Scenario:
- Create a universe with packed columns, tablet splitting enabled
```
  master_flags = {
                    "enable_automatic_tablet_splitting": "true",
                    "tablet_split_low_phase_size_threshold_bytes": "13421",
                    "tablet_split_low_phase_shard_count_per_node": "16",
                    "ysql_enable_packed_row": "true"
                    # TODO add compression gflag also
                }
            tserver_flags = {
                    "yb_num_shards_per_tserver": "1",
                    "ysql_enable_packed_row": "true"
                }
```
- Create a db, table with 15 data types and a materialized view and populate the table and materialized view
```
Create database db_bug;
\c db_bug;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE TYPE complex AS (re float8, im float8);
CREATE TYPE e_details AS ENUM ('Email', 'Sms', 'Phone');
CREATE TABLE random_table (id int primary key, uuid_col uuid DEFAULT uuid_generate_v4 (), name text, c complex, info json, contact JSONB, arr smallint[], cash money, i inet, m macaddr, i2 serial, i3 bigserial, val smallint, details e_details);
INSERT INTO random_table(id, name, c, info, contact, arr, cash, i, m, i2, i3,val) VALUES (1,'Sally',(1,2), '{"customer": "John Doe", "items": {"product": "Laptop","qty": 6}}','{"phones":[ {"type": "mobile", "phone": "001001"}, {"type": "fix", "phone": "002002"}]}', '{1, 2, 3}', '$99.99' ,'1.1.1.1', '00:00:00:00:00:00',1,2,3,'Sms');


DO
$do$
BEGIN 
   FOR i IN 1..10001 LOOP
      INSERT INTO random_table(id, name, c, info, contact, arr, cash, i, m, i2, i3,val,details) VALUES (i,'Sally',(1,2), '{"customer": "John Doe", "items": {"product": "Laptop","qty": 6}}','{"phones":[ {"type": "mobile", "phone": "001001"}, {"type": "fix", "phone": "002002"}]}', '{1, 2, 3}', '$99.99' ,'1.1.1.1', '00:00:00:00:00:00',i,i+1,555,'Sms');
   END LOOP;
END
$do$;
```
- Insert more data and refresh the materialized view
- Create a backup of the database
- Drop the materialized view
- Restore the backup to the same universe
- Restore task fails with 
```
YW 2022-08-08T13:15:00.587Z [DEBUG] e9e689f2-c244-47f3-afdb-e78e449db49e from ShellProcessHandler in TaskPool-BackupUniverse(6390f0a1-d795-4f60-bf27-0bc02cba2b99)-0 - 2022-08-08 13:13:28,954 ERROR: Failed to run command [[ ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ControlMaster=auto -o 'ControlPath=~/.ssh/ssh-%r@%h:%p' -o ControlPersist=1m -i /opt/yugabyte/yugaware/data/keys/ee803664-8b70-4012-a054-1d3c3f194167/yb-itest-9ba5b5927c-20220808-124001_ee803664-8b70-4012-a054-1d3c3f194167-key.pem -p 54422 -q yugabyte@10.9.130.129 'cd / &&  bash -c '"'"'/home/yugabyte/master/bin/yb-admin --master_addresses 10.9.130.129:7100,10.9.198.50:7100,10.9.216.211:7100 list_tablet_servers 10e5d7f3ed2849c5b45d4cb6a845ef87 --never_fsync=false'"'"'' ]]: code=1 output=Error running list_tablet_servers: Illegal state (yb/tools/yb-admin_client.cc:1413): Unable to list tablet servers of tablet 10e5d7f3ed2849c5b45d4cb6a845ef87: Incorrect number of locations 0 for tablet 10e5d7f3ed2849c5b45d4cb6a845ef87.
```

CC: @lingamsandeep , @bmatican

**Comment by druzac** [comment]
I can repro this using @kripasreenivasan's schema. It's only an issue when restoring in place to the existing cluster and existing database. Restoring to a new database on the existing cluster succeeds as expected.

**Comment by druzac** [comment]
Ok, I have a handle on this issue. Dropping an object is not required and I suspect the materialized view is irrelevant, but I haven't spent time refining the repro to a minimal working example.

The given sql writes enough data to the table that the split manager decides to split one of the tablets backing the table. In my repro that occurs after the backup is created and before the restore is performed. I had to inject a sleep into my script to insure this ordering.

After the split, bugs in the `import_snapshot` tool insure the restore will consistently fail. When processing the table metadata in the snapshot, we notice the tablet counts in the snapshot vs. the current state for the table in question don't match [here](https://github.com/yugabyte/yugabyte-db/blob/master/src/yb/master/catalog_manager_ext.cc#L1990) and call `CatalogManager::RepartitionTable(table, table_data))`. This results in us sending some delete tablet requests for the tablets in the snapshot as the parent tablet is inactive.

Next we proceed along with matching tablets in the snapshot with currently live tablets in the cluster. [Here](https://github.com/yugabyte/yugabyte-db/blob/master/src/yb/master/catalog_manager_ext.cc#L2199) we find the snapshot table id (`table_data.old_table_id`) matches the table id currently live in the cluster (`table_data.new_table_id`). This is because we're doing an in-place restore. Given this match we conclude the matching is trivial and we can match the tablet in the snapshot metadata with the exact same tablets. But these are precisely the tablets we deleted above. We return this mapping to the backup script `yb_backup.py`, and when it tries to determine the tablet servers hosting the new tablets in the map we computed it asks us for a deleted tablet, producing the observed error.

**Comment by bmatican** [comment]
@druzac Do I understand correctly, that this assumes we restore over the existing database?

I thought we explicitly disallow that from YBA now. Was this test executed with the raw yb-admin / yb_backup commands?

**Comment by bmatican** [comment]
If that's the case, then this reinforces the idea that we should just go ahead with https://github.com/yugabyte/yugabyte-db/issues/5372, so we don't keep having to deal with such issues. Bonus points if as part of that, we don't just disallow the restore, but also remove the respective code for dealing with merging into existing data / different tablet counts / validation, etc... cc @lingamsandeep

**Comment by druzac** [comment]
@bmatican yes, that's right. This is only an issue when doing an in-place, overwrite-existing-db restore. @def- references yugaware here, but possibly this issue was filed before we restricted this case from YBA.
