### ISSUE TITLE
[YSQL] PostgreSQL backend not releasing memory once query execution is finished.

### ISSUE THREAD

**Issue by sushantrmishra** [yugabyte/yugabyte-db#12858]
Jira Link: [DB-2619](https://yugabyte.atlassian.net/browse/DB-2619)
### Description

TCMalloc is not releasing the allocated memory  once the query execution is finished. 
I did this basic test to retrieve  large number of rows from a table and do a order by (sort) on a non-sorted column which basically forced the sort in the PG layer.

**Steps to reproduce:**

**- Create orders tables** 

```
CREATE TABLE orders (
    order_id INTEGER PRIMARY KEY,
    customer_id INTEGER,
    order_number INTEGER,
    item TEXT,
    price double PRECISION,
    item_description text,
    comments text);
```

- **Increase work_mem** 

```
set work_mem='10000MB';

show work_mem ;
 work_mem
----------
 10000MB
(1 row)
```

 
- **Loaded large number of rows 3M or higher in the orders table  and run the following query -**

`explain analyze select * from orders order by order_number;
` 

-  **top command shows 650M in RSS after execution of the query has finished –**
```
  PID      USER      PR  NI  VIRT        RES    SHR S  %CPU %MEM     TIME+ COMMAND                                   
26325 yugabyte      20   0 1030.4m    649.2m  14.1m S   0.0  4.2  11:22.56 postgres
 ```
 RSS == 649.2m 

**- Backend is idle when memory usage  was captured.**

```
ps -ef|grep -i 26325
yugabyte 26325 20006 12 22:24 ?        00:11:22 postgres: yugabyte yugabyte 172.151.31.67(44868) idle

```

- **Dump the memory context using gdb, PostgreSQL layer is not consuming much memory.**

```
TopMemoryContext: 389840 total in 8 blocks; 34656 free (20 chunks); 355184 used
  smgr relation table: 16384 total in 2 blocks; 4592 free (2 chunks); 11792 used
  Shared pinned objects cache: 8192 total in 1 blocks; 2088 free (0 chunks); 6104 used
  Pinned objects cache: 262144 total in 6 blocks; 37424 free (13 chunks); 224720 used
  TableSpace cache: 8192 total in 1 blocks; 2088 free (0 chunks); 6104 used
  Operator class cache: 8192 total in 1 blocks; 552 free (0 chunks); 7640 used
  Type information cache: 24352 total in 2 blocks; 2616 free (0 chunks); 21736 used
  Operator lookup cache: 24576 total in 2 blocks; 10752 free (3 chunks); 13824 used
  Record information cache: 8192 total in 1 blocks; 1576 free (0 chunks); 6616 used
  RowDescriptionContext: 8192 total in 1 blocks; 6888 free (0 chunks); 1304 used
  MessageContext: 8192 total in 1 blocks; 6888 free (1 chunks); 1304 used
  TransactionAbortContext: 32768 total in 1 blocks; 32504 free (0 chunks); 264 used
  Portal hash: 8192 total in 1 blocks; 552 free (0 chunks); 7640 used
  TopPortalContext: 8192 total in 1 blocks; 7928 free (1 chunks); 264 used
  Relcache by OID: 16384 total in 2 blocks; 2464 free (2 chunks); 13920 used
  CacheMemoryContext: 1048576 total in 8 blocks; 450968 free (0 chunks); 597608 used
……………………………………………..
…………………………………………….
…………………………………………….

  WAL record construction: 49768 total in 2 blocks; 6360 free (0 chunks); 43408 used
  PrivateRefCount: 8192 total in 1 blocks; 2616 free (0 chunks); 5576 used
  MdSmgr: 8192 total in 1 blocks; 7928 free (0 chunks); 264 used
  LOCALLOCK hash: 8192 total in 1 blocks; 552 free (0 chunks); 7640 used
  Rendezvous variable hash: 8192 total in 1 blocks; 552 free (0 chunks); 7640 used
  Timezones: 104120 total in 2 blocks; 2616 free (0 chunks); 101504 used
  ErrorContext: 8192 total in 1 blocks; 7928 free (0 chunks); 264 used
Grand total: 2270992 bytes in 202 blocks; 682232 free (135 chunks); 1588760 used
```

- **Added the view yb_get_tcmalloc_stats to dump the tcmalloc output.**
As observed, current_heap_size is quite large.
```
select * from yb_get_tcmalloc_stats();
-[ RECORD 1 ]-------------+----------
current_allocated_bytes   | 5233968
current_heap_size         | 722010112
actual_allocated_bytes    | 687497216
thread_cache_free_bytes   | 3700416
central_cache_free_bytes  | 929552
transfer_cache_free_bytes | 4930816
pageheap_free_bytes       | 672702464
```

**Comment by mbautin** [comment]
@sushantrmishra:
A few questions about the details:
- Was this test done on Linux? (If it was done on macOS, it should be repeated on Linux.)
- How exactly were the rows loaded? (For repeatability.)
- Please share the code for yb_get_tcmalloc_stats (e.g. in a branch under your fork of yugabyte-db on GitHub). Otherwise it is difficult to map the field names in the output to what the tcmalloc documentation describes at https://gperftools.github.io/gperftools/tcmalloc.html:

generic.current_allocated_bytes | Number of bytes used by the application. This will not typically match the memory use reported by the OS, because it does not include TCMalloc overhead or memory fragmentation.
-- | --
generic.heap_size | Bytes of system memory reserved by TCMalloc.
tcmalloc.pageheap_free_bytes | Number of bytes in free, mapped pages in page heap. These bytes can be used to fulfill allocation requests. They always count towards virtual memory usage, and unless the underlying memory is swapped out by the OS, they also count towards physical memory usage.
tcmalloc.pageheap_unmapped_bytes | Number of bytes in free, unmapped pages in page heap. These are bytes that have been released back to the OS, possibly by one of the MallocExtension "Release" calls. They can be used to fulfill allocation requests, but typically incur a page fault. They always count towards virtual memory usage, and depending on the OS, typically do not count towards physical memory usage.
tcmalloc.slack_bytes | Sum of pageheap_free_bytes and pageheap_unmapped_bytes. Provided for backwards compatibility only. Do not use.
tcmalloc.max_total_thread_cache_bytes | A limit to how much memory TCMalloc dedicates for small objects. Higher numbers trade off more memory use for -- in some situations -- improved efficiency.
tcmalloc.current_total_thread_cache_bytes | A measure of some of the memory TCMalloc is using (for small objects).

- What is the value of vm.swappiness? This test should be done with `vm.swappiness=0` to remove the confusion of some of the virtual memory being swapped out and not included in the resident size.

**Comment by fritshoogland-yugabyte** [comment]
I too see this behaviour, but it's not unique to tcmalloc.
This is using stock postgres: https://dev.to/yugabyte/postgres-memory-allocation-and-os-memory-allocation-30f1
And I see the same behaviour when using YSQL: https://dev.to/fritshooglandyugabyte/yugabytedb-ysql-memory-allocation-and-os-allocation-1mo0-temp-slug-8723147?preview=7eaaf2e691e9e416c06381bcccf55be3bea463bc8e8ca304b54a74a2a10f24f90f967d46d8c8c4dd53b073b28b45a4f6ace7fc2441ee98e8ae35c583

I would have expected memory allocations that are created in a postgres portal (unique execution memory context) to be dropped after execution, which postgres does, and then OS allocations to be dropped accordingly, because with multiple connections (which there always are in any normal circumstance, and mostly too much) memory can become a premium really quick. 

However, that is not what I witness, which can potentially lead to serious memory shortage. Which is what we do see a lot too.

My guess is the memory allocators keep the memory with the intention that the memory might be reused, and thus it saves the overhead of deallocation and allocation again. 

There are notions for both ptmalloc (standard linux) and tcmalloc (yugabyte) that non-used memory is actually freed using madvise(), however I do not see any proof of that, and for now am inclined to think that the allocated (postgres level freed) memory is uniquely allocated.
