### ISSUE TITLE
Unable to create schema in a single node universe

### ISSUE THREAD

**Issue by brianhks** [YugaByte/yugabyte-db#13]
Running on ubuntu yugabyte-0.9.1.0

I create a keyspace with replication factor of 1 and then when creating tables I get the following error:

SQL error (yb/yql/cql/ql/ptree/process_context.cc:181): Invalid Table Definition. Invalid argument (yb/common/wire_protocol.cc:148): Error creating table kairosdb.data_points on the master: Not enough live tablet servers to create a table with the requested replication factor 3. 1 tablet servers are alive.

If I try to connect using cqlsh I get the following:
./bin/cqlsh localhost
Connection error: ('Unable to connect to any servers', {'127.0.0.1': IndexError('list index out of range',)})

**Comment by brianhks** [comment]
I created a 3 node cluster (3 physical machines) and the keyspace was created but with a replication factor of 3.  I tried to alter the keyspace and change it to 1 but it gives me a syntax error.

**Comment by brianhks** [comment]
This is the error:

E1231 02:42:33.709224  4218 process_context.cc:180] SQL Error: Invalid SQL Statement. syntax error, unexpected KEYSPACE, expecting LANGUAGE
alter KEYSPACE kariosdb WITH REPLICATION = {'class': 'SimpleStrategy','replication_factor' : 1} ;

**Comment by bmatican** [comment]
Hey @brianhks ! Thanks for reporting this. Unfortunately, this is a long-standing TODO in our backend, to be able to support overridable RF from universe -> keyspace -> table. As such, because the backend does not support this, we have disabled this in the language layer, for now, as well. Perhaps we could augment the error messaging though, to better support this fact, instead of telling the client the syntax is wrong...

Since you do mention that you're running this on 3 physical machines though, might I ask what you're trying to do? Perhaps we can work around this limitation somehow, for now.
Also, are you already running 3 masters + 3 tservers on these 3 machines, in RF3 mode? From your error message, it sounds as if you only have 1 tserver running?
Do you intend to mix together tables of RF1 and RF3 on the cluster?

**Comment by brianhks** [comment]
So for 99% of my testing I like to run just a single server.  Simpler for running system tests.

The 3 node cluster is for performance comparison against C*.  I run it in different configurations RF 1 and RF 3 and I look at network as well as cpu load during tests.

**Comment by schoudhury** [comment]
Hi Brian,
As Bogdan noted, you can either create a RF3 universe or a RF1 universe but you cannot change the RF after the universe is created. We will add this feature soon but for your testing purposes hoping you can destroy the RF3 universe and create a new RF1 universe when needed.

For creating a RF1 universe on 3 nodes simply pick one node to run the yb-master and start yb-master with the `--replication_factor` config flag set to 1. This is documented here: https://docs.yugabyte.com/admin/yb-master/#config-flags

Note that yb-tserver should be run on all the 3 nodes since you are running a 3 node cluster.

**Comment by kmuthukk** [comment]
hi @brianhks : closing this issue for now given the notes from @schoudhury above. But feel free to re-open if that doesn't resolve the issue.
