### ISSUE TITLE
[DocDB][PITR][Tablet Splitting]Tablets' count is not matching after restore.

### ISSUE THREAD

**Issue by Arjun-yb** [yugabyte/yugabyte-db#13094]
Jira Link: [DB-2805](https://yugabyte.atlassian.net/browse/DB-2805)
### Description

Steps: 

1. Create universe with below gflags
```
* Master:
enable_automatic_tablet_splitting = true
tablet_split_low_phase_size_threshold_bytes = 1048576        
tablet_split_low_phase_shard_count_per_node = 16
tablet_split_high_phase_size_threshold_bytes=10485760			
tablet_split_high_phase_shard_count_per_node=10000					

* Tserver:
enable_automatic_tablet_splitting = true
yb_num_shards_per_tserver=1
ysql_num_shards_per_tserver=1
```
2. Create database and table
3. Create snapshot schedule and collect the time(t1) and collect the tablets count of table(tc1)
4. Load the data and wait until tablets get splitting, once splitting reaches >=40 tablets
5. Stop the workload and restore back to collected time(t1).

**Actual**:
Initial tablets count was 3
After restore tablet count was 6

**Expected**:
It should restore back to the state where tablets count was 3

**Comment by sanketkedia** [comment]
This is expected. The restore actually restores to 3 tablets but after restore (and before querying the tablet count), the tablets get split again even if you don't insert anything. This is because restoration on tservers doesn't actually remove the data from sst files, it just sets the hybrid time filter and so even though logically you read 0 rows from the tablet, physically it has a lot of data in sst files due to which split is triggered.
