### ISSUE TITLE
[Ossexp] [yugabyted] Add tables page for yugabyted UI

### ISSUE THREAD

**Issue by nchandrappa** [yugabyte/yugabyte-db#13208]
### Description

The tables page for yugabyted UI should list both YCQL and YSQL tables.

**Comment by djiang9001** [comment]
We will implement this feature by parsing the html from localhost:7000/tables. This is the easiest and most efficient method, but note that significant changes to the tables page will break this feature.

Note that when getting the table size, we will use the "Total" size which is the sum of WAL log files and SST files. In cloud, it looks like the file size is calculated only using the sst file size, since they use the "rocksdb_current_version_sst_files_size" metric.

Other methods include:
Connecting by psql and querying for a list of databases, then connecting by psql to each database and getting the list of tables. To get databases: 
```SELECT n.nspname as "Schema",
  c.relname as "Name",
  CASE c.relkind WHEN 'r' THEN 'table' WHEN 'v' THEN 'view' WHEN 'm' THEN 'materialized view' WHEN 'i' THEN 'index' WHEN 'S' THEN 'sequence' WHEN 's' THEN 'special' WHEN 'f' THEN 'foreign table' WHEN 'p' THEN 'table' WHEN 'I' THEN 'index' END as "Type",
  pg_catalog.pg_get_userbyid(c.relowner) as "Owner",
 c2.relname as "Table",
  pg_catalog.pg_size_pretty(pg_catalog.pg_table_size(c.oid)) as "Size",
  pg_catalog.obj_description(c.oid, 'pg_class') as "Description"
FROM pg_catalog.pg_class c
     LEFT JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace
     LEFT JOIN pg_catalog.pg_index i ON i.indexrelid = c.oid
     LEFT JOIN pg_catalog.pg_class c2 ON i.indrelid = c2.oid
WHERE c.relkind IN ('r','p','i','I','')
      AND n.nspname <> 'pg_catalog'
      AND n.nspname <> 'information_schema'
      AND n.nspname !~ '^pg_toast'
  AND pg_catalog.pg_table_is_visible(c.oid)
ORDER BY 1,2;
```
To get the tables:
```
select  
  '0000'||lpad(to_hex(datoid::int),4,'0')
  ||'0000'||'3000'||'8000'
  ||'00000000'||lpad(to_hex(reloid::int),4,'0') 
as uuid, relname  from
(select oid reloid, relname, relnamespace, relkind, relowner, relam  from pg_class) rel
natural left join (select nspname,oid relnamespace from pg_namespace) ns
natural left join (select amname,oid relam from pg_am) am
cross join (select datname,oid datoid from pg_database where datname=current_database()) dat
where nspname not in ('pg_catalog','information_schema')
order by relkind desc, 1
;
```
The reason for why we need the uuid is because to get the table sizes, we need to use the localhost:9000/metrics endpoint, and namespace + table name is not enough to uniquely identify a table in ysql. From this endpoint, we get the sum of all the "rocksdb_current_version_sst_files_size" metrics of type "tablet" for each table.

To get ycql tables we can just `select * from system_schema.tables;` then ignore all system keyspaces.

Another method is to use the /dump-entities endpoint to get all namespaces and tables with their uuids, then get the metrics from localhost:9000/metrics. The problem with this method is that it is difficult to filter out system tables.

**Comment by nchandrappa** [comment]
The feature has landed.
