### ISSUE TITLE
[DocDB] Ensure uniform distribution of leaders at Table creation time

### ISSUE THREAD

**Issue by lingamsandeep** [yugabyte/yugabyte-db#13308]
Jira Link: [DB-2943](https://yugabyte.atlassian.net/browse/DB-2943)
### Description

The commit https://github.com/yugabyte/yugabyte-db/commit/c8e7c91e8321e40a1b1e5c11d5a31078f8c9eed6, changes create table workflow to ensure tablets are being spread out in a balanced way. 
An extension to this is to ensure that leaders are spread out in a balanced way during table creation so that load balancer does not perform another set of leader moves immediately after table creation.

Changes would be similar to the commit referenced above.

**Comment by hulien22** [comment]
See also the original issue for assigning leaders at creation: https://github.com/yugabyte/yugabyte-db/issues/1258

**Comment by joe-maley** [comment]
Here's how I understand the current behavior:

1. When the master creates a tablet, it maps each replica to a specific tserver.
2. For each replica, the master sends an async CreateTabletRequest to the corresponding tserver.
3. After the first replica has been bootstrapped, the master may receive a tablet report from a tserver heartbeat. The master will initiate leader election, randomly proposing one of the replicas as the leader.

At the time that the master maps the replicas for balance, it could also select a proposed leader. We would plumb this information through the CreateTabletRequests and back to the master through the tablet report. We would modify step 3 to use this proposed leader instead of picking one at random during the initial leader election.

Can anyone poke a hole in this approach? @lingamsandeep @hulien22 @sanketkedia

**Comment by joe-maley** [comment]
Currently blocked by #13389

**Comment by joe-maley** [comment]
Also blocked by #13891, which I'm currently investigating.
cc @lingamsandeep
