### ISSUE TITLE
[YCQL] Full table count using cassandra-unloader do not match the actual count in the table

### ISSUE THREAD

**Issue by Ammara5251** [yugabyte/yugabyte-db#13506]
Jira Link: [DB-3102](https://yugabyte.atlassian.net/browse/DB-3102)
### Description

The table has ~2M rows.

```
[yugabyte@ip-172-31-29-90 bin]$ ./ycqlsh `hostname -i` -e "select count(*) from ybdemo_keyspace.cassandrakeyvalue;"

 count
---------
 2000255

(1 rows)
```
Using ycrc gives correct count:

```
[yugabyte@ip-172-31-29-90 tmp]$ ./ycrc -c 172.31.29.90 ybdemo_keyspace
Checking table row counts for keyspace: ybdemo_keyspace
Checking row counts for: ybdemo_keyspace.cassandrakeyvalue
Partitioning columns for ybdemo_keyspace.cassandrakeyvalue:(k)
Performing 4096 checks for ybdemo_keyspace.cassandrakeyvalue with 16 parallel tasks
==========
Total time: 625 ms
==========
Total Row Count ybdemo_keyspace.cassandrakeyvalue = 2000255
```

When using cassandra-unloader there is a count mismatch

```
[yugabyte@ip-172-31-29-90 tmp]$ ./cassandra-unloader -boolStyle 1_0 -schema "ybdemo_keyspace.cassandrakeyvalue(k)" -host 172.31.29.90 -port 9042 -delim $'\t' -f test2.tsv
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by io.netty.util.internal.PlatformDependent0$1 (file:/tmp/cassandra-unloader) to field java.nio.Buffer.address
WARNING: Please consider reporting this to the maintainers of io.netty.util.internal.PlatformDependent0$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Total rows retrieved: 2000231
```

**Comment by ashetkar** [comment]
This issue is fixed in the cassandra-unloader with the latest release [YB Cassandra Loader (v0.0.27-yb-3)](https://github.com/yugabyte/cassandra-loader/releases/tag/v0.0.27-yb-3).

cassandra-unloader splits the entire range of values between Long.MIN_VALUE and Long.MAX_VALUE into smaller ones based on the number of threads. The ranges are defined such that **(lower bound, upper bound]** - meaning lower bound is excluded and upper bound is included in the range.
```
range 1 = (Long.MIN_VALUE, bound1]
range 2 = (bound1, bound2]
...
last range = (boundN, Long.MAX_VALUE]
```
As one can see above, the token which has its value exactly equal to Long.MIN_VALUE is never considered.
This is fine with vanilla Cassandra which ensures that no token with value Long.MIN_VALUE is generated.

But for YugabyteDB, it made cassandra-unloader end up skipping the data with token exactly equal to Long.MIN_VALUE.
The fix was to **include** Long.MIN_VALUE in the first range.
```
range 1 = [Long.MIN_VALUE, bound1]
```

Similar fix in other tools such as dsbulk may not be applicable and we may need to revisit the logic in the DB.
