### ISSUE TITLE
[DocDB] Add support for Google tcmalloc

### ISSUE THREAD

**Issue by amitanandaiyer** [yugabyte/yugabyte-db#13701]
Jira Link: [DB-3241](https://yugabyte.atlassian.net/browse/DB-3241)
### Description

gperftools has a max-cap of 1G for thread cache max bytes.

This can be much lower than what we'd like to set it as for high memory machines. TCMalloc's latest code https://github.com/google/tcmalloc doesn't have this limitation and has other desirable properties such as per-core caching. We should consider moving to this version instead.

[DB-3241]: https://yugabyte.atlassian.net/browse/DB-3241?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rthallamko3** [comment]
@SrivastavaAnubhav , Don't we have more work around the integration? Is the default already changed?

**Comment by rthallamko3** [comment]
reactivating, till the new tcmalloc is made the default.

**Comment by SrivastavaAnubhav** [comment]
Task tracker:

- [ ] Support --use-google-tcmalloc
- [ ] Fix PgMemoryGC.PgMemoryGcThresholdOverride test (memory is being released without calling ReleaseMemoryToSystem; this might be intentional)
- [ ] Enable the snapshot profiler (requires adding protobuf to the bazel build for tcmalloc, so we can access the profile marshaller to convert to the outputted profile to the pprof format)
