### ISSUE TITLE
[flaky test] org.yb.pgsql.TestPgRegressTable.testPgRegressTable

### ISSUE THREAD

**Issue by m-iancu** [yugabyte/yugabyte-db#13884]
Jira Link: [DB-3383](https://yugabyte.atlassian.net/browse/DB-3383)
### Description

Looks like it's mostly `yb_pg_alter_table` test that is failing, sometimes also `yb_create_table`.

**Comment by emhna** [comment]
`yb_pg_alter_table` test is failing due to a server crash.
The crash occurs on line 285 of `yb_pg_alter_table.sql`: `select * from my_locks order by 1;`
The `my_locks` is a view type which retrieves lock mode from pg_locks table:
```
create or replace view my_locks as
select case when c.relname like 'pg_toast%' then 'pg_toast' else c.relname end, max(mode::lockmodes) as max_lockmode
from pg_locks l join pg_class c on l.relation = c.oid
where virtualtransaction = (
        select virtualtransaction
        from pg_locks
        where transactionid = txid_current()::integer)
and locktype = 'relation'
and relnamespace != (select oid from pg_namespace where nspname = 'pg_catalog')
and c.relname != 'my_locks'
group by c.relname;
```
The problematic query comes from the `virtualtransaction` subquery which attempts to retrieve the current transaction ID.

When `select  txid_current();` query runs as a standalone, it reproduces the same server crash error.
Same error occurs when the query runs inside a transaction block except when the transaction rollsback:
 ```
begin;
select  txid_current();
 txid_current 
--------------
            5
(1 row)
commit; -- server closed the connection unexpectedly

begin;
select  txid_current();
 txid_current 
--------------
            6
(1 row)
rollback;
ROLLBACK 
```

The crash comes from a failed assertion in `procarray.c` inside `ProcArrayEndTransaction` function:
```TRAP: FailedAssertion("!(!((allPgXact[proc->pgprocno].xid) != ((TransactionId) 0)))", File: "../../../../../../../src/postgres/src/backend/storage/ipc/procarray.c", Line: 440)```
This function attempts to mark a postgres transaction as no longer running. 
If the transaction ID passed from the caller is invalid, we first confirm the top-level transaction ID from the global process structure (ProcGlobal) is also invalid -- this is where it fails. Then it proceeds to clear out the member variables of the PGProc struct in shared memory.

**Comment by emhna** [comment]
The second issue with `yb_pg_alter_table` test is the different output than the expected sql result.
This occurs when chains of sql files run prior to this alter sql test which are dependent commands.
For example:
`onek_unique1` is an index created from `yb_pg_create_index.sql` file.
`onek` is a table created from `yb_pg_create_table.sql` file.

In `yb_pg_alter_table.sql`, there are commands that tries to rename the above index, add/drop constraint and rename the above table. 
The expected output used to work correctly for those sql commands until a change was added by another commit which changed the command outputs to return "does not exist" error instead.
The culprit commit was [adding support for CREATE STATISTICS statement](https://phabricator.dev.yugabyte.com/D18429) (please check in `yb_pg_alter_table.out` line 226 to 239).
It seems like the `yb_pg_alter_table` file was tested as a standalone which is why it expected the index and table to return the "does not exist" error. 
In the detective, I see there are 3 builds that failed with `TestPgRegressTable` and 2 builds which failed to rebase so perhaps the test was dismissed.

We must revert the change to the original expected output result.

**Comment by emhna** [comment]
The third issue is in `yb_create_table.sql` test.
There's a section that connects to `\c yugabyte` then creates a temporary table and view.
The creation of temporary table fails due to `restart read required` error:
```
create temporary table temp_tab(a int);
ERROR:  Query error: Restart read required at: { read: { physical: 1663169507084339 } local_limit: { physical: 1663169507084339 } global_limit: <min> in_txn_limit: <max> serial_no: 0 }
```
The error comes from `async_rpc.cc`'s `CommonResponseCheck()` function.
The function checks against the ReadHybridTime using the response protobuf and checks whether `has_restart_read_time()` is set to true.
If so, this long string of error is created in `read_hybrid_time.h` commanding for a read restart.

The error is not reproducible in ysql shell as the temporary table gets created without any issue.
A possible workaround is to add a sleep thread immediately after `\c yugabyte` to give some time for the tablet server which has skewed clock to correct itself.
