### ISSUE TITLE
[DocDB] flaky test: PgPessimisticLockingTest.TestDeadlock and PgPessimisticLockingTest.TestDeadlockWithWrites

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#13975]
Jira Link: [DB-3459](https://yugabyte.atlassian.net/browse/DB-3459)
### Description

https://detective.dev.yugabyte.com/stability/test?branch=master&class=PgPessimisticLockingTest&name=TestDeadlock

https://detective.dev.yugabyte.com/stability/test?branch=master&class=PgPessimisticLockingTest&name=TestDeadlockWithWrites

There are some failures coming from a PG MemTracker race condition, tracked in: #13912

But there also seem to be some timeouts: https://jenkins.dev.yugabyte.com/job/github-yugabyte-db-centos-master-clang12-tsan/913/artifact/build/tsan-clang12-dynamic-ninja/yb-test-logs/tests-pgwrapper__pg_pessimistic_locking-test/PgPessimisticLockingTest_TestDeadlockWithWrites.log, perhaps, like `PgMini.*`, some of these are not TSAN friendly?

**Comment by robertsami** [comment]
these tests were recently renamed and seem to be passing reliably since the rename:

https://detective.dev.yugabyte.com/stability/test?analyze_trends=true&branch=master&class=PgWaitQueuesTest&name=TestDeadlock
https://detective.dev.yugabyte.com/stability/test?analyze_trends=true&branch=master&class=PgWaitQueuesTest&name=TestDeadlockWithWrites

they also have tsan disabled
