### ISSUE TITLE
[DocDB] Potential duplicate WRITE_OP due to split and WriteRPC timeout interference

### ISSUE THREAD

**Issue by ttyusupov** [yugabyte/yugabyte-db#14005]
Jira Link: [DB-3505](https://yugabyte.atlassian.net/browse/DB-3505)
### Description

Scenario for the potential issue:
1. Parent tablet leader received `WriteRpc` 1 and added `WRITE_OP` 1 to the WAL. But `YBClient` didn’t get the response.
2. Parent tablet got `SPLIT_OP` and added it to the WAL.
3. YBClient is retrying `WriteRpc` 1 to the parent tablet leader and getting error that tablet started split (or already split).
4. YBClient is preparing new `WriteRpc` 2 to retry the same YBOperation to the child tablet and sends it to the child tablet.
5. Child tablet leader applies `WRITE_OP` 2 caused by the same user request as `WRITE_OP` 1.

We need to implement a unit-test and then fix it. ~~Idea for fix - make tablet leader first checking for duplicate request and only after that for whether it started split. Then at step 3 parent tablet leader will reject `WriteRpc` 1 as a duplicate and `YBClient` will not retry it to the child tablet.~~

UPDATE: Consider reusing the same request_id for splitting-related retries (we would need to keep filling retryable requests for child tablets).

**Comment by Huqicheng** [comment]
Notes:

1. rpc -> parent tablet : get TABLET_SPLIT error
2. Non-retryable internally in the current rpc call by DoDelayedRetry
3. Restart session and route to the child tablet instead (YQL_STATUS_RESTART_REQUIRED_ERROR)

```cpp
TabletInvoker::Done {
   …
  const bool is_tablet_split = ErrorCode(rsp_err) == tserver::TabletServerErrorPB::TABLET_SPLIT;
  if (is_tablet_split || ClientError(*status) == ClientErrorCode::kTablePartitionListIsStale) {
    // Replace status error with TryAgain, so upper layer retry request after refreshing
    // table partitioning metadata.
    *status = status->CloneAndReplaceCode(Status::kTryAgain);
    if (is_tablet_split) {
      tablet_->MarkAsSplit();
    }
    rpc_->Failed(*status);
    return true;
  }
  …
}

 ```
=>
```cpp
AsyncRpc::Failed{
      ...
      case YBOperation::Type::QL_READ: FALLTHROUGH_INTENDED;
      case YBOperation::Type::QL_WRITE: {
        QLResponsePB* resp = down_cast<YBqlOp*>(yb_op)->mutable_response();
        resp->Clear();
        resp->set_status(status.IsTryAgain() ? QLResponsePB::YQL_STATUS_RESTART_REQUIRED_ERROR
                                             : QLResponsePB::YQL_STATUS_RUNTIME_ERROR);
        resp->set_error_message(error_message);
        break;
      }
      ...
}
```

This will have a brand new rpc call instance for the child tablet, hence new request_id.

**Comment by Huqicheng** [comment]
Seems not only tablet split related error can cause the issue,

```
 I0919 19:17:10.289409 22757 tablet_rpc.cc:497] Operation failed. Try again (yb/client/meta_cache.cc:1006): LookupByIdRpc(tablet: eebdcac8910f46a4af7b7fcaccafa5fa, num_attempts: 1) failed:      Received table 6fa4338d59b244f9bc1581a172418d5c partitions version: 0x00007f28ec6b71cc -> 2, MetaCache's table partitions version: 0: kTablePartitionListIsStale (client error 1), command:      Write(tablet: eebdcac8910f46a4af7b7fcaccafa5fa, num_ops: 1, num_attempts: 2, txn: 00000000-0000-0000-0000-000000000000, subtxn: [none]), retrier: { task_id: -1 state: kIdle deadline: 19017     .181s }
```

If we hit this error when retrying a timedout rpc call, will also create a new RPC with a different request id.

**Comment by ttyusupov** [comment]
As I see the log message above contains `kTablePartitionListIsStale` that only happens due to tablet splitting.

**Comment by Huqicheng** [comment]
Reusing the same request_id for splitting-related retries (we would need to keep filling retryable requests for child tablets)

1. When creating rpc, cache the request_id and min_running_request_id to YBOperation.
2. When retrying the batcher, ops having same group and same tablet should have the same`request_id` and min_running_request_id set previously even if tablet split happens and split one rpc to the parent tablet to two rpcs to both child tablets.
3. If request_id is set and we are under batcher retrying, use the cached one instead of assigning a new request_id when create write rpc.

**Comment by Huqicheng** [comment]
TabletSplitITest.SplitTabletDuringReadWriteLoad is failing:

session 1: retrying batcher including an rpc reusing request_id=2, but Reregister is not yet called
session 2: create a new rpc to have request_id = 3, and since the running_request is empty, 3 is min_running_request_id
session 1: send WRITE_OP with request_id=2 to tserver, tserver complained the request is expired..

Considering copy all running_requests from parent tablet to both child tablets at `MaybeUpdateMinRunningRequestId`.

**Comment by Huqicheng** [comment]
TabletSplitITest.SplitSingleTabletWithLimit

Tablet 1  running [1]

Tablet 2                    tablet 3

Tablet 4 tablet 5

Meta cache skipped tablet 2, hence tablet 4 not able to  copy running requests from tablet 2.

**Comment by rthallamko3** [comment]
@Huqicheng , Should we backport to 2.14 branch too or not?
