### ISSUE TITLE
[YSQL] Pre-create initial cluster data during the build to eliminate initdb on cluster startup

### ISSUE THREAD

**Issue by mbautin** [yugabyte/yugabyte-db#1411]
The approach is as follows:
- During the build, run initdb once and save RocksDB and sys catalog tablet metadata information.
- In tests and in new cluster creation, don't run initdb but restore the sys catalog tablet RocksDB and tablet metadata from this snapshot.

Sys catalog tablet metadata will probably need to be saved/restored via the ChangeMetadataRequestPB mechanism.

Example sys catalog tablet metadata: https://gist.githubusercontent.com/mbautin/da09a2662ba26bdf164d2ea08c7967e2/raw

**Comment by m-iancu** [comment]
Fixed by commits above: [c3a62bb](https://github.com/yugabyte/yugabyte-db/commit/c3a62bb1d60864254f832d489d976bdd7c422145), [78b49bb](https://github.com/yugabyte/yugabyte-db/commit/78b49bb5727359c8159a56cdf4321ef1d91308fd), [bdec7bd](https://github.com/mbautin/yugabyte-db/commit/bdec7bdc2b48301c6b097cf7f54e5bb425bdc2e3)
