### ISSUE TITLE
[YSQL] [Pessimistic Locking] No serialization error observed while concurrent transactional updates to the same row

### ISSUE THREAD

**Issue by Karvy-yb** [yugabyte/yugabyte-db#14137]
Jira Link: [DB-3613](https://yugabyte.atlassian.net/browse/DB-3613)
### Description

Steps to reproduce:
- Enable Pessimistic Locking on the cluster with gflags `enable_pessimistic_locking , enable_deadlock_detection=true`
- In T1, execute `begin transaction isolation level repeatable read; \ START TRANSACTION `
- In parallel, in T2, execute `begin transaction isolation level repeatable read;`
`START TRANSACTION`
- In T1, execute an update statement: `update test set v=2 where k=1;`
- In T2 in parallel, execute an update statement: `update test set v=2 where k=1;`
- Commit T1
-Expected:  In the case of commit, T2 should throw a serialization error- `ERROR: could not serialize access due to concurrent update`

There is no serialization error and T2 executes after waiting for T1 to commit/rollback.

**Comment by tedyu** [comment]
In the above example, `v` is set to the same value in session 2.
I think a different value should be used for illustration purpose.

**Comment by pkj415** [comment]
@robertsami I think the reason is incorrect -- we don't push forward commit time, we just retry the whole transaction if there is a serialization error in the first statement of a transaction block. This goes back to this message - https://yugabyte.slack.com/archives/C041XF2MN3H/p1663866906717909?thread_ts=1663854796.725819&cid=C041XF2MN3H

@Karvy-yb I have a suggest - you can disable the automatic retry mechanism for serialization & read restart errors for the first statement in transactions by setting ysql_max_write_restart_attempts=0 and ysql_max_read_restart_attempts=0. This way you will only test for wait queues and read committed and the retries won't come in the way.
