### ISSUE TITLE
[YCQL] Race between restoring a snapshot and writing consensus updates during hearbeat processing can fail queries

### ISSUE THREAD

**Issue by qvad** [yugabyte/yugabyte-db#14164]
Jira Link: [DB-3636](https://yugabyte.atlassian.net/browse/DB-3636)
### Description

Scenario is restoring few times in the row and at some point we throw an exception on YCQL query that validates number of restored rows. During validation following exception may occurs.

Wasn't able to reproduce issue if tablet splitting disabled.

```
2022-09-16 21:32:09,018:DEBUG: < 172.151.45.175 < /tmp/tests/SchedulePerformanceSuite/test_ycql_snapshots_daily_test/commands.ycqlsh.20220916213202.sql:2:InvalidRequest: Error from server: code=2200 [Invalid query] message="Execution Error. Row QL_READ client: YQL_CLIENT_CQL
request_id: 401091904344418624
schema_version: 0
hash_code: 61152
selected_exprs {
  tscall {
    opcode: 4
    operands {
      value {
      }
    }
  }
}
limit: 100
paging_state {
  next_partition_key: "\356\340"
  next_row_key: ""
  total_num_rows_read: 0
  total_rows_skipped: 0
}
return_paging_state: true
distinct: false
column_refs {
}
query_id: 3813560704
rsrow_desc {
  rscol_descs {
    name: "count"
    ql_type {
      main: INT64
    }
  }
}
is_forward_scan: true
is_aggregate: true
is_compatible_with_previous_version: false
 not in partition hash_split: [0xE658, 0xEEE0), partition key: EEE0, tablet: 736740953fec4518a6fa91c913b0817b
select count(*) from ybdemo_keyspace.postgresqlkeyvalue5;
^^^^^^
 (ql error -300)"
```

[DB-3636]: https://yugabyte.atlassian.net/browse/DB-3636?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rthallamko3** [comment]
@qvad , Is this is still a problem for tablet-splitting?

**Comment by druzac** [comment]
Tablet splitting is a red herring. The issue is:

1. Tserver sends a heartbeat to master
2. RPC handler for TSHeartbeat begins running and grabs in-memory state for tablets to update.
3. Client sends a RestoreSnapshotSchedule request to master
4. Master updates tablet and table sys catalog entries for the restored DB
5. RPC handler thread writes tablet state to sys catalog, clobbering update in (4)

d7cf0a74421676eb7271089bc186aabe0fdb7c85 fixed this by putting a barrier in based on the number of PITRs performed. RPC handler threads that want to write tables or tablets to the sys catalog must grab the current count of PITRs when they begin, and then pass that count to the sys catalog mutation APIs. If that count doesn't match the current count, the mutation is rejected. The PITR flow updates the count before doing any sys catalog writes.
