### ISSUE TITLE
Pending delete message is logged too frequently in the master log

### ISSUE THREAD

**Issue by rao-vasireddy** [YugaByte/yugabyte-db#1421]
Messages like the one below seem to be logged in the master log 60 times a sec. 
"I0522 05:58:46.541398 28267 cluster_balance_util.h:401] tablet server 7f1eb600612044bfa88cfda14f67fad3 has a pending delete"

**Comment by bmatican** [comment]
@rahuldesirazu I think we have the same issue with the mechanism that prevents us from operating with dead servers, seeing spew of the following per run in envs with bunch of tables:
>W0531 04:32:26.409832 25240 cluster_balance.cc:194] Skipping load balancing f9a8bec1a9334e828482691c963207a4: Leader not ready to serve requests. (../../src/yb/master/cluster_balance_util.h:268): Master leader has not yet received heartbeat from ts 5beb0383af4e4e2e88137f9a63fc7872, either master just became leader or a network partition.

**Comment by rahuldesirazu** [comment]
@bmatican nice catch, I'm thinking that theres some situations where we want to continue trying to load balance other tables even if AnalyzeTablets fails for a given table, but maybe we could break out and log if the error is leader not ready. How does this sound?

**Comment by bmatican** [comment]
I think this particular pattern revolves more around us having a TS in a raft group, but as far as the master is concerned, it is either dead (our 60s master time limit vs the default raft kick out time of 300s), or maybe it even never has heartbeat to us ever (some partition case between us and the TS ever since we became master leader). This would make LB difficult, since we cannot properly account for this TS in our planning, so we just bail atm...

I think if we have tables that somehow have not been spread across all TS (maybe once we have #149, so that some are restricted in some AZ), then in advance of that, we should probably try to LB all tables!

In a bigger sense and maybe as a follow-up, maybe we can load up TS information once and prepare a default State object and then use that as a starter for all follow-up LB planning for the N tables we'll be analyzing. That way maybe we don't have to loop over all the TS for every table?

**Comment by rahuldesirazu** [comment]
+1 for proposal to load up per TS information once.

**Comment by rahuldesirazu** [comment]
Fixed in edad9e70ad008f3a418b6ddcc78ef4b84e22b691, closing.
