### ISSUE TITLE
[YCQL] Thread Sanitizer data race observed in CppCassandraDriverTest_TestTableBackfillWithLeaderMoves

### ISSUE THREAD

**Issue by kripasreenivasan** [yugabyte/yugabyte-db#14246]
Jira Link: [DB-3705](https://yugabyte.atlassian.net/browse/DB-3705)
### Description

Thread Sanitizer data race observed in CppCassandraDriverTest_TestTableBackfillWithLeaderMoves in latest master 2.15.4.0-b40. This failure has been hit 184 times recently- https://detective-gcp.dev.yugabyte.com/stability?branch=master&fail_tag=tsan&num_commits=500 
Stacktrace- https://gist.github.com/kripasreenivasan/87a0eda3e1fa5e08057d13864e55cf34

**Comment by m-iancu** [comment]
https://detective-gcp.dev.yugabyte.com/stability/test?branch=master&build_type=all&class=CppCassandraDriverTest&fail_tag=tsan&name=TestTableBackfillWithLeaderMoves&platform=all

Closing since this is an older issue and looks like this test has been passing in TSAN in latest builds (13 runs without fail in a row).
