### ISSUE TITLE
[YSQL][Savepoints]: Unexpected serialization error for implicit-explicit locking

### ISSUE THREAD

**Issue by Karvy-yb** [yugabyte/yugabyte-db#14389]
Jira Link: [DB-3808](https://yugabyte.atlassian.net/browse/DB-3808)
### Description

Steps to reproduce:

-T1: begin;
-T2: begin;
-T1: savepoint s1; select * from test1 where k=1 for update; rollback to s1;
-T2: update test1 set v='A' where k=1;
-T2: commit;
-T1: select * from test1 where k=1 for update;

T1 throws serialization error here despite `rollback to s1` since the readtime of T1 has been set by the s1 read and not reset on rollback. The tserver is returning the following error to pg:
```
Operation failed. Try again (yb/docdb/conflict_resolution.cc:795): Value write after transaction start: { days: 19374 time: 12:45:24.245338 } >= { days: 19374 time: 12:45:02.402114 }: kConflict (transaction error 3)
```

[DB-3808]: https://yugabyte.atlassian.net/browse/DB-3808?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by robertsami** [comment]
This is a peculiar case where the savepoint is set at the beginning of the transaction, so rolling back to the savepoint should functionally be equivalent to rolling back the transaction. But in reality, the read time is maintained, so performing another read after T2 commits causes a serialization error.

In order to fix this, we would need to reset the transaction entirely in such a case, or handle read restarts as if no data has been read.

Interestingly, in case we do a vanilla `select ` in the subtransaction s1, and if T1 is serializable, even rolling back s1 should not unblock T2, per https://github.com/yugabyte/yugabyte-db/issues/9587

**Comment by robertsami** [comment]
Note that this issue was originally found when testing wait-on-conflict concurrency control but this happens with fail-on-conflict behavior as well, so this should not block GA for wait-on-conflict concurrency control

**Comment by pkj415** [comment]
This doesn't seem to be a bug. It is expected behaviour. We can surely optimize to make the rollback of the savepoint in T1 equivalent to a transaction restart and hence avoid the serialization error, but that is an improvement.
