### ISSUE TITLE
[Docs] YugabyteDB Quick start (for Docker)

### ISSUE THREAD

**Issue by chbussler** [yugabyte/yugabyte-db#14384]
### Description

My environment is 
- Docker Desktop on Windows 11
- Yugabyte running in a container following these instructions: https://docs.yugabyte.com/preview/quick-start/docker/
- Both Admin UIs work after Yugabyte startup (at http://localhost:7000/ and http://localhost:9000/)

The instructions say (for Docker):
- Clients can now [connect to the YSQL and YCQL APIs](https://docs.yugabyte.com/preview/quick-start/docker/#connect-to-the-database) at http://localhost:5433 and http://localhost:9042 respectively.

When following the link, it directs to at the end of the page that explains how to invoke the YSQL shell
- That works fine.

It is not clear, however, why the two localhost:port references are mentioned, as those are not needed when starting the YSQL shell as outlined at the end of the page.

After some reading I assume that those two localhost:port references are for when starting the yugabyte-client in a separate terminal and separate Docker container. When running the yugabyte-client standalone, I get the following response (looked up here: https://docs.yugabyte.com/preview/admin/ysqlsh/):
```
docker run -it yugabytedb/yugabyte-client ysqlsh -h localhost -p 5433
ysqlsh: could not connect to server: Connection refused
        Is the server running on host "localhost" (127.0.0.1) and accepting
        TCP/IP connections on port 5433?
could not connect to server: Cannot assign requested address
        Is the server running on host "localhost" (::1) and accepting
        TCP/IP connections on port 5433?

docker run -it yugabytedb/yugabyte-client ysqlsh -h localhost -p 9042
ysqlsh: could not connect to server: Connection refused
        Is the server running on host "localhost" (127.0.0.1) and accepting
        TCP/IP connections on port 9042?
could not connect to server: Cannot assign requested address
        Is the server running on host "localhost" (::1) and accepting
        TCP/IP connections on port 9042?
```

So it looks like that when running Yugabyte in one container, and trying to start a second one with the yugabyte-client, there are connectivity issues (in my case). 

Suggestion
- If I may suggest, it'd be great if you could add a separate section to the bottom of the page that explains how to setup the yugabyte-client in a separate container so that above error is resolved.

**Comment by FranckPachot** [comment]
Right, this the following is wrong:
> Clients can now [connect to the YSQL and YCQL APIs](https://docs.yugabyte.com/preview/quick-start/docker/#connect-to-the-database) at http://localhost:5433 and http://localhost:9042 respectively.
because those are YSQL (PostgreSQL protocol) and YCQL (Cassandra protocol) that has nothing to do with `http://`.

From the `docker run` in this document, you can connect either:
- from one container, like `docker exec -it 78a511819674 ysqlsh -h localhost` or `docker exec -it 78a511819674 bash -c 'ysqlsh -h $(hostname)' because the `yb-tserver` listens on al interfaces
- from the host with ysqlsh if installed or the postgresql client `psql -h localhost -p 5433` because the port was exposed to the host

From another container by linking it with a hostname, I'm using `yb` here:
- from a client container
```
docker run -it --link 78a511819674:yb yugabytedb/yugabyte-client ysqlsh -h yb -p 5433
```

But the best way is to create a docker network and assign hostnames. You will need it when adding more nodes. And example [in this blogpost](https://dev.to/yugabyte/i-want-to-try-it-yugabytedb-at-kubecon-3cm7)

**Comment by chbussler** [comment]
Great input, thank you! It'd be great if this content could be added at the end to the QuickStart guide (for newbies that would help and also open up possible next steps naturally).

Thanks again!
