### ISSUE TITLE
[DocDB] [xCluster][DDL Changes] drop column on target after source add halts Schema Modifications

### ISSUE THREAD

**Issue by Arjun-yb** [yugabyte/yugabyte-db#14408]
Jira Link: [DB-3827](https://yugabyte.atlassian.net/browse/DB-3827)
### Description

**Version**: `2.15.4.0-b77`
**Steps**:
1. Create database and table at both sides(Source and Target) 
    create database demo; 
    \c demo;
     create table test1(id int, name text);
2. Setup one-way replication on the created database.
3. Alter table at Source: alter table test1 add column age int;
4. < Wait until replication halted >
5. Alter table at Target: alter table test1 drop column name;

**Actual**:
1. It is allowing user to drop the column (possibly WAD)
2. Cannot add the column from Step # 3 to Target after the drop.  XCluster is blocked without disabling halt_ddl.

**Expected**:
1. Should be able to drop name on the Source, add age on the Target, and Resume replication

**Comment by nspiegelberg** [comment]
We should consider the proper behavior here.  Currently, this is WAD.  
- S->T should be blocked.  Cannot replicate (id [1], name [2], age [3]) -> (id [1])
- T->S should be running.  Valid to replicate (id [1]) -> (id [1], name [2], age [3])
- Unblocking S->T replication should require adding removing (name [2]) from S and either adding (age [3]) to T or removing it from S

This flow may be complicated with PackedColumns, since we can currently store a column that has been deleted from the schema without that feature.
