### ISSUE TITLE
[YEDIS] Add support for MULTI, EXEC, DISCARD and WATCH commands for handling multi-key transactions

### ISSUE THREAD

**Issue by Exocomp** [yugabyte/yugabyte-db#1443]
YugaByte Version 1.2.6

I'm using the Redis Client drivers @ https://docs.yugabyte.com/latest/yedis/develop/client-drivers/csharp/

Using the CreateTransaction option I'm getting the following error when executing the transaction:

`ERR EXEC: Unsupported call`

**Comment by schoudhury** [comment]
YEDIS API is a strongly-consistent, distributed, key-value API with focus on single-key operations. Hence, it does not support multi-key operations/transactions. As a result, the concept of an explicit `CreateTransaction` does not exist. Every YEDIS operation is implicitly a single-key transaction where you essentially get a linearizability guarantee on that single key.

If you need multi-key transactions, then you have to use either YCQL or YSQL.

**Comment by Exocomp** [comment]
I'm not sure I understand what you mean by multi-key.  From what I understand regarding how redis does transactions (https://redis.io/topics/transactions) (I under yedis is a different implementation) is that you can use single key operations however using the MULTI command you can enter multiple commands where redis will queue them until an EXEC is called (calling DISCARD gets rid of them).  If I have horribly misunderstood it then please let me know.

How would one handle the following scenario:

1) First call to yedis completes
2) Second call to yedis fails
3) How does  one clean up the first call?

**Comment by schoudhury** [comment]
The current list of YEDIS commands is documented here: https://docs.yugabyte.com/latest/yedis/api/

As you can see, none of the Redis `transactions` commands such as MULTI, DISCARD, WATCH are implemented in YEDIS. This is because YugaByte DB has its own notion of transactions (which is fully ACID) and we did not want users to get confused with Redis's use of transactions (which is essentially A and a weak form of I of ACID, there is no C and D). We want YEDIS to remain a strict single-key access API and not pollute it with multi-key semantics (the way Redis has done). As I noted before, if you need any multi-key transactions then you should use YCQL or YSQL.

**Comment by Exocomp** [comment]
> The above is a good example of why this is the case.

That's a useful feature in my opinion, so not sure if that is a good example. Others in the future will likely run into the same issue or need that capability.

**Comment by schoudhury** [comment]
Appreciate the feedback and we will keep this mind for the future. For now, there are no new features being built for YEDIS, hence the recommendation to use YCQL/YSQL even outside of this feature request. Please make sure to review the note on this page: https://docs.yugabyte.com/latest/yedis/

**Comment by Exocomp** [comment]
I understand it is not supported at the moment. Thanks for considering this for the future.

**Comment by m-iancu** [comment]
Closing as `wontfix` since this is not in our current roadmap.
