### ISSUE TITLE
[DocDB] flaky test: org.yb.pgsql.TestPgDropDatabase.testCreateDatabaseWithFailures

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#14495]
Jira Link: [DB-3886](https://yugabyte.atlassian.net/browse/DB-3886)
### Description

https://detective-gcp.dev.yugabyte.com/stability/test?analyze_trends=true&branch=master&buckets=50&build_type=all&class=org.yb.pgsql.TestPgDropDatabase&fail_tag=all&name=testCreateDatabaseWithFailures&platform=linux

traces back to https://phabricator.dev.yugabyte.com/D19522

**Comment by msun07** [comment]
This test randomly injects IO failure for the SyncWrite of sys_catalog_ and we don’t have a complete GC mechanism for failed namespace creation. The transaction rollback relies on the state shift (e.g., SysSnapshotEntryPB::DELETING or SysSnapshotEntryPB::FAILED) of the namespace which can fail as well due to IO failure.

**Comment by druzac** [comment]
This test exposes a valid issue with our db creation for YSQL in yb-master. It's possible to get into an inconsistent state with postgres metadata and yb-master metadata. The test exposes the problem by randomly failing IO:

1. CM receives `CreateNamespace`. It writes a sys catalog table entry with the namespace in the `PREPARING` state, and enqueues the async task `ProcessPendingNamespace`.
2. CM returns `OK` to YBClient.
3. YBClient loops calling `IsNamespaceCreateComplete` waiting for the namespace to transition to `RUNNING`.
4. `ProcessPendingNamespace` calls `CopyPgsqlSysTables`, which fails.
5. `ProcessPendingNamespace` updates the in-memory state of the namespace to `FAILED`. It also attempts to update the on-disk sys catalog table entry to `FAILED`, but whether or not this succeeds is immaterial.
6. Now when YBClient calls `IsNamespaceCreateComplete`, this method indicates to YBClient the creation failed.
7. YBClient tries to create the database again: `Already present (yb/master/catalog_manager.cc:8509): Keyspace 'basic_db_with_failures' already exists`
8. YBClient tries to drop the database: `ERROR:  database "basic_db_with_failures" does not exist`

At this point the name is effectively reserved and a db with that name cannot be created. I believe a master leader restart would fix this problem (assuming no further IO errors) as there is cleanup logic in the namespace loader, but I haven't tested this.

I believe the issue here is the postgres system catalog doesn't have any metadata for the table, but the CM's map `namespace_names_mapper_` does have an entry for this keyspace. Thus postgres will fail deletion attempts and the CM will fail creation attempts. The logic in CM to block creation of YSQL databases with the same name was introduced by 7fb3dd30310c07e9d1b26c07f61f26d6134bd8bb, which fixed a PGSQL creation race issue. In fact, given the logic in the namespace loader - it adds an entry in the `namespace_names_mapper_` for all namespaces except `DELETED` ones, and the async cleanup task for `FAILED`, `PREPARING`, and `DELETING` namespaces removes the entry - the uniqueness of keyspace names is a crucial system invariant, so 7fb3dd30310c07e9d1b26c07f61f26d6134bd8bb had the right idea.
