### ISSUE TITLE
[YSQL]: Create index must allow tablespace option

### ISSUE THREAD

**Issue by dodilp** [yugabyte/yugabyte-db#1466]
tablespace
The tablespace in which to create the index. If not specified, default_tablespace is consulted, or temp_tablespaces for indexes on temporary tables.

**Comment by OlegLoginov** [comment]
See the reference:
https://docs.yugabyte.com/latest/api/ycql/ddl_create_index/

`index_name cannot be qualified with a keyspace name because an index must be created in the table’s keyspace.`

Technically the index is a separate table, which is always located in the same keyspace as the original table. So, no sense to specify the keyspace name in the index name because it's automatically defined from the original table name.

The same in the Apache Cassandra:
https://docs.datastax.com/en/archived/cql/3.3/cql/cql_reference/cqlCreateIndex.html

The 'index_name' cannot contain the keyspace name here.

NOTE: the index name is optional (automatic index name in case if it's not specified).

**Comment by OlegLoginov** [comment]
Reopened the issue for YSQL.

**Comment by OlegLoginov** [comment]
Tablespaces in Postgres:
https://www.postgresql.org/docs/10/manage-ag-tablespaces.html

**Comment by ndeodhar** [comment]
@dodilp Tablespace in postgres is used to specify disk location and doesn't apply to YB. We don't support `CREATE TABLESPACE` command as well.
Can you add some more context about why you need support for this?

**Comment by deeps1991** [comment]
Supported via 238099e717e51fb5c3a14080e825bcaa4ab06c18.
