### ISSUE TITLE
Speed up bootstrap WAL processing by skipping over files with op_ids already in rocksdb

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#1468]
Upon node restart or remote bootstrap, once a TS has all the rocksdb SST files and the raft WAL files, it will process all the WALs and try to rebuild its in memory state, using the last flushed op_id in rocksdb as a cutoff to ignore entries in the WAL lower than that.

However, the way this works still relies on opening all of the WAL files and going over all the entries. We should be able to shortcut this by checking for the first op_id in every file and not processing files that have ops with IDs strictly smaller than the last one in rocksdb!

This is made even worse in remote bootstrap, as we take an explicit rocksdb checkpoint, thus flushing the mem table and likely rendering all WAL files unnecessary. However, we still keep a minimum set of WAL files (default last 2) and/or amount of time worth of ops (default 300s).

cc @rahuldesirazu @hectorgcr @spolitov @kmuthukk

**Comment by georgeklees** [comment]
I have been implementing and testing this code. However, there are two important matters that @bmatican and I wanted to address for clarification:

*  Right now, the WAL segment op IDs are checked against `state.regular_stored_op_id` to see if they are earlier than the most-recently flushed operation. However, when I print the value of `regular_stored_op_id` to the INFO log it is always `{ term: 0 index: 0 }`, which makes little sense (there should have been later entries that were flushed) and of course destroys the purpose of this optimization. Does someone have insight as to why this would be the case?

* At today's ybase meeting, it was pointed out that a change @spolitov made (@mbautin told me that it is https://phabricator.dev.yugabyte.com/D5660) might conflict with this optimization. We intend to skip reading all WAL entries with op ID < the last op ID flushed to RocksDB, but apparently some of these entries still need to be replayed to get the correct in-memory state. Can somebody who worked on that change provide more context, and their opinion on whether this optimization might still be workable?

**Comment by georgeklees** [comment]
After discussion last week we came up with a potential solution, but I want to run it by @spolitov to make sure that it seems okay, since he implemented the diff on retryable requests. The idea is that we will only worry about retaining information on retryable requests back a certain point in time (configurable through a gflag, defaulting to 90 seconds). So going backwards through WAL segments from the most recent one, we will know to stop going any further when the segment op ID < the last flushed op ID and the segment time < (last segment's time - retryable request retention limit). Does this sound alright?

cc @bmatican @rahuldesirazu @kmuthukk

**Comment by bmatican** [comment]
Turned on by default in 52541eb11c92e573a6357992c2fcfae8b08759e5
