### ISSUE TITLE
Support column families, grouping multiple columns into 1 kv

### ISSUE THREAD

**Issue by ddorian** [YugaByte/yugabyte-db#147]
I don't know how much more efficient the DocDB is compared to RocksDB, but cockroachdb ended up grouping all columns into 1 kv by default: https://www.cockroachlabs.com/docs/stable/column-families.html

This the same for cases when you mostly want to get back the whole array/map/set. 

Maybe even using the Merge operator https://github.com/facebook/rocksdb/wiki/Merge-Operator to add non-reading-updates like tokumx https://www.percona.com/doc/percona-tokumx/fast_updates.html

Makes sense ?

**Comment by rkarthik007** [comment]
Hi @ddorian,

Great points as always @ddorian! Here are some discussions we had originally about this architectural choice.

> I don't know how much more efficient the DocDB is compared to RocksDB, but cockroachdb ended up grouping all columns into 1 kv by default: https://www.cockroachlabs.com/docs/stable/column-families.html

Read the link, seems like cockroachdb keeps one kv by default for all rows (all the columns encoded in one row). If there are `FAMILY` definitions, the kvs cells are split across RocksDB column families but still stored as one row. Based on our Cassandra (entire row in one cell) vs HBase (one column per cell) experience, we felt  the "entire row per cell" approach is significantly better compared to the "one column per cell" approach if done carefully:

- reads are generally more efficient because they do not need to deserialize the entire row
- the key index is more uniform at locating data irrespective of the size of the values
-  the one column per cell is much better at handling tables with lots of columns (esp for complex types like JSON documents). This is because
    - in the "entire row per cell" approach, all the columns worth of data needs to be brought into memory, which causes significant increase in the memory used while compacting data. The "one column per cell" is much more memory-efficient because we only need one cell to compact, and the DB block can be a subset of the row.
    - Further, we prefix compress the individual cells in memory for a compact representation, so the extra bloat is pretty much not an issue.

- Lastly, we support per column TTL efficiently without having to deserialize the whole row

> This the same for cases when you mostly want to get back the whole array/map/set.

This can be achieved with the `FROZEN` keyword: https://docs.yugabyte.com/latest/api/cassandra/type_frozen/

> Maybe even using the Merge operator https://github.com/facebook/rocksdb/wiki/Merge-Operator to add non-reading-updates like tokumx https://www.percona.com/doc/percona-tokumx/fast_updates.html

We support fast updates - most inserts in Cassandra are "upserts". We do read-modify-write only if we need to `INSERT IF NOT EXISTS`.

**Comment by ddorian** [comment]
But `FROZEN` can only be updated as a whole no ?

**Comment by rkarthik007** [comment]
Ah I see your point. Yes `FROZEN` is a full update.

Our default is fine-grained updates and compactions bring data close together for efficient reads. We did not use merge operators, instead have made changes into the DocDB directly to be able to understand the layout of data on our modified RocksDB.

**Comment by ddorian** [comment]
This can be implemented in a jsonb blob, since it's stored as a single kv https://github.com/YugaByte/yugabyte-db/issues/26
