### ISSUE TITLE
[Platform] Test, backup, MAC: Incorrect backup size in JSON metafile

### ISSUE THREAD

**Issue by OlegLoginov** [yugabyte/yugabyte-db#14724]
### Description

Mac OS only!

The test `org.yb.pgsql.TestYbBackup.testBackupCreateGetBackupSize` is disabled for Mac OS because used command `du -sb` (in `yb_backup.py`) does not work on Mac.

Alternative way to calculate the backup size (works for Linux & Mac): `du -sk` * 1024

The Mac OS is not a production platform now, so the issue is not planned to be fixed yet.

Storage type = NFS.

**Comment by OlegLoginov** [comment]
Related diff:  https://phabricator.dev.yugabyte.com/D17095

**Comment by OlegLoginov** [comment]
Closing as `Won't fix` (may be reopened in future).

**Comment by jasonyb** [comment]
Linux `du -sb` is not equivalent to mac `du -sk` * 1024 because the former uses apparent size but the latter uses disk usage size.  Apparent size can be larger than disk usage size in case of sparse files, for example, or smaller in case of extremely small files (like a 10-char file being allocated by the filesystem as 4KB).

Mac appears to have a `-A` option for apparent size, and `-B` for block size can be set to 1 to avoid an extra x1024 calculation.
