### ISSUE TITLE
[YugabyteD] [QA] [Enhancement] Add Help for advanced flags supported in --config

### ISSUE THREAD

**Issue by zlareb1-yb** [yugabyte/yugabyte-db#14875]
### Description

Currently we don't have any help text for --config supported advanced flags like - 
```
--ycql_port
--ysql_port
--master_rpc_port
--tserver_rpc_port
--master_webserver_port
--tserver_webserver_port
--webserver_port
--callhome
--master_flags
--tserver_flags
--ysql_enable_auth
--use_cassandra_authentication
```

Our current help text is below:
`Use conf file to configure advanced flags. Learn more about advanced flags refer to the docs page: https://docs.yugabyte.com/preview/reference/configuration/yugabyted/#start.
`

We should give help text for these flags as well. Maybe we can give this help as part of an advanced flag command inside start command?

**Comment by nchandrappa** [comment]
@zlareb1-yb We don't want to overburden first-time users with these additional flags. One of the objectives of the yugabyted project is to simplify the user experience. We don't want the help text for these advanced flags in the command, all power users can go to the reference section for additional details. 

Initially, all these advanced flags were part of the start command, by design they were moved under advanced flags. I think we will need to add an example in docs on how to set the config file.

**Comment by zlareb1-yb** [comment]
Makes sense @nchandrappa . Closing this
