### ISSUE TITLE
A multi-region Kubernetes cluster has the same region displayed in YW Pods page

### ISSUE THREAD

**Issue by pallavisreerama** [YugaByte/yugabyte-db#1503]
A multi-region Kubernetes cluster has the same region displayed in Pods page even though the cluster is distributed geographically.

![image](https://user-images.githubusercontent.com/36684364/59137722-f94b9000-893d-11e9-90bc-037096da23d0.png)

**Comment by ramkumarvs** [comment]
We store the placement information in two places in YugaWare, and apparently for multi-cluster k8s universes, we never updated the placement information on the cloud info parameter inside of the node details. And this is where the UI pulls the data, which was the reason for the inconsistency. We have addressed this issue, and it is included as part release 1.2.11.0-b11.

**Comment by sraghavan-eqix** [comment]
Hi Ram,

After creating Universe if we try to click on the Universe to check this UI fix - the page goes blank.
I noticed in the logs also after creating Universe that there is some API that throws an error:

2019-06-10 20:32:19.594 ERROR UniverseController.java:373 [application-akka.actor.default-dispatcher-18] Unable to fetch cost for universe 232c7d02-84b2-4baf-8ffc-25e85b673202.

![Screen Shot 2019-06-10 at 2 07 15 PM](https://user-images.githubusercontent.com/47008714/59226984-1cb64b00-8b89-11e9-9553-afae09052fb3.png)

Screenshot above shows list of universes


Clicking on any of the universes renders the page blank. No information is seen.

Did an page inspect and this is what is seen.

![Screen Shot 2019-06-10 at 2 09 47 PM](https://user-images.githubusercontent.com/47008714/59227157-846c9600-8b89-11e9-8bfe-f46071cb97a5.png)

**Comment by sraghavan-eqix** [comment]
Just to give more clarity this issue is present when all 3 regions are selected for universe creation 
![Screen Shot 2019-06-10 at 7 47 46 PM](https://user-images.githubusercontent.com/47008714/59240265-a8939b80-8bb8-11e9-8595-75732ed0395f.png)

However, if universe is created In just one region and we click on the universe created we see the proper behavior.. 

![Screen Shot 2019-06-10 at 7 48 54 PM (2)](https://user-images.githubusercontent.com/47008714/59240334-e4c6fc00-8bb8-11e9-902f-92ca689fe962.png)
