### ISSUE TITLE
[YW] Add a widget for Inbound connections for the CQL proxies in YugaWare metrics

### ISSUE THREAD

**Issue by rao-vasireddy** [YugaByte/yugabyte-db#1528]
At the moment we do not display how many connections are there for the tserver. Please add a new widget for this in the tserver section of YW metrics.
@amitanandaiyer , please list which metric from the prometheus data can be used for this.

**Comment by amitanandaiyer** [comment]
something like: 
rpc_connections_alive { node_prefix="yb-prod-xxxx-prod0x", metric_id="yb.cqlserver" }

**Comment by rao-vasireddy** [comment]
@amitanandaiyer , if this is CQL specific then maybe it should be in the YCQL advanced. Do we have this metric for other connections also that can be listed in the tserver section by aggregating them?

**Comment by amitanandaiyer** [comment]
Yeah. YCQL advanced section should be good.

I don' thtink it makes sense to have this at the level of TServer since most of the connections to the Tservers would be from the proxies (controlled by us).

We could probably add a similar one for the Postgres/SQL at some point. But, the internals of that layer may be different from the CQL proxy, so it may be a different metric string. (@ndeodhar @m-iancu may know if we need it).

**Comment by yb-andrew** [comment]
Merged to master on 69a35685473d958fbad4fc47fee793442bb354c3
