### ISSUE TITLE
Build 1.2.10 - Ran into issues with Foreign Key

### ISSUE THREAD

**Issue by dodilp** [yugabyte/yugabyte-db#1558]
Try the following script - 
https://pgexercises.com/dbfiles/clubdata.sql

--
ALTER TABLE ONLY bookings
    ADD CONSTRAINT bookings_pk PRIMARY KEY (bookid);

--
ALTER TABLE ONLY bookings
    ADD CONSTRAINT fk_bookings_facid FOREIGN KEY (facid) REFERENCES facilities(facid);

--See screenshots
<img width="687" alt="Screen Shot 2019-06-17 at 1 09 52 AM" src="https://user-images.githubusercontent.com/2207029/59632477-4a1a7000-9118-11e9-85b7-528f91ae8177.png">
<img width="679" alt="Screen Shot 2019-06-17 at 1 04 01 AM" src="https://user-images.githubusercontent.com/2207029/59632482-4e468d80-9118-11e9-90dd-9eabb6cb0292.png">

**Comment by ndeodhar** [comment]
Hi @dodilp, this is because we don't support adding primary key after the table is created. So, these 2 statements for example, will error out:
```
ALTER TABLE ONLY bookings
    ADD CONSTRAINT bookings_pk PRIMARY KEY (bookid);

ALTER TABLE ONLY facilities
    ADD CONSTRAINT facilities_pk PRIMARY KEY (facid);
```

To work around this, you can specify the primary key in the `CREATE TABLE` statement. Let me know if that works for you.
Note that you can use `ALTER TABLE ... ADD CONSTRAINT` to add a foreign key after table has been created.

**Comment by dodilp** [comment]
Thank you, @ndeodhar. The workaround was successful and it's working now.

**Comment by m-iancu** [comment]
Closing as adding a primary key after the table is created is now supported in a limited way (after commit https://github.com/lizayugabyte/yugabyte-db/commit/fd257e7faaf701439cdaf1ff936cc46fc0f8927d).
Note that pre-creating the table with the appropriate primary key is still recommended.
