### ISSUE TITLE
[YSQL] Select from 'information_schema.columns' causes assertion failure

### ISSUE THREAD

**Issue by d-uspenskiy** [YugaByte/yugabyte-db#1576]
On `centos` `debug` version  simple query

```
SELECT * FROM information_schema.columns;
```
causes

```
Check failed: !request.has_paging_state() Optimization failure due to wrong assumption
```

error. Cluster become unavailable.

**Comment by nocaway** [comment]
This bug has been fixed by commit https://github.com/YugaByte/yugabyte-db/commit/77a9af06dd4ccb4a68078c031e9683cf10f2495e.

The fix was to add an optimization for scanning when range-key is not fully specified. Our storage layer (DocDB) hadn't supported this operation prior to this bug-fix.  However, the proxy-server assumed it had and therefore sent a request to DocDB to apply this optimization.
