### ISSUE TITLE
[Jepsen] [YSQL] Inconsistency in bank-multitable test 

### ISSUE THREAD

**Issue by frozenspider** [YugaByte/yugabyte-db#1577]
(This test isn't possible in YCQL)
We're observing inconsistency in both YSQL banking test (transactionally moves funds around from one account to another, each in its own table) - even without any nemeses funds total diverge from initial $100

**Note that this issue is far from being 100% reproducible. I had more luck catching it with `--concurrency 20` setting.**

Full logs: 
[logs-jepsen_2019-06-20_19-15-21__bank-multi.tar.gz](https://github.com/YugaByte/yugabyte-db/files/3310819/logs-jepsen_2019-06-20_19-15-21__bank-multi.tar.gz)

Reproducible with master ad50ea9, related to #938 and #1553

**Comment by ttyusupov** [comment]
This test is not intended to work for YCQL because there is no support for multiple select statements inside a single transaction. This is commented in the test code:
```
;; Shouldn't be used until we support transactions with selects.
(c/defclient CQLMultiBank keyspace []
```
https://github.com/YugaByte/jepsen/blob/master-yb/yugabyte/src/yugabyte/ycql/bank.clj#L63

As for YSQL - please double check that selects are wrapped in a transaction.

**Comment by frozenspider** [comment]
@ttyusupov Thanks, you're right, this test isn't applicable to YCQL, edited the description to refrlect that.
This still actual for YSQL though - transactions for `SELECT`s are in place.
