### ISSUE TITLE
YEDIS 'set' call failure with 1,000 or more active connections

### ISSUE THREAD

**Issue by JackDavidson** [YugaByte/yugabyte-db#1612]
When many connections are active to YEDIS (about 1,000 or more) set calls fail.

The interesting thing is that it takes a couple seconds before the set calls start to fail. For example, the following python usually runs successfully:

```
from redis import Redis
import time

conns = []

n = 1000

for i in range(1,n + 1):
  new_conn = Redis('127.0.0.1')
  new_conn.set(i, 'connected.')
  conns += [new_conn]
  if (i % 1000 == 0):
    print('established ' + str(i) + ' connections.')

while True:
  time.sleep(100)

```

But if you then give it a moment and try the redis-cli you will see that the set command now fails:

./bin/redis-cli 
127.0.0.1:6379> get a
"b"
127.0.0.1:6379> set a d
(error) Write(tablet: fb1c4fc5836340259f987b424d86ee23, num_ops: 1, num_attempts: 5, txn: 00000000-0000-0000-0000-000000000000) passed its deadline 2393.616s (passed: 3.853s): Remote error (yb/rpc/local_call.cc:96): Local call error
(3.85s)

Disconnecting/killing the python program allows set commands to start working again.

**Comment by kmuthukk** [comment]
Reposting [my response on StackOverflow](https://stackoverflow.com/questions/56727844/interface-connection-limit-configuration) here.

Thanks for reporting this issue, and the additional input on the YugaByte slack channel to help isolate the issue.

Turned out there were two issues at play here:

a) When a `yb-tserver` is launched on its own, it assumes it can use 85% of the system RAM (and this is configurable), but the `yb-ctl` way of launching a test cluster only gives the `yb-tserver` process 1GB of RAM by default.

b) For YEDIS connections, the fixed overhead of each connection was 1MB. So at about 8000 connections, this overhead itself would require about 8GB of memory. This is controlled by the `redis_rpc_block_size` `yb-tserver` gflag that defaults to 1MB.

Due to these two factors, writes to the system were being rejected with the following error:
```
I0624 21:32:28.317205  6772 maintenance_manager.cc:341] we have exceeded our soft memory limit (current capacity is 136.82%).  However, there are no ops currently runnable which would free memory.
```

The following overrides should unblock your workload:
```
 ./yb-ctl destroy
 ./yb-ctl start --disable_ysql --tserver_flags="redis_rpc_block_size=131072,memory_limit_hard_bytes=6000000000"
 ./yb-ctl setup_redis
```
The above memory_limit_hard_bytes value of ~6GB assumes that you have a 8GB machine. Note that the yb-master's memory requirements aren't too high.
