### ISSUE TITLE
[YSQL] [Unit Test] Unit Test QLTabletTest.GetMiddleKey got flaky

### ISSUE THREAD

**Issue by rjalan-yb** [yugabyte/yugabyte-db#16426]
Jira Link: [DB-5836](https://yugabyte.atlassian.net/browse/DB-5836)
### Description

With commit [3d4ce592](https://github.com/yugabyte/yugabyte-db/commits/3d4ce5926dc3ebf6cbaa0e499fe1a6a9d01a6fa8), Unit Test QLTabletTest.GetMiddleKey got very flaky across builds with the error:

```
../../src/yb/client/ql-tablet-test.cc:1437
Expected: (num_keys_less_percent) <= (60), actual: 62 vs 60
```
Stability Trend Page: https://detective-gcp.dev.yugabyte.com/stability/test?analyze_trends=true&class=QLTabletTest&name=GetMiddleKey&num_commits=500

Before this commit, it did not fail this frequently.

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-5836]: https://yugabyte.atlassian.net/browse/DB-5836?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by arybochkin** [comment]
Looks like this is a side effect from #15027 and packed rows enabling by default just increased the probability of the failure. Previously middle key was selected from the largest SST file. But since #15027 resulting middle key is taken as a weighted (on base of file size) middle point of middle key of all SST files. In practice it means: 1) all SST files are sorted on base of its middle key, 2) file sizes are summed up until half of the total size is reached, 3) middle key is taken from a file on which half of the total size is reached. This means the largest file may even not be considered as a candidate for a middle key -- and this is the case when test fails.
From the logs:
1) Failure case:
```
file1: 397937 bytes
file2: 89668 bytes
file3: 89518 bytes
file4: 90201 bytes
file5: 89640 bytes
file6: 67031 bytes
total size: 823995 bytes
half size: 411997 bytes
files order selection: file6, file2, file3, file5, file4 — middle key selection from small file
```
2) Success case:
```
file1: 395551 bytes
file2: 89561 bytes
file3: 89531 bytes
file4: 89535 bytes
file5: 89439 bytes
file6: 68156 bytes
total size: 821773 bytes
half size: 410886 bytes
files order selection: file5, file4, file3, file2, file1 — middle key selection from the largest file
```
Turns out middle key selection algorithm should be modified to cover such cases. Also it is looking reasonable to put #15027 behind some gflag.

**Comment by arybochkin** [comment]
Fixed, test name was changed to:

> QLTabletRf1TestToggleEnablePackedRow.GetMiddleKey/0
> QLTabletRf1TestToggleEnablePackedRow.GetMiddleKey/1
