### ISSUE TITLE
[YSQL] Handle or avoid "Unknown session" error

### ISSUE THREAD

**Issue by timothy-e** [yugabyte/yugabyte-db#16445]
Jira Link: [DB-5852](https://yugabyte.atlassian.net/browse/DB-5852)
### Description

PostgreSQL process serving the client connection can  time out and left with a "Unknown session" error. To recover from this error,  user has to terminate the connection and recreate new connection. 

Elevate the "Unknown session" error to FATAL error to auto terminate the PostgreSQL process and avoid having client to cleanup the connection.

In certain scenarios, It would be a better experience  to recreate the session to avoid  "Unknown session" error though that aspect is not covered by this issue.

Looks like it’s referring to the PgClient service session (pggate to tserver connection): 

https://github.com/YugaByte/yugabyte-db/blob/master/src/yb/tserver/pg_client_service.cc#L491-L500

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-5852]: https://yugabyte.atlassian.net/browse/DB-5852?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by jasonyb** [comment]
This happens when pg client session expires.  tserver maintains a pg client session for each postgres backend.  It is kept alive by heartbeats between those two processes.  If heartbeat does not happen within `FLAGS_pg_client_session_expiration_ms` (default 60000ms = 1m), the session is destroyed.  So next time a pg request from that client comes in, it won't have the proper session state.  Session state includes

```
  const uint64_t id_;
  client::YBClient& client_;
  scoped_refptr<ClockBase> clock_;
  const TransactionPoolProvider& transaction_pool_provider_;
  PgTableCache& table_cache_;
  const XClusterSafeTimeMap* xcluster_safe_time_map_;
  std::shared_ptr<PgMutationCounter> pg_node_level_mutation_counter_;
  PgResponseCache& response_cache_;
  PgSequenceCache& sequence_cache_;

  std::array<SessionData, kPgClientSessionKindMapSize> sessions_;
  uint64_t txn_serial_no_ = 0;
  boost::optional<uint64_t> saved_priority_;
  TransactionMetadata ddl_txn_metadata_;
  UsedReadTime plain_session_used_read_time_;
```

I am not certain, but it looks like there is important state that should not be lost within the same session.  Definitely cannot spawn a new session and resume a transaction since that loses txn state.  It may be possible to spawn a new session if we abort the current transaction, but the correctness of that needs to be reviewed.  For example, it could result in caches (like table cache, sequence cache) being refreshed more than you'd expect (e.g. it could refresh even if there's no catalog version bump detected).

It would be good to know what cases actually hit this in practice, since this shouldn't happen apart from a debugger stopping execution.

**Comment by jameshartig** [comment]
There's a duplicate issue that I commented on https://github.com/yugabyte/yugabyte-db/issues/19218#issuecomment-1839676159

Ideally this would be a "fatal" error as it pertains to the postgres format so that drivers can immediately terminate the connection.
