### ISSUE TITLE
PSQLException: ERROR: Operation only supported in SERIALIZABLEisolation level

### ISSUE THREAD

**Issue by intellectcubed** [yugabyte/yugabyte-db#1647]
Jira Link: [DB-1407](https://yugabyte.atlassian.net/browse/DB-1407)
[YugabyteStackTrace.txt](https://github.com/YugaByte/yugabyte-db/files/3337075/YugabyteStackTrace.txt)

Getting the attached stack trace warning me about the "Operation only supported in SERIALIZABLEisolation level".  The stack trace actually refers to a current issue, but I'm not clear what the problem is, nor how to resolve it.  My code works fine when pointing to Postgresql, but when I change to Yugabyte, I get the exception.

More info:
I am using straight hibernate from Java.  A schema and tables are auto created, but when I try to insert into that table, I get this exception.

Here is a code snippet: 

        Session session = openCurrentSession();
        Transaction transaction = session.beginTransaction();
        try {
            session.save(entity);
            transaction.commit();
        } catch(RuntimeException rte) {
            transaction.rollback();
        }
        session.close();

**Comment by kmuthukk** [comment]
Like related to https://github.com/YugaByte/yugabyte-db/issues/1199

Does the table have FK constraints?

**Comment by intellectcubed** [comment]
Hi,
No, I made sure not to have FK constraints.
    On Thursday, June 27, 2019, 08:37:02 PM EDT, Kannan Muthukkaruppan <notifications@github.com> wrote:  
 
 
Like related to #1199

Does the table have FK constraints?

**Comment by ndeodhar** [comment]
@intellectcubed This is most likely because `hibernate` is using foreign keys / triggers under the hood. Can you try doing this?:
1. Update `postgresql.conf` file located in `$yugabyte_data_dir/node-1/disk-1/pg_data/` folder and add the line `default_transaction_isolation='serializable'`.
2. Do step (1) on all nodes where you've installed YB and then restart `yb-tserver` process on those nodes. Note that if you're using local setup, you can restart using `./bin/yb-ctl restart`.

Now, you should not see the error while running your app.

**Comment by sushantrmishra** [comment]
@intellectcubed  . Please try out the suggestion in https://github.com/yugabyte/yugabyte-db/issues/1647#issuecomment-516512373 and reopen the issue if still a problem.
