### ISSUE TITLE
Support conditional DMLs in transaction statement block

### ISSUE THREAD

**Issue by robertpang** [yugabyte/yugabyte-db#166]
Support conditional DMLs in transaction statement block in YugaByte DB. When a conditional DML fails to execute because the condition is not satisfied, the transaction should be aborted. For example,

```SQL
BEGIN TRANSACTION
  UPDATE inventory SET total = total - 1 WHERE item_id = 4012 IF total >= 1;
  INSERT INTO orders (order_id, customer_id, item_id) VALUES (10000423, 1001, 4012);
END TRANSACTION;
```

**Comment by m-iancu** [comment]
As a first step, we could start this by allowing `IF` conditions if and only if `ELSE ERROR` option is used.
In that case the failing condition will cause an error and abort the transaction as expected.

## Implementation

Code-wise this could be started with the simple change in analyzer (`list_node.cc`):
```
-      if (dml->if_clause() != nullptr) {
+      if (dml->if_clause() != nullptr && dml->else_error() == false) {
         return sem_context->Error(dml,
-                                  "Conditional DML not supported in a statement batch yet",
+                                  "batch execution of conditional DML statement without ELSE ERROR"
+                                  " is not supported yet",
                                   ErrorCode::CQL_STATEMENT_INVALID);
```

## Example
The the following should work as below:

### Set up a (transactional) table
```
create keyspace sample;
use sample;
create table test(h int, r int, v int, primary key(h,r)) with transactions = { 'enabled' : true };
```

### Insert some rows in a transaction
```
begin transaction
  insert into test(h,r,v) values (1,1,11) if not exists else error;
  insert into test(h,r,v) values (1,2,12) if not exists else error;
end transaction;
```
```

 [applied]
-----------
      True
      True
```

### Run a block of inserts where one will fail (because of `IF` condition)

```
begin transaction
  insert into test(h,r,v) values (2,2,11) if not exists else error;
  insert into test(h,r,v) values (1,2,12) if not exists else error;
end transaction;
```
```
InvalidRequest: Error from server: code=2200 [Invalid query] message="Execution Error. Condition was not satisfied.
begin transaction
  insert into test(h,r,v) values (2,2,11) if not exists else error;
  insert into test(h,r,v) values (1,2,12) if not exists else error;
      ^^^^^
end transaction;
 (ql error -300)"
```

### Confirm txn was rolled back:
```
cqlsh:sample> select * from test;

 h | r | v
---+---+----
 1 | 1 | 11
 1 | 2 | 11

(2 rows)
```

## Some additional notes:
1. Need to test this thoroughly along the lines of [returns status test](https://github.com/yugabyte/yugabyte-db/blob/master/java/yb-cql/src/test/java/org/yb/cql/TestReturnsClause.java) as there are a lot of combinations that should work and also that should be disallowed.
2. This should also work for multiple tables in one txn (example above is for one table only). This should be explicitly tested.
3. Should we allow `returns_status` in transactions (`RETURNS STATUS AS ROW`). For now would suggest disable it by adding a new check in `list_node.cc` (see above).
4. It may be hard to identify the failing query. Parser normally tries to show the location with `^^^` but in case that is not reliable the `ELSE ERROR` message could include at least the table name.

Also, as future we could consider whether returns status or conditional dmls in general can also be allowed. Right now, each returned row may have different schema (depending on whether the condition succeeds or failing -- e.g. `applied` vs `applied, message`) causing the result set to have (de)serialization issues.

**Comment by OlegLoginov** [comment]
Fixed by the commit above.
