### ISSUE TITLE
[DocDB] Enable automatic_tablet_splitting for new clusters using AutoFlags

### ISSUE THREAD

**Issue by rthallamko3** [yugabyte/yugabyte-db#16807]
Jira Link: [DB-6154](https://yugabyte.atlassian.net/browse/DB-6154)
### Description

Enable automatic_tablet_splitting for new clusters using AutoFlags, to avoid upgrades from getting the feature by default. Clusters that are being upgraded from below 2.18 needs manual inspection around existing tablet sizes and whether the splits will run into long running compactions that can potentially cause writes to get throttled etc.

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-6154]: https://yugabyte.atlassian.net/browse/DB-6154?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by arybochkin** [comment]
@rthallamko3 current implementation of autoflags does not support such behaviour: to keep configured value for upgrades and use new value for setups from scratch.

**Comment by hari90** [comment]
This is a limitation with splitting. How about a max_tablet_spkit_size_GB=5 flag so that only large tablets don't get split after upgrade. Medium size and newly created tablets will kepp splitting and not reach the max size limit. Customers can set max_tablet_spkit_size_GB to a higher value during maintenance windows.
