### ISSUE TITLE
[YSQL] Fix FailedAssertion("!(YbIsSearchNull(key))"

### ISSUE THREAD

**Issue by jasonyb** [yugabyte/yugabyte-db#16927]
Jira Link: [DB-6263](https://yugabyte.atlassian.net/browse/DB-6263)
### Description

When working on issue #16926, changing indexes to range caused failure in yb_pg_aggregates, line `select max(unique1) from tenk1 where unique1 < 42;`.  I derive a smaller repro from that:

```sql
create table t (i int);
create index on t (i asc);
select max(i) from t where i < 42;
```

```
TRAP: FailedAssertion("!(YbIsSearchNull(key))", File: "../../../../../../../src/postgres/src/backend/access/yb_access/yb_scan.c", Line: 1400)
2023-04-18 18:50:36.801 PDT [2602134] WARNING:  server process (PID 154062) was terminated by signal 6: Aborted
2023-04-18 18:50:36.801 PDT [2602134] DETAIL:  Failed process was running: select max(i) from t where i < 42;
```

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-6263]: https://yugabyte.atlassian.net/browse/DB-6263?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by jasonyb** [comment]
Note `Assert`s are not hit in release build: I was running a fastdebug build.

Only min/max seem to have the issue.  Tried count, sum, avg, but they're fine.  Alternatively, removing the WHERE clause also does not hit the assertion.

**Comment by tanujnay112** [comment]
It would appear that we have this issue whenever we have a query `k IS NOT NULL AND <simple condition on k>` where `k` is an index key. These clauses are automatically generated in the case of `max/min(k)` + `clause on k` as above. It seems like we have been trying to bypass handling `IS NOT NULL` in a hackyish way in `yb_scan.c`, causing such anomalies. Since DocDB can handle `IS NULL`/`IS NOT NULL` filters now, we should try to simply push down these filters.

**Comment by m-iancu** [comment]
Not able to repro on latest:
```
ysqlsh (11.2-YB-2.19.1.0-b0)
Type "help" for help.

yugabyte=# create table t (i int);
CREATE TABLE
yugabyte=# create index on t (i asc);
CREATE INDEX
yugabyte=# select max(i) from t where i < 42;
``` 
This is with a DEBUG build:
```
version 2.19.1.0 build PRE_RELEASE revision d5809e26064d375de77cb32274231fadb22cb82e build_type DEBUG
```
@jasonyb Can you validate if it's still there -- else we can close it.

**Comment by jasonyb** [comment]
@m-iancu Cannot repro.  Someone should figure out which commit fixed it.

**Comment by m-iancu** [comment]
Tracking through commits a bit I suspect https://github.com/yugabyte/yugabyte-db/commit/cd0d8589a788fc79f78822cef5448ee330a80083 by @foucher might have fixed it (specifically the changes in `yb_scan.c`).
This is because the plan for min max involves an `IS NOT NULL` (i.e. max on an ASC-ordered column is a limit 1, backwards scan with `IS NOT NULL` set).

```
explain select max(i) from t where i < 42;
                                          QUERY PLAN
----------------------------------------------------------------------------------------------
 Result  (cost=0.52..0.53 rows=1 width=4)
   InitPlan 1 (returns $0)
     ->  Limit  (cost=0.00..0.52 rows=1 width=4)
           ->  Index Only Scan Backward using t_i_idx on t  (cost=0.00..5.22 rows=10 width=4)
                 Index Cond: ((i IS NOT NULL) AND (i < 42))
(5 rows)
```
From local testing it does look that we are handling such cases correctly too (though the `IS NOT NULL` condition is redundant in this case).

**Comment by jasonyb** [comment]
The tests in yb_pg_aggregates.sql should be uncommented: @foucher
