### ISSUE TITLE
[DocDB][Jepsen] Enabling local transactions table for geo partitioned case leads to TX inconsistencies

### ISSUE THREAD

**Issue by qvad** [yugabyte/yugabyte-db#17319]
Jira Link: [DB-6539](https://yugabyte.atlassian.net/browse/DB-6539)
### Description

New test case
1. Start cluster with geo flags
2. Change append test so tables are geo distributed, row partitioned. 
3. After running test w/o creating local transactions table it is passed.

PR in yugabyte/jepsen repository with all code changes
https://github.com/yugabyte/jepsen/pull/96

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-6539]: https://yugabyte.atlassian.net/browse/DB-6539?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rthallamko3** [comment]
@qvad , Can you share the instructions to run the Jepsen tests locally? cc @es1024

**Comment by bmatican** [comment]
Reducing backports to just 2.18 and 2.20, as per @cdavid cc @rthallamko3

**Comment by rthallamko3** [comment]
Summary: Aborted transaction showing up as committed to the user.

When we promote a transaction from local to global in geo-partitioning deployments, we send UpdateTransactionStatusLocation RPCs immediately, without waiting for the first PROMOTED heartbeat to the new transaction coordinator. This can leave a small window where participants are pointed to the new coordinator that does not yet recognize the transaction. If the transaction is aborted due to conflict during this window, the new transaction coordinator won't do anything (since it's an unrecognized transaction), and then later when the PROMOTED heartbeat finally arrives, the new transaction coordinator sets up the new transaction without realizing that the transaction should have been aborted, resulting in the transaction that should have been aborting continuing on and eventually committing.

Additionally, if a participant queries the coordinator for transaction status in this window, the coordinator will return that the transaction is aborted (due to not recognizing it), and cause the transaction to be unnecessarily aborted via the participant.

The fix delays the sending of UpdateTransactionStatusLocation RPCs to after the response of the first PROMOTED heartbeat is received, to fix the above problem.
