### ISSUE TITLE
[YSQL] Support NULLS LAST option in SELECT query

### ISSUE THREAD

**Issue by m-iancu** [YugaByte/yugabyte-db#1734]

**Comment by mrpanda** [comment]
If this is going to be added, then can I request that the same capability is added to index creation as documented in https://www.postgresql.org/docs/11/indexes-ordering.html 

Thanks

**Comment by ndeodhar** [comment]
Hi @mrpanda, we are tracking the work for supporting NULLS LAST in index creation here: https://github.com/YugaByte/yugabyte-db/issues/1723. We created two separate issues because supporting it during index creation requires some additional work in DocDB layer whereas enabling it in SELECT is only a grammar change.

We are actively working on both these and hope to have these available in the next couple of weeks.
