### ISSUE TITLE
pg SET timezone bug also in YB [YSQL]

### ISSUE THREAD

**Issue by mrpanda** [YugaByte/yugabyte-db#1738]
I don't know how you want to treat this, but I was able to replicate this problem in pg 11.4.1 so it is not unique to YB.

The problem is the SET timezone functionality is using the inverse sign of the time offset. See the example below:

```sql
postgres=# select current_timestamp;
       current_timestamp       
-------------------------------
 2019-07-09 02:18:16.257668+00
(1 row)

postgres=# SET timezone = 'Australia/Sydney';
SET
postgres=# select current_timestamp;
       current_timestamp       
-------------------------------
 2019-07-09 12:18:33.881477+10
(1 row)

postgres=# SHOW timezone;
     TimeZone     
------------------
 Australia/Sydney
(1 row)

postgres=# SET timezone = '+10:00:00';
SET
postgres=# SHOW timezone;
 TimeZone  
-----------
 +10:00:00
(1 row)

postgres=# select current_timestamp;
       current_timestamp       
-------------------------------
 2019-07-08 16:19:22.721011-10
(1 row)

postgres=# SET timezone = '-10:00:00';
SET
postgres=# SHOW timezone;
 TimeZone  
-----------
 -10:00:00
(1 row)

postgres=# select current_timestamp;
       current_timestamp       
-------------------------------
 2019-07-09 12:19:48.872958+10
(1 row)

postgres=# SET timezone = 'Australia/Sydney';
SET
postgres=# select current_timestamp;
       current_timestamp       
-------------------------------
 2019-07-09 12:20:07.304223+10
(1 row)
```

You can see that Australia/Sydney works fine (UTC+10), but if I manually set this to +10, then it sets it to -10, and if I set it to -10, it sets it to +10. Weird.

What do you want to do ?

**Comment by ndeodhar** [comment]
@mrpanda Thanks for pointing this out - will be good to add this to our documentation. This is expected behavior per postgres docs:
`Another issue to keep in mind is that in POSIX time zone names, positive offsets are used for locations west of Greenwich. Everywhere else, PostgreSQL follows the ISO-8601 convention that positive timezone offsets are east of Greenwich.`
from: https://www.postgresql.org/docs/11/datatype-datetime.html#DATATYPE-TIMEZONES

**Comment by mrpanda** [comment]
OK, I will add to my documentation. Thanks
