### ISSUE TITLE
[DocDB] Add HTTP security headers

### ISSUE THREAD

**Issue by Nithinignatius** [yugabyte/yugabyte-db#17401]
Jira Link: [DB-6584](https://yugabyte.atlassian.net/browse/DB-6584)
### Description

Add the following HTTP Security headers on the webserver which DB uses for the processes that access ports 7000, 9000 and 13000.

1. HTTP Strict Transport Security header (HSTS)
```
    Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
```
2. X-Content-Type-Options
```
    X-Content-Type-Options: nosniff
```

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-6584]: https://yugabyte.atlassian.net/browse/DB-6584?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by ionthegeek** [comment]
In current master branch, the http headers are set in `src/yb/server/webserver.cc` around lines 645 / 652.

It doesn't look like we have an existing mechanism for customizing the http headers (they're mostly hard-coded at the moment). While we could add these headers to the hard-coded list (possibly behind a gflag), it might be better to add a general mechanism for customizing the http headers produced by the embedded web server.

From past experience, requests to customize http headers aren't frequent but tend to be high impact / high visibility because they're often security related.

**Comment by rthallamko3** [comment]
The fixes were done as part of https://github.com/yugabyte/yugabyte-db/issues/17608
