### ISSUE TITLE
[docs] Anchor links seem broken

### ISSUE THREAD

**Issue by bmatican** [YugaByte/yugabyte-db#1757]
I was using our docs search: https://docs.yugabyte.com/search/?q=sysctl

The one result pointed to: https://docs.yugabyte.com/latest/quick-start/install/#prerequisites

This apparently first loads the page, then blanks the body.

Finally, when you click on, say, the linux tab, it correctly loads, but does not change the link to the new anchor.

cc @rkarthik007 @schoudhury @vitpankin

**Comment by yb-andrew** [comment]
The first issue if the docs search leading to a broken link is due to my change here: https://github.com/YugaByte/docs/pull/114
I think we'll have to update algolia or our config file

Second issue of the tab not changing the url from the anchor link is due to my change here: https://github.com/YugaByte/docs/pull/108
I have a solution for this issue.

**Comment by yb-andrew** [comment]
Fixed anchor links issue but Algolia search may still be outdated
