### ISSUE TITLE
[DocDB] pg_locks results won't include awaiting lock info of fast path transactions

### ISSUE THREAD

**Issue by basavaraj29** [yugabyte/yugabyte-db#18195]
Jira Link: [DB-7217](https://yugabyte.atlassian.net/browse/DB-7217)
### Description

After https://github.com/yugabyte/yugabyte-db/issues/16914 lands, `GetLockStatus` wouldn't return awaiting locks corresponding to fast path transactions.

Transactions coordinators don't track fast path transactions. Post the above change lands, we would query the txn coordinators for old transactions, and then send rpcs to involved tablets alone. Implies that we would no more be returning locks corresponding to fast path transactions. 

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-7217]: https://yugabyte.atlassian.net/browse/DB-7217?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by robertsami** [comment]
one thing we could do is register these waiters with the localwaitingtxnregistry, and then we would still need to send a request to every tserver from pg_client_service, but instead of checking every tablet they need only check this one component. one caveat is that fast-path waiters are restarted every 30s, so we may not have an accurate read on the true age of these waiters
