### ISSUE TITLE
[YSQL] Support TLS Server-Server Encryption through YSQL API

### ISSUE THREAD

**Issue by m-iancu** [yugabyte/yugabyte-db#1845]
Currently, if [Server-Server Encryption](https://docs.yugabyte.com/latest/secure/tls-encryption/server-to-server/) is enabled for `yb-master` and `yb-tserver` processes, the settings do not propagate to the YSQL-connections processes.
Therefore, the internal queries from the YSQL connection processes to the master/tserver get rejected. 
Instead, we should inherit the settings from the parent `yb-tserver` process (we should already inherit the gflags so likely there is some extra step needed).

**Comment by kntait** [comment]
I am experience the same issue, this is preventing me from being able to use Yugabytedb as i can't enable cluster TLS and use YSQL. 

I see this missed the v2.0.0 release, will this be fixed in the next release?

**Comment by ndeodhar** [comment]
Hi @kntait This is in active development and TLS for YSQL will likely be available in a minor release in 3-4 weeks.

**Comment by kntait** [comment]
Thanks @ndeodhar.  Just to clarify are you saying that in addition to this issue being fixed you are also going to support client TLS connectivity for the YSQL API?

**Comment by ndeodhar** [comment]
@kntait yes. You can use https://github.com/yugabyte/yugabyte-db/issues/2471 to track progress on client-server TLS.

**Comment by dmosruby** [comment]
I'm a little bit confused about the name of this issue versus what was actually fixed/the problem. 

- The name is referring to **Server-Server** communication, which on the way the document states it, should be the interaction between yb-master and yb-tserver.
- Versus **Client-Server** communication which is the corresponding APIs for YCQL, YSQL, and YEDIS. 

As the documentation says - [TLS Encryption](https://docs.yugabyte.com/latest/secure/tls-encryption/) YCQL was the only one currently supported with YSQL being in progress (which is what I assume was fixed in 2.0.3 and with the PRs mentioned in this issue) and YEDIS which is not currently supported. 

- Was I wrong in assuming though that **Server-Server** TLS wasn't completely separate from the supported APIs for **Client-Server** TLS and that if I use YEDIS or the 2.0.0 version of YSQL to communicate, some of the network traffic between **Server-Server** will not be TLS encrypted?
- Or was this issue misnamed and in reality it was only tracking the **Client-Server** TLS being unsupported until recently for YSQL and **Server-Server** TLS is fully functional no matter the API being used on the tserver to store/query data?

**Comment by ndeodhar** [comment]
@dmosruby Both server-server and client-server TLS wasn't ready for YSQL :) With this issue, @d-uspenskiy has fixed server-server TLS. Supporting client-server TLS for YSQL is still being worked on and is tracked here: https://github.com/yugabyte/yugabyte-db/issues/2471

**Comment by dmosruby** [comment]
@ndeodhar do you know if the YEDIS Server-Server tls is working today then?
Its strange for me that the Server-Server tls even matters about what API you used to store data. If this is the case, the documentation should definitely be updated because the Server-Server tls makes no mention to not having been working based on the API used to store data, while the Client-Server tls documentation does make that distinction.

**Comment by ndeodhar** [comment]
@dmosruby We don't support TLS for YEDIS. See note here:
https://docs.yugabyte.com/latest/secure/tls-encryption/

Are you using YEDIS? And do you need TLS for YEDIS?

**Comment by dmosruby** [comment]
@ndeodhar using kubernetes sidecar I was able to implement a TLS proxy service for the tserver to handle TLS termination when talking to the YEDIS client. I was more worried that when interacting with YEDiS, the tserver talks over the Server-Server communication line and some of that might not be encrypted.

**Comment by ndeodhar** [comment]
Yes, Server-server communication as detailed in https://docs.yugabyte.com/latest/secure/tls-encryption/server-to-server/ will work for YEDIS, but client-server won't.

**Comment by dmosruby** [comment]
Awesome 😃 thank you for clarifying!
