### ISSUE TITLE
[DocDB] Transaction gets added to the wait queue but never gets released causing RPC timeout

### ISSUE THREAD

**Issue by shishir2001-yb** [yugabyte/yugabyte-db#18520]
Jira Link: [DB-7477](https://yugabyte.atlassian.net/browse/DB-7477)
### Description

Tried on version **2.19.1.0-b397**

While running parallel transaction(Read Committed Isolation level)  some of the Transaction fails with RPC timeout. In  the Postgres log I didn't see any repeated retries from Postgres except 1 retry. @pkj415 and I are thinking that the transaction was added to the wait queue but never got released.

```com.yugabyte.util.PSQLException: ERROR: Perform RPC (request call id 90) to 172.151.29.40:9100 timed out after 602.000s```

Steps to repro: (I have a local sample app which can used to repro this issue)
```
1. "CREATE TABLE %s (k VARCHAR PRIMARY KEY, v1 VARCHAR, v2 INTEGER);
2. Start 8 parallel transaction and perform the following operation
       a. BEGIN;
       b. "INSERT 10 rows in the table"
       c. "UPDATE table SET V1='ABC' WHERE k LIKE '%s'" %s-> Can be any alphabetical character
       d. SELECT k FROM %s WHERE k LIKE '%s'" %s-> Can be any alphabetical character
       e. COMMIT;
       
```
Tserver and Master Flags
```
yb_enable_read_committed_isolation : True
enable_deadlock_detection: True
enable_wait_queues: True
```
[172.151.29.40-logs.tar.gz](https://github.com/yugabyte/yugabyte-db/files/12240774/172.151.29.40-logs.tar.gz)
[172.151.33.79-logs.tar.gz](https://github.com/yugabyte/yugabyte-db/files/12240775/172.151.33.79-logs.tar.gz)
[172.151.54.33-logs.tar.gz](https://github.com/yugabyte/yugabyte-db/files/12240776/172.151.54.33-logs.tar.gz)

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-7477]: https://yugabyte.atlassian.net/browse/DB-7477?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by robertsami** [comment]
some details on the workload itself --

- create 4 threads, for each thread
  - create 4 connections
  - for each connection:
    - insert 10 random rows
  - for each connection
    - update all rows ending with randomly chosen character
  - for each connection:
    - select 1 random row

there is a deadlock happening in the test itself, because each of the 4 connections in each of the 4 threads is operating in lock step. e.g. consider connection 2 in thread 3 tries to update all rows ending in "s", but finds that there is one such row in intentsdb which is part of the pending connection 1 in thread 1. if connection 1 in thread 1 is also blocked on some connection managed by thread 3, then these two connections will deadlock

we should re-write the test to ensure that application-level deadlocks cannot happen. there is nothing we can do about this at the db layer

**Comment by rthallamko3** [comment]
cc @kripasreenivasan, Hope the above unblocks your team.
