### ISSUE TITLE
[YSQL] [Read Committed]: Some of the queries doesn't get retried.

### ISSUE THREAD

**Issue by shishir2001-yb** [yugabyte/yugabyte-db#18587]
Jira Link: [DB-7519](https://yugabyte.atlassian.net/browse/DB-7519)
### Description

Tried on version **2.19.2.0-b7**.
      One of the query inside a transaction(Read Committed Isolation level) doesn't get retried while other queries are retired continuously. 
Note: Wait queues and Deadlock detection were disabled 
```
The following query gets hung(No retries)-> See Attached SS
SELECT k FROM tbl_no_explicit_lock WHERE k like 'k%'  FOR NO KEY UPDATE

The below 3 queries were retired continuously

UPDATE tbl_no_explicit_lock SET V1='be8ef4cb-ec72-4679-a488-5af1eb848d36:90' WHERE k like 'k%'
UPDATE tbl_no_explicit_lock SET V1='be8ef4cb-ec72-4679-a488-5af1eb848d36:91' WHERE k like 'p%' 
UPDATE tbl_no_explicit_lock SET V1='be8ef4cb-ec72-4679-a488-5af1eb848d36:92' WHERE k like 'q%' 
```

```
Steps to repro:
1. CREATE TABLE %s (k VARCHAR PRIMARY KEY, v1 VARCHAR, v2 INTEGER);
2. Start 8 parallel transaction and perform the following operation
       a. BEGIN;
       b. INSERT 10 rows in the table"
       c. UPDATE table SET V1='ABC' WHERE k LIKE '%s'" %s-> Can be any alphabetical character
       d. SELECT k FROM %s WHERE k LIKE '%s'" %s-> Can be any alphabetical character
       e. COMMIT;
```
https://github.com/yugabyte/yugabyte-db/assets/59393494/8e649cfe-2572-4730-bf7f-f79b882e226c

![Screenshot 2023-08-03 at 3 31 46 PM](https://github.com/yugabyte/yugabyte-db/assets/59393494/0f695283-e27b-4a5c-b96d-78320e64bf0e)

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-7519]: https://yugabyte.atlassian.net/browse/DB-7519?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by pkj415** [comment]
The `SELECT NO KEY UPDATE` statement does have retries but it is just taking a long time in this case. The reason is this:

When the pk of a single row is not specified in an explicit locking statement in RC/RR, Pg reads rows that match the where clause and then issues a lock rpc separately for each row. And given that we continuously add rows to the table in this workload, I assume that table is quite huge and hence locking each row sequentially using 1 rpc round trip is incurring the large time.

An easy way to check this is to load a lot of rows in a simple table and perform `select * from ... for update`.

```
./bin/ysqlsh

> create table test (k int primary key, v int);
> insert into test select i, i from generate_series(1, 10000) as i;
> \timing
> select * from test for update;
   k   |   v
-------+-------
   854 |   854
  9643 |  9643
  .......
Time: 28558.564 ms (00:28.559)
```
