### ISSUE TITLE
[YSQL] Support uuid-ossp extension

### ISSUE THREAD

**Issue by m-iancu** [yugabyte/yugabyte-db#1867]
```
-- Support to auto-generate UUIDs (aka GUIDs)
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
```
See related issue (for extensions in general): #1154

**Comment by bllewell** [comment]
This enhancement is essential for the safe and performant population of a surrogate primary key column like this:
```
create table t(
  k uuid
  default uuid_ns_x500()
  constraint t_pk primary key,

  v1 varchar
  ...)
```
The semantic effect of auto-uniqueness is famously provided by a sequence via this usual syntax:
```
create table t(
  k int
  generated always as identity
  constraint t_pk primary key,
    
  v1 varchar
  ...)
```
However, for well-understood reasons, sequences bring poor performance in a distributed SQL database.

An informal test, to compare the performance of _"k int generated always as identity"_ and _"k timestamp default clock_timestamp()"_ shows that the sequence-based approach is about 2x slower than the approach based on a built-in SQL function.

I used _"clock_timestamp()"_ rather than "uuid_ns_x500()" because the former is ordinarily available but the latter requires special steps. Of course, _"clock_timestamp()"_ is unreliable as a universal unique ID generator. But it's sufficient for informal tests 'cos the probability of collision in a single-user test is tiny.

This issue requests that "uuid_ns_x500()", and its cousins, be made ordinarily available just as _"clock_timestamp()"_ already is.

**Comment by ndeodhar** [comment]
@bllewell Can you use `pgcrypto` extension? https://docs.yugabyte.com/latest/api/ysql/extensions/#pgcrypto

We already support pgcrypto in YB and that has a generate UUID function. Sample usage:
```
CREATE EXTENSION pgcrypto;
SELECT gen_random_uuid();
```

**Comment by bllewell** [comment]
@ndeodhar How random is random? In other words, what's the probability of collision? It would be a pain if the user has to use it in a tightly enclosing "try" block (whatever this is called in the language of choice) and retry in the event of a "unique constraint violation" for the PK column.

Does `gen_random_uuid()` have an identical implementation to `uuid_generate_v4()` from the` uuid-ossp` module? The doc seems to suggest that `uuid_generate_v5()` (also from the the` uuid-ossp` module) is better than `uuid_generate_v4()` because the v5 version is described thus: _"The generation of UUIDs by this method has no random or environment-dependent element and is therefore reproducible."_ This sounds like this property will make certain kinds of testing easier.

**Comment by ndeodhar** [comment]
@bllewell It's similar to `uuid_generate_v4()` - both generate version 4 UUIDs. Per wikipedia, the chance of collision is extremely low:
https://en.wikipedia.org/wiki/Universally_unique_identifier#Collisions
`Thus, the probability to find a duplicate within 103 trillion version-4 UUIDs is one in a billion.`

**Comment by bllewell** [comment]
Thanks for the explanation, @ndeodhar. I'm convinced, now, that `gen_random_uuid()` will satisfy my requirement. I'll test it out for performance. I'm expecting a table created thus:
```
create table t(
  k uuid
  default gen_random_uuid()
  constraint t_pk primary key,

  v1 varchar
  ...)
```
will perform (for insert tests) similarly to a table created thus:
```
create table t(
  k timestamp
  default clock_timestamp()
  constraint t_pk primary key,

  v1 varchar
  ...)
```
but without the relatively high collision change brought by using `clock_timestamp()`.

It seems that `gen_random_uuid()` can be used without a retry scheme—and, indeed, without any specific "try-catch" logic.

**Comment by rkarthik007** [comment]
Hi folks, is this extension now supported? If so could we close this issue?

**Comment by m-iancu** [comment]
`uuid-ossp` is supported now so closing the issue. 
However, the extension is not natively included yet (needs to be installed following the steps from https://docs.yugabyte.com/latest/api/ysql/extensions/#uuid-ossp) -- that part is tracked separately in #2415.
