### ISSUE TITLE
[DocDB] New DB API to query master leader for the last RAFT heartbeat time of the followers

### ISSUE THREAD

**Issue by iSignal** [yugabyte/yugabyte-db#18788]
Jira Link: [DB-7670](https://yugabyte.atlassian.net/browse/DB-7670)
### Description

This is needed as part of the following flow related to master replacement

1. Platform queries a new DB API to query master leader for the last RAFT heartbeat time of the followers. 
2. A lagging master that is unable to catch up via WAL should not be considered to be heartbeating succesfully. 
3. The API returns an error if the leader lease is not held so that no action is taken if a master leader does not exist.
4. Platform will identify 1 master with max delay such that delay > configurable delta (30 mins). 

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-7670]: https://yugabyte.atlassian.net/browse/DB-7670?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by mohatagarvit** [comment]
Hi,

Hope you are doing well!

I am [Garvit Mohata](https://github.com/mohatagarvit), a MS CS student at UT Austin. My teammate ([Kulin Shah](https://github.com/kulinshah98)) and I are taking the graduate [Distributed Systems](https://github.com/vijay03/cs380d-f23/tree/master) course and as a part of the course project, we are exploring the opportunity of contributing to the tikv open source repository.

This issue seems closely related to the content of the course so we were wondering if we can contribute to solve this issue.

Can you provide a bit more specific expectations and details to solve this issue and pointers if possible?
Thank you!

Regards,
Garvit

**Comment by SrivastavaAnubhav** [comment]
Hi @mohatagarvit , I'm excited to hear you're exploring contributing to Yugabyte. I think this and the other issue you commented on (#16954) are a bit hard to pick up for new contributors since they require a lot of system context. I recommend browsing issues tagged with the "Good first issue" tag. Those are ones we explicitly think are self-contained. If you have any more questions, feel free to DM me on the community slack channel.
