### ISSUE TITLE
[YSQLSH] Connect to UNIX Socket without specifying `-h` explicitly

### ISSUE THREAD

**Issue by yogendra** [yugabyte/yugabyte-db#18915]
YSQLSH requires UNIX-domain socket to be specified (via -h parameter) in order to connect. In psql on postgres we do not need to specify the parameter. 

Example: `./bin/ysqlsh -h /tmp/.yb.0.0.0.0:5433`
Same thing in postgres works easily with just running `psql`. 

Also, its not clear in the documentation that UNIX-domain socket can be provided.

**Comment by yogendra** [comment]
Also, there is no clear indication about the socker file location in the documentation for tserver.

**Comment by jasonyb** [comment]
> Same thing in postgres works easily with just running psql.

Not exactly. 

```sh
mkdir /tmp/customsockdir
bin/pg_ctl start -D data -l logfile -o -k/tmp/customsockdir
bin/psql
```

YB specifies a custom sock dir under the hood, so this is expected.

> Also, there is no clear indication about the socker file location in the documentation for tserver.

Please create a docs issue for this if it is true.

**Comment by dmagda** [comment]
There are more usability issues related to the peer authentication and ysqlsh tool. 

I've started a tserver with the following config where `dmagda` is my OS user:
```shell
./bin/yb-tserver \
--tserver_master_addrs=127.0.0.1:7100 \
--rpc_bind_addresses=127.0.0.1:9100 \
--enable_ysql \
--ysql_hba_conf_csv="host all yugabyte 127.0.0.1/0 trust,local all dmagda peer" \
--fs_data_dirs=/home/dmagda/yb-dir  &
```

Next, I've added a database role corresponding to my OS user and grant all access to the `yugabyte` database:
```sql
CREATE USER dmagda WITH LOGIN PASSWORD 'dmagda';
GRANT ALL PRIVILEGES ON DATABASE yugabyte TO dmagda;
```

However, when I'm trying to connect using the peer-auth method, I'm getting the following error:
```shell
./bin/ysqlsh -h /tmp/.yb.127.0.0.1\:5433
ysqlsh: FATAL:  no pg_hba.conf entry for host "[local]", user "yugabyte", database "yugabyte", SSL off
```
and `whoami` returns `dmagda`.
Thus, either `ysqlsh` or tserver doesn't capture my OS user and check it against the `pg_hba.conf` records.

At the same time, I can connect to the cluster using `psql` that does capture my OS user:
```shell
psql -h /tmp/.yb.127.0.0.1\:5433 -p 5433 -d yugabyte
psql (13.11 (Debian 13.11-0+deb11u1), server 11.2-YB-2.18.2.1-b0)
Type "help" for help.

yugabyte=>
```

As a workaround for `ysqlsh`, we have to specify the user explicitly:
```shell
./bin/ysqlsh -h /tmp/.yb.127.0.0.1\:5433 -U dmagda
ysqlsh (11.2-YB-2.18.2.1-b0)
Type "help" for help.

yugabyte=>
```

**Comment by dmagda** [comment]
@jasonyb 

Yogi is right, vanilla Postgres doesn't require you to specify a Unix socket directory. Try the following on your end.

1. Start a Postgres instance in Docker (feel free to use your favorite image):
```shell
mkdir ~/postgresql_data/

docker run --name postgresql \
-e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=password \
-p 5432:5432 \
-v ~/postgresql_data/:/var/lib/postgresql/data -d sibedge/postgres-plv8
```
2. Connect to the container. 
3. Make sure the user is `root` by running `whoami`

Next, enable the peer authentication:
1. Open this file: `vi /var/lib/postgresql/data/pg_hba.conf`
2. Locate and replace `local   all             all                                     trust`
     with `local   all             all                                     peer`
3. Create a database user for `root`:
```sql
psql -U postgres

CREATE USER root WITH LOGIN PASSWORD 'root';
GRANT ALL PRIVILEGES ON DATABASE postgres TO root; 
```
4. Reload the config and exist `psql` session:
```sql
SELECT pg_reload_conf();
\q
```

Now, you can connect to the cluster with `root` OS user and don't need to provide the Unix socket location:
```shell
# psql -d postgres
psql (15.3)
Type "help" for help.

postgres=>
```

**Comment by jasonyb** [comment]
> Yogi is right, vanilla Postgres doesn't require you to specify a Unix socket directory.

No, you missed my point.  Try changing `#unix_socket_directories = '/var/run/postgresql'` to `unix_socket_directories = '/var/lib/postgresql'` in `postgresql.conf`, and you get

```
# psql -U postgres
psql: error: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
        Is the server running locally and accepting connections on that socket?
```

This is not a YB issue.  If you have multiple vanilla pg clusters on the same machine, each using a different unix domain socket directory, I don't think you can avoid specifying `-h`.

> Please also review another usability issue in the comment above. It's also associated with the peer authentication in yugabytedb. If needed we can rename the ticket subj.

Please create a new issue for the peer authentication.

**Comment by dmagda** [comment]
> No, you missed my point. Try changing #unix_socket_directories = '/var/run/postgresql' to unix_socket_directories = '/var/lib/postgresql' in postgresql.conf, and you get

I don't get why I, as an end user, would need to change the directory in the first place. If this is what YugabyteDB does while starting a tserver, then it's a change in default Postgres behavior introduced by YugabyteDB.

> This is not a YB issue. If you have multiple vanilla pg clusters on the same machine, each using a different unix domain socket directory, I don't think you can avoid specifying -h.

Again, we're just sharing what users experience while switching to YugabyteDB whuch claims and strives to be runtime-compatible with Postgres.

* A user starts a single Postgres instance on a machine
* The user enables the peer authentication
* The user can connect to Postgres without providing `-h`. This is the default Postgres behavior users expect.

Then, the same user:
* Starts a YugabyteDB instance
* Configures the same per authentication
* But fails to connect to YugabyteDB unless the `-h` is provided. This is clearly a compatibility issue. 

> Please create a new issue for the peer authentication.

sure, not a problem: https://github.com/yugabyte/yugabyte-db/issues/18962

**Comment by jasonyb** [comment]
(First, peer auth can be taken out of the picture and just focus on local auth: peer auth problems can be covered in the other issue.)

> If this is what YugabyteDB does while starting a tserver, then it's a change in default Postgres behavior introduced by YugabyteDB.

It is a change made by YB that the code currently depends on for tserver-postgres communication, such as index backfill, ysql upgrade.  Originally, local auth was not intended to be a user-visible feature, so it was taken for a specific purpose.  It is possible to remove the reliance, but that would take engineering effort.  So for now, let the discussion accept that situation.

The socket dir is derived such that it respects multiple nodes on the same machine.  Therefore, it is not a very predictable path.

Not only the socket dir, but YB always sets other flags to the postgres subprocess under yb-tserver.  Try `yb-ctl create`, then look at the arguments passed to the `postgres` process:

```
postgres -D <HOME>/yugabyte-data/node-1/disk-1/pg_data -p 5433 -h 127.0.0.1 -k /tmp/.yb.127.0.0.1:5433 -c unix_socket_permissions=0700 -c logging_collector=on -c log_directory=<HOME>/yugabyte-data/node-1/disk-1/yb-data/tserver/logs -c yb_pg_metrics.node_name=<HOST>:9000 -c yb_pg_metrics.port=13000 -c config_file=<HOME>/yugabyte-data/node-1/disk-1/pg_data/ysql_pg.conf -c hba_file=<HOME>/yugabyte-data/node-1/disk-1/pg_data/ysql_hba.conf
```

- the data directory is in an unpredictable location
- the logs are in an unpredictable location
- the config file is in an unpredictable location
- the hba file is in an unpredictable location

Commands like `pg_controldata` work out of the box for vanilla postgres because

> If no data directory (DATADIR) is specified, the environment variable PGDATA
> is used.

and `PGDATA` can be predictably set by the system install location.  In YB, it isn't always in the same location, and there can be multiple clusters in the same machine.  This command does not work out of the box, nor is it reasonable to have a fixed default given the current state...

**The only way this issue makes sense is if we set a standard for single-node-per-machine and we are okay with not supporting the cases outside of that.**  If we can settle on such a standard, then that path can be made to not need `-h`.  For example, if the single-node-per-machine standard is `0.0.0.0` listen address, `/tmp/.yb.0.0.0.0:5433` socket dir, then the following changes are needed:

- Make `ysqlsh` default host `/tmp/.yb.0.0.0.0:5433`: this is a major change because it currently defaults to `localhost`
- Make hba conf default to allow local auth: another major change
- Make yb-ctl default to 0.0.0.0 listen address: this is because users today may already be used to not having to use `-h`

**Comment by dmagda** [comment]
@jasonyb thanks a lot for the detailed explanation of why things work this way in YugabyteDB.

The current implementation looks reasonable to me now. Let me reassign this ticket to the documentation team asking to put  a note about the `-h` flag.

Hey @ddhodge we need to provide more details in the `local` authentication section here:
https://docs.yugabyte.com/preview/secure/authentication/host-based-authentication/#local

Similarly to Postgres, YugabyteDB supports opening connections via the Unix sockets when the `local` authentication is used. However, unlike in Postgres, YugabyteDB requires ysqlsh, psql and other tools to provide a full path to the socket location. If you use ysqlsh then you need to use the `-h` flag. 

The path to the socket location is written to the logs of a tserver and can look as follows:
```shell
2023-09-05 13:56:20.154 UTC [1261] LOG:  listening on Unix socket "/tmp/.yb.127.0.0.1:5433/.s.PGSQL.5433"
```

The user needs to take the first part of the path `/tmp/.yb.127.0.0.1:5433/` and pass it via the `-h` option in ysqlsh:
```shell
./bin/ysqlsh -h /tmp/.yb.127.0.0.1:5433
```

for psql you also need specify the port number:
```shell
psql -h /tmp/.yb.127.0.0.1:5433/ -p 5433
```

Overall, the path needs to be specified for the following combinations:

* `local` authentication with the `peer` method: https://docs.yugabyte.com/preview/secure/authentication/host-based-authentication/#peer
* `local` authentication with the `trust` method: https://docs.yugabyte.com/preview/secure/authentication/host-based-authentication/#trust
