### ISSUE TITLE
Encoding error in cqlsh yugabyte-1.1.7.0

### ISSUE THREAD

**Issue by Benjamin-liu-Narvar** [YugaByte/yugabyte-db#1902]
We have a table with a column `object_info` defined as JSONB. When executing `SELECT *` or `SELECT object_info`, certain rows will throw the following error:
`'ascii' codec can't encode character u'\xfc' in position 356: ordinal not in range(128)`

This happens regardless if we start cqlsh with utf-8 encoding:
./bin/cqlsh --encoding utf-8

I've identified one of the rows containing a json value of `M\xfcnchen` which corresponds to `München`.

**Comment by m-iancu** [comment]
@Benjamin-liu-Narvar It looks like there is an issue specific to `cqlsh` where our python formatter for `jsonb` values does not use the user-set encoding but the default python one.
(I believe it was introduced in [this](https://github.com/YugaByte/cqlsh/commit/2df8eae92e1e8765665bd0ca9459ba62ff3628fa) commit).
We should fix this in the code in a followup version of our `cqlsh`.

Meanwhile, the following workaround might work for you:

1. _[Optional]_ First confirm that the local, default python encoding is `ascii`:
```
python -c 'import sys; print(sys.getdefaultencoding())'
``` 
2. Create a `sitecustomize.py` that changes the default python encoding to `utf-8` (or the intended `cqlsh` encoding) instead of `ascii`:
```
echo "import sys; sys.setdefaultencoding('utf-8')" > sitecustomize.py
```
3. _[Optional]_ Confirm that setting the path updates the encoding:
```
PYTHONPATH=".:$PYTHONPATH" python -c 'import sys; print(sys.getdefaultencoding())'
```
_Note: we intentionally set this for the current command only, so that it does not affect other python programs that may rely on `ascii` being the default._

4. Run `cqlsh` with that file in the python path:
```
PYTHONPATH=".:$PYTHONPATH" ./bin/cqlsh --encoding utf-8
``` 

(Hopefully) the query should work now.
