### ISSUE TITLE
[YCQL] YugabyteDB silently fails on update when data does not exist for a particular row

### ISSUE THREAD

**Issue by mrajcevic01** [yugabyte/yugabyte-db#19222]
Jira Link: [DB-8016](https://yugabyte.atlassian.net/browse/DB-8016)
### Description

Behavior between YugabyteDB (in YCQL) and Apache Cassandra differs when attempting to update a particular row that does not exist. In YugabyteDB we see a silent failure whereas in Cassandra this is an invalid operation. This issue has been raised to change the current YugabyteDB behavior to reflect that of Cassandra and throw an error. 

**YugabyteDB behaviour:**
```
ycqlsh> CREATE KEYSPACE k;

ycqlsh> CREATE TABLE k.t (c1 INT PRIMARY KEY, c2 INT);

ycqlsh> UPDATE k.t SET c2 = 100 WHERE c1 = 1;

ycqlsh> SELECT * FROM k.t;

 c1 | c2
----+-----
  1 | 100

(1 rows)

ycqlsh> TRUNCATE TABLE k.t;

ycqlsh> UPDATE k.t SET c2 = c2 + 1 WHERE c1 = 1;

ycqlsh> SELECT * FROM k.t;

 c1 | c2
----+----

(0 rows)

```
**Cassandra behaviour:**
```
cassandra@cqlsh> CREATE KEYSPACE k WITH REPLICATION = {'class' : 'SimpleStrategy', 'replication_factor' : 1};

cassandra@cqlsh> CREATE TABLE k.t (c1 INT PRIMARY KEY, c2 INT);

cassandra@cqlsh> UPDATE k.t SET c2 = 100 WHERE c1 = 1;

cassandra@cqlsh> SELECT * FROM k.t;

 c1 | c2
----+-----
  1 | 100

(1 rows)

cassandra@cqlsh> TRUNCATE TABLE k.t;

cassandra@cqlsh> UPDATE k.t SET c2 = c2 + 1 WHERE c1 = 1;
InvalidRequest: Error from server: code=2200 [Invalid query] message="Invalid operation (c2 = c2 + 1) for non counter column c2"
```

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-8016]: https://yugabyte.atlassian.net/browse/DB-8016?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by m-iancu** [comment]
This is not a bug, rather the correct and intended semantics.
In YCQL, we have extended Cassandra to support expression evaluation on some non-counter columns.
So this mismatch is simply because we have broader support here. Other than that the internal semantics matches that of Cassandra.

There are two aspects here.
First `null + 1` evaluates to `null` and that's what we see above. Essentially we are setting that column to just `NULL`.
Second, if all columns of a row are null, the row gets deleted. Here there is a subtlety of insert vs update where insert adds an entry for the key itself (liveness column).
So for a row added by update, making all value columns null will make the row disappear.
While, for a row added by insert, the key will remain so the row will remain.

Example with same schema as above:

#### Set up initial data
```
TRUNCATE k.t;
INSERT INTO k.t(c1, c2) values (1,11);
UPDATE k.t SET c2 = 22 where c1 = 2;
SELECT * FROM k.t;
```
```

 c1 | c2
----+----
  1 | 11
  2 | 22
```

#### Test updating columns to null
```
UPDATE k.t SET c2 = NULL WHERE c1 = 1; // inserted row, will remain
UPDATE k.t SET c2 = NULL WHERE c1 = 2; // upserted row, will disappear
UPDATE k.t SET c2 = NULL WHERE c1 = 3; // new (upserted) row, no row will appear
SELECT * FROM k.t;
```
```

 c1 | c2
----+------
  1 | null
```


### Workaround for the use-case 
Now, for the actual use-case mentioned here, there are 3 options:

#### YCQL counter type
Counter type defaults to `0` rather than `NULL` so the expression will evaluate as intended for this use-case. However there are many caveats with counters so it may not be a good choice. We generally recommend *against* using counter type.

#### YCQL `ELSE ERROR` clause

Adding the `IF EXISTS ELSE ERROR` clause combination will mean that if `c2` is not initialized app will get an error.

```
ycqlsh:k> UPDATE k.t SET c2 = c2 + 1 WHERE c1 = 1 IF EXISTS ELSE ERROR;

 [applied]
-----------
      True
Row does not exists case, app can catch error and insert row manually
```
ycqlsh:k> UPDATE k.t SET c2 = c2 + 1 WHERE c1 = 2 IF EXISTS ELSE ERROR;
InvalidRequest: Error from server: code=2200 [Invalid query] message="Execution Error. Condition on table t was not satisfied.
UPDATE k.t SET c2 = 1 WHERE c1 = 2 IF EXISTS ELSE ERROR;
^^^^^^
 (ql error -300)"

```

Then the app can handle the non-initialized error by doing a simple insert or update to initialize that row.
However, in a multi-threaded app, the app logic must ensure this process is thread safe.

For example the following for can be used to make it safe.
```
 UPDATE k.t SET c2 = 1 WHERE c1 = 2 IF NOT EXISTS ELSE ERROR;
```
Then if no error occurs for this new (initialization) update it means we initialized it safely. Else the app knows someone else initialized it in the meantime and can handle the error by retrying the previous (increment) update.

#### Use YSQL instead of YCQL
This use-case can be modeled easier in YSQL for instance using `INSERT ON CONFLICT DO UPDATE` though the performance characteristics may be different.
