### ISSUE TITLE
[DocDB] Replicate deadlock status to follower coordinators

### ISSUE THREAD

**Issue by robertsami** [yugabyte/yugabyte-db#19257]
Jira Link: [DB-8053](https://yugabyte.atlassian.net/browse/DB-8053)
### Description

In order to ensure we correctly return a deadlocked transaction status in case a transaction is cancelled due to deadlock, we track the deadlock status of transactions in memory at coordinators for a short period of time even after records for the transaction have been removed. If a coordinator loses leadership, there could be a race with a query layer heartbeat hitting the new leader, and not receiving the correct transaction status. Replicating this deadlock status would solve this case

NB: this case should be rare, so TBD if there is a worthwhile practical solution

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-8053]: https://yugabyte.atlassian.net/browse/DB-8053?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by mohatagarvit** [comment]
Hi,

Hope you are doing well!

I am [Garvit Mohata](https://github.com/mohatagarvit), a MS CS student at UT Austin. My teammate ([Kulin Shah](https://github.com/kulinshah98)) and I are taking the graduate [Distributed Systems](https://github.com/vijay03/cs380d-f23/tree/master) course and as a part of the course project, we are exploring the opportunity of contributing to the tikv open source repository.

This issue seems closely related to the content of the course so we were wondering if we can contribute to solve this issue.

Can you provide a bit more specific expectations and details to solve this issue and pointers if possible? 
Thank you!

Regards,
Garvit

**Comment by rthallamko3** [comment]
@mohatagarvit , We are taking a look to see if there are smaller issues that you can get started with before venturing on this one. cc @robertsami , @basavaraj29
