### ISSUE TITLE
Intents of applied transaction are not removed at followers

### ISSUE THREAD

**Issue by spolitov** [YugaByte/yugabyte-db#1951]

**Comment by kmuthukk** [comment]
Additional notes:

* This was a recent regression introduced due to the fix for #1240.
* Symptoms due to this bug are -- much slower performance

and the logs had lines like:

`W0731 22:03:19.206131 23337 docdb_compaction_filter_intents.cc:92] Number of aborted transactions not cleaned up on account of reaching size limits:94856`
