### ISSUE TITLE
cache lookup failed for type 0

### ISSUE THREAD

**Issue by cevin** [yugabyte/yugabyte-db#1969]
![image](https://user-images.githubusercontent.com/338110/62413410-4481d680-b641-11e9-9c73-c7864bbdfb53.png)

**Comment by ndeodhar** [comment]
Hi @cevin, few followup questions to help debug this:
1. Can you run `\d+ ww` on psql and share the output?
2. What version of YugaByte are you using?
3. Do you see any errors in postgresql or tserver logs? You can find those at `$yugabyte_data_dir/node-1/disk-1/yb-data/tserver/logs`. Postgres logs will be named `postgresql.*.log` while tserver logs will be `yb-tserver.INFO.*`

**Comment by m-iancu** [comment]
I think this error can happen after the target table is altered to drop (remove) a column.
This is because the dropped column remains in the column list (`pg_attribute` table) but is marked as dropped (and its type id becomes `0`).
So if we don't accurately skip dropped columns when iterating through the columns, they will appear to have invalid type.

To replicate:
```
postgres=# create table test(a int, b int);
CREATE TABLE
postgres=# insert into test(a,b) values(1,1);
INSERT 0 1
postgres=# update test set a = 2 where a = 1;
UPDATE 1
postgres=# alter table test drop column b;
ALTER TABLE
postgres=# update test set a = 3 where a = 2;
ERROR:  cache lookup failed for type 0
```
