### ISSUE TITLE
[DocDB] Disk threshold to stop master from adding new tablets to a tserver

### ISSUE THREAD

**Issue by iSignal** [yugabyte/yugabyte-db#19740]
Jira Link: [DB-8577](https://yugabyte.atlassian.net/browse/DB-8577)
### Description

Master load balancing continues to add tablets to a tserver even if it doesn't have the disk capacity. This can cause the tserver to run out of disk and shut down.

We need a tserver side "free disk space" threshold on adding new tablets (preferable, because it also handles create table scenarios) or a master side knob for this.

@lingamsandeep 

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-8577]: https://yugabyte.atlassian.net/browse/DB-8577?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by mohatagarvit** [comment]
Hi @iSignal,

Hope you are doing well!

I am [Garvit Mohata](https://github.com/mohatagarvit), a MS CS student at UT Austin. My teammate ([Kulin Shah](https://github.com/kulinshah98)) and I are taking the graduate [Distributed Systems](https://github.com/vijay03/cs380d-f23/tree/master) course and as a part of the course project, we are exploring the opportunity of contributing to the tikv open source repository.

This issue seems closely related to the content of the course so we were wondering if we can contribute to solve this issue.

Can you provide a bit more specific expectations and details to solve this issue and pointers if possible?
Thank you!

Regards,
Garvit

**Comment by AyoubKaz07** [comment]
Can you provide more details ? At which phase of the operation should the threshold stop master from to tserver ? What should be this threshold set to ?

**Comment by rthallamko3** [comment]
DUP of https://github.com/yugabyte/yugabyte-db/issues/23987
