### ISSUE TITLE
Implement the SCAN Redis command

### ISSUE THREAD

**Issue by hengestone** [yugabyte/yugabyte-db#2]
In order to make searching more useful.

**Comment by hectorgcr** [comment]
Thanks for the input @hengestone 

I will be writing a design document for this feature and will share it here once it's ready.

**Comment by rahuldesirazu** [comment]
SCAN cursor [MATCH pattern] [COUNT count]

https://redis.io/commands/scan

In a nutshell, SCAN returns all redis keys in a cluster. A few customers have asked for the SCAN redis command for debug purposes, since there is currently no way to see all the redis keys that have been created. I plan on implementing in a few steps:

Implement SCAN without a cursor or pattern. This will return the first n (TBD what this default is) keys in the cluster, unless count is specified, in which case we respect that and return the first count keys. Since the redis spec has no semantics for ordering of keys, we will just query tablets in order of increasing hash range. We will iterate through the tablets sequentially until we have enough keys to satisfy the request, or until we have looped through the whole keyspace. Since there is no concept of a cursor as yet, we will just return 0 to the client for the cursor, as this is the default cursor position for beginning of the keyspace.

Implement pattern. This will allow the user to specify a regex by which to match keys. Note that the pattern is applied after the keys are retrieved, so a SCAN call can potentially return 0 elements if none of the keys match the pattern, even if the count specified is greater than 0. This should be pretty straightforward, as we simply loop through the collection we would return as part of step 1 and simply do another layer of filtering.

Implement cursor. The redis spec is loose on the semantics of what exactly the cursor represents, other than that it’s a 64-bit integer. So we have some flexibility in how we want to represent our cursor. We should have a design discussion to talk about how we’re going to implement this. Perhaps, in a naive solution, the cursor can represent the hash of the last key returned. Note that this operation should be stateless.

**Comment by mbautin** [comment]
@rahuldesirazu: I think we could do some optimizations for the pattern case. We could restrict the range of primary keys to scan in case a pattern does not start with a `*`. For each tablet, we can start scanning, find an existing hash value, and immediately seek to the earliest key with that hash value that could match the pattern. When we scan all the keys with this hash value that match the pattern, we will seek to the incremented hash value.

**Comment by rahuldesirazu** [comment]
@hengestone Thanks for your patience. For now, we're no longer adding new Redis functionality to YugaByte. However, we do have support for the KEYS command. 

https://docs.yugabyte.com/latest/yedis/api/keys/
