### ISSUE TITLE
Implement dynamic priorities for compaction tasks

### ISSUE THREAD

**Issue by spolitov** [yugabyte/yugabyte-db#2004]

**Comment by rthallamko3** [comment]
The commit [b2c27a1](https://github.com/yugabyte/yugabyte-db/commit/b2c27a1d49c58b12cec58f7aed3b071c1d1e6216) implements dynamic priorities for compactions and a new way to calculate compaction task priority.

The priority is based on the number of SST files in the tablet and the size of the compaction (small vs. large).
When the tablet has less than `FLAGS_compaction_priority_start_bound` SST files, a task would have a base priority of 0, otherwise, it will have a base priority of 1.
And for each `FLAGS_compaction_priority_step_size` SST files it will get its priority incremented by 1.
Also, small compactions would have an extra amount of `FLAGS_small_compaction_extra_priority` added to their priority.
