### ISSUE TITLE
[DocDB] T-Server debug assertion failure / crash on TRUNCATE of colocated table in a transaction

### ISSUE THREAD

**Issue by tverona1** [yugabyte/yugabyte-db#20153]
Jira Link: [DB-9089](https://yugabyte.atlassian.net/browse/DB-9089)
### Description

Truncating a colocated table within an explicit transaction results in t-server crash and an assertion failure in debug mode.

Repro:

```
CREATE DATABASE x WITH colocation=true;
\c x;
CREATE TABLE x (t int);
begin;
insert into x values (1);
truncate x;
WARNING:  AbortSubTransaction while in ABORT state
ERROR:  recvmsg error: Connection refused

```

T-server logs show:
`F1130 22:52:46.761531 4033330 wait_queue.cc:260] Check failed: txn_start_us || id.IsNil() 
`

The above issue was introduced with this change:
[D25252](https://phorge.dev.yugabyte.com/D25252) [#17290] DocDB: Enable wait-on-conflict behavior in debug

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-9089]: https://yugabyte.atlassian.net/browse/DB-9089?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by robertsami** [comment]
Root cause here is that `TRUNCATE` of colocated tables uses a tablet level tombstone, which conflicts with the DML issued by the same session. These two operations are executed in different transactions, which causes a deadlock that is invisible to docdb. We should fix this issue by changing `TRUNCATE` of colocated tables to operate similarly to `TRUNCATE` of non-colocated tables
