### ISSUE TITLE
[YSQL] Insert query fails with ERROR: LookupByIdRpc(tablet: 18663a5c41604213bdcbdabf44d27f0b, num_attempts: 1) failed: Tablet deleted: Table deleted at 2024-01-30 10:11:28 UTC

### ISSUE THREAD

**Issue by shishir2001-yb** [yugabyte/yugabyte-db#20959]
Jira Link: [DB-9934](https://yugabyte.atlassian.net/browse/DB-9934)
### Description

Tried on version: **2.21.0.0-b516/2.21.1.0-b3**

During the execution of the Cross DB DDL sample app, some of the insert queries failed with the following error:
` ERROR: LookupByIdRpc(tablet: 18663a5c41604213bdcbdabf44d27f0b, num_attempts: 1) failed: Tablet deleted: Table deleted at 2024-01-30 10:11:28 UTC`

Update:
DROP INDEX idx1_tb_0 query was running in parallel with this. So i would expect something like below
`The object '<table_uuid>.idx1_tb_0' does not exist: OBJECT_NOT_FOUND`

**Test details**:
`
Start the Cross-DB Concurrent DDLs sample app with 25 write threads, 5 read threads and 15 databases which will execute DDLs in parallel with DMLs across different databases. Notably, we ensure there is no simultaneous execution of DDL operations within the same database.
`

**List of DDLs:**
```
private static List<List<String>> ddlList = List.of(
            List.of("CREATE INDEX idx1 ON ? (k)", "DROP INDEX idx1"),
            List.of("CREATE TABLE tempTable1 AS SELECT * FROM ? limit 1000000", "ALTER TABLE tempTable1 RENAME TO tempTable1_new", "DROP TABLE tempTable1_new"),
            List.of("CREATE MATERIALIZED VIEW mv1 as SELECT k from ? limit 10000", "REFRESH MATERIALIZED VIEW mv1", "DROP MATERIALIZED VIEW mv1"),
            List.of("ALTER TABLE ? ADD newColumn1 TEXT DEFAULT 'dummyString'", "ALTER TABLE ? DROP newColumn1"),
            List.of("ALTER TABLE ? ADD newColumn2 TEXT NULL", "ALTER TABLE ? DROP newColumn2"),
            List.of("CREATE VIEW view1_? AS SELECT k from ?", "DROP VIEW view1_?"),
            List.of("ALTER TABLE ? ADD newColumn3 TEXT DEFAULT 'dummyString'", "ALTER TABLE ? ALTER newColumn3 TYPE VARCHAR(1000)", "ALTER TABLE ? DROP newColumn3"),
            List.of("CREATE TABLE tempTable2 AS SELECT * FROM ? limit 1000000", "CREATE INDEX idx2 ON tempTable2(k)", "ALTER TABLE ? ADD newColumn4 TEXT DEFAULT 'dummyString'", "ALTER TABLE tempTable2 ADD newColumn2 TEXT DEFAULT 'dummyString'", "TRUNCATE table ? cascade", "ALTER TABLE ? DROP newColumn4", "ALTER TABLE tempTable2 DROP newColumn2", "DROP INDEX idx2", "DROP TABLE tempTable2"),
            List.of("CREATE VIEW view2_? AS SELECT k from ?", "CREATE MATERIALIZED VIEW mv2 as SELECT k from ? limit 10000", "REFRESH MATERIALIZED VIEW mv2", "DROP MATERIALIZED VIEW mv2", "DROP VIEW view2_?")
 );

```

Logs : [https://drive.google.com/file/d/1oC-J1HA2taboJucOhfREBYgkf_GqlrU0/view?usp=sharing](https://drive.google.com/file/d/1oC-J1HA2taboJucOhfREBYgkf_GqlrU0/view?usp=sharing)

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-9934]: https://yugabyte.atlassian.net/browse/DB-9934?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by shishir2001-yb** [comment]
Similar Issues
[https://github.com/yugabyte/yugabyte-db/issues/16130](https://github.com/yugabyte/yugabyte-db/issues/16130)
[https://github.com/yugabyte/yugabyte-db/issues/18891](https://github.com/yugabyte/yugabyte-db/issues/18891)
[https://github.com/yugabyte/yugabyte-db/issues/15468](https://github.com/yugabyte/yugabyte-db/issues/15468)

**Comment by myang2021** [comment]
I was able to reproduce this issue locally using dev vm RF-3 cluster. This error is expected. Following is the analysis:

During normal operation, each DML read/write RPC needs to go through the
following steps as shown in the following logs

```
(1) [ts-3] I0226 23:46:55.037580 13063 tablet_rpc.cc:163] vlog4: Selected TServer { uuid: 1b01e7a2c11c4d3b8e7e44c671579c2e private: [host: "127.48.46.1" port: 29115] cloud_info: placement_cloud: "cloud1" placement_region: "datacenter1" placement_zone: "rack1" as leader for 0079795d6c7b4af6b2b87ff6a2931445
(2) [ts-3] I0226 23:46:55.037611 13063 tablet_rpc.cc:264] vlog2: Tablet 0079795d6c7b4af6b2b87ff6a2931445: Sending Write(tablet: 0079795d6c7b4af6b2b87ff6a2931445, num_ops: 1, num_attempts: 1, txn: 7d8dc4cf-2e5a-41a1-944a-b60597a63a63, subtxn: [none]) to replica { uuid: 1b01e7a2c11c4d3b8e7e44c671579c2e private: [host: "127.48.46.1" port: 29115] cloud_info: placement_cloud: "cloud1" placement_region: "datacenter1" placement_zone: "rack1"
(3) [ts-2] I0226 23:46:55.047886 12694 tablet_service.cc:2094] vlog2: Received Write RPC: tablet_id: "0079795d6c7b4af6b2b87ff6a2931445"

```

Then ts-2 should successfully perform the Write RPC request and return a OK
status back to the Write RPC sender ts-3.

But when the table is deleted, then for a Write RPC like the above that is
prepared using the stale metadata of the table (when the table existed)
after step (3) we will see a failure, such as

```
(1) [ts-1] I0226 23:46:57.252840 12990 tablet_rpc.cc:163] vlog4: Selected TServer { uuid: 1b01e7a2c11c4d3b8e7e44c671579c2e private: [host: "127.48.46.1" port: 29115] cloud_info: placement_cloud: "cloud1" placement_region: "datacenter1" placement_zone: "rack1" as leader for 0079795d6c7b4af6b2b87ff6a2931445

(2) [ts-1] I0226 23:46:57.252858 12990 tablet_rpc.cc:264] vlog2: Tablet 0079795d6c7b4af6b2b87ff6a2931445: Sending Write(tablet: 0079795d6c7b4af6b2b87ff6a2931445, num_ops: 2, num_attempts: 1, txn: 6ac136de-53ab-4aac-8bc0-fa811edb9a46, subtxn: [none]) to replica { uuid: 1b01e7a2c11c4d3b8e7e44c671579c2e private: [host: "127.48.46.1" port: 29115] cloud_info: placement_cloud: "cloud1" placement_region: "datacenter1" placement_zone: "rack1"

(3) [ts-2] I0226 23:46:57.259052 12692 tablet_service.cc:2094] vlog2: Received Write RPC: tablet_id: "0079795d6c7b4af6b2b87ff6a2931445"

(4) [ts-1] I0226 23:46:57.259449 12988 tablet_rpc.cc:393] vlog4: Retryable failure: Not found (yb/tserver/ts_tablet_manager.cc:2256): Tablet 0079795d6c7b4af6b2b87ff6a2931445 not found (tablet server error 6), response: 0x00003470fcf90a40 -> code: TABLET_NOT_FOUND status { code: NOT_FOUND message: "Tablet 0079795d6c7b4af6b2b87ff6a2931445 not found" source_file: "../../src/yb/tserver/ts_tablet_manager.cc" source_line: 2256 errors: "\005\006\000\000\000\000" }

(5) [ts-1] I0226 23:46:57.259739 12988 tablet_rpc.cc:292] vlog1: Failing Write(tablet: 0079795d6c7b4af6b2b87ff6a2931445, num_ops: 2, num_attempts: 1, txn: 6ac136de-53ab-4aac-8bc0-fa811edb9a46, subtxn: [none]) to a new replica: Not found (yb/tserver/ts_tablet_manager.cc:2256): Tablet 0079795d6c7b4af6b2b87ff6a2931445 not found (tablet server error 6), old replica: 0x00003470ffc24018 -> { uuid: 1b01e7a2c11c4d3b8e7e44c671579c2e private: [host: "127.48.46.1" port: 29115] cloud_info: placement_cloud: "cloud1" placement_region: "datacenter1" placement_zone: "rack1"

(6) [ts-1] I0226 23:46:57.259770 12988 meta_cache.cc:390] vlog2: T 0079795d6c7b4af6b2b87ff6a2931445: Current remote replicas in meta cache: 36e46ef9ccb2479e902aefef4bd1c33a (FOLLOWER, OK), d057030abaa742058c7ca15bcc4c8f54 (FOLLOWER, OK), 1b01e7a2c11c4d3b8e7e44c671579c2e (LEADER, OK). Replica { uuid: 1b01e7a2c11c4d3b8e7e44c671579c2e private: [host: "127.48.46.1" port: 29115] cloud_info: placement_cloud: "cloud1" placement_region: "datacenter1" placement_zone: "rack1" has failed: Not found (yb/tserver/ts_tablet_manager.cc:2256): Tablet 0079795d6c7b4af6b2b87ff6a2931445 not found (tablet server error 6)


```
Then the sender will try next replica assuming it may be the new leader, the
code is:

```
  if (!current_ts_) {
    // Try to "guess" the next leader.
    vector<RemoteTabletServer*> replicas;
    tablet_->GetRemoteTabletServers(&replicas);
    for (RemoteTabletServer* ts : replicas) {
      if (!followers_.count(ts)) {
        current_ts_ = ts;
        break;
      }
    }
    if (current_ts_) {
      assign_new_leader_ = true;
```


it also failed because there is no real next leader when the table is deleted.

After all the replicas have been guessed and failed, it concluded that

`[ts-1] I0226 23:46:57.284149 12567 tablet_rpc.cc:158] Unable to pick leader for 0079795d6c7b4af6b2b87ff6a2931445, replicas: [], followers: [{0x00003470ffc24978 -> { uuid: d057030abaa742058c7ca15bcc4c8f54 private: [host: "127.48.46.0" port: 21181] cloud_info: placement_cloud: "cloud1" placement_region: "datacenter1" placement_zone: "rack1", { status: Not found (yb/tserver/ts_tablet_manager.cc:2256): Tablet 0079795d6c7b4af6b2b87ff6a2931445 not found (tablet server error 6) time: 0.007s }}, {0x00003470ffd31c38 -> { uuid: 36e46ef9ccb2479e902aefef4bd1c33a private: [host: "127.48.46.2" port: 24209] cloud_info: placement_cloud: "cloud1" placement_region: "datacenter1" placement_zone: "rack1", { status: Not found (yb/tserver/ts_tablet_manager.cc:2256): Tablet 0079795d6c7b4af6b2b87ff6a2931445 not found (tablet server error 6) time: 0.015s }}, {0x00003470ffc24018 -> { uuid: 1b01e7a2c11c4d3b8e7e44c671579c2e private: [host: "127.48.46.1" port: 29115] cloud_info: placement_cloud: "cloud1" placement_region: "datacenter1" placement_zone: "rack1", { status: Not found (yb/tserver/ts_tablet_manager.cc:2256): Tablet 0079795d6c7b4af6b2b87ff6a2931445 not found (tablet server error 6) time: 0.025s }}]`


The relevant code is (inside TabletInvoker::Execute)


```
  // If we've tried all replicas, force a lookup to the master to find the
  // new leader. This relies on some properties of LookupTabletByKey():
  // 1. The fast path only works when there's a non-failed leader (which we
  //    know is untrue here).
  // 2. The slow path always fetches consensus configuration information and
  //    updates the looked-up tablet.
  // Put another way, we don't care about the lookup results at all; we're
  // just using it to fetch the latest consensus configuration information.
  //
  if (!current_ts_) {
    client_->LookupTabletById(tablet_id_,
                              table_,
                              include_inactive_,
                              include_deleted_,
                              retrier_->deadline(),
                              std::bind(&TabletInvoker::LookupTabletCb, this, _1),
                              UseCache::kTrue);
    return;
  }
```

TabletInvoker::LookupTabletCb is the callback after the LookupTabletById RPC
returns. When the table is deleted, we'll get an "Not found" error back, as we
can see in the following comment which mentions exactly "Not found" which is an
error status that is *persistent*.

```
  // We should retry the RPC regardless of the outcome of the lookup, as
  // leader election doesn't depend on the existence of a master at all.
  // Unless we know that this status is persistent.
  // For instance if tablet was deleted, we would always receive "Not found".
  if (!result.ok() &&
      (result.status().IsNotFound() ||
       ClientError(result.status()) == ClientErrorCode::kTablePartitionListIsStale)) {
    command_->Finished(result.status());
    return;
  }

```

So this is how the DML query eventually see a "Not found" error. The Write RPC
that was prepared using stale metadata could not even reach the target tablet
yet because no tablet leader could be selected. Had a tablet leader been
successfully selected just before the tablet is deleted from the target tserver,
we could have shown a different error as in ticket #21200 .

**Comment by myang2021** [comment]
The difference between ticket #20959 and #21200 is that #20959 the target server could not be successfully selected (because the table is deleted), so the lookup RPC has failed. In #21200, target server was successfully selected but when the RPC reaches the target server, the tablet is already deleted. So #20959 detected the error at the RPC sender side, #21200 detected the error at the RPC receiver side. But they both failed for the same reason: the table is deleted. Because the error is detected at difference locations in the cluster, the exact error text can be different.
