### ISSUE TITLE
[YSQL] [Cross-DB-DDL] Database gets created with no catalog version

### ISSUE THREAD

**Issue by shishir2001-yb** [yugabyte/yugabyte-db#21213]
Jira Link: [DB-10141](https://yugabyte.atlassian.net/browse/DB-10141)
### Description

Tried on version **2.21.1.0-b124**
Logs: [https://drive.google.com/file/d/1RK6PiTh20-2UGd0jZr7-Al4_bBnPEBUh/view?usp=sharing](https://drive.google.com/file/d/1RK6PiTh20-2UGd0jZr7-Al4_bBnPEBUh/view?usp=sharing)
While running the Cross DB DDL sample app, noticed that one of the database got created without any catalog version.
```
2024-02-26 13:10:43,627 [main] ERROR AppBase - Going to retrieve connection again: FATAL: catalog version for database 16384 was not found.
  Hint: Database might have been dropped by another user
com.yugabyte.util.PSQLException: FATAL: catalog version for database 16384 was not found.
  Hint: Database might have been dropped by another user
  
  
  
For postgres_0, catalog version is not present

yugabyte=# SELECT datname from pg_database where oid = 16384;
  datname   
------------
 postgres_0
(1 row)

yugabyte=# SELECT CURRENT_VERSION FROM pg_yb_catalog_version WHERE db_oid =16384;
 current_version 
-----------------
(0 rows)


For postgres_1 it’s present

yugabyte=# SELECT oid  from pg_database where datname='postgres_1';
  oid  
-------
 16385
(1 row)

yugabyte=# SELECT CURRENT_VERSION FROM pg_yb_catalog_version WHERE db_oid =16385;
 current_version 
-----------------
               1
(1 row)

```

```
"tserverGFlags": [
               {"name": "ysql_enable_packed_row", "value": "true"},
               {"name": "ysql_enable_packed_row_for_colocated_table", "value": "true"},
               {"name": "enable_automatic_tablet_splitting", "value": "true"}, 
               {"name": "ysql_max_connections", "value": "500"},
               {"name": "client_read_write_timeout_ms", "value": "1800000"},
               {"name": "yb_client_admin_operation_timeout_sec", "value": "1800"}, 
               {"name": "consistent_restore", "value": "true"},
               {"name": "ysql_enable_db_catalog_version_mode", "value": "true"}
],
master_gflags=[
               {"name": "ysql_enable_packed_row", "value": "true"},
               {"name": "ysql_enable_packed_row_for_colocated_table", "value": "true"},
               {"name": "enable_automatic_tablet_splitting", "value": "true"},
               {"name": "tablet_split_high_phase_shard_count_per_node", "value": 20000},
               {"name": "tablet_split_high_phase_size_threshold_bytes", "value": 2097152}, 
               {"name": "tablet_split_low_phase_size_threshold_bytes", "value": 102400},
               {"name": "tablet_split_low_phase_shard_count_per_node", "value": 10000},
               {"name": "consistent_restore", "value": "true"},
               {"name": "ysql_enable_db_catalog_version_mode", "value": "true"}, 
              {"name": "allowed_preview_flags_csv", "value": "ysql_enable_db_catalog_version_mode"}, 
              {"name": "tablet_replicas_per_gib_limit", "value": 0}
]

```

List of DDLs executed in sample app

```
private static List<List<String>> ddlList = List.of(
            List.of("CREATE INDEX idx1 ON ? (k)", "DROP INDEX idx1"),
            List.of("CREATE TABLE tempTable1 AS SELECT * FROM ? limit 1000000", "ALTER TABLE tempTable1 RENAME TO tempTable1_new", "DROP TABLE tempTable1_new"),
            List.of("CREATE MATERIALIZED VIEW mv1 as SELECT k from ? limit 10000", "REFRESH MATERIALIZED VIEW mv1", "DROP MATERIALIZED VIEW mv1"),
            List.of("ALTER TABLE ? ADD newColumn1 TEXT DEFAULT 'dummyString'", "ALTER TABLE ? DROP newColumn1"),
            List.of("ALTER TABLE ? ADD newColumn2 TEXT NULL", "ALTER TABLE ? DROP newColumn2"),
            List.of("CREATE VIEW view1_? AS SELECT k from ?", "DROP VIEW view1_?"),
            List.of("ALTER TABLE ? ADD newColumn3 TEXT DEFAULT 'dummyString'", "ALTER TABLE ? ALTER newColumn3 TYPE VARCHAR(1000)", "ALTER TABLE ? DROP newColumn3"),
            List.of("CREATE TABLE tempTable2 AS SELECT * FROM ? limit 1000000", "CREATE INDEX idx2 ON tempTable2(k)", "ALTER TABLE ? ADD newColumn4 TEXT DEFAULT 'dummyString'", "ALTER TABLE tempTable2 ADD newColumn2 TEXT DEFAULT 'dummyString'", "TRUNCATE table ? cascade", "ALTER TABLE ? DROP newColumn4", "ALTER TABLE tempTable2 DROP newColumn2", "DROP INDEX idx2", "DROP TABLE tempTable2"),
            List.of("CREATE VIEW view2_? AS SELECT k from ?", "CREATE MATERIALIZED VIEW mv2 as SELECT k from ? limit 10000", "REFRESH MATERIALIZED VIEW mv2", "DROP MATERIALIZED VIEW mv2", "DROP VIEW view2_?")
 );

```

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-10141]: https://yugabyte.atlassian.net/browse/DB-10141?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by myang2021** [comment]
This is a known restriction that DDL statements are not supported during the finalization phase of a YSQL cluster upgrade (to a release where the per-db catalog version mode is enabled).
The test is done by first creating the cluser with the gflag `"ysql_enable_db_catalog_version_mode=true,allowed_preview_flags_csv=ysql_enable_db_catalog_version_mode"`, but the table `pg_yb_catalog_version` remains in global mode (which means there is only one row in it). This situation is like simulating a YSQL cluster upgrade as described above. Then the following statements were executed (simulating what happens during the finalization phase):

```
SET yb_non_ddl_txn_for_sys_tables_allowed=true;
SELECT yb_fix_catalog_version_table(true);
```

In the failed test run, it was found that dropping 40 databases took roughly 400ms, which is less than a tserver-master heartbeat delay.

```
2024-02-26 13:09:47,282 [main] INFO CmdLineOpts - SqlTransactions: will use 30 value columns for the main table
2024-02-26 13:09:47,766 [main] INFO SqlCrossDBLoadWithDDL - Dropped 40 databases
```

The log timestamp means from 282 millisecond to 766 millisecond? That ’s less than a heartbeat delay.


What happened is: right after `SELECT yb_fix_catalog_version_table(true);`, the test quickly finished dropping 40 databases, and then immediately starts to create the databases. There is a very small racing window (up to 1 second heartbeat delay). During this time, we have `pg_yb_catalog_version` table already fixed up by the above two statements, but due to heartbeat delay, that fact (table has multiple rows) hasn’t propagated to all tserver yet. As a result, the backend that starts to create DBs still sees only 1 row in tserver (represented as an in-memory map just like the table itself, using db_oid as the key of the map). The logic is that if the tserver map only has 1 row, then the PG backend will still operate in global catalog version mode despite that the gflag is on. Only until the tserver map has changed to > 1 rows, the PG backend will dynamically switch to per-db mode.
So if when creating the very first DB, the tserver map still only had 1 row, then this create DB statement is going to operate in global mode, which will not create the row in `pg_yb_catalog_version` table. The symptom of this bug aligns well with the above theory that the very first DB was created in global-mode so it does not have a row in `pg_yb_catalog_version` table while all the rest do because by the time they are executed it has well passed 1 second heartbeat delay so the PG backend operates in perdb mode and thus created a row for each of the rest DB.


In YSQL upgrade, there are two phases:
(1) a tryout phase (the upgrade can be rolled back) when the gflag is on, but the table still only has 1 row
(2) a finalization phase (the upgrade cannot be rolled back)
It. is known that during finalization phase DDL statements are not supported. That is the phase when the above SELECT happens and customers are advised not to run any DDL during this phase. However currently it is not enforced. In the future it is planned to treat this finalization phase as a critical section and yb-master will fail all DDLs during this window.

To work around the test issue, we can add a 2-second delay right after `SELECT yb_fix_catalog_version_table(true);` to allow enough time for the new state of `pg_yb_catalog_version` to propagate via tserver-master heartbeat.

**Comment by myang2021** [comment]
I also verified that the issue can be manually fixed by rerunning the statements:

```
SET yb_non_ddl_txn_for_sys_tables_allowed=true;
SELECT yb_fix_catalog_version_table(true);
```
