### ISSUE TITLE
[DocDB][DB Clone][YSQL] Colocated DB Cloning fails to the time before drop colocated table

### ISSUE THREAD

**Issue by Arjun-yb** [yugabyte/yugabyte-db#21626]
Jira Link: [DB-10521](https://yugabyte.atlassian.net/browse/DB-10521)
### Description

**Version**: **2.23.0.0-b36**
**Steps**:

1. Create colocated database(demo1) and create snapshot schedule
2. Create table and load some data
3. Collect time(t1)
4. Drop table
5. Clone demo1 to demo2 at time t1

**Observation**:
DB clone command works and returns namespace id and seq number, but is_clone_done command returns false and there wont be any cloned DB

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-10521]: https://yugabyte.atlassian.net/browse/DB-10521?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by yamen-haddad** [comment]
Tried to repro locally after having the fix. 
Currently, the clone operation will finish successfully and I was able to connect to the target database and check the existence of the table t.

However, surprisingly, I wasn't able to read any data from the table. i,e: on the source database and at time t1, the table t has:
```
db1=# select * from t;
 k | v 
---+---
 1 | 1
 2 | 2
 3 | 3
 4 | 4
 5 | 5
(5 rows)
```

However, on the target database:
```
db2=# select * from t;
 k | v 
---+---
(0 rows)

```

I still need to figure out why that happens. What I can confirm is that the colocated target database has been created successfully. The same for the creation of the colocated table t. 

I checked the data files in the tablet of the target database vs source database, and they were not copied from source to target.
<img width="1681" alt="Screenshot 2024-06-06 at 3 36 17 AM" src="https://github.com/yugabyte/yugabyte-db/assets/22749018/1f5537eb-8c3e-4790-9366-3270201b725a">

I also didn't find the snapshot directory in the target tablet.   So most likely we failed at export/import snapshot steps of clone.

**Comment by yamen-haddad** [comment]
Was YSQL auth disabled in this universe?
If yes, then clone is failing as `ysql_dump` cannot connect to postgres using local unix domain socket. The error we are getting is:
`ysql_dump: [archiver (db)] connection to database "db1" failed: FATAL:  no pg_hba.conf entry for host "[local]", user "yugabyte", database "db1", SSL off`
After checking the `pg_hba.conf` and when ysql auth is off:
```
$ cat /mnt/d0/pg_data/ysql_hba.conf
# This is an autogenerated file, do not edit manually!
# Internal configuration:
# local all postgres yb-tserver-key
hostssl all all all trust
```
However, when ysql auth is enabled then clone should succeed. This is because we trust local connections in case ysql auth is on. As shown here:
```
$ cat /mnt/d0/pg_data/ysql_hba.conf
# This is an autogenerated file, do not edit manually!
# Internal configuration:
# local all postgres yb-tserver-key
local all yugabyte trust
hostssl all all all md5
```
So in order for clone to work we need to run ysql_dump and ysqlsh according to whether ysql auth is enabled/disabled as follows:

- When ysql auth is disabled, we guarantee that we trust connections using ssl:  hostssl all all all trust and thus we connect to pg using IP.

- When ysql quth is enabled, we guarantee that we trust local connections using unix domain sockets local all yugabyte trust and thus we connect to pg using local UDX.
