### ISSUE TITLE
[DocDB] [DB Clone][YSQL] DB Cloning is not happening to the time before materialised view drop

### ISSUE THREAD

**Issue by Arjun-yb** [yugabyte/yugabyte-db#21621]
Jira Link: [DB-10516](https://yugabyte.atlassian.net/browse/DB-10516)
### Description

**Version**: **2.23.0.0-b36**
**Steps**:

1. Create database(demo1) and create snapshot schedule
2. Create table and load some data
3. Create materialised view
4. Collect time(t1)
5. Drop materialised view
6. Clone demo1 to demo2 at time t1

**Observation**:
DB clone command works and returns namespace id and seq number, but is_clone_done command returns false and there wont be any cloned DB

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-10516]: https://yugabyte.atlassian.net/browse/DB-10516?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by yamen-haddad** [comment]
I tried to repro locally after having the [fix](https://phorge.dev.yugabyte.com/D35178). The clone operation now succeeds and I verified that we can use both the materialized view and the original table in some select queries in the target database.

I even tried to add some data to the original table on the target database and then refresh the materialized view. I was able to read the most recent data after refreshing.

Therefore, this issue and https://github.com/yugabyte/yugabyte-db/issues/21600 share the same root cause.
I am leaving the ticket open as I am planning to write a unit test covering this case.
