### ISSUE TITLE
[DocDB][DB Clone][YSQL] Colocated DB Cloning fails to the time before drop index

### ISSUE THREAD

**Issue by Arjun-yb** [yugabyte/yugabyte-db#21627]
Jira Link: [DB-10522](https://yugabyte.atlassian.net/browse/DB-10522)
### Description

**Version**: **2.23.0.0-b36**
**Steps**:

1. Create colocated database(demo1) and create snapshot schedule
2. Create table and load some data
3. Create index
4. Collect time(t1)
5. Drop index
6. Clone demo1 to demo2 at time t1

**Observation**:
DB clone command works and returns namespace id and seq number, but is_clone_done command returns false and there wont be any cloned DB

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-10522]: https://yugabyte.atlassian.net/browse/DB-10522?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by yamen-haddad** [comment]
Getting to the bottom of this:
The error we see when querying the clone database is:
```
ERROR:  LookupByIdRpc(tablet: 9ed75cb744e147e7b16d233436378219, num_attempts: 2) failed: Tablet deleted: Old tablets of table 00004002000030008000000000004003.colocation.parent.uuid deleted at 2024-08-07 01:08:00 UTC
```
This comes from the fact that the index is pointing to the original colocated tablet created as part of executing the ysql_dump (rather than pointing to the new colocated tablet that is created as part of `repartionTable` of the parent table).
As per why the index info is not updated to point to the new tablet, this is because we are skipping the `ImportTableEntry` step in `ImportSnapshotCreateAndWaitForTables` for indexes.
