### ISSUE TITLE
[YSQL] Decreased Total ops after upgrade from 2.18.4.0-b52 to 2024.1 (INSERT only workloads)

### ISSUE THREAD

**Issue by shamanthchandra-yb** [yugabyte/yugabyte-db#22023]
Jira Link: [DB-10940](https://yugabyte.atlassian.net/browse/DB-10940)
### Description

Please find slack thread in JIRA.

**Steps:**
7 nodes, RF3 universe setup.
Started multiple INSERT only workloads with single read/write thread for all workloads, such that CPU comes to 70% or 75% range. 
Run for an hour on 2.18 and then upgrade to 2024.1

![Screenshot 2024-04-17 at 8 33 32 AM](https://github.com/yugabyte/yugabyte-db/assets/109518123/e697ed49-53a0-466c-8048-8a799c85892a)
![Screenshot 2024-04-17 at 8 33 48 AM](https://github.com/yugabyte/yugabyte-db/assets/109518123/942a716b-d560-4fb0-9687-dd8f8662c6c1)

**Observation:**
It hits https://github.com/yugabyte/yugabyte-db/issues/21979 but if databases are less (QA note: by increasing read/write threads to 3 or 5), it comes back after 3 to 4 mins. But, total ops, is much lesser and stays in the same level even after hours.

Workload Example: 
```
java -jar /tmp/tests/artifacts/stress-sample-app-tool/yb-stress-sample-apps-1.1.43.jar --workload SqlDataLoad --num_writes -1 --num_threads_write 1 --num_threads_read 1 --num_reads -1 --num_unique_keys 100000000000000 --batch_size 3 --num_value_columns 10 --create_table_name table_db_28015f --default_postgres_database db_28015f --uuid_column --uuid 7a8a205e-51f2-447d-849e-3a2a593c5ecb --large_key_multiplier 3 --large_value_multiplier 3 --use_hikari true --uuid_marker db_28015f_file --nodes 172.151.23.72:5433,172.151.23.146:5433,172.151.26.159:5433,172.151.25.68:5433,172.151.18.7:5433,172.151.31.67:5433,172.151.17.128:5433
```

Read and write code can be seen here: https://github.com/yugabyte/yb-stress-test/blob/master/tools/sample-app/src/main/java/com/yugabyte/sample/apps/SqlDataLoad.java

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-10940]: https://yugabyte.atlassian.net/browse/DB-10940?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by myang2021** [comment]
After debugging, we now believe the root cause of this regression is the newly introduced tserver memory limit where we put a cap of the memory that tserver can use in order to leave some room for PG backends. Otherwise, if tserver uses as much memory as it needs/wants to, then the node will not have much memory left for PG backends. However when tserver has less memory as its disposal, it is also less powerful and therefore has less processing power. Therefore the automatic flow control mechanism will throttle the amount of traffic that the client can send to the tserver, which leads to descreased total ops.
