### ISSUE TITLE
[Platform] Add itest to test upgrades for YSQL enabled clusters

### ISSUE THREAD

**Issue by ndeodhar** [yugabyte/yugabyte-db#2270]

**Comment by ndeodhar** [comment]
Related to #2354

**Comment by iSignal** [comment]
@ndeodhar and @Arnav15  had a suggestion that simplifies the itest code. Instead of explicitly checking for tables to be present across upgrades, we could use the sample apps workload to make sure data is present across upgrades. Currently, SQL sample apps workload may try to recreate missing tables and I may need to add parameters that allow it to simply read and error if tables/rows are not found. We also need to coordinate the itest upgrade so that it waits for the SQL sample workload to begin before upgrading.

**Comment by iSignal** [comment]
Added itest for AWS and Kubernetes. Will track remaining work in #2533
