### ISSUE TITLE
[docs] Stop tracking generated SVG files

### ISSUE THREAD

**Issue by jaki** [yugabyte/yugabyte-db#2316]
Currently, generated diagram and grammar files for YSQL API docs are tracked in the repo.  The fact that they are generated should be good enough reason to try to get them untracked, but what makes it worse is the fact that the diagram files contain large SVG images in them--practically binaries.  Every small edit to the grammar can cause huge diffs from the SVG images changing.  The sooner these generated files get ignored, the smaller this repository will be for the future.

**Comment by jj-kim** [comment]
The main files/directories in question are the following:

* [`docs/content/latest/api/ysql/syntax_resources/grammar_diagrams.md`][1]
* [`docs/content/latest/api/ysql/syntax_resources/commands/`][2]

The YCQL side does not seem to be generating files (at least the last time that I checked), so that can remain untouched.

This will likely not be as simple as adding lines to [`.gitignore`][3].

* The deployment to https://docs.yugabyte.com may need to be looked at for potential conflicts with this change.  This should be investigated first to see how feasible this change is in the first place.
* When generated files are taken out of the repo, the current generation method will likely not be feasible.  As detailed in the [docs README][4] and implemented in the [RRDiagram generator][5], **existing** files are searched, and their file names determine what to generate.  Not tracking the files from the [`commands`][2] directory makes it difficult to determine what to generate.  There are two approaches that I currently have in mind:

  * Tweak the [RRDiagram generator][4] to not rely on existing files and their filenames.  A new method of reading from a configuration file (or even the [EBNF file][6]) could be designed.
  * Update the [docs README][5] to have users manually create all these files with their respective filenames.  By itself, it sounds like a terrible idea to me, but maybe there's some other similar way to go about solving this while leaving the [RRDiagram generator][4] unchanged.

[1]: https://github.com/yugabyte/yugabyte-db/blob/master/docs/content/latest/api/ysql/syntax_resources/grammar_diagrams.md
[2]: https://github.com/yugabyte/yugabyte-db/tree/master/docs/content/latest/api/ysql/syntax_resources/commands
[3]: https://github.com/yugabyte/yugabyte-db/blob/master/docs/.gitignore
[4]: https://github.com/yugabyte/yugabyte-db/blob/master/docs/README.md
[5]: https://github.com/yugabyte/RRDiagram
[6]: https://github.com/yugabyte/yugabyte-db/tree/master/docs/content/latest/api/ysql/syntax_resources/ysql_grammar.ebnf

**Comment by polarweasel** [comment]
Hey @yb-andrew and @jharveysmith let's look at what it would take to generate the SVGs as part of the docs build.

Right now, there are 646 `*.diagram.md* files, and they're all the same format: a markdown heading 3, and a very long inline SVG element. This seems ripe for automation. :)

**Comment by polarweasel** [comment]
We may address this at some point in the future, but not anytime soon

**Comment by bllewell** [comment]
Note: the title is badly worded. It's not just the generated SVG files (i.e. _*.diagram.md_) that should be excluded from the repo; it's also the generated plain text _*.grammar.md_ files.
