### ISSUE TITLE
[YSQL] For testing of using mini cluster, which languguage (C++ or Java) should be used and why?

### ISSUE THREAD

**Issue by tony-bigmath** [yugabyte/yugabyte-db#23281]
Jira Link: [DB-12210](https://yugabyte.atlassian.net/browse/DB-12210)
### Description

For testing by using mini cluster, there are two languages to apply.

One is C++. For example, src/yb/integration-tests/external_mini_cluster-test.cc. 
We can use the external mini cluster (usually 6 sub-process for a cluster) for testing by C++.

The other is Java. For example, java/yb-pgsql/src/test/java/org/yb/pgsql/BasePgSQLTest.java. 
There are something like above which also use a mini cluster of 6 sub-process for a cluster.

Why use two languages for the same mini cluster?

If I want to wite a test case, which one is preferred? 

Thanks.

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-12210]: https://yugabyte.atlassian.net/browse/DB-12210?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by tony-bigmath** [comment]
For two examples.

1、 Just a simple INSERT statement (DML). 

2、If I want to build a more complex testing like creating an index(DDL) by backfilling and checking whether it is finished.

**Comment by jasonyb** [comment]
The main types are

- Java mini cluster tests
- regress tests (wrapped using Java)
- C++ external mini cluster tests
- C++ mini cluster tests

Regress tests are most user friendly.  But they are not flexible.

Java mini cluster tests and C++ external mini cluster tests are similar: both create master and tserver (and PG) processes.  There are some individual differences between them:
- Java exercises the JDBC driver and C++ exercises libpq.  Java tests tend to use the extended query protocol while C++ tests tend to use the simple query protocol.  Unless you know the difference, it is unlikely to be a deciding factor for where you place your test.  We have found bugs related to the extended query protocol, so maybe that is a slight reason in favor of Java.
- Certain features have helpers written on one side.  For example,
  - upgrade tests: java
  - YSQL connection manager: java
  - DDL atomicity: C++
- Java is slower to build and run

Both are more powerful than regress tests, for example,
- Values can easily be stored in variables in code.  For regress tests, that is possible but not as user friendly.
- Multithreading: simple regress tests do not do that, and isolation regress tests are still very inflexible.
- There's access to tools like yb-admin
- There's access to HTTP endpoints for master/tserver web UIs

C++ mini cluster tests are different in that they have all masters and tservers in the same process as the test process.  This breaks some workflows such as index backfill.  However, it provides even more accessibility over the above because you have access to the master/tserver process internals such as catalog manager.  Avoid this unless you intentionally want the deep access to internals.

Please see https://docs.yugabyte.com/preview/contribute/core-database/build-and-test for more details.

> creating an index(DDL) by backfilling and checking whether it is finished

You can check out src/yb/yql/pgwrapper/pg_index_backfill-test.cc.  But this assumes you specifically care about the index creation.  General index creation can go in other tests, such as pg_libpq-test.cc.  Or if your test cares a lot more about transactions, maybe some transaction test file.

**Comment by tony-bigmath** [comment]
Great and detailed answer.
Thank you very much.
------------------------------------------------------------------
发件人：jasonyb ***@***.***>
发送时间：2024年7月26日(星期五) 00:22
***@***.***>
***@***.***>; ***@***.***>
主　题：Re: [yugabyte/yugabyte-db] [YSQL] For testing of using mini cluster, which languguage (C++ or Java) should be used and why? (Issue #23281)
The main types are

 * 
Java mini cluster tests

 * 
regress tests (wrapped using Java)

 * 
C++ external mini cluster tests

 * 
C++ mini cluster tests
Regress tests are most user friendly. But they are not flexible.
Java mini cluster tests and C++ external mini cluster tests are similar: both create master and tserver (and PG) processes. There are some individual differences between them:

 * 
Java exercises the JDBC driver and C++ exercises libpq. Java tests tend to use the extended query protocol while C++ tests tend to use the simple query protocol. Unless you know the difference, it is unlikely to be a deciding factor for where you place your test. We have found bugs related to the extended query protocol, so maybe that is a slight reason in favor of Java.

 * 
Certain features have helpers written on one side. For example, 
 * 
upgrade tests: java

 * 
YSQL connection manager: java

 * 
DDL atomicity: C++

 * 
Java is slower to build and run
Both are more powerful than regress tests, for example,

 * 
Values can easily be stored in variables in code. For regress tests, that is possible but not as user friendly.

 * 
Multithreading: simple regress tests do not do that, and isolation regress tests are still very inflexible.

 * 
There's access to tools like yb-admin

 * 
There's access to HTTP endpoints for master/tserver web UIs
C++ mini cluster tests are different in that they have all masters and tservers in the same process as the test process. This breaks some workflows such as index backfill. However, it provides even more accessibility over the above because you have access to the master/tserver process internals such as catalog manager. Avoid this unless you intentionally want the deep access to internals.
Please see https://docs.yugabyte.com/preview/contribute/core-database/build-and-test <https://docs.yugabyte.com/preview/contribute/core-database/build-and-test > for more details.
creating an index(DDL) by backfilling and checking whether it is finished
You can check out src/yb/yql/pgwrapper/pg_index_backfill-test.cc. But this assumes you specifically care about the index creation. General index creation can go in other tests, such as pg_libpq-test.cc. Or if your test cares a lot more about transactions, maybe some transaction test file.

**Comment by ddorian** [comment]
Closing as completed.
