### ISSUE TITLE
[Docs] The sequence of actions is wrong on this Assess Migration page

### ISSUE THREAD

**Issue by yushenng** [yugabyte/yugabyte-db#23684]
### Description

The sequence of actions is wrong on this Assess Migration page

CURRENT STEPS:
  1. Install yb-voyager
  2. Prepare the source database (with a user and permissions)
  3. Run "yb-voyager assess migration"
  4. Create a target YugabyteD cluster
  5. Proceed with migrating (offline, live, etc)

The problem with the CURRENT STEPS is: after step 4 and step 5, if you visit the yugabyteD web GUI and click on the "Migrations" icon on the left nav, you'll see "No migrations available."

I worked with Nikhil C and came up with the below steps to correct this behavior

CORRECTED NEW STEPS:
  1. Install yb-voyager
  2. Prepare the source database (with a user and permissions)
  3. Create a target YugabyteD cluster
  4. Run "yb-voyager assess migration"
  5. Proceed with migrating (offline, live, etc)

(Note that I've swapped steps 3 and 4)

With these corrected steps, you'll see a migration appear in the yugabyteD web GUI after step 4.  This is the better & desired behavior.

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

**Comment by ddhodge** [comment]
@yushenng @ymahajan 
https://docs.yugabyte.com/preview/yugabyte-voyager/migrate/assess-migration/#get-started-with-migration-assessment
Page was recently updated - albeit without the Prepare Source db step. Is that necessary for the Assessment, or only for the actual offline/live migration?
Can still be improved but otherwise I think it addresses the basic problem - seeing migrations in yugabyted
