### ISSUE TITLE
--ysql_enable_auth unable to authenticate

### ISSUE THREAD

**Issue by kntait** [yugabyte/yugabyte-db#2465]
Using docker image yugabytedb/yugabyte:2.0.0.0-b16 i am not able to user authenticate with YSQL when using the t-server command option --ysql_enable_auth. 

Feedback from mihne.
mihnea (YB)  2 hours ago
There is no password by default which causes issues when creating the cluster with that flag.  As a workaround, you can start the cluster without the flag. Then connect  and set passwords (and/or add/remove users as needed) with the usual SQL commands. Finally restart the cluster with that flag. I think we should improve the defaults for the auth case soon, so that it works out of the box. (edited)

The above aproach is not practical when automating a deployment of YugabyteDB, when enabling  --ysql_enable_auth we should be able to login with default credentials and then create our own accounts and reset the default account password.

**Comment by ddorian** [comment]
Did you try with `postgres/postgres` and `yugabyte/yugabyte` as username/password when setting --ysql_enable_auth ?

**Comment by kntait** [comment]
Hi @ddorian, 

The following options all fail with --ysql_enable_auth=true set on all t-servers.

u:postgres p:postgres 
u:postgres p:
u:yugabyte p:yugabyte
u:yugabyte p:

As i mentioned above @m-iancu confirm on the the Yugabyte slack channel that "There is no password by default which causes issues when creating the cluster with that flag". I was then asked to create this issue.

The only thing that does work is to pass the below giving super user access with no password, however this is not practical or secure in a production environment.

--ysql_hba_conf='host all yugabyte 0.0.0.0/0 trust,host all all 0.0.0.0/0 md5,host all yugabyte ::0/0 trust,host all all ::0/0 md5'

**Comment by schoudhury** [comment]
The latest 2.0.1 release has fixed this issue the following way.

1. `yugabyte` user defaults a password `yugabyte` for all new clusters starting 2.0.1. 
- if the new cluster is started without the `ysql_enable_auth` flag then this default password will not be used.
- if the new cluster is started with the `ysql_enable_auth` flag turned on , then the default password will be used.
2. clusters that upgrade from 2.0.0 to 2.0.1 will continue to have the `yugabyte` user without any password. so a password has to be explicitly set for this user in case the cluster is started with the `ysql_enable_auth` flag turned on.

@m-iancu pls close this issue when you have a moment since 2.0.1 release is already available for download along with the necessary doc updates.
