### ISSUE TITLE
[docdb] Track remote bootstrapping tablets in IsLoadBalanced API

### ISSUE THREAD

**Issue by rahuldesirazu** [yugabyte/yugabyte-db#2474]
Jira Link: [DB-1883](https://yugabyte.atlassian.net/browse/DB-1883)
Currently, remote bootstrapping tablets aren't tracked as table or tablet server tasks. Which means that IsLoadBalanced can return true even if a peer is remote bootstrapping.

cc: @bmatican

**Comment by bmatican** [comment]
@hulien22 Can you double check if this is actually still a concern? In particular, I'm thinking there's 2 windows where this could be an issue
- the tablet is doing remote bootstrap, so the new peer has yet to start the tablet
- the tablet is done remote bootstrapping, and now the peer is opening it up, but it will take a while to do log replay, during which the tablet should be in BOOTSTRAPPING state, I believe

Technically, both of these should be covered by the LB and it should not report idle -- I believe Hector added a mechanism for the TS to report via heartbeats, that it is bootstrapping a tablet, but TBD if that only overs part 2, of locally bootstrapping... We should also have some gflags to slow down both remote bootstrap and local bootstrap, to simulate this (eg: taking 5-10 LB runs to actually finish either operation).

cc @sanketkedia @rahuldesirazu

**Comment by bmatican** [comment]
@lingamsandeep Might be an easy starter task to try out the above behavior.

**Comment by joe-maley** [comment]
We have a flag `simulate_long_remote_bootstrap_sec` that will sleep after the remote bootstrap client fetches all files but before it finalizes the session. I tested the following scenario:
```
- Set a 20-second delay using the above flag.
- Add a tserver to the cluster.
- Issued a `IsLoadBalanced` RPC to the master every 500ms for 30 seconds.
```

I observed the following:

1. The `IsLoadBalanced` correctly returned a non-balanced status while the new tablet was remote bootstrapping, but for the wrong reason. The load balancer added a task to move a tablet from an existing tserver to the new tserver, which was hung in an active state until the remote bootstrapping completed. I think this is just a coincidence for my particular repro, so I'll say that this problem is still a concern.

2. After the new tserver was added, each tserver reported that the `PeerMemberType` of the new tserver was a `PRE_VOTER`. The comments in the remote bootstrap path indicate that the bootstrapping peer will be in either a `PRE_VOTER` or `PRE_OBSERVER` state. The remote bootstrap client moves the peer into either the `VOTER` or `OBSERVER` state when it finalizes the remote bootstrap. I think we could use this state to cover both of the cases that @bogdan mentioned. However, I am not familiar enough with the bootstrapping process to be certain that the peer will always be in one of these `PRE_*` states.

3. The heartbeat/report sent by the new tserver reports that the `TabletDataState` of the remote bootstrapping tablet is `TABLET_DATA_COPYING`. When the remote bootstrap completes, this state is reported as `TABLET_DATA_READY`. I think we could use this state to cover the second case that Bogdan mentioned.
