### ISSUE TITLE
[docdb] Develop a custom WriteBatch format for UpdateConsensus to reduce memory allocations and duplication

### ISSUE THREAD

**Issue by mbautin** [yugabyte/yugabyte-db#2569]
Jira Link: [DB-1601](https://yugabyte.atlassian.net/browse/DB-1601)

**Comment by bmatican** [comment]
Hey @spolitov @mbautin what's the background for this issue? Would this cause any compatibility issues?

**Comment by spolitov** [comment]
During the write-heavy load, we observe the situation that allocation/deallocation of key-value pairs protobuf takes a significant amount of time.
So instead of creating and replicating the key-value pairs list, we could create a write batch at the leader.
Write batch is just a string, so we could replicate only this one string and apply it in followers.

But for transactions, we don't put key-value as is.
And could generate several intents/rocksdb entries per key-value pair.
So the first step is to create a new batch format, that will be parsed to multiple rocksdb entries.

**Comment by spolitov** [comment]
And yes, it will break backward compatibility, so nodes with an old version would not be able to apply new write batches correctly.
To address this issue we plan to add gflag, which will disable new functionality by default.
