### ISSUE TITLE
Add HTTP endpoint for determining master leadership

### ISSUE THREAD

**Issue by fastest963** [yugabyte/yugabyte-db#2606]
Right now if we point a GCE load balancer at port 7000 and the GCE lb sends the traffic to a follower then the page just says "Cannot get Leader information to help you redirect...". Instead if there was a `/api/v1/is_leader` that returns 200 if it's the leader and a non-200 status code when it's not the leader then I could set the GCE lb to look at that endpoint for health checking and then only the master would be healthy.

**Comment by fastest963** [comment]
The reason I think that we get the `Cannot get Leader information to help you redirect...` is because it's trying to talk to the other master via it's hostname and not the `server_broadcast_addresses` if that's a bug I can file it separately. Our hostnames are not resolvable which is why I've been passing the correct resolvable address via `server_broadcast_addresses`.

**Comment by vvkgopalan** [comment]
A commit addressing this issue by adding an `<web>/api/v1/is-leader` endpoint as well as an additional `<web>/api/v1/masters` endpoint to dump information about the masters has been checked in here: https://github.com/yugabyte/yugabyte-db/commit/843e622f433751e02769c1e815ff1023d4201ca6. 
`<web>/api/v1/is-leader` returns a `503 Service Unavailable` response code when the master is not a leader and a `200` response otherwise.
