### ISSUE TITLE
Integration test failure for ysql

### ISSUE THREAD

**Issue by ramkumarvs** [yugabyte/yugabyte-db#2744]
Fix integration test failure around ysql 

testupgrade-k8s-ysql: Start
        (     0.445s) User Login : Success
        (     0.113s) Refresh YB Version : Success
        (   170.573s) Setup Provider : Success
        (   296.944s) Create universe sched-a86581f455-20191028-080021 : Success
        (   233.742s) Upgrade Software : Success
        (     0.080s) Check and stop workloads : >>> Integration Test Failed <<<
Workload reported error: 122590 [Thread-6] FATAL com.yugabyte.sample.apps.SqlInserts  - Failed reading value: val:27710
        (    13.763s) Saved server log files at /home/centos/save/20191028-080021/2.0.3.0_a86581f455_20191028_132907 : Success
        (     5.089s) Destroy universe : Success
testupgrade-k8s-ysql: End

**Comment by iSignal** [comment]
@Arnav15 looked into this in more detail - the issue was that yb-sample-apps SQL workload makes a JDBC connection to the kubernetes load balancer on port 5433. During the upgrade, as nodes are restarted, the connection will be terminated, causing the SQL workload to start reporting 'FATAL' errors. The regular java JDBC driver does not re-establish failed connections (the cql driver seems to do so instead), so the error never clears.

It is actually suprising that this test ever passed in the past, so the current plan is to:
1/ understand why the test passed earlier
2/ disable the itest for now until we get a smart SQL client that can re-establish connections (@m-iancu )

For now, this test failure should not hold up the release.

**Comment by iSignal** [comment]
@Arnav15 's theory was correct. I was able to run the itest for upgrade k8s ysql succesfully and lines after line 40 had errors but the itest only checks the first 40 lines of the output.

https://gist.github.com/iSignal/51f866293e4e2c5bb5256a3e0966fb47

**Comment by iSignal** [comment]
Fixed by disabling the test. We will need a smarter SQL client (than the one in yb-sample-apps) in order to re-enable this test.
