### ISSUE TITLE
[YCQL] Issue with enabling node to node TLS within a docker-compose container due to changes in bind_address behavior

### ISSUE THREAD

**Issue by kntait** [yugabyte/yugabyte-db#2783]
Jira Link: [DB-4688](https://yugabyte.atlassian.net/browse/DB-4688)
In YugabyteDB v2.0.3 (Docker image yugabytedb/yugabyte:2.0.3.0-b7) i have identified an issue with YCQL on tservers not binding to 0.0.0.0:9042 when specifying "--rpc_bind_addresses".

This was not an issue in prior versions.

When specifying "--rpc_bind_addresses" the YCQL listening address changes to 'container ip':9042

In my setup i need to set the "--rpc_bind_addresses='container name':9100" for node-node TLS with "--use_node_to_node_encryption=true".

I have successfully replicated this issue using the documented example docker-compose file at
https://docs.yugabyte.com/latest/deploy/docker/docker-compose/, see below:

As a workaround i have tried to set "--cql_proxy_bind_address=0.0.0.0:9042" with "--rpc_bind_addresses=yb-tserver-n1:9100" and "--use_node_to_node_encryption=true" however the tservers start and then immediately fail with no error message.

Example compose file:

version: '2'

services:
  yb-master:
      image: yugabytedb/yugabyte:2.0.3.0-b7
      container_name: yb-master-n1
      command: [ "/home/yugabyte/bin/yb-master",
                "--fs_data_dirs=/mnt/disk0,/mnt/disk1",
                "--master_addresses=yb-master-n1:7100",
                "--replication_factor=1",
                "--enable_ysql=true"]
      ports:
      - "7000:7000"
      environment:
        SERVICE_7000_NAME: yb-master

  yb-tserver:
      image: yugabytedb/yugabyte:2.0.3.0-b7
      container_name: yb-tserver-n1
      command: [ "/home/yugabyte/bin/yb-tserver",
                "--fs_data_dirs=/mnt/disk0,/mnt/disk1",
                "--start_pgsql_proxy",
                "--tserver_master_addrs=yb-master-n1:7100",
                "--rpc_bind_addresses=yb-tserver-n1:9100"]
      ports:
      - "9042:9042"
      - "6379:6379"
      - "5433:5433"
      - "9000:9000"
      environment:
        SERVICE_5433_NAME: ysql
        SERVICE_9042_NAME: ycql
        SERVICE_6379_NAME: yedis
        SERVICE_9000_NAME: yb-tserver
      depends_on:
      - yb-master

**Comment by kntait** [comment]
Hi @iSignal, as discussed here is the issue.

**Comment by iSignal** [comment]
One recent change in this area is https://github.com/yugabyte/yugabyte-db/commit/1c8d73ff69418f25006165e83210b05d7434add0 - which it makes cql_proxy_bind_address follow the value of rpc_bind_address. So that part is expected.

However, I am not sure why --rpc_bind_address=container_name --cql_proxy_bind_address=0.0.0.0:9042 causes the tserver to fail. @kntait could you attach logs from /mnt/disk0/yb-data/tserver/logs/yb-tserver.INFO inside the yb-tserver container?

@kntait, could you please also add some more information about the higher level goal - what you are trying to accomplish by specifing rpc_bind_address explicitly?

I checked that with the default docker compose file at https://docs.yugabyte.com/latest/deploy/docker/docker-compose/ and build 2.0.3.0-b7, we do bring up master, tserver correctly and are able to talk to the CQL interface from the host.

cc @bmatican

**Comment by kntait** [comment]
In my setup i need to set the "--rpc_bind_addresses='container name':9100" for node-node TLS by setting "--use_node_to_node_encryption=true". 

If i don't set the container name in the rpc_bind_addresses then TLS fails as the address does not match the certificate common name which for me is the container name.

When tservers have YCQL listening on  'container ip':9042 then /home/yugabyte/bin/cqlsh commands fail on the local tserver container. It complains that it can't connect at 127.0.0.1:9042.

**Comment by kntait** [comment]
Have you tried setting "--rpc_bind_addresses=yb-tserver-n1:9100" on a tserver and then execute a /home/yugabyte/bin/cqlsh command on that tserver?

**Comment by iSignal** [comment]
@kntait any luck getting logs from /mnt/disk0/yb-data/tserver/logs/yb-tserver.INFO inside the yb-tserver container?

**Comment by iSignal** [comment]
Hello @kntait , so I tried the two scenarios that you talked about in https://github.com/yugabyte/yugabyte-db/issues/2783

(1) I started your docker-compose file and did a docker exec into the tserver container. You are right that bin/cqlsh does not work at that point, because the cql proxy is bound to the docker network interface and not to local network. However, in this case running cqlsh `hostname` 9042 still works by connecting to the right interface. Would that help your workflow?

(2) I started your docker-compose file with an added argument https://gist.github.com/iSignal/838701acd917590d2fbfba9e17c43e64#file-gistfile1-txt-L25 to make the cql proxy bind to 0.0.0.0. In this case, when I docker exec into the tserver container and run /home/sanketh/bin/cqlsh with no args, it connects to 127.0.0.1 properly and I am able to execute CQL queries.

At this point, it looks like the issue you ran into is really an issue with the use_node_to_node_encryption flag in combination with the cql proxy bind address = 0.0.0.0. I will attempt to repro that scenario now. 

How do you generate the certs for your docker container? Specifically, what do you set the IP in the cert name and in the CommonName field to?

**Comment by m-iancu** [comment]
Closing since this is an old issues we might have fixed already. Can re-open if this re-occurs.
