### ISSUE TITLE
[docdb] Tool to flush all tablets on a tablet server

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#2785]
During a rolling restart, we can use this to spend less time applying WAL records into rocksdb after restart.

cc @rajukumaryb

**Comment by mirageyjd** [comment]
Hi! I am working on this issue and got an unexpected error when testing my code. When I tried to flush or compact tablets called `Transactions`, it got network failure and the yb-tserver is stopped.
![image](https://user-images.githubusercontent.com/54912085/81900205-fdd2ec80-9581-11ea-9a9d-0e7a3bd57a49.png)

![image](https://user-images.githubusercontent.com/54912085/81899982-99179200-9581-11ea-8324-994108d34cbd.png)

My test steps are as followed:
1. Create a cluster `./bin/yb-ctl create`
2. Get `tablet_id` from `yb-tserver` by `./build/latest/bin/yb-ts-cli list_tablets`
3. Pick the `tablet_id` of a tablet called `Transactions` (there are two in total), and run the command `./build/latest/bin/yb-ts-cli flush_tablet <tablet_id>`

The attached files are `yb-tserver.INFO` and `yb-tserver.WARNING` in `yb-data/tserver/logs/`. I change the suffix so that it can be uploaded here.
[yb-tserver_INFO.LOG](https://github.com/yugabyte/yugabyte-db/files/4626437/yb-tserver_INFO.LOG)
[yb-tserver_WARNING.LOG](https://github.com/yugabyte/yugabyte-db/files/4626438/yb-tserver_WARNING.LOG)

**Comment by bmatican** [comment]
Oh nice, you found a bug :)

We only crash in a small handful of ways:
- for code paths we cannot progress from, we generally add extra debug information in a  `LOG(FATAL)` -- this should generate the `yb-tserver.FATAL` log file I was expecting
- for invariant violations, we use `CHECK(xxx)` -- this would generate a core file
- for various signals, most frequently SEGV -- this would also generate a core file
- for system killing us, ie: OOM killer -- this would only end up writing to the system message file, eg: `/var/log/messages` on centos

In this case, I was able to quickly repro with the existing yb-admin command using `flush_table system transactions`.

This crashes all the TS and they each generate a core file! Using GDB (`gdb ./build/latest/bin/yb-tserver core.1769`) and dumping backtraces (`bt`), you can see the following:
```
#0  yb::tablet::Tablet::WaitForFlush (this=0x2abcd10) at ../../src/yb/tablet/tablet.cc:1753
#1  0x00007f6802bae2e1 in yb::tserver::TabletServiceAdminImpl::FlushTablets (this=this@entry=0x2d576c0, req=req@entry=0x3214e50, resp=resp@entry=0x31f4190, context=...) at ../../src/yb/tserver/tablet_service.cc:1121
#2  0x00007f67ff6983bb in yb::tserver::TabletServerAdminServiceIf::Handle (this=0x2d576c0, call=...) at src/yb/tserver/tserver_admin.service.cc:238
#3  0x00007f67fb948629 in yb::rpc::ServicePoolImpl::Handle (this=0x29e3680, incoming=...) at ../../src/yb/rpc/service_pool.cc:262
#4  0x00007f67fb8ebe84 in yb::rpc::InboundCall::InboundCallTask::Run (this=<optimized out>) at ../../src/yb/rpc/inbound_call.cc:212
#5  0x00007f67fb954278 in yb::rpc::(anonymous namespace)::Worker::Execute (this=<optimized out>) at ../../src/yb/rpc/thread_pool.cc:100
#6  0x00007f67fa2ae1bf in operator() (this=0x31056d8) at /n/jenkins/linuxbrew/linuxbrew-20181203T161736-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/Cellar/gcc/5.5.0_4/include/c++/5.5.0/functional:2267
#7  yb::Thread::SuperviseThread (arg=0x3105680) at ../../src/yb/util/thread.cc:744
#8  0x00007f67f4cc4694 in start_thread (arg=0x7f67e7b52700) at pthread_create.c:333
#9  0x00007f67f4a0641d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
```

That top stack frame tells us where to go next:
> #0  yb::tablet::Tablet::WaitForFlush (this=0x2abcd10) at ../../src/yb/tablet/tablet.cc:1753

Most likely that call to the `regular_db_`, on L1756, should also be checked that that is not null, like we do for the `intents_db_` on L1757.
