### ISSUE TITLE
[YSQL] Support txn batch size for importing data using COPY FROM

### ISSUE THREAD

**Issue by ndeodhar** [yugabyte/yugabyte-db#2855]
Today for improving COPY performance, we have a non-txn-copy gflag that can be used to run copy in non transactional mode. However, this does not take effect if table requires transactions (for example, if table has an index).

We should add a copy_txn_batch_size option to improve COPY performance for such transactional tables. This will reduce the batch size for transactions instead of loading all the data in a single large transaction.

**Comment by mbautin** [comment]
It might be useful to expose these COPY behavior options as GUCs, so that we could say e.g. `SET yb_copy_txn_batch_size=100` in a session.

**Comment by emhna** [comment]
CopyFrom function in copy.c file is allocating memories in following places within copy forloop:
The allocated memories are not getting freed after each for loop, except YBCPgAttrValueDescriptor.
Will experiment if rest of the memories can be released at the end of each loop.

https://github.com/yugabyte/yugabyte-db/blob/master/src/postgres/src/backend/commands/copy.c#L2682
AllocAlloc: ExprContext: 0x123a86108, 128 => HeapTuple

https://github.com/yugabyte/yugabyte-db/blob/master/src/postgres/src/backend/commands/copy.c#L2876
AllocAlloc: PortalContext: 0x1234b2a58, 8 => GetFullYBTablePrimaryKey
AllocAlloc: PortalContext: 0x123a88028, 32 => YBCPgAttrValueDescriptor
AllocAlloc: PortalContext: 0x123a88060, 32 => YBCPgDmlBuildYBTupleId
AllocFree: PortalContext: 0x123a88028, 32 => Frees YBCPgAttrValueDescriptor

**Comment by emhna** [comment]
These are the places where memory gets pallocated while running CopyFrom function at each forloop iteration:

function: heap_form_tuple 
structure: HeapTuple
size: 128 bits
https://github.com/yugabyte/yugabyte-db/blob/master/src/postgres/src/backend/access/common/heaptuple.c#L1127
to be pfreed at the end of each copy for loop

function:  bms_make_singleton
structure: Bitmapset
size: 8 bits
https://github.com/yugabyte/yugabyte-db/blob/master/src/postgres/src/backend/nodes/bitmapset.c#L255
to be pfreed at the end of YBCGetYBTupleIdFromTuple function, similar to YBCPgAttrValueDescriptor

function: YBCGetYBTupleIdFromTuple 
structure: YBCPgAttrValueDescriptor
size: 32 bits
https://github.com/yugabyte/yugabyte-db/blob/master/src/postgres/src/backend/executor/ybcModifyTable.c#L146
pfreed at the end of the function: https://github.com/yugabyte/yugabyte-db/blob/master/src/postgres/src/backend/executor/ybcModifyTable.c#L172

function: cstring_to_text_with_len 
structure: text cast to Datum
size: 32 bits
https://github.com/yugabyte/yugabyte-db/blob/master/src/postgres/src/backend/utils/adt/varlena.c#L163
to be pfreed at the end of each copy for loop

======

After pfreeing each variable per row insertion, observed in postgresql logs the following alloc/free happens in repetition (per row):
AllocAlloc: ExprContext: 0x1132ee108, 128                                                            
AllocAlloc: PortalContext: 0x11cd46a58, 8                                                            
AllocAlloc: PortalContext: 0x11d30e028, 32                                                           
AllocAlloc: PortalContext: 0x11d30e060, 32                                                           
AllocFree: PortalContext: 0x11cd46a58, 8                                                             
AllocFree: PortalContext: 0x11d30e028, 32                                                            
AllocFree: PortalContext: 0x11d30e060, 32                                                            
AllocFree: ExprContext: 0x1132ee108, 128  

This helped to reduce query runtime from 1+hour to ~10 min and memory usage for postgres backend process from 50gb+ to 10gb while processing 75mb file. However, 10gb memory usage still seems too high.
Perhaps frequent alloc and free is causing the issue. Need to figure out a way to release these memories at batch level instead of row level.

**Comment by emhna** [comment]
After running perf command, report shows that only small percentage of time is called on alloc and free for the above memory allocation work (only accounts for less than 2% within its direct parent function).  

41.12%--CopyFrom
	36.46%--YBCExecuteInsert
		36.29%--YBCExecuteInsertInternal
		11.26%--YBCGetYBTupleIdFromTuple
		7.81%--YBCPgNewInsert
		…
		0.83%--YBGetTablePrimaryKeyBms
	1.71%--NextCopyFrom
	1.35%--pfree
	0.86%--heap_form_tuple

Running (gdb) p MemoryContextStats(TopMemoryContext) showed the following:
TopMemoryContext: 389872 total in 8 blocks; 34552 free (13 chunks); 355320 used
  RowDescriptionContext: 8192 total in 1 blocks; 6880 free (0 chunks); 1312 used
  MessageContext: 8192 total in 1 blocks; 6880 free (1 chunks); 1312 used
  Operator class cache: 8192 total in 1 blocks; 512 free (0 chunks); 7680 used
  TransactionAbortContext: 32768 total in 1 blocks; 32504 free (0 chunks); 264 used
  Portal hash: 8192 total in 1 blocks; 512 free (0 chunks); 7680 used
  TopPortalContext: 8192 total in 1 blocks; 7928 free (1 chunks); 264 used
  Relcache by OID: 32768 total in 3 blocks; 14528 free (5 chunks); 18240 used
  CacheMemoryContext: 6392064 total in 146 blocks; 407560 free (147 chunks); 5984504 used
    EventTriggerCache: 8192 total in 1 blocks; 7928 free (0 chunks); 264 used
      Event Trigger Cache: 8192 total in 1 blocks; 2584 free (0 chunks); 5608 used
    relation rules: 8192 total in 4 blocks; 2816 free (0 chunks); 5376 used: user_mappings
    relation rules: 16384 total in 5 blocks; 2200 free (0 chunks); 14184 used: user_mapping_options
    relation rules: 16384 total in 5 blocks; 192 free (0 chunks); 16192 used: _pg_user_mappings
    relation rules: 8192 total in 4 blocks; 1664 free (0 chunks); 6528 used: foreign_tables
    relation rules: 8192 total in 4 blocks; 1024 free (0 chunks); 7168 used: foreign_table_options
    relation rules: 24576 total in 6 blocks; 912 free (0 chunks); 23664 used: _pg_foreign_tables
    **relation rules: 8192 total in 4 blocks; 328 free (1 chunks); 7864 used: foreign_servers**
    relation rules: 8192 total in 4 blocks; 1320 free (1 chunks); 6872 used: foreign_server_options
    relation rules: 16384 total in 5 blocks; 840 free (0 chunks); 15544 used: _pg_foreign_servers
    relation rules: 8192 total in 4 blocks; 1584 free (0 chunks); 6608 used: foreign_data_wrappers
    **relation rules: 8192 total in 4 blocks; 1608 free (1 chunks); 6584 used: foreign_data_wrapper_options**
    relation rules: 16384 total in 5 blocks; 4480 free (0 chunks); 11904 used: _pg_foreign_data_wrappers
    relation rules: 8192 total in 4 blocks; 80 free (0 chunks); 8112 used: column_options
    **relation rules: 24576 total in 6 blocks; 4168 free (1 chunks); 20408 used: _pg_foreign_table_columns**
    relation rules: 106496 total in 16 blocks; 928 free (0 chunks); 105568 used: element_types
    relation rules: 57344 total in 10 blocks; 2104 free (0 chunks); 55240 used: data_type_privileges
    relation rules: 49152 total in 9 blocks; 7752 free (0 chunks); 41400 used: views
    relation rules: 32768 total in 7 blocks; 3784 free (0 chunks); 28984 used: view_table_usage
    relation rules: 32768 total in 7 blocks; 5080 free (0 chunks); 27688 used: view_routine_usage
    relation rules: 40960 total in 8 blocks; 6688 free (0 chunks); 34272 used: view_column_usage
    relation rules: 40960 total in 8 blocks; 6712 free (0 chunks); 34248 used: user_defined_types
    **relation rules: 16384 total in 5 blocks; 3888 free (1 chunks); 12496 used: role_usage_grants**
    **relation rules: 163840 total in 23 blocks; 6088 free (1 chunks); 157752 used: usage_privileges**
    relation rules: 16384 total in 5 blocks; 4536 free (0 chunks); 11848 used: role_udt_grants
    relation rules: 40960 total in 8 blocks; 3712 free (0 chunks); 37248 used: udt_privileges
    relation rules: 49152 total in 9 blocks; 7408 free (0 chunks); 41744 used: triggers
    relation rules: 32768 total in 7 blocks; 1656 free (0 chunks); 31112 used: triggered_update_columns
    **relation rules: 204800 total in 28 blocks; 560 free (2 chunks); 204240 used: transforms**
    relation rules: 73728 total in 12 blocks; 3624 free (0 chunks); 70104 used: tables
    **relation rules: 16384 total in 5 blocks; 3888 free (1 chunks); 12496 used: role_table_grants
    relation rules: 49152 total in 9 blocks; 7944 free (1 chunks); 41208 used: table_privileges**
    relation rules: 65536 total in 11 blocks; 5648 free (0 chunks); 59888 used: table_constraints
    relation rules: 32768 total in 7 blocks; 6728 free (0 chunks); 26040 used: sequences
    relation rules: 16384 total in 5 blocks; 4632 free (0 chunks); 11752 used: schemata
    **relation rules: 139264 total in 20 blocks; 7512 free (1 chunks); 131752 used: routines**
    relation rules: 16384 total in 5 blocks; 2592 free (0 chunks); 13792 used: role_routine_grants
    relation rules: 40960 total in 8 blocks; 1800 free (0 chunks); 39160 used: routine_privileges
    **relation rules: 16384 total in 5 blocks; 3888 free (1 chunks); 12496 used: role_column_grants**
    relation rules: 155648 total in 22 blocks; 432 free (0 chunks); 155216 used: referential_constraints
    relation rules: 57344 total in 10 blocks; 5800 free (0 chunks); 51544 used: parameters
    relation rules: 40960 total in 8 blocks; 4848 free (0 chunks); 36112 used: key_column_usage
    relation rules: 8192 total in 4 blocks; 2736 free (0 chunks); 5456 used: enabled_roles
    relation rules: 106496 total in 16 blocks; 5472 free (0 chunks); 101024 used: domains
    relation rules: 24576 total in 6 blocks; 4816 free (0 chunks); 19760 used: domain_udt_usage
    relation rules: 24576 total in 6 blocks; 2080 free (0 chunks); 22496 used: domain_constraints
    **relation rules: 24576 total in 6 blocks; 2608 free (1 chunks); 21968 used: constraint_table_usage**
    relation rules: 65536 total in 11 blocks; 5024 free (0 chunks); 60512 used: constraint_column_usage
    relation rules: 294912 total in 39 blocks; 8136 free (0 chunks); 286776 used: columns
    relation rules: 73728 total in 12 blocks; 5768 free (0 chunks); 67960 used: column_udt_usage
    **relation rules: 98304 total in 15 blocks; 2576 free (2 chunks); 95728 used: column_privileges**
    **relation rules: 32768 total in 7 blocks; 6184 free (1 chunks); 26584 used: column_domain_usage**
    relation rules: 16384 total in 5 blocks; 2376 free (0 chunks); 14008 used: collation_character_set_applicability
    **relation rules: 16384 total in 5 blocks; 3880 free (1 chunks); 12504 used: collations**
    **relation rules: 98304 total in 15 blocks; 8400 free (1 chunks); 89904 used: check_constraints
    relation rules: 24576 total in 6 blocks; 1856 free (1 chunks); 22720 used: check_constraint_routine_usage**
    relation rules: 32768 total in 7 blocks; 5656 free (0 chunks); 27112 used: character_sets
    relation rules: 163840 total in 23 blocks; 5624 free (0 chunks); 158216 used: attributes
    relation rules: 8192 total in 4 blocks; 2936 free (0 chunks); 5256 used: administrable_role_authorizations
    relation rules: 24576 total in 6 blocks; 1648 free (0 chunks); 22928 used: applicable_roles
    **relation rules: 4096 total in 3 blocks; 1128 free (1 chunks); 2968 used: information_schema_catalog_name
    relation rules: 8192 total in 4 blocks; 2568 free (1 chunks); 5624 used: pg_replication_origin_status**
    relation rules: 32768 total in 7 blocks; 5656 free (0 chunks); 27112 used: pg_user_mappings
    relation rules: 24576 total in 6 blocks; 296 free (0 chunks); 24280 used: pg_stat_progress_vacuum
    relation rules: 8192 total in 4 blocks; 208 free (0 chunks); 7984 used: pg_stat_bgwriter
    relation rules: 8192 total in 4 blocks; 496 free (0 chunks); 7696 used: pg_stat_archiver
    relation rules: 24576 total in 6 blocks; 4176 free (0 chunks); 20400 used: pg_stat_xact_user_functions
    relation rules: 24576 total in 6 blocks; 4176 free (0 chunks); 20400 used: pg_stat_user_functions
    relation rules: 16384 total in 5 blocks; 7464 free (0 chunks); 8920 used: pg_stat_database_conflicts
    **relation rules: 24576 total in 6 blocks; 7008 free (1 chunks); 17568 used: pg_stat_database**
    relation rules: 24576 total in 6 blocks; 5016 free (0 chunks); 19560 used: pg_replication_slots
    relation rules: 16384 total in 5 blocks; 6784 free (0 chunks); 9600 used: pg_stat_ssl
    relation rules: 16384 total in 5 blocks; 1000 free (0 chunks); 15384 used: pg_stat_subscription
    relation rules: 16384 total in 5 blocks; 4192 free (0 chunks); 12192 used: pg_stat_wal_receiver
    relation rules: 49152 total in 9 blocks; 7224 free (0 chunks); 41928 used: pg_stat_replication
    **relation rules: 49152 total in 9 blocks; 5832 free (1 chunks); 43320 used: pg_stat_activity**
    relation rules: 8192 total in 4 blocks; 800 free (0 chunks); 7392 used: pg_statio_user_sequences
    relation rules: 8192 total in 4 blocks; 800 free (0 chunks); 7392 used: pg_statio_sys_sequences
    relation rules: 24576 total in 6 blocks; 3048 free (0 chunks); 21528 used: pg_statio_all_sequences
    relation rules: 16384 total in 5 blocks; 7720 free (0 chunks); 8664 used: pg_statio_user_indexes
    relation rules: 16384 total in 5 blocks; 7720 free (0 chunks); 8664 used: pg_statio_sys_indexes
    relation rules: 81920 total in 13 blocks; 1656 free (0 chunks); 80264 used: pg_statio_all_indexes
    **relation rules: 16384 total in 5 blocks; 7104 free (1 chunks); 9280 used: pg_stat_user_indexes
    relation rules: 16384 total in 5 blocks; 7104 free (1 chunks); 9280 used: pg_stat_sys_indexes**
    **relation rules: 81920 total in 13 blocks; 1472 free (1 chunks); 80448 used: pg_stat_all_indexes**
    relation rules: 16384 total in 5 blocks; 5256 free (0 chunks); 11128 used: pg_statio_user_tables
    relation rules: 16384 total in 5 blocks; 5256 free (0 chunks); 11128 used: pg_statio_sys_tables
    relation rules: 131072 total in 19 blocks; 7392 free (0 chunks); 123680 used: pg_statio_all_tables
    relation rules: 16384 total in 5 blocks; 5256 free (0 chunks); 11128 used: pg_stat_xact_user_tables
    relation rules: 24576 total in 6 blocks; 6376 free (0 chunks); 18200 used: pg_stat_user_tables
    relation rules: 16384 total in 5 blocks; 5256 free (0 chunks); 11128 used: pg_stat_xact_sys_tables
    relation rules: 24576 total in 6 blocks; 6376 free (0 chunks); 18200 used: pg_stat_sys_tables
    relation rules: 57344 total in 10 blocks; 7528 free (0 chunks); 49816 used: pg_stat_xact_all_tables
    **relation rules: 65536 total in 11 blocks; 8008 free (1 chunks); 57528 used: pg_stat_all_tables**
    relation rules: 8192 total in 4 blocks; 3928 free (0 chunks); 4264 used: pg_config
    **relation rules: 8192 total in 4 blocks; 2696 free (1 chunks); 5496 used: pg_timezone_names**
    relation rules: 8192 total in 4 blocks; 3280 free (0 chunks); 4912 used: pg_timezone_abbrevs
    relation rules: 16384 total in 5 blocks; 7768 free (0 chunks); 8616 used: pg_hba_file_rules
    relation rules: 8192 total in 4 blocks; 848 free (0 chunks); 7344 used: pg_file_settings
    relation rules: 32768 total in 7 blocks; 6712 free (0 chunks); 26056 used: pg_settings
    141 more child contexts containing 1197056 total in 417 blocks; 179544 free (89 chunks); 1017512 used
  WAL record construction: 49776 total in 2 blocks; 6344 free (0 chunks); 43432 used
  PrivateRefCount: 8192 total in 1 blocks; 2584 free (0 chunks); 5608 used
  MdSmgr: 8192 total in 1 blocks; 7928 free (0 chunks); 264 used
  LOCALLOCK hash: 8192 total in 1 blocks; 512 free (0 chunks); 7680 used
  Timezones: 104128 total in 2 blocks; 2584 free (0 chunks); 101544 used
  ErrorContext: 8192 total in 1 blocks; 7928 free (4 chunks); 264 used
Grand total: 12282144 bytes in 1374 blocks; 1133600 free (288 chunks); 11148544 used

**Comment by emhna** [comment]
Summary after code change:
After introducing local memory context, I observed the memory usage was reduced to 24-25mb rather than in tens of gb.
However, while processing 1.2gb file, I noticed the query exited in the middle of execution (after processing about 700mb).
The error seem to be related to write transaction failing to the backend data storage (see below for logs).
Now that memory issue is fixed, it seems necessary to commit in smaller batches rather than waiting for all rows to be committed at the same time as it seems to exceed memory limits while writing to the table.

Logs:
I0816 17:36:06.339464 13677 tablet.cc:806] T 48f517d21e844eac93487a95b3db95f6 P 15247878ab454bddb7a5f5099b8ab7f4: Intents SST file will be deleted: { total_size: 29172888 base_size: 1118643 uncompressed_size: 110965129 name: "/000094.sst" db_path: "/home/centos/yugabyte-data/node-1/disk-1/yb-data/tserver/data/rocksdb/table-000030a9000030008000000000004000/tablet-48f517d21e844eac93487a95b3db95f6.intents" imported: 0 being_compacted: 0 column_family_name: default level: 0 smallest: { seqno: 1125900003956784 user_frontier: 0x000000000430df80 -> { op_id: 1.31589 hybrid_time: { physical: 1597599231251142 } history_cutoff: <invalid> hybrid_time_filter: <invalid> } } largest: { seqno: 1125900005406183 user_frontier: 0x0000000146c8c990 -> { op_id: 1.32058 hybrid_time: { physical: 1597599335699006 } history_cutoff: <invalid> hybrid_time_filter: <invalid> } } }, max ht: { physical: 1597599335699006 }, min running transaction start ht: <max>
I0816 17:36:06.341207 13677 **write_operation.cc**:130] **Apply operation failed: Operation failed. Try again. (yb/tablet/tablet.cc:1084): Transaction metadata missing: 5829fad6-4d14-4697-8f8e-356cb44dbd71, looks like it was just aborted (pgsql error 40001)**
I0816 17:36:06.341413 13677 tablet_service.cc:405] **Write failed**: Operation failed. Try again. (yb/tablet/tablet.cc:1084): **Transaction metadata missing**: 5829fad6-4d14-4697-8f8e-356cb44dbd71, looks like it was just aborted (pgsql error 40001)
...
I0816 17:36:13.988098 13703 maintenance_manager.cc:342] we have exceeded our soft memory limit (current capacity is 98.23%).  However, there are no ops currently runnable which would free memory.
I0816 17:36:18.995375 13703 maintenance_manager.cc:342] we have exceeded our soft memory limit (current capacity is 102.77%).  However, there are no ops currently runnable which would free memory.
I0816 17:36:24.002367 13703 maintenance_manager.cc:342] we have exceeded our soft memory limit (current capacity is 102.77%).  However, there are no ops currently runnable which would free memory.
I0816 17:36:29.009768 13703 maintenance_manager.cc:342] we have exceeded our soft memory limit (current capacity is 133.55%).  However, there are no ops currently runnable which would free memory.
I0816 17:36:34.017417 13703 maintenance_manager.cc:342] we have exceeded our soft memory limit (current capacity is 133.55%).  However, there are no ops currently runnable which would free memory.
I0816 17:36:39.024309 13703 maintenance_manager.cc:342] we have exceeded our soft memory limit (current capacity is 133.55%).  However, there are no ops currently runnable which would free memory.
I0816 17:36:44.031172 13703 maintenance_manager.cc:342] we have exceeded our soft memory limit (current capacity is 133.55%).  However, there are no ops currently runnable which would free memory.
...
I0816 17:37:54.442641 13693 ts_tablet_manager.cc:309] **Memstore global limit of 1013983825 bytes reached**, looking for tablet to flush
I0816 17:37:54.482740 13693 ts_tablet_manager.cc:317] T 48f517d21e844eac93487a95b3db95f6 P 15247878ab454bddb7a5f5099b8ab7f4: Flushing tablet with oldest memstore write at { physical: 1597599335857861 }

**Comment by emhna** [comment]
Found that fixing the memory issue per batch level does not resolve the above problem.
Smaller commits (https://github.com/yugabyte/yugabyte-db/issues/5453) must be executed at each batch for larger files (greater than 1-2 gb) to succeed `copy from`.
If not, write operation fails as logs show above.
In order to properly execute `copy from` both problems must be fixed.

**Comment by emhna** [comment]
Snapshot of logs while processing 15gb file.

<img width="1920" alt="15gb failed 1 1" src="https://user-images.githubusercontent.com/66644511/91076339-57c96080-e60d-11ea-8466-8be34d8d4a38.png">
<img width="1920" alt="15gb failed 1 2" src="https://user-images.githubusercontent.com/66644511/91076344-58fa8d80-e60d-11ea-87c8-2ac03abcd4b2.png">

**Comment by emhna** [comment]
To enable batch size transaction commits, the `rows_per_transaction` query option has been added to `COPY FROM` query statement.
Eg. `COPY tab FROM 'absoluteFilePath' WITH (FORMAT CSV, HEADER, ROWS_PER_TRANSACTION 100);`
The above query will commit 100 rows at a time from the file rather than as a single all rows commit.

This change enables larger files to be copied over successfully. The maximum file tested was on 15gb in size with 
375 million rows. 

The documentation on the usage may be found here as well: https://docs.yugabyte.com/latest/api/ysql/commands/cmd_copy/#import-a-large-table-using-smaller-transactions
