### ISSUE TITLE
add support for AVG builtin

### ISSUE THREAD

**Issue by kmuthukk** [YugaByte/yugabyte-db#290]
YCQL (our Cassandra API) doesn't have support for AVG. We support MIN, MAX, SUM - but not AVG.

**Comment by rven1** [comment]
Average is different from other aggregate functions because it cannot be
completely executed on a per tablet basis. Instead each tablet returns a
count and a sum for the values in the column as a map. The values for
all tablets are aggregated and the average is calculated. Hence, this
change involves changing the type of the return from the tablet to a
map.

After switching to map, can do avg for different types.
cqlsh:test> select avg(h), avg(r), avg(v1), avg(v2), avg(v5), avg(v6) from test_aggr_expr;

avg(h) | avg(r) | avg(v1) | avg(v2) | avg(v5) | avg(v6)
----------------------------------+--------
2 | 3 | 4 | 5 | 4 | 3

(1 rows)

**Comment by rven1** [comment]
Added support for Avg. In keeping with the behavior in Apache Cassandra, AVG and sum return 0 when there are no matched rows or the column value is NULL in every matched row.
