### ISSUE TITLE
[YSQL] Remove SELECT vs SELECT FOR UPDATE conflict

### ISSUE THREAD

**Issue by jaki** [yugabyte/yugabyte-db#2936]
Jira Link: [DB-1966](https://yugabyte.atlassian.net/browse/DB-1966)
Regular `SELECT` statements and `SELECT FOR` row locking statements should not conflict.  However, they do so in certain circumstances, namely when the regular `SELECT` is in a serializable isolation transaction and the row locking statements are `UPDATE` or `NO KEY UPDATE`.

| Session A | Session B |
| --- | --- |
| `CREATE TABLE t (i int PRIMARY KEY, j int)` ||
| `INSERT INTO t VALUES (1, 10), (2, 20), (3, 30)` ||
| `BEGIN ISOLATION LEVEL <REPEATABLE READ\|SERIALIZABLE>` ||
| `SELECT '(setting read point)'` ||
|| `BEGIN ISOLATION LEVEL SERIALIZABLE` |
|| `SELECT '(setting read point)'` |
| `SELECT * FROM t FOR [NO KEY] UPDATE` ||
|| `SELECT * FROM t` |
| `COMMIT` ||
|| `COMMIT` |

The failure takes case in one of two areas (it is probabilistic):

* On the `SELECT * FROM t`:

  ```
  ERROR:  Operation failed. Try again.: e9fcc42c-e00c-4612-9224-e147ca0b19ac Conflicts with higher priority transaction: 1ccef572-88ce-4b28-b847-84455b08c314
  ```

* On Session A's `COMMIT`:

  ```
  ERROR:  Error during commit: Operation expired: Transaction expired: 25P02
  ```

There is another variant:

| Session A | Session B |
| --- | --- |
| `CREATE TABLE t (i int PRIMARY KEY, j int)` ||
| `INSERT INTO t VALUES (1, 10), (2, 20), (3, 30)` ||
|| `BEGIN ISOLATION LEVEL SERIALIZABLE` |
|| `SELECT * FROM t` |
| `SELECT * FROM t FOR [NO KEY] UPDATE` ||
|| `COMMIT` |

The failure takes case in one of two areas (it is probabilistic):

* On the `SELECT * FROM t FOR [NO KEY] UPDATE`:

  ```
  ERROR:  Operation failed. Try again.: df17a1e1-081e-4e69-83f4-f481384b68a4 Conflicts with higher priority transaction: e29646d5-2362-407e-98c3-77e67bea8ebf
  ```

* On Session B's `COMMIT`:

  ```
  ERROR:  Error during commit: Operation expired: Transaction expired: 25P02
  ```

**Comment by pkj415** [comment]
In YSQL's serializable isolation, `SELECT` and `SELECT FOR UPDATE/NO KEY UPDATE` are expected to conflict. This differs from Pg behaviour because of a difference in the implementation for serializable isolation. YSQL uses 2PL (two phase locking) while Pg uses SSI (Serializable Snapshot Isolation) which results in lower conflicts.

The behaviour for YSQL's Repeatable Read however matches Pg (re-open if you think that is not the case).

Lastly, if you use YSQL's serializable in the new [Wait-on-Conflict concurrency control mode](https://docs.yugabyte.com/preview/architecture/transactions/concurrency-control/#wait-on-conflict), the above examples will match Pg behaviour. Note that there will still be cases where YSQL's 2PL serializable with Wait-on-Conflict concurrency will still differ from Pg's SSI.
