### ISSUE TITLE
How to add new node in already running Yugabyte cluster server

### ISSUE THREAD

**Issue by sadeshjayraj** [YugaByte/yugabyte-db#300]
Dear Team,

We are running yugabyte cluster server on 9 node, suppose I want to add any node as master into the same cluster  then how we can add it?

Currently what I have done, to add any additional node as master server I have  stopped all server,then I have added master node into master server depoly command 

./bin/yb-master --fs_data_dirs "/abc/data" --webserver_interface **.**.**.** --rpc_bind_addresses **.**.**.** --replication_factor=3 --master_addresses **.**.**.**:7100,**.**.**.**:7100,**.**.**.**:7100  --placement_cloud=companyname --placement_region=xyz --placement_zone=rack1  &

So is there any way  to add master server without stopping whole cluster?.........................

**Comment by kmuthukk** [comment]
Hi @sadeshjayraj 

To make sure I understand the question: You have a 9 node cluster (say n1, ... n9). And given that your replication_factor=3, are three of the nodes already running yb-master process (say n1, n2, n3) and all the 9 nodes are running a yb-tserver process (n1, n2, ..., n9). Correct?

So, are you trying to add a 4th master or are you trying to move a master from one of the existing nodes to a different node? Is this a new node (say n10) or are you trying to move the master to one of the existing nodes.

Just trying to confirm the scenario before posting the response. But short answer is  - yes it is possible to add a new master (and optionally remove an old one).

regards,
Kannan

**Comment by sadeshjayraj** [comment]
Hi Kannan,

Thanks for quick response..........
 We have cluster setup of  6 server (from n1....n6).These servers are belong to 2 diff data centers. Like n1...n3 are from x datacenter and n4.......n6 are from y datacenter. In this cluster i have kept n1 and n4 node as master node. Now I want to add 3 (n7.............n9) new node which are from suppose to be z data center.Also I want to add n7 as master node.How I can do it without bringing down whole cluster..

**Comment by kmuthukk** [comment]
Hi @sadeshjayraj 

If replication_factor is 3, we do not allow creating a cluster with just two masters. Even for the initial cluster create all 3 masters must be started (and they must start of with each others addresses), for example via:

--master_addresses n1:7100,n4:7100,n7:7100 

So I am not sure how your cluster currently only has two masters n1 and n4? Or does it have a third master (one node from n2, n3, n5 or n6) and you want to move that master over to n7 node?

Can you confirm if somehow you were able to create a cluster with just n1 and n4 as masters?

Are you able to go to say http://<n1>:7000/ and browse the cluster state?

regards,
Kannan

**Comment by sadeshjayraj** [comment]
Hi Kannan,

for 6 server cluster setup with 2 master, we have kept replication factor 2 , but to make 3 master we have to keep replication factor=3 is it correct, 
My question is how to add 3 master into already running cluster server (6 node cluster out of which 2 nodes are master) without bringing it down.

**Comment by kmuthukk** [comment]
hi @sadeshjayraj 

We don't recommend RF=2 setting because we use a quorum based replication protocol (raft). 

So you need to two things:

a) First - update the replication factor to 3.

b) Then, add in the new master.

For (a), to update the replication factor, you can restart the yb-master processes (in a rolling fashion, i.e. one at a time) with 

--replication_factor 3
instead of:
--replication_factor 2 (that you previously had).

For (b), to add a new master, say n7, into an existing cluster, you prepare the yb-master command for it with all the options *except* (and this important) the --master_addresses option. So do not pass the --master_addresses option to n7 master's startup command. This causes the master to be a dummy master that is waiting to be added to the master quorum. You can now tell the existing masters to add this new master to the quorum using the yb-admin tool:

```
./bin/yb-admin --master_addresses <n1>:7100,<n4>:7100 change_master_config ADD_SERVER n7 
 7100
```

If you now check http://<n1>:7000/ UI, it should show all three masters.

**Comment by kmuthukk** [comment]
Hi @sadeshjayraj 

One thing I wanted to mention is about the location of the yugabyte logs by default.

Assuming you are not passing `--log_dir` argument, then the default log directory is derived from the `--fs_data_dirs` argument.

Suppose, your `--fs_data_dirs` argument is `/disk1/data,/disk2/data`

then the default lot directory will use the 1st data directory (/disk1/data) in the above list, and within that directory, it'll create a:

`/disk1/data/yb-data/tserver/logs/`
or
`/disk1/data/yb-data/master/logs/`

depending on the process type, and use the directory for storing the *.INFO, *.WARNING, *.ERROR, *.FATAL, log file.

Currently, we are also sending all ERROR and FATAL level logs to stdout of the process, and that might be causing some confusion.  Hope you are redirecting stdout and stderr of these processes to some well know location so that you can look for an significant errors there as well.

**Comment by kmuthukk** [comment]
hi @sadeshjayraj : closing this issue for now. But feel free to re-open if this is still unresolved.

**Comment by zhangm365** [comment]
hi, now i have a issue about the `tserver` node:

The ip addresses about the 3-node cluster.
---------
10.0.0.1
10.0.0.2
10.0.0.3
---------

How to add the tserver node(10.0.0.4) to the cluster? Now I have started the tserver process, but the `yb-ctl` and `yb-admin` don't have the corresponding the config about the tserver node.
