### ISSUE TITLE
[docdb] Add global load balance step for leader moves

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#3040]
Currently, our load balancing algorithm works on a per-table level. For tablet / data load balancing, we can add and remove peers, so ultimately can reach an equilibrium where the variance between highest and lowest loaded server is at most 1 tablet / table. However, for leader load, we have to operate in the raft groups that are available.

We have observed situations where, due to how the tablets are placed by the data load balancing, the gap between highest and lowest leader loaded servers can be >1!

*We've had discussions before about extending the load balancing state to not just per-table state, but also keeping in mind some global changes.*

One explicit code blocker is that we stop making moves if the gap between target and destination server is <2. This was a cheap solution to prevent having to worry about the potential of an infinite loop where 2 servers A and B have just 1 leader difference between them and the load balancer just ping pongs that leader back and forth between them.

cc @rajukumaryb @hectorgcr @rahuldesirazu

**Comment by bmatican** [comment]
Since we've started playing around more aggressively with low number of tablets / table, we should actively look into this, as it cna lead to some pretty heavy IO inbalance

**Comment by RunningJon** [comment]
Balancing the number of leaders across the nodes is one way to handle this but we may still encounter hot spots. For example, if the data model has a large transaction log table with heavy writing and reading with many small to medium sized lookup tables, then it might be more "balanced" to have the log table leader alone on a single node to isolate the leader.
So, can we capture stats per tablet leader and then balance based on the load rather than just the number of leaders?

**Comment by sanketkedia** [comment]
@RunningJon thanks for bringing it up. Yes, this is already under consideration and is planned for the future. I'll go ahead and close this issue as the fix has been merged.
