### ISSUE TITLE
[YEDIS] Support the TIME command 

### ISSUE THREAD

**Issue by rkarthik007** [yugabyte/yugabyte-db#31]

**Comment by swayamraina** [comment]
Hi, 
Could you please elaborate the issue?
The TIME command was introduced in REDIS in 2.6.0 and we are currently running on 4.0.1?

**Comment by schoudhury** [comment]
@swayamraina this open issue tracks the need to support the TIME command in YEDIS, YugaByte DB's Redis-compatible distributed KV API. Other than being compatible with the Redis wire protocol, YEDIS is a net new implementation and has no linkage to whether a given command is supported in the native in-memory Redis or not. Hope this explains the context. Let us know if you have more questions. Also, recommend you join the community slack at http://www.yugabyte.com/slack so that we can chat interactively.

**Comment by rkarthik007** [comment]
@swayamraina - adding the repro steps for this issue. Let me know if this looks interesting to you, I will give you some details about where to look in the codebase. Thanks for your interest!

1. Install (or build) YugaByte DB locally and run it.
2. Connect to the DB using `redis-cli` (you can find this in the binary directory of the install package)
3. Run the ping command:
```
$ redis-cli
127.0.0.1:6379> time
(error) ERR time: Unsupported call.
```

This should instead be something as follows:
```
127.0.0.1:6379> time
1) 1558494400
2) 536911
```

**Comment by swayamraina** [comment]
Yeah sure, this sounds interesting, I will take this up.
So far I have successfully build the source code and the build directory is pointed to 
`yugabyte-db/build/release-clang-dynamic-community-ninja`

I am unable to run the server (how to actually run it, docs have no mention of which binary to run) and find yedis-cli,
on doing `find . -name redis-cli` this shows,
./bin/redis-cli
./thirdparty/installed/common/bin/redis-cli
./thirdparty/build/common/redis-4.0.1/src/redis-cli

and I believe nonel of these are yedis.

**Comment by bmatican** [comment]
Hey @swayamraina, glad to see you've managed to successfully build the code and are on your way towards testing some changes!

For running yugabyte, you can use the same flow as in our [Quick Start guides](https://docs.yugabyte.com/latest/quick-start/create-local-cluster/), noting that, instead of unpacking a tar.gz and looking for `bin/yb-ctl`, you would use the actual one from the repo!

As for @rkarthik007 's recommendation to use `redis-cli`, you should be able to use `bin/redis-cli`, which would connect to our Redis-compatible API.

Let me know if that works for you and, as @schoudhury mentioned, feel free to pop by our [Slack channel](http://www.yugabyte.com/slack), if you'd like some more real time communication.

**Comment by kmuthukk** [comment]
@swayamraina --

./bin/redis-cli is the CLI for YEDIS. YEDIS is wire-protocol compatible with Redis - and hence the vanilla redis-cli works just fine.

**Comment by m-iancu** [comment]
Closing as `wontfix` since this is not in our current roadmap.
