### ISSUE TITLE
we have existing ycql cluster already running, but wanted to enable YSQL without recreating new universe

### ISSUE THREAD

**Issue by murugesan70** [yugabyte/yugabyte-db#3121]
We have existing YCQL cluster already running in production with several of our enterprise customers and wanted to enable YSQL without having to recreate a new universe and move data around. How we do we enable YSQL?

We are in 2.0.5 of YugabyteDB.

**Comment by rkarthik007** [comment]
The set of steps should look like the following:
* Restart the masters and tservers with the appropriate flags to start the YSQL subsystem.
* The existing method of pre-creating the system catalog will no work (due to existing tables).
* Run `initdb` the cluster. Ensure it can initialize the YSQL system catalog.
* Ensure that the existing YCQL system catalog entries are not affected.

Once the above is done, we would need to wire this sequence through Yugabyte Platform.

**Comment by ddorian** [comment]
@murugesan70 do the steps above answer your question ?
Feel free to reopen the issue if not.
