### ISSUE TITLE
Set "ysql_dump" "--serializable-deferrable" on by default

### ISSUE THREAD

**Issue by stevebang** [yugabyte/yugabyte-db#3127]
@mbautin is suggesting that we make the `ysql_dump` `--serializable-deferrable`option on by default.

Here is the current draft description of the `--serializable-deferrable` flag for `ysql_dump`:

"Use a serializable transaction for the dump to ensure that the snapshot used is consistent with later database states by waiting for a point in the transaction stream at which no anomalies can be present, so that there is no risk of the dump failing or causing other transactions to roll back with a `serialization_failure`. 

If there are active read-write transactions, the maximum wait time until the start of the dump will be `50ms` (based on the default `--max_clock_skew_usec` for YB-TServer and YB-Master services.) If there are no active read-write transactions when `ysql_dump` is started, this option will not make any difference. Once running, performance with or without the switch is the same."

**Comment by rkarthik007** [comment]
@mbautin - will this method have any impact on the existing transactions against the db? The ideal implementation would pick a timestamp enough in the past and read off the "snapshot", I just wanted to understand how `serializable-deferrable` would work in practice.

cc @m-iancu @ndeodhar

**Comment by mbautin** [comment]
@stevebang: in YugabyteDB, read-only transactions (SERIALIZABLE or REPEATABLE READ) would never block other transactions / operations, except, potentially, TRUNCATE. The read operation itself could run into read restarts if it finds rows that were modified concurrently within a small time window, and that's what we are avoiding using the "deferrable" mode.  I think we could even rename this flag to `--deferrable` because it is not specific to SERIALIZABLE isolation level.

@rkarthik007 No, this will not have an impact on existing transactions. I think the ideal implementation should back up all the data that existed at the moment the backup command was called, even if that requires waiting a bit, which is what we can achieve in the "deferrable" mode (which amounts to selecting the read timestamp equal to current time plus clock skew, to ensure there are no read restarts.)

**Comment by stevebang** [comment]
Noticed that we're now using this for ysql_dump from yb_backup.py only (see [#4990](https://github.com/yugabyte/yugabyte-db/issues/4990), but based on comments here it seems that this should always be used.

**Comment by kmuthukk** [comment]
We can close this issue, right @m-iancu (because of https://github.com/yugabyte/yugabyte-db/issues/5128)?

**Comment by m-iancu** [comment]
As @kmuthukk mentioned above, this is fixed by #5128.
