### ISSUE TITLE
How to upgrade yugabyte from 1.0.1.0 to 1.0.3.0

### ISSUE THREAD

**Issue by sadeshjayraj** [YugaByte/yugabyte-db#317]
Hi Team,

I got latest patch of  Yugabyte 1.0.3.0 . I am trying to upgrade my cluster server from 1.0.1.0 to  1.0.3.0
Is there any way how to do upgrade??
I have followed below mentioned steps 
1.Untar the yugabyte patch 1.0.3.0
2.Run post_install.sh command
"patchelf does not found"
3. copied patchelf  file under bin folder from existing yugabyte 1.0.1.0
4.Again run post_install.sh command
But I am getting error like 
"Dynamic linker not found or is not executable: '/data/hdfs23/yugabyte-1.0.3.0/lib/ld.so' "

I have observed ld.so file was missing from lib directory

Kindly look and suggest.

**Comment by kmuthukk** [comment]
hi @sadeshjayraj 

Is it possible that instead of pulling the Linux version from:

% wget https://downloads.yugabyte.com/yugabyte-ce-1.0.3.0-linux.tar.gz

you might have pulled the MacOS/Darwin version instead:

% wget https://downloads.yugabyte.com/yugabyte-ce-1.0.3.0-darwin.tar.gz

Because, the Linux version should have a bin/patchelf file inside. 

For example, these are the steps I tried:

```
$ wget https://downloads.yugabyte.com/yugabyte-ce-1.0.3.0-linux.tar.gz
$ tar xvf yugabyte-ce-1.0.3.0-linux.tar.gz
$ cd yugabyte-1.0.3.0/
[centos@ip-10-9-123-137 yugabyte-1.0.3.0]$ ls -lrt bin/patchelf
-r-xr-xr-x 1 centos centos 1141216 Jun  1 01:01 bin/patchelf

[centos@ip-10-9-123-137 yugabyte-1.0.3.0]$ ./bin/post_install.sh
+ /home/centos/yugabyte-1.0.3.0/bin/patchelf --set-interpreter /home/centos/yugabyte-1.0.3.0/lib/ld.so log-dump
+ /home/centos/yugabyte-1.0.3.0/bin/patchelf --set-rpath /home/centos/yugabyte-1.0.3.0/lib/yb:/home/centos/yugabyte-1.0.3.0/lib/yb-thirdparty:/home/centos/yugabyte-1.0.3.0/lib/linux\
brew log-dump
+ /home/centos/yugabyte-1.0.3.0/bin/patchelf --set-interpreter /home/centos/yugabyte-1.0.3.0/lib/ld.so sst_dump
+ /home/centos/yugabyte-1.0.3.0/bin/patchelf --set-rpath /home/centos/yugabyte-1.0.3.0/lib/yb:/home/centos/yugabyte-1.0.3.0/lib/yb-thirdparty:/home/centos/yugabyte-1.0.3.0/lib/linux\
brew sst_dump
....
....
```

**Comment by sadeshjayraj** [comment]
Hi Kannan,
Thanks for immediate reply :)

You were correct, mistakenly we have downloaded  MacOs version.
We have downloaded the linux latest patch and after installation it works fine.

In addition to above steps
Is there any way to upgrade yugabyte server ?? currently we are replacing whole binary and deploying whole cluster maanually.
What should be standard way to do yugabyte ugbyte??

Kindly suggest.

**Comment by kmuthukk** [comment]
Hi @sadeshjayraj 

Given that YugaByte is a replicated and highly-available database, the recommended mode is to do a rolling upgrade of the cluster one node at a time.

The basic flow is to upgrade each yb-master and yb-tserver one at a time, verifying after each step from the master UI (http://<yb-master>:7000/) that the cluster is healthy and the upgraded process is back online. 

If you plan to script this in a loop, then a pause of about 60 secs is recommended before moving from one process/node to another.

**Note**: Your data/log/conf directories are generally stored in a separate location which stays the same across the upgrade so that the cluster data, it's configuration settings etc. are retained across the upgrade.

Roughly, for each yb-master:
```
% pkill yb-master
% < switch binaries to new release >
% < start the yb-master process >
% < verify in http://<any-yb-master>:7000/ that all masters are alive.> 
% < pause 60 secs or so before upgrading next yb-master >
```

Similarly, for each yb-tserver:
```
% pkill yb-tserver
% < switch binaries to new release > 
% < start yb-tserver process>
% <verify in http://<any-yb-master>:7000/tablet-servers to see if the new TServer is alive and heart beating >
% < pause 60 secs or so before upgrading next yb-tserver >
```

**Comment by kmuthukk** [comment]
hi @sadeshjayraj : Hope the upgrade steps helped. Closing this issue out for now, but feel free to re-open if you run into issues.
