### ISSUE TITLE
Access local cluster from another machine in AWS

### ISSUE THREAD

**Issue by amit2103** [YugaByte/yugabyte-db#329]
Hi We setup a local cluster of Yugabyte in AWS .
Now  we seem to be unable to connect via Yedis from another machine (Note we started all Yedis services required). We can connect from the same machine but not from another.

**Comment by bmatican** [comment]
Hey @amit2103 ! It would be great if you could provide some more details about how you've started the YB master/tserver processes (in particular any flags you used) as well as what do you mean when you say you connected from that machine (did you use something like `redis-cli -h localhost -p 6379`?).

However, a common set of things to check on would be the following:
- since you say you can access the Yedis interface locally, can you confirm if you've actually passed anything as the `redis_proxy_bind_address` flag? If not, it should have successfully bound to `0.0.0.0`, which should allow for public/private IP connectivity, as well as localhost (which I assume is the last one you tested.
- another normal part is just ensuring you've opened up the security groups on that EC2 machine, to allow for traffic to flow to the machine! For this, just make sure you open up `6379` port access from whatever machine you're trying to connect.

**Comment by bmatican** [comment]
Hey @amit2103 , one more note. It occurred that you might have been using `yb-ctl` to start a local cluster on one of the nodes and then trying to connect to it from the outside. That will not work, as `yb-ctl` is explicitly designed to be a single node testing tool (binds all the servers to localhost aliases, eg: `127.0.0.1`, `127.0.0.2`, ...)

Here's a recent issue from someone having gone through a similar flow: https://github.com/YugaByte/yugabyte-db/issues/309#issuecomment-393164350

Also, here's our most recent docs for manual multi-node deployments: https://docs.yugabyte.com/latest/deploy/manual-deployment/

**Comment by amit2103** [comment]
Yes we were using a local cluster. Is there an easy way to bind a local cluster to 0.0.0.0 ?

**Comment by kmuthukk** [comment]
Hi @amit2103 

The yb-ctl are just helper scripts that internally start the yb-master & yb-tserver processes needed. 

To start a replication factor 1 cluster on a single node that's externally accessible, it is sufficient to start one yb-master and yb-tserver process, and use the appropriate IP address that's externally accessible. The steps are roughly as follows:

```
# 
# Prepare data directory or directories (first time / during cluster creation only)
# For example:
#
rm -rf /mnt/disk1/yb-data
rm -rf /mnt/disk2/yb-data
mkdir /mnt/disk1/yb-data
mkdir /mnt/disk1/yb-data

#
# kill any old yb-master/yb-tserver processes
#
pkill yb-master
pkill yb-tserver

# Specify your IP here - one that's externally accessible also.
export IP=10.9.123.137
export DATA_DIRS="/mnt/disk1/yb-data,/mnt/disk2/yb-data"

# cd to the directory where you have untar'ed the release. 
# And start the yb-master and yb-tserver processes. 
# For example
cd /home/centos/yugabyte-1.0.1.0/bin
./yb-master --master_addresses $IP:7100 --fs_data_dirs $DATA_DIRS --replication_factor 1 >& /mnt/disk1/yb-data/master.out &
./yb-tserver --tserver_master_addrs $IP:7100 --fs_data_dirs $DATA_DIRS --cql_proxy_bind_address $IP:9042 --redis_proxy_bind_address $IP:6379 >& /mnt/disk1/yb-data/tserver.out &
```

**Comment by amit2103** [comment]
Okay. Thats also good enough. I need another help ;- We are using Yedis. We need some kind of DS where we can cap the length to say 1000 of elements. What is the best way to do it.

**Comment by bmatican** [comment]
Hey @amit2103 ! Glad the above helped! As for the DS question, I believe the recommended way of doing that would be to just use a normal list, but at some frequency, call something like `LTRIM`, to trim it back down to your desired 1000 elements. Would that be good enough?

**Comment by amit2103** [comment]
Is it possible to explain bit more what you mean ? By normal LIst you mean
Array List or something  of that kind?

**Comment by bmatican** [comment]
Hey @amit2103 ! Sorry about my earlier comment, I did not realize we do not have `LIST` support yet. This is our page describing what we do and do not yet support: https://docs.yugabyte.com/latest/api/redis/

Technically, if you require a list/array, you should be able to use a hashmap to accomplish similar functionality, for example. If nothing from that list seems like a good match though, please share a couple more details about what you are trying to achieve so we can see how we can help!

One more note though, since neither myself nor @kmuthukk mentioned it explicitly. If you are setting up YugaByte manually and would like to use the YEDIS interface, make sure you run the following manual setup step: https://docs.yugabyte.com/latest/deploy/manual-deployment/verify-deployment/#setup-redis-compatible-yedis-service

Essentially: `./bin/yb-admin --master_addresses $IP:7100 setup_redis_table`

**Comment by amit2103** [comment]
What i need to do is :-

Hold a list of value 1000. i fit goes over 1000 retain the latest 1000 and
discard the ones which are old

**Comment by amit2103** [comment]
As per Yedis yea thats fine. I understand that part

**Comment by kmuthukk** [comment]
hi @amit2103 : 

We don't support Redis's `list` type yet. But once we implement that, you'll be able to do what you are looking for. See for example: https://stackoverflow.com/questions/12060004/limit-list-length-in-redis

Please feel free to open a separate issue for `list` data type support in YEDIS.

Until then, a workaround would be to use YEDIS's timeseries data type.

For example, for a key `k` you would add:

```
TSADD k 1 val1
TSADD k 2 val2
TSADD k 3 val3 
...
```

and so on. At this point, the key k has 3 data points at time 1, 2, 3.  So think of this as your list with 3 items so far. 

When adding an entry to the list, you would first have to find/read the current latest index to determine what index the next add would go at:

```
127.0.0.1:6379> TSLASTN k 1
1) "3"
2) "val3"
```

You would use the above read operation's result to determine the fact the next index to be added is at 4. So the next add we would something like:

```
TSAdd k 4 val4
```

Over time, let's say the index is now at 1000, and the next add will be done at 1001. At this time you'll need to do an add at index 1001 and remove the item at index 1, since you are at the limit of number of items you want:

```
TSAdd k 1001 val1001
TSRem k 1
```
and next operation would be:
```
TSAdd k 1002 val1002
TSRem k 2
```
At any given time to get all the elements in the list, you would do something like:

```
TSLastN k 1000
```

*Note*: This proposal is not race condition free if you have multiple concurrent writers as two clients may think that the next available index to write is 1003 and overwrite each other. So it depends on whether your use case if OK with this restriction. If you can share more details on the exact use case, perhaps there might be alternative solutions we can come up with.

**Comment by amit2103** [comment]
The expiry will work for us. Because in our case data is being written at a specified interval.  Can you guy let me know the expected time the List data structure will be completed ?

**Comment by kmuthukk** [comment]
hi @amit2103 

Don't have a specific timeline for list data structure.  But happy to look into it if this is important for your use case. Is the use case for list  different than the use case you mentioned earlier (with the retaining the 1000 latest elements)? And if so, could you describe the read/write operations on the list that this use case will perform. 

Perhaps you can open a separate github issue for List support in YEDIS, along with (if possible) any additional description/details you can provide of the intended use case.

Will close this current issue out since your original issue is resolved.

regards,
Kannan

**Comment by amit2103** [comment]
@kmuthukk  I do have a question. Does  the yedis cluster you asked us to create is actually a "Redis cluster" that can shard keys ? Because from what I can see is that, it can only replicate for reads and not shard like a normal Redis cluster

**Comment by amit2103** [comment]
So redis seems to have 4 modes. Which two do Yugabyte Support ? I know one is Single/ What are the other ones

**Comment by kmuthukk** [comment]
hi @amit2103 

YugaByte is an auto-sharded/clustered clustered database irrespective of the API you use (e.g., YCQL or YEDIS). When adding nodes the balancing of shards to new nodes for example is automatic.

This post details some of the [key benefits](https://blog.yugabyte.com/using-redis-as-a-true-distributed-fault-tolerant-database-8504a924a3f7) of using Redis-compatible API with YugaByte DB. 

You can explore a lot of these features on a dev server or a laptop using a pseudo-distributed cluster (and yb-ctl). 

For example, the steps mentioned [here](https://docs.yugabyte.com/latest/explore/cloud-native/linear-scalability/) to explore linear scalability and automatic movement of shards, can be tried with a Redis flavored application provided in the sample jar.

For example:

```
# create a pseudo-distributed cluster on a single node.
# This creates 3 yb-master and 3-yb-tserver processes. 
# Think of each yb-tserver/yb-master process as running on a different node.
% ./bin/yb-ctl destroy
% ./bin/yb-ctl --rf 3 --num_shards_per_tserver 4 create
% ./bin/yb-ctl setup_redis
```

Run a sample Redis load:
```
% java -jar ./java/yb-sample-apps.jar --workload RedisKeyValue  --nodes 127.0.0.1:6379 --num_threads_write 1 --num_threads_read 4
```

On master's tablet-servers view:
```
http://127.0.0.1:7000/tablet-servers
```
you'll see that each logical node (tablet-server) has 24 tablets. And read/write IOPS against each one are also reported in this view.

Now, add another yb-tserver (node/process):
```
% ./bin/yb-ctl add_node
```

And master's tablet-servers view:
```
http://127.0.0.1:7000/tablet-servers
```
should show the tablets gradually moving to the newly added node.

**Comment by kmuthukk** [comment]
Screenshot before adding the 4-th yb-tserver (at this point there are 24 tablets per TServer)

<img width="723" alt="screen shot 2018-06-18 at 8 56 17 am" src="https://user-images.githubusercontent.com/13615376/41548409-cdc0d328-72d7-11e8-863d-c7546a295987.png">

Screenshot after adding 4th TServer. Once the tablets move gradually, we see that there are 18 tablets per TServer
<img width="734" alt="screen shot 2018-06-18 at 9 12 27 am" src="https://user-images.githubusercontent.com/13615376/41548416-d0a37082-72d7-11e8-8873-ba7f1b6c4d40.png">

**Comment by kmuthukk** [comment]
Hi @amit2103 

On this question:
<< So redis seems to have 4 modes. Which two do Yugabyte Support ? I know one is Single/ What are the other ones >>

could you clarify the question? With YugaByte - replication factor and number of nodes are both independent levers that can be dialed. With replication factor 1, for example, you can start with just one node and scale as you go without worrying about re-sharding at the app layer. Similarly, with replication factor of 3, the min number of nodes to start with is 3, and then you can scale with ease to many many nodes.

**Comment by hectorgcr** [comment]
@amit2103 

>  Does the yedis cluster you asked us to create is actually a "Redis cluster" that can shard keys ?
I'm working on #35 to support redis cluster. I'll commit this feature this week.
