### ISSUE TITLE
Support for Redis LIST

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#338]
We should support the LIST data type and at least some subset of the commands for it, ideally both LPUSH/LPOP and RPUSH/RPOP so it could be used as a queue. See: https://github.com/YugaByte/yugabyte-db/issues/329#issuecomment-397297966 for a user requirement.

https://redis.io/commands#list

**Comment by ddorian** [comment]
It would be great to support LTRIM on YQL too.

**Comment by rkarthik007** [comment]
Hi @ddorian, great suggestion. Do you mind opening a separate issue for that so we track it?

Guessing you are referring to something like: https://www.w3schools.com/sql/func_sqlserver_ltrim.asp

**Comment by kmuthukk** [comment]
Hi @rkarthik007 

[I had this confusion too in a separate context. LTRIM in SQL is a string function, and in Redis it is a list function.]

Here I think @ddorian is asking for the Redis LTRIM (https://redis.io/commands/ltrim). So we can just track this in this same github issue. I think @bmatican just gave a few sample commands like (LPUSH/LPOP), but we should just plan on implementing LTRIM also as part of the LIST implementation in YEDIS.

regards,
Kannna

**Comment by kmuthukk** [comment]
But yes, @ddorian , if you were referring to LTRIM in the YCQL (Cassandra-compatible API), then please could you create a separate issue for that?

**Comment by ddorian** [comment]
@kmuthukk @rkarthik007 I meant having the same functionality of this issue on YQL too.
I said LTRIM cause that was mentioned on the linked comment on the post.

**Comment by schoudhury** [comment]
@ddorian YQL refers to YugaByte's internal Query Layer that forms the basis for our multiple APIs (and is not an API in itself). The APIs we have today are YCQL (Cassandra-compatible), YEDIS (Redis-compatible) and PostgreSQL. Can you pls confirm that when you are referring to YQL you actually mean YCQL?

**Comment by ddorian** [comment]
@schoudhury My bad, I meant the YCQL.

**Comment by kmuthukk** [comment]
@ddorian, @rkarthik007 :

Ok, so my misunderstanding. Part of it is due to the terminology. Let me elaborate:

YQL (yugabyte query layer) is a component name we have been using to refer to the multi-model query layer component in our implementation and it includes:

* YCQL (Cassandra-compatible) - YugaByte Cloud Query Language (based on Cassandra with some newer extensions such as JSON, secondary indexes, multi-table txns) 
* YEDIS (Redis-compatible) - YugaByte Dictionary Service (based on Redis with some newer extensions)
* Postgres (SQL)

So to make sure, you are asking for LTRIM (list trim) support in *YCQL* `list` type?

**Comment by ddorian** [comment]
@kmuthukk 
Yes. Cassandra layer, list functions (append, ltrim, append_if_not_exists). Based on previous discussions that YCQL would be most featureful query-layer.

**Comment by m-iancu** [comment]
This is partially supported in [0d9feb2](https://github.com/yugabyte/yugabyte-db/commit/0d9feb266d6c6bca121ea05dc5652e795c2ba74a). Closing as no current plans to extend support beyond that.
