### ISSUE TITLE
Maximum number of keys in a Yedis database?

### ISSUE THREAD

**Issue by tarangill** [yugabyte/yugabyte-db#3395]
[Redis FAQ](https://redis.io/topics/faq) says maximum number of keys in a database is 2^32 - 1. However, that page has not been updated since 2010. In a Google groups thread, somebody said that the max number of keys is 2^32 - 1 on a 32 bit system, and 2^64 - 1 on a 64 bit system. I have been looking for any info on the maximum number of keys in a Yedis database. Can anyone please tell me what the number is? Also, is Yedis multithreaded?

**Comment by ddorian** [comment]
@tarangill yes Yedis is multithreaded and can take advantage of multi core systems. 

YugabyteDB YEDIS (or YCQL/YSQL for that matter) does NOT have a 2^32 (4B) limitation on number of keys. The theoretical limit is likely to be 2^64 - 1, because queries like select count(*) return a int64. For example, in the experiment described in this post, 20 billion keys were loaded. 

https://blog.yugabyte.com/performance-benchmarks-tb-database-cluster-high-data-density-nodes/

Please reopen the issue if you have further questions.
