### ISSUE TITLE
yb-cqlserver Segmentation fault

### ISSUE THREAD

**Issue by wqxiang88** [YugaByte/yugabyte-db#341]
Hi, guys.
A segmentation error occurred when I ran yb-cqlserver.

`./bin/yb-cqlserver --cql_proxy_bind_address="127.0.0.1:7799" --fs_data_dirs=/tmp/cqlserver --cqlserver_master_addrs="127.0.0.1,127.0.0.2,127.0.0.3" --logtostderr`

The result is shown in the figure below：

<img width="719" alt="2018-06-21 6 16 58" src="https://user-images.githubusercontent.com/38744875/41713340-6ae055a8-757f-11e8-8530-6e4213290b11.png">

I found the issue code at:
[https://github.com/YugaByte/yugabyte-db/blob/31563f27f7fa5592fde6bfbd23cac82f8b048f17/src/yb/client/async_initializer.cc#L31](url)

It should changed look like below, and it worked.

`
  client_builder_.set_skip_master_leader_resolution(opts->GetMasterAddresses() && 
                                                                                      opts->GetMasterAddresses()->size() == 1);
`

It worked:

<img width="1424" alt="2018-06-21 6 32 33" src="https://user-images.githubusercontent.com/38744875/41714001-872ea82a-7581-11e8-9e3e-3f96a1a767ea.png">

Thank you so much for opening this great project.^_^.

**Comment by kmuthukk** [comment]
Firstly, regarding your note: <<< Thank you so much for opening this great project.^_^. >>>

We thank you for your feedback! Appreciate it. 

One thing I want to mention is that in our recommended deployment mode (whether it be for [local dev testing ](https://docs.yugabyte.com/latest/quick-start/create-local-cluster/) or production style [multi-node deployments](https://docs.yugabyte.com/latest/deploy/)), the only two server side processes of interest are yb-master & yb-tserver. The functionality of yb-cqlserver is essentially bundled into the yb-tserver itself, and the yb-cqlserver does not need to be run separately and is no longer heavily tested.

Each node's TServer process itself listens to a Cassandra & Redis compatible protocol natively and implements the YCQL & YEDIS compiler/execution engines in a embedded manner. [There is no need to separately run the yb-cqlserver process.] For an architectural overview of yb-tserver process and its sub-components, see [here](https://docs.yugabyte.com/latest/architecture/concepts/universe/#yb-tserver).

For example, you can start a yb-tserver and specify gflags for which port you want to listen to the YCQL & YEDIS protocols on:
```
./yb-tserver --tserver_master_addrs $IP:7100 --fs_data_dirs $DATA_DIRS --cql_proxy_bind_address $IP:9042 --redis_proxy_bind_address $IP:6379 >& /mnt/disk1/yb-data/tserver.out &
```
Having said that, we'll look into this error, and report back. [CC'ing @amitanandaiyer for this input.] Is there a particular reason you want to run the YCQL query layer/engine outside as a separate process rather than the in-process embedded default inside of the yb-tserver process?

**Comment by amitanandaiyer** [comment]
Hope you were able to follow kannan's suggestion to use the embedded cqlserver.

I've cleaned up the unmaintained stand alone cql/redis/pg servers in https://github.com/YugaByte/yugabyte-db/commit/4dd62b7e5a7910f53ad68431c5b82a8c17987289
