### ISSUE TITLE
[docdb] Fix Load Balancer for Preferred Regions

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#3461]
Noticed this in a deployment recently:
- manual 3 AZ deployment: 3,3,2 nodes though
- node tags and cluster placement info configured
- LB successfully balanced the total load across AZs, but the per-node distributions were way off: some 500, some 50
- confirmed with verbose logging that the LB was in fact working, just every second deciding no work needed to be done

One example from enabling `--v=2`:

> I0124 20:40:46.097873 66342 cluster_balance.cc:545] Table load: 63ab228326154255bc5c3c78dc6306ba:2 9df76d2c336047c7b00706b247927e03:16 f14eab757b3944a3a04233ef006c77dd:16 fbedf78177b1466fb3d8848c8fcf8620:16 0cb76ff14b7748538e5b83daafa58b79:23 d7a10420a8414b939044b392e646e444:23 0ec4f8c469d54ed1a563189186bbbc20:24 d24f9994342e48b89a2f2599af54f405:24 

cc @rahuldesirazu @rajukumaryb

**Comment by rahuldesirazu** [comment]
Problem 

Currently, we have load move logic to not move cross-az and not move a tablet from a peer that is the leader for the tablet. Typically this is fine as all nodes will have tablets for which they are followers. But in the case of preferred leaders, we run into a problem trying to move load from a node in a preferred placement if the node is leader for all of its tablets.

Repro

Create a table on a 3 zone 3 node cluster with preferred leaders set to just 1 zone. Add a node to the preferred zone and no load will balance to the new node.

Fix 

The solution is to allow load moves of leader peers if no other move exists. This can be implemented as a two phase approach where we first check moves under stricter conditions and then relax conditions if no moves exist.

If we move from a peer that is leader, we first trigger a RBS to the new node. After that, we just have to make sure we first trigger a leader step-down before doing the remove server step. In our current code path, that won’t happen naturally. Using the repro example, the remove path will now see over-replication and see 2 nodes as candidates. And since it cannot remove the leader peer, it will remove the one just added! 

To fix this, we will have to enable picking remove candidates that are leaders for RF=3 (currently it’s just done for RF=1). Once we do this, we’ll end up triggering a leader step-down without a destination. This is also not ideal, since the lack of destination currently just locally steps down the leader, leaving it up to the follower failure detectors to kick in. Here, we have a few options:

Add logic to raft to pick a peer at random instead of going through FD. This will reduce unavailability window, but we may end up making a leader move that violates preferred regions or moves to a tserver with high leader load already.
Break out of the remove path and do the work as part of the leader balance path, which will trigger a leader move with a hint. This may cause issues if for whatever reason, leader load is already balanced (Can this happen?)

Note that some combo of options 1 and 2 may be the best option. After the leader move is done, the LB can now safely trigger a remove server.

After meeting, we decided that the best approach would be to leave the raft path as is, but make the following changes.
Allow moving load from a leader if no moves are available to move from a non-leader
Disallow the force leader step-down path as part of LB remove.

These two in conjunction means that first we let the load balance path trigger a load move from a leader server. Once the add server is done, instead of forcing a leader step-down as part of remove, which doesn’t use a hint and uses the FD, we can instead skip to the leader LB path to do a leader move before triggering a remove as part of the next run. As an example, let’s say we have this config after adding a node:

A : (8, 8), B : (0, 0)  ||||  C : (8, 0)  ||||  D : (8, 0) 

Where we have (load count, leader count) and |||| represents a zone, and the first zone is affinitized. With the new load move logic (1), we’ll now be able to trigger an add server on B:

A : (8, 8), B : (1, 0)  ||||  C : (8, 0)  ||||  D : (8, 0) 

With the new remove code path (2), we skip removing any peer which is a leader. And since A is a leader for every tablet, we move to the leader load balancing step, where we should move a leader from A onto B:

A : (8, 7), B : (1, 1)  ||||  C : (8, 0)  ||||  D : (8, 0)

On the LB’s next iteration, we will now find a tablet on A that’s not a leader, so we can successfully remove it:

A : (7, 7), B : (1, 1)  ||||  C : (8, 0)  ||||  D : (8, 0)

This same process will repeat until we have the desired configuration:

A : (4, 4), B : (4, 4)  ||||  C : (8, 0)  ||||  D : (8, 0)

We still want to prioritize moving off a non-leader, so we should add logic that moves off a non-leader when possible and only resorts to moving off a leader if that’s the only option.
