### ISSUE TITLE
[Platform] Gflags update on the UI persists doesn't update the db state

### ISSUE THREAD

**Issue by ramkumarvs** [yugabyte/yugabyte-db#3533]
Gflags that are updated from platform should be persisted as is. Right now we keep appending. If a user put an incorrect gflag, and when they go back and update it, we should persist the latest value.

**Comment by iSignal** [comment]
While verifying this, I noticed one slightly inconsistent behavior. When an nonexistent flag is specified, the update gflags operation goes through succesfully in the VM case (AWS/GCP/onprem) because nonexistent flags are ignored in flagfiles. However, in the k8s case, it looks like the flags are passed directly to the container and the update gflags operation ends up in a crash loop.

**Comment by iSignal** [comment]
Verified fixed on portal.

However, in the VM scenario, the flags are still merged, presumably by the devops scripts, so an incorrect flag still remains in the flag file. @bmatican mentioned this might be expected.
