### ISSUE TITLE
Expose metrics for leader/follower on each tablet

### ISSUE THREAD

**Issue by ddorian** [yugabyte/yugabyte-db#3688]
So we can know the number of leaders/followers on each yb-tserver per-table & in total.

**Comment by Adm28** [comment]
Is this issue still unassigned. I would like to have a go at it.

**Comment by Adm28** [comment]
Is this issue still unassigned. I would like to give it a shot.

**Comment by bmatican** [comment]
Hey @Adm28 , yes, this issue is up for grabs! A couple of high level notes, let us know if you need more input:
- For actually plugging in the metrics, you'll likely want to hook directly into `raft_consensus.cc`, when a replica becomes a leader vs a follower
- For how to define metrics, just look around for `METRIC_DEFINE_*`
- For how to manually test this, you can probably even do this on a local cluster, create some tables and let the leaders get balanced, confirming the metrics match the distributions you see in, say, `master_ip:7000/tablet-servers`. Then also add some more nodes, so the LB moves some tablets and leaders around, and then re-confirm the distribution vs the metrics.

cc @rahuldesirazu

**Comment by Adm28** [comment]
Hey **@bmatican** , thanks for the inputs. 
If my understanding is correct ,  the metrics are supposed to track the following on each yb-tserver.
- Number of leaders and followers associated with each table.
- Total number of leaders and followers on yb-tserver.

Please let me know if I have missed something or there is something more to this.

**Comment by bmatican** [comment]
@Adm28 I think that would be great! For reference though, if we track per tablet, then we already have some metrics aggregation code on the Prometheus path, which will bubble up to Table level and then from there, an operator can just do a per-TS sum in Prometheus to get the total, so in practice it might be a-ok to just expose these as tablet-level metrics (using a tablet metric entity in code)

**Comment by Adm28** [comment]
**@bmatican** In that case it would be better to track at tablet level. So are we supposed to track if a tablet is a leader/follower ?

**Comment by bmatican** [comment]
@Adm28 Yeah I think that would be good enough, just need to make sure it cleanly changes when transitioning from follower to leader and back.
