### ISSUE TITLE
Why is the same schema, Tablet::AlterSchema will go to refresh the disk?

### ISSUE THREAD

**Issue by BiterrorChen** [YugaByte/yugabyte-db#369]
https://github.com/YugaByte/yugabyte-db/blob/8f27259c7e62d8209a0de89b1258984b06ef65bb/src/yb/tablet/tablet.cc#L1246
I think that `same_schma` should be changed to an`!same_schma`.
```
    // If the current schema and the new one are equal, there is nothing to do.
    if (!same_schema) {
      return metadata_->Flush();
    }
```

**Comment by hectorgcr** [comment]
@BiterrorChen schema versions are different, otherwise we would never be here because of the check
```
 if (metadata_->schema_version() >= operation_state->schema_version())
```
which returns  `Status::OK()`

In other words, `schema()->Equals` doesn't check versions are equal.

This line is also confusing because there used to be more code after this check: https://github.com/YugaByte/yugabyte-db/commit/17277e65fa933c1924c88d874f9c4bd1e4521d51#diff-9d0bc1834972cbedc114bc27868b2502L1603

But it seems that we need to flush unconditionally. So I'll run some tests, and get back to you.

**Comment by BiterrorChen** [comment]
Ok, I understand. Thank you very much. @hectorgcr

**Comment by hectorgcr** [comment]
@BiterrorChen 
Here is what happens when we don't flush the metadata after an alter schema.
Assume you have table T with column a.
Later you add a new column b. In `Tablet::AlterSchema`, the metadata_ gets updated in memory, but not flushed. Something to notice is that before `Tablet::AlterSchema` gets called, we have already replicated this OP in the raft log.

Before the worse could happen (all the nodes crash), we could have two cases:
1. The max op_id flushed to disk (this is a different Flush from `metadata_->Flush`) is less than the `ALTER_SCHEMA_OP` id. So after the nodes get started we load a stale metadata of the table, but we use the raft log and replay anything that has an id greater than the flushed op_id which includes ALTER_SCHEMA_OP,  so the table will end up with the correct schema. See https://github.com/YugaByte/yugabyte-db/blob/1a8d0ffeb2326cf90ba335a658fb027596b3bbbd/src/yb/tablet/tablet_bootstrap.cc#L618

2. The max op_id flushed to disk is greater than the `ALTER_SCHEMA_OP` id (most likely because there were some `WRITE_OP`s after altering the schema and these ops were flushed). When the nodes come back we will load a stale metadata of the table, but in this case because the `ALTER_SCHEMA_OP` is less than the max flushed op_id, we won't replay the `ALTER_SCHEMA_OP` from the log. But we have code to detect this inconsistency and fix it: https://github.com/YugaByte/yugabyte-db/blob/16960cf537fe05733f4c72685e20dfdf31a46456/src/yb/master/catalog_manager.cc#L3020

So in either case, not flushing the metadata won't affect correctness.
