### ISSUE TITLE
Query list of token_ranges, query by token_range

### ISSUE THREAD

**Issue by ddorian** [yugabyte/yugabyte-db#371]
Is it possible to get a list of token-ranges on a table ? Hopefully along with a `master_id` column, so I can group by master-node ?

Then is it possible to query a table by token-range(s) (so I can be certain I'll query 1-x servers) by using the data from the query in the first question ?

regards,
ddorian

**Comment by kmuthukk** [comment]
@ddorian - by master_id - are you actually referring to the notion of "leader" for the tablet(s)? [In YugaByte DB, yb-master is another set of processes, which is also kept HA via Raft, and it is responsible for keeping system metadata and performing various admin/background tasks. So we are  use the term leader (instead of master) to refer to the Raft leader(s).]

Please note this is being discussed here as another person asked something similar: https://github.com/YugaByte/yugabyte-db/issues/353#issuecomment-403418807

**Comment by ddorian** [comment]
Yes, leader. 

Should I close this then ?

**Comment by kmuthukk** [comment]
Hi @ddorian - perhaps we can close this once we post a summary of the "HOW TO" for your question in this thread or simply document it in docs.yugabyte.com. Let's leave this open until then.

**Comment by ddorian** [comment]
this is implemented in `systems.partitions` in YCQL.
