### ISSUE TITLE
[YSQL] DEFERRABLE ERROR

### ISSUE THREAD

**Issue by wolrd** [yugabyte/yugabyte-db#3987]
I'm using Django and I got the error: 
```
django.db.utils.NotSupportedError: DEFERRABLE constraint not supported yet
LINE 1: ...type_id") REFERENCES "django_content_type" ("id") DEFERRABLE...
                                                             ^
HINT:  See https://github.com/YugaByte/yugabyte-db/issues/1129. Click '+' on the description to raise its priority
```

I see the issue https://github.com/YugaByte/yugabyte-db/issues/1129 but there is no solution.

When can we expect a solution?

**Comment by ndeodhar** [comment]
Hi @wolrd , I'll look into this to get a better understanding of the scope and then give you an estimate of the timeline. We haven't so far prioritized it for 2.2 release (June) but if the scope seems manageable, then we could pick it up sooner.

**Comment by wolrd** [comment]
@ndeodhar thank you for asking.

I didn't understand a little bit. Will the solution be definitely in March or not? Thanks.

**Comment by ndeodhar** [comment]
No, it won't be in March. I'll check if we can deliver it by June and will give you an update (in 1-2 days) on whether we can have the feature ready by June or after June.

**Comment by wolrd** [comment]
@ndeodhar thanks. I will be waiting for.

The Django community is very large.  And I think it will be the right step to allow us to join your product.

**Comment by rkarthik007** [comment]
Hi @wolrd ,

Just wanted to say that our intention is to totally support Django (and this is irrespective of what our competitors are doing, because Django is a very popular app framework). The issue we're facing is not one of intent, however prioritization. We've been getting requests across the board, and we judge this based on overall community interest.

A couple of things I can suggest:
* Could you please open a github issue for supporting Django on YugabyteDB? This issue with the `DEFERRABLE ERROR` may just be one, there could be others. That way, we can keep adding and resolving all blockers to getting there and use that issue as a top level task for the Django ORM support. cc @nchandrappa 
* We're growing as a team as well, so the minute we get more resources and are able to take this task up, we will.
* We plan to publish our 2.2 roadmap soon (cc @ndeodhar @schoudhury) for the YSQL area especially, please do take a look at that.
* If you know anyone who would be interested in helping us, we would love to accelerate this effort.
