### ISSUE TITLE
Add unique_row_id() function to generate int64 values

### ISSUE THREAD

**Issue by ddorian** [yugabyte/yugabyte-db#417]
Hi,

I know that all the hype nowdays is to use as big identifiers as possible, but int64bit is still king. So something that uses `machine_id` + `timestamp` should make it possible to generate enough unique-id-s as to saturate all writes on all servers.

Or something like https://blog.twitter.com/engineering/en_us/a/2010/announcing-snowflake.html too.

Makes sense ?

**Comment by kmuthukk** [comment]
Hi @ddorian 

The [timeuuid](https://docs.yugabyte.com/latest/api/cassandra/type_uuid/) type is 128-bit, but otherwise works similar to what you want (i.e. approx machine_id + timestamp). The [now()](https://docs.yugabyte.com/latest/api/cassandra/function_datetime/#now) builtin function generates a timeuuid.

Does that work or you specifically care for int64 integer type value?

**Comment by ddorian** [comment]
Hi @kmuthukk 

I mostly care for 64-bit.

**Comment by emhna** [comment]
Based on past design discussions, we have decided to use bigserial type to represent int64 unique row ID. To allow large number of sequences to be cached and thus reduce RPC calls, TServer GFlag is introduced so high cache values can be configured easily. 
Eg.
```
./bin/yb-ctl create "ysql_sequence_cache_minval=1000"
CREATE SEQUENCE s1;           // cache set to 1000 for s1
CREATE TABLE S (id SERIAL); // cache set to 1000 for id
```
Note, serial is a pseudo datatype which creates and depends on sequence object for generating its values.
