### ISSUE TITLE
Acceptor::Shutdown problem

### ISSUE THREAD

**Issue by BiterrorChen** [yugabyte/yugabyte-db#420]
Jira Link: [DB-1643](https://yugabyte.atlassian.net/browse/DB-1643)
[CHECK(sockets_to_add_.empty())](https://github.com/YugaByte/yugabyte-db/blob/master/src/yb/rpc/acceptor.cc#L121) may check failed. For example, suppose we have tow threads.
1. Thread1 : [Acceptor::Listen](https://github.com/YugaByte/yugabyte-db/blob/master/src/yb/rpc/acceptor.cc#L81) is called, and add socket to `sockets_to_add_ `.
2. Thread2: [Acceptor::Shutdown](https://github.com/YugaByte/yugabyte-db/blob/master/src/yb/rpc/acceptor.cc#L117) is called before calling `Acceptor::AsyncHandler`.

In this case, the check will fail.

**Comment by spolitov** [comment]
There is if clause, that contains this check: `if (closing_) {`, so that could happen only if shutdown is called twice.
Ideally in this case we should wait until `sockets_to_add_` becomes empty, before return.
But, since the rest of the code don't invoke acceptors shutdown twice, it is very low pri for us now.

**Comment by jaki** [comment]
Got this check fail: https://gist.github.com/jaki/02d2244892026bb0a8a1536277814eaa/raw.

**Comment by bmatican** [comment]
@jaki seems like the problem is slightly above:
> I0527 21:21:42.241690 23528 webserver.cc:279] Webserver: set_ports_option: cannot bind to 0.0.0.0:29484: 98 (Address already in use)

I assume this is a potential concern in our test suite, that despite our best efforts, with multiple processes concurrently trying to find free ports, we could still end up with 2 picking the same port.

However, for mini clusters, we should figure out how to turn this into a more explicit FATAL root caused on failing to bind! cc @mbautin
