### ISSUE TITLE
[docdb] Master leader UI numbers display switched to exponential format

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#4224]

**Comment by aegershman** [comment]
Hey! Just to clarify is this something that's currently weird with 2.1.14.0, or was it supposed to be fixed in 2.1.14.0? Because I just upgraded from 2.1.13.0 to 2.1.14.0 and am _now_ seeing this in the masters' UI under "ram used" when I wasn't before:

<img width="1193" alt="Screen Shot 2020-04-16 at 2 04 12 PM" src="https://user-images.githubusercontent.com/5619476/79496433-be999600-7feb-11ea-8a4a-150c7036d94e.png">

**Comment by bmatican** [comment]
Hey @aegershman, sry about the regression, this did not make the cut in 2.1.4.0, but we'll have the fix in 2.1.5.0!
