### ISSUE TITLE
[Phase 1][YSQL][Colocation] Alter table fails on colocated table

### ISSUE THREAD

**Issue by ndeodhar** [yugabyte/yugabyte-db#4293]
Jira Link: [[DB-391]](https://yugabyte.atlassian.net/browse/DB-391)
Alter table fails on colocated DB:
```
yugabyte=# create database codb with colocated=true;
CREATE DATABASE
yugabyte=# \c codb
You are now connected to database "codb" as user "yugabyte".
codb=# create table test(a int primary key);
CREATE TABLE
codb=# insert into test select generate_series(1,100);
INSERT 0 100
codb=# alter table test add column b int;
ERROR:  Timed out: Timed out waiting for AlterTable
```

[DB-391]: https://yugabyte.atlassian.net/browse/DB-391?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by jaki** [comment]
The overall issue is that alter table doesn't handle non-primary tables of tablets well.  Here are some details to fix it, going in time order:

1. master `AsyncAlterTable` should take table param (otherwise, it always uses tablet's primary table)
1. `ChangeMetadataRequestPB` probably needs some `alter_table_id` field
1. Some modifications to `TabletService`
1. Some modifications to `Tablet`
1. Some modifications to `RaftGroupMetadata`
1. master `HandleTabletSchemaVersionReport` should take table param (otherwise, it always uses tablet's primary table)

See https://github.com/jaki/yugabyte-db/tree/colo-alter-table for partial work.

**Comment by frozenspider** [comment]
Verified - this has been fixed, ALTER works for both means of colocation
