### ISSUE TITLE
[platform] Expose metric for number of elements in our RPC queues to highlight backpressure

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#4294]
If our backends get overloaded, requests keep piling up in the queues. For top-level RPCs, our queue size is 5k, after which we start responding with `backpressure` errors. It would be useful to expose a metric on the number of elements queued up, so we can quickly tell if a cluster is just overloaded by clients.

cc @mbautin @spolitov @amitanandaiyer

**Comment by spolitov** [comment]
We have several metrics in the service pool:
rpc_incoming_queue_time - Number of microseconds incoming RPC requests spend in the worker queue

rpcs_timed_out_in_queue - Number of RPCs whose timeout elapsed while waiting in the service queue, and thus were not processed. Does not include calls that were expired before we tried to execute them.

rpcs_timed_out_early_in_queue - Number of RPCs whose timeout elapsed while waiting 
in the service queue, and thus were not processed. Timeout for those calls were detected before the calls tried to execute.

rpcs_queue_overflow - Number of RPCs dropped because the service queue was full.

And dynamically created metric for number of RPCs in service queue:
rpcs_in_queue_SERVICE_NAME

**Comment by bmatican** [comment]
Thanks @spolitov !

@rahuldesirazu IMO, let's graph these atm: `rpcs_in_queue_SERVICE_NAME`, as these should highlight whenever one of the queues start filling, quite easily.

**Comment by bmatican** [comment]
<img width="1560" alt="Screen Shot 2020-05-14 at 8 28 05 AM" src="https://user-images.githubusercontent.com/395011/81953793-f0872380-95bc-11ea-8c44-e8800cc29bbe.png">

Example of adding entries for Master, Tserver, YCQL, YEDIS

**Comment by amitanandaiyer** [comment]
@bmatican Does RPC in the top right graph legend correspond to TabletServerService?

**Comment by bmatican** [comment]
@amitanandaiyer yes! Specifically, this was the YML for that chart:
```
+tserver_rpc_queue_size_tserver:
+  metric: ""
+  function: "max"
+  filters:
+    saved_name: "rpcs_in_queue_.*"
+    export_type: "tserver_export"
+  group_by: "saved_name"
+  layout:
+    title: "RPC queue sizes (Tserver)"
+    xaxis:
+      type: "date"
+    yaxis:
+      alias:
+        "rpcs_in_queue_yb_consensus_ConsensusService": "Consensus"
+        "rpcs_in_queue_yb_server_GenericService": "Generic"
+        "rpcs_in_queue_yb_tserver_RemoteBootstrapService": "RemoteBootstrap"
+        "rpcs_in_queue_yb_tserver_TabletServerService": "RPC"
+        "rpcs_in_queue_yb_tserver_TabletServerBackupService": "Backups"
+        "rpcs_in_queue_yb_tserver_TabletServerAdminService": "Admin"
+        "rpcs_in_queue_yb_cdc_CDCService": "CDC"
```

**Comment by amitanandaiyer** [comment]
Makes sense. Probably TabletService/TS-RPC or something more specific would be descriptive. 

RPC in the header of the graph corresponds to "all the rpc's together".
In the same graph, we are using it to mean a specific type of RPC -- which is the default for the particular server/proxy.

Could be confusing for users who aren't too familiar.

**Comment by bmatican** [comment]
<img width="1356" alt="Screen Shot 2020-05-14 at 11 57 11 AM" src="https://user-images.githubusercontent.com/395011/81974215-1b33a500-95da-11ea-844e-d9d10c85d8d0.png">

Filtered a bit cc @amitanandaiyer
