### ISSUE TITLE
[docdb] Increase load balancer parallelism leads to ineffective raft config changes

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#4412]
Was working on fixing #4393 and speeding up those sets of java tests. Added mechanics to increase the parallelism for the LB:
```
     flags.put("load_balancer_max_concurrent_adds", "5");
     flags.put("load_balancer_max_over_replicated_tablets", "5");
     flags.put("load_balancer_max_concurrent_removals", "5");
     flags.put("load_balancer_max_concurrent_moves", "5");
```

Noticed that the LB would sometimes get stuck redoing some work over and over again!
```
240019:m3|pid26391|:22907 I0506 03:02:05.004878 26420 cluster_balance.cc:929] Moving tablet b2d1e1caaee7462c97c93a6534e41630 from 4260105a7dfc40cf90eade02ac4b8d8b to 8b95b6ef0c4c41c6ad1ff5acd51164f6
240673:m3|pid26391|:22907 I0506 03:02:05.506129 26420 cluster_balance.cc:946] Removing replica 8b95b6ef0c4c41c6ad1ff5acd51164f6 from tablet b2d1e1caaee7462c97c93a6534e41630
241365:m3|pid26391|:22907 I0506 03:02:06.006803 26420 cluster_balance.cc:929] Moving tablet b2d1e1caaee7462c97c93a6534e41630 from 4260105a7dfc40cf90eade02ac4b8d8b to 8b95b6ef0c4c41c6ad1ff5acd51164f6
241927:m3|pid26391|:22907 I0506 03:02:06.508348 26420 cluster_balance.cc:946] Removing replica 8b95b6ef0c4c41c6ad1ff5acd51164f6 from tablet b2d1e1caaee7462c97c93a6534e41630
242759:m3|pid26391|:22907 I0506 03:02:07.008978 26420 cluster_balance.cc:929] Moving tablet b2d1e1caaee7462c97c93a6534e41630 from 4260105a7dfc40cf90eade02ac4b8d8b to 8b95b6ef0c4c41c6ad1ff5acd51164f6
244270:m3|pid26391|:22907 I0506 03:02:07.510437 26420 cluster_balance.cc:946] Removing replica 8b95b6ef0c4c41c6ad1ff5acd51164f6 from tablet b2d1e1caaee7462c97c93a6534e41630
245451:m3|pid26391|:22907 I0506 03:02:08.011001 26420 cluster_balance.cc:929] Moving tablet b2d1e1caaee7462c97c93a6534e41630 from 4260105a7dfc40cf90eade02ac4b8d8b to 8b95b6ef0c4c41c6ad1ff5acd51164f6
246033:m3|pid26391|:22907 I0506 03:02:08.512460 26420 cluster_balance.cc:946] Removing replica 8b95b6ef0c4c41c6ad1ff5acd51164f6 from tablet b2d1e1caaee7462c97c93a6534e41630
247076:m3|pid26391|:22907 I0506 03:02:09.013061 26420 cluster_balance.cc:929] Moving tablet b2d1e1caaee7462c97c93a6534e41630 from 4260105a7dfc40cf90eade02ac4b8d8b to 8b95b6ef0c4c41c6ad1ff5acd51164f6
248232:m3|pid26391|:22907 I0506 03:02:09.514366 26420 cluster_balance.cc:946] Removing replica 8b95b6ef0c4c41c6ad1ff5acd51164f6 from tablet b2d1e1caaee7462c97c93a6534e41630
248858:m3|pid26391|:22907 I0506 03:02:10.015054 26420 cluster_balance.cc:929] Moving tablet b2d1e1caaee7462c97c93a6534e41630 from 4260105a7dfc40cf90eade02ac4b8d8b to 8b95b6ef0c4c41c6ad1ff5acd51164f6
249361:m3|pid26391|:22907 I0506 03:02:10.516346 26420 cluster_balance.cc:946] Removing replica 8b95b6ef0c4c41c6ad1ff5acd51164f6 from tablet b2d1e1caaee7462c97c93a6534e41630
249899:m3|pid26391|:22907 I0506 03:02:11.016997 26420 cluster_balance.cc:929] Moving tablet b2d1e1caaee7462c97c93a6534e41630 from 4260105a7dfc40cf90eade02ac4b8d8b to 8b95b6ef0c4c41c6ad1ff5acd51164f6
250565:m3|pid26391|:22907 I0506 03:02:11.518338 26420 cluster_balance.cc:946] Removing replica 8b95b6ef0c4c41c6ad1ff5acd51164f6 from tablet b2d1e1caaee7462c97c93a6534e41630
```
cc @rahuldesirazu @hectorgcr @rajukumaryb @nspiegelberg

**Comment by rahuldesirazu** [comment]
**Problem**

On several clusters, we’ve seen repeated add server remove server tasks on the same set of tablets and tablets servers, triggered each second by the load balancer. This resulted in load remaining unbalanced across the cluster and the LB stuck in an active state.  

This state can be traced to a mismatch between the load balancer’s in-memory state and the actual raft configs for each tablet, causing the LB to make incorrect moves. Here is the repro and steps that reproduce this problem: 

**Repro**

 RF = 3, 3 node 3 zone cluster with 3 tablets and load_balancer_max_over_replicated_tablets > 1 (This is a cluster wide flag for the total number of tablets that can be over-replicated), then add a node to one of the zones. 

**Explanation**

Let’s call the tablets “a”, “b”, “c” and the 2 relevant tservers, ts1 and ts2.

After adding the new node, we have:

```
Start of 1st LB run
Ts1 : {a, b, c}     
Ts2: {}
```

In its first run, the LB sees that ts1 has 3 tablets and ts2 has 0 tablets, so it triggers a move of tablet “a”. The first step of the move is adding “a” to ts2:

```
Start of 2nd LB run
Ts1: {a, b, c}
Ts2: {a}
```

Note that “a” is on both ts1 and ts2 since we’ve done the add step, but LB will only remove the old peer once the new peer has been fully bootstrapped. On the 2nd LB run, because we have greater than 1 over-replication limit, we call move logic on “b”. Now, although “b” is still on ts1, we incorrectly modify the in-memory state of the LB to indicate that it’s already been removed from ts1. Therefore, the LB view of the system is as follows after moving “b”:

```
After calling Move on 2nd LB run
Ts1: {a, c}
Ts2: {a, b}
```

We have an over-replication of “a”, so in the same run, the LB picks the highest loaded server to remove from. Since both ts1 and ts2 have the same number of replicas in the LB’s eyes, the LB picks the ts with the lowest sorted uuid. Let’s say this is ts2, then the LB thinks the state looks as follows:

```
After calling Remove on 2nd LB Run
Ts1: {a, c}
Ts2” {b}
```

This looks fine, but the problem is that we haven’t actually removed “b” from ts1. Therefore, when starting the 3rd LB run, the state is actually:

```
Start of 3rd LB Run
Ts1: {a, b, c}
Ts2: {b}
```

And we have a repeat of state 2). This process results in repeated add and remove tasks on the same set of tablets/tablet servers.

**Solution**

The fix is to not mark tablets as removed on LB in-memory state before they’ve actually been removed from the tserver.
