### ISSUE TITLE
[2DC] Support colocated tables

### ISSUE THREAD

**Issue by ndeodhar** [yugabyte/yugabyte-db#4516]
Add ability to setup replication for colocated tables.
This involves changes to:
SetupUniverseReplication flow (schema validation)
Creation of CDC streams (today, we have 1 stream per table)
Producer-consumer tablet mapping

**Comment by rahuldesirazu** [comment]
A few high-level questions to think about for this feature:

1. Do we want to support xDC at the database level or leave it as a per table replication stream? 
2. What happens if a table is collocated on only one side? Is this a mode we want to support? How will the tablet mapping look in this case?
3. How will we store/expose metrics? Currently we have n tablets per stream so we can roll up tablet level metrics to get a per stream metric, but this will change when we have n streams per tablet.

**Comment by hulien22** [comment]
Closed by 07f2c71.
