### ISSUE TITLE
Docker logs say "Yugabyte is already running" but nothing started.

### ISSUE THREAD

**Issue by zeinali0** [yugabyte/yugabyte-db#4554]
I tried to create a yugabyte cluster on docker with:
`docker run -d --name yugabyte -p7000:7000 -p9000:9000 -p5433:5433 -p9042:9042 -p6379:6379 -v yb_data:/home/yugabyte/var yugabytedb/yugabyte:latest bin/yugabyted start --daemon=false --ui=false`

Everything worked fine, but after i restarted my computer i can't start container any more.
I used `docker start [yb-container-id]`, nothing start and in `docker logs [yb-container-id]` it show:
```
yugabyted is already running!
yugabyted is already running!
yugabyted is already running!
yugabyted is already running!
yugabyted is already running!
```
while i even tried restart docker, removing container and re-creating it, restart computer, it still say: `yugabyted is already running!`

**Comment by ddorian** [comment]
Hi @zeinali0 
Sorry for not getting back to you earlier. Are you still hitting this issue ?
If yes, can we move the conversation to slack so we can move this faster ?

**Comment by zeinali0** [comment]
Yeah, it still happening.
I found it happen when i restart my computer while yugabyte is running on docker then I can't start it any more.
But when i create new container and changing the file path from  `yb_data:/home/yugabyte/var` to something like  `yb_data3:/home/yugabyte/va` i can start new cluster and running that
It seems it's checking some flag on disk which is not updated on sudden close or stop so the only way to start cluster is creating new container with new path

**Comment by ddorian** [comment]
Can you paste the `.INFO` and `.WARNING` logs of yb-tserver & yb-master ?
Also `yb-tserver.err` and `yb-master.err` ?

**Comment by dahvlhldle** [comment]
I encountered the same problem .
yb-tserver.err and yb-master.err  have nothing .

yugabyted.log only print
`[yugabyted start] 2020-06-10 08:36:42,583 INFO:  | 0.0s | cmd = start using config file: /home/yugabyte/var/conf/yugabyted.conf (args.config=None)`

**Comment by iSignal** [comment]
@zeinali0  @dahvlhldle : I am working on a fix for this issue. In the meantime, you can do the following to unblock yourself if you are certain that there is no docker process running already (docker ps is not showing yugabyte containers):
1. Start with a new data volume: yb_data_1 instead of yb_data as @dahvlhldle mentioned above.
2. Inspect the data volume and delete the files `data/*.pid` within that volume. You can access the data path for volume yb_data by doing a `docker inspect yb_data` and looking at the Mountpoint in the output.

Hope that helps make progress for now. In the meantime, please feel free to reach out to us on Slack at https://www.yugabyte.com/slack if you continue to face these issues.

**Comment by zeinali0** [comment]
I pulled latest images 8 days ago and i still can't start container after i stop it with this new log:
```
Starting yugabyted...
✅ System checks
Starting yugabyted...
❌ Database failed to start
Starting yugabyted...
❌ Database failed to start
```
I'm not sure where and how should i get `.INFO` and `.WARNING` logs in docker.

I'm using docker version `19.03.8`

**Comment by iSignal** [comment]
@zeinali0 : can you share the full docker command used to start this container and the environment (Mac/linux/windows)?

Please feel free to drop by our Slack channel at https://www.yugabyte.com/slack so we can debug this issue in real-time.

To get the logs you can use the following steps:

1. `docker run --name yugabyte -v yb_data:/home/yugabyte/var yugabytedb/yugabyte:latest bin/yugabyted collect_logs`. This should place the logs into a file named like `/root/yugabyted-2020-06-29-16:00:11.181145.tar.gz` within the container

2. You can get the logs out of the container by either (a) doing a `docker volume inspect yb_data` and going to the mountpoint listed in that output or (b) on MacOS, where approach (a) does not work, you can start the container with a `docker run -it --name yugabyte -v yb_data:/home/yugabyte/var yugabytedb/yugabyte:latest bash` and do a `docker cp yugabyte:/root/yugabyted-2020-06-29-16:00:11.181145.tar.gz /tmp/` to retrieve the file from the container.

3. If you start the database with a different mount point, do you still run into this error? So instead of yb_data, if you try yb_data_1, does it still happen?

**Comment by zeinali0** [comment]
yes i used this command: 
`docker run -d --name yugabyte  -p7000:7000 -p9000:9000 -p5433:5433 -p9042:9042 -v yb_data3:/home/yugabyte/var yugabytedb/yugabyte:latest bin/yugabyted start --daemon=false --ui=false`
and also i tried to init Redis too. Could the problem caused by Redis? because in https://github.com/yugabyte/yugabyte-db/issues/4907 said Redis not supported in yugabyted

**Comment by iSignal** [comment]
Hello @zeinali0 : I don't believe that should prevent the database from starting up. 

One easy way to understand this is to run this as 

`docker run -d --name yugabyte -p7000:7000 -p9000:9000 -p5433:5433 -p9042:9042 -v ~/yb_data3:/home/yugabyte/var yugabytedb/yugabyte:latest bin/yugabyted start --daemon=false --ui=false` 

Note that I used ~/yb_data3 in the volume mount, so this is a new volume mount which is specified as an absolute path.

If this docker container does not come up, please share the logs in `~/yb_data3/logs/` either here or on Slack.

**Comment by ddorian** [comment]
Closing as completed.
