### ISSUE TITLE
[Platform] Add a new RBAC role in YW for non-admins to take and schedule backups

### ISSUE THREAD

**Issue by rao-vasireddy** [yugabyte/yugabyte-db#4694]
Aha! Link: https://yugabyte-test.aha.io/features/PLATFORM-336

**Comment by Arnav15** [comment]
Have made the necessary changes to the backend. Just need an okay on the name of the role (currently using `backupAdmin`) and can then have this diff out for review as well.

**Comment by rkarthik007** [comment]
Per discussion offline, the naming `BackupAdmin` is ok as a name.

* Discussion around making this a tree-like structure, because `BackupAdmin` might need `ReadOnly` automatically. While this simplistic model is ok for now, its not future proofed, since adding other roles may cause issues. This means that we need something like a `PermissionsManager` to map current role to the set of effective permissions.
* Also need to design the Rest API and UI for this feature.
 cc @chirag-yb
