### ISSUE TITLE
Window Function Test Issues

### ISSUE THREAD

**Issue by ngov17** [yugabyte/yugabyte-db#4832]
Using the given postgres window.sql file, I singled out all the queries that were causing errors with respect to the expected window.out and compiled examples of output I am getting for the aforementioned queries that are not working in YB in window_test_error and the corresponding expected outputs in window_test_expected. (The queries that are working have been put into yb_pg_window.sql with the erroneous ones commented out).

[window_test_error.txt](https://github.com/yugabyte/yugabyte-db/files/4804101/window_test_error.txt)
 
[window_test_expected.txt](https://github.com/yugabyte/yugabyte-db/files/4804103/window_test_expected.txt)

On running multiple tests, I realized that the output constantly changes every time I run the build for the specific queries in the above files, possibly suggesting intermittent errors.

**Comment by kmuthukk** [comment]
@bllewell 's guess on the above was that on queries like:
```
SELECT sum(unique1) over (rows between current row and unbounded following),
	unique1, four
FROM tenk1 WHERE unique1 < 10  ORDER by 1,2,3;
```
we would need an ORDER BY in the OVER clause to make the results predictable/deterministic.

So instead of:
`over (rows between current row and unbounded following)`
do a:
`over (ORDER BY unique1 rows between current row and unbounded following)`

@ngov17 is going to give the above a try and report back.

**Comment by bllewell** [comment]
Here's a re-write of one of @ngov17 's examples. First, some general observations:

- The names are short and agnostic to emphasize the generality of the pedagogy.

- The table is a regular table—not a `TEMPORARY` table. If that's an interesting test, it can be done separately.

- The "value" column that is summed has a unique constraint to guarantee that there are no ties. A tie guarantees a non-deterministic result and so defeats the point of a test that aims to compare YSQL results with PG results.

- There are no columns that aren't referenced in the test queries.

- I use the `random()` built-in to insert the rows in a different order each time the test is repeated. This reduces the risk of meaningless test results in a test scenario where semantics are defined with respect to row ordering.

- The understanding that you need to work with window functions, and with aggrehate functions used in window mode, is described carefully in the dedicated "Window functions" section of the YB doc, due to be publisherd here, as brand-new content, during the week of 22-Jun-2020:

  > https://docs.yugabyte.com/latest/api/ysql/exprs/window_functions/

Run this at the ysqlsh prompt:
```
set client_min_messages = warning;
drop table if exists t;

-- This is the textbook idiom so that the random() built-in
-- will generate a different series of values on each new run.
do $body$
declare
  t constant double precision not null :=
    (extract(microseconds from now()))/60000000.0;
begin
  perform setseed(t);
end
$body$;

create table t(
  surrogate_pk  numeric primary key,
  class         text,
  k             int,
  v             int,
  constraint    t_class_k_unq unique(class, k),
  constraint    t_vunq unique(v)
);

insert into t
with
  rows as (
    values
    ('develop',    1, 5300),
    ('develop',    2, 4200),
    ('develop',    3, 4500),
    ('develop',    4, 6000),
    ('develop',    5, 5200),
    ('personnel',  6, 3500),
    ('personnel',  7, 3900),
    ('sales',      8, 5000),
    ('sales',      9, 4700),
    ('sales',     10, 4800))
  ,
  rows_with_randowm_key as (
    select
      random()::numeric as r,
      column1,
      column2,
      column3
  from rows)

select
  r,
  column1,
  column2,
  column3
from rows_with_randowm_key

-- comment out the "oder by" to show how the
-- beginner can be fooled.
order by r
;

-- Text-book bad: undefined result ordering.
select class, k, v
from t;
```
Save this as e.g. `nishant.sql` and run it repeatedly at the ysqlsh prompt. You'll see a different ordering every time. (It's probably the insert-order. But you cannot rely on this.) Here are two examples:
```
   class   | k  |  v   
-----------+----+------
 develop   |  1 | 5300
 develop   |  2 | 4200
 sales     |  9 | 4700
 develop   |  5 | 5200
 develop   |  4 | 6000
 sales     | 10 | 4800
 personnel |  6 | 3500
 personnel |  7 | 3900
 sales     |  8 | 5000
 develop   |  3 | 4500
```
and:
```
   class   | k  |  v   
-----------+----+------
 develop   |  5 | 5200
 sales     |  8 | 5000
 develop   |  4 | 6000
 develop   |  1 | 5300
 develop   |  3 | 4500
 personnel |  7 | 3900
 sales     |  9 | 4700
 develop   |  2 | 4200
 personnel |  6 | 3500
 sales     | 10 | 4800
```
This is very what the SQL textbooks predict. You need this query for reproducible results:
```
-- Now by the book.
select class, k, v
from t
order by class, v;
```
Now add this at the end of the script and run and re-run:
```
-- Text-book semantic error. "sum(v)" returns unpredicable
-- and therefore meaningless, values.
select
  class,
  k,
  v,
  sum(v) over (rows between current row and unbounded following) as s
from t order by class, v;
```
Here, you get a different value for _"s"_ each time each time you re-run (but _"k"_ and _"v"_ have the same values and are ordered predictably.) Here are two examples:
```
   class   | k  |  v   |   s   
-----------+----+------+-------
 develop   |  2 | 4200 | 12500
 develop   |  3 | 4500 | 25600
 develop   |  5 | 5200 | 47100
 develop   |  1 | 5300 | 30900
 develop   |  4 | 6000 | 36900
 personnel |  6 | 3500 |  8300
 personnel |  7 | 3900 | 21100
 sales     |  9 | 4700 | 17200
 sales     | 10 | 4800 |  4800
 sales     |  8 | 5000 | 41900
```
and
```
   class   | k  |  v   |   s   
-----------+----+------+-------
 develop   |  2 | 4200 |  9000
 develop   |  3 | 4500 | 27000
 develop   |  5 | 5200 | 32200
 develop   |  1 | 5300 | 22500
 develop   |  4 | 6000 | 47100
 personnel |  6 | 3500 | 17200
 personnel |  7 | 3900 | 41100
 sales     |  9 | 4700 | 13700
 sales     | 10 | 4800 |  4800
 sales     |  8 | 5000 | 37200
```
Here's how to fix it:
```
-- Now done properly.
select
  class,
  k,
  v,
  sum(v) over (order by v rows between current row and unbounded following) as s
from t order by class, v;
```
It produces this correct result reliably each time that you re-run:
```
   class   | k  |  v   |   s   
-----------+----+------+-------
 develop   |  2 | 4200 | 39700
 develop   |  3 | 4500 | 35500
 develop   |  5 | 5200 | 16500
 develop   |  1 | 5300 | 11300
 develop   |  4 | 6000 |  6000
 personnel |  6 | 3500 | 47100
 personnel |  7 | 3900 | 43600
 sales     |  9 | 4700 | 31000
 sales     | 10 | 4800 | 26300
 sales     |  8 | 5000 | 21500
```
Notice that _"s"_ decreases monotonically, but separately, in each of the three windows—just as the window definition specifies.

Finally, add this at the end:
```
-- This is OK without a window ORDER BY because
-- the window fram is the whole window.
select
  class,
  k,
  v,
  sum(v) over (partition by class) as s
from t order by class, v;
```
It produces this result:
```
   class   | k  |  v   |   s   
-----------+----+------+-------
 develop   |  2 | 4200 | 25200
 develop   |  3 | 4500 | 25200
 develop   |  5 | 5200 | 25200
 develop   |  1 | 5300 | 25200
 develop   |  4 | 6000 | 25200
 personnel |  6 | 3500 |  7400
 personnel |  7 | 3900 |  7400
 sales     |  9 | 4700 | 14500
 sales     | 10 | 4800 | 14500
 sales     |  8 | 5000 | 14500
```

Notice that _"s"_ is the same for each row in each successive window—but, of course, the value that each window gets differs from what the other windows get. This value is what you get with this more familiar use of an aggregated function:

```
--"Classic" use of "sum()" with GROUP BY
select
  class,
  sum(v) as s
from t group by class order by class;
```
This is the result:
```
   class   |   s   
-----------+-------
 develop   | 25200
 personnel |  7400
 sales     | 14500
```

The attached `issue-4832,zip` has everything shown here:

- ``issue-4832.sql` has all the bad semantics queries commented out. This means that it writes an identical spool file on each successive repeat.
- `yb.txt` was produced using `YB-2.1.6.0`.
- `pg.txt` was produced using `PostgreSQL 11.2`.

Any _"diff"_ program shows that these two files are identical.

CC @ngov17, @kmuthukk

**Comment by bllewell** [comment]
[issue-4832.zip](https://github.com/yugabyte/yugabyte-db/files/4807387/issue-4832.zip)

**Comment by ngov17** [comment]
@bllewell 's suggestion outlined in the above comment worked. In addition, whenever a window frame is defined for a window function: 
window_function_name ( expression ) OVER (
    partition_clause
    order_clause
    frame_clause
), it is necessary for the order clause to be unique across all rows of the table to always ensure a meaningful result.

These changes have been made where necessary.

**Comment by kmuthukk** [comment]
Thx for the additional notes @ngov17 !

**Comment by ngov17** [comment]
To elaborate further, create and populate table "test" as follows on YB(2.1.8.2) and postgres(12.3) respectively:

`create table test (unique1 int, four int);`
```
insert into test values 
(4, 0), 
(1, 1), 
(2, 2), 
(0, 0), 
(8, 0), 
(9, 1), 
(3, 3), 
(6, 2), 
(5, 1), 
(7, 3);
```

Consider the following window function query on test: 
```
SELECT 
  last_value(unique1) over (ORDER BY four rows between current row and 2 following exclude current row) 
from test;
```
 
In the above query, the window is defined by `ORDER BY four`. However, since the values under column four are not unique across all rows of the table, it is possible that a query of multiple columns from YB and postgres are ordered slightly differently, but still correct in both cases:

`SELECT * from test order by four;`
```
 unique1 | four 
---------+------
       4 |    0
       0 |    0
       8 |    0
       9 |    1
       1 |    1
       5 |    1
       6 |    2
       2 |    2
       3 |    3
       7 |    3
```
**YB(2.1.8.2)**



`SELECT * from test order by four;`
```
 unique1 | four 
---------+------
       0 |    0
       8 |    0
       4 |    0
       9 |    1
       1 |    1
       5 |    1
       6 |    2
       2 |    2
       3 |    3
       7 |    3
```
**postgres(12.3)**

As a consequence of this, the window itself is defined differently in both servers, albeit correctly. Thus, to make the query absolutely clear and avoid this issue, it is necessary to order the frame by a column whose values are unique across all rows of the window.
