### ISSUE TITLE
Already present: Multiple homogeneous errors:

### ISSUE THREAD

**Issue by phamtai97** [yugabyte/yugabyte-db#4853]
Hi all.
I am running insert about 2 million rows into the table. And then error: 

```log
FATAL: PQexec() failed: 7 Already present: Multiple homogeneous errors: [Already present (yb/consensus/retryable_requests.cc:239): Duplicate request]
(last message repeated 4 times)
```

I do not find issue anywhere.

**Comment by ddorian** [comment]
Hi @phamtai97 

Is this a single transaction with 2M rows ? 
Or multiple concurrent transactions with smaller batches ?

**Comment by phamtai97** [comment]
Hi @ddorian.
I insert a parallel batch. I ran concurrent 64 threads to insert.

**Comment by ndeodhar** [comment]
Hi @phamtai97 , can you increase the gflag `retryable_rpc_single_call_timeout_ms` to a higher value like 60000? This typically happens because we have 2.5sec limit for each request and your writes (an individual RPC) is taking longer than 2.5 seconds.

Note that we are working on improving this experience so that you don't need to tune this gflag in future: https://github.com/yugabyte/yugabyte-db/issues/4789

**Comment by phamtai97** [comment]
Hi @ndeodhar 
I tried to set retryable_rpc_single_call_timeout_ms = 60000 and it worked. When this bug had been fixed, pls notify me.

Thank you.

**Comment by shuyouZZ** [comment]
Hi @phamtai97 
I have the same problem,where can I set this config?

**Comment by ddorian** [comment]
@shuyouZZ 

This can be set in `yb-tserver` config.

**Comment by shuyouZZ** [comment]
I've set this gflag in both tServer and Master, but there's still a problem.
Operation failed. Try again.: Multiple homogeneous errors #5032

**Comment by ddorian** [comment]
fixed in https://github.com/yugabyte/yugabyte-db/issues/4789
