### ISSUE TITLE
[YSQL] Support backup for pre-split multi-tablet range tables

### ISSUE THREAD

**Issue by ndeodhar** [yugabyte/yugabyte-db#4873]
Jira Link: [DB-2111](https://yugabyte.atlassian.net/browse/DB-2111)
Currently `ysql_dump` being used for distributed backups only adds `SPLIT INTO` clause (or tablet partition information) for hash tables. We should add support for pre-split range tables.

**Comment by OlegLoginov** [comment]
The idea is simple:
1.  CREATE TABLE ... SPLIT AT VALUES... creates the range-table and the split points are stored in the Master table record in the sys-catalog.
2. ysql_dump should get the info and decode back the stored info into the SPLIT AT VALUES (<VALUES>) - so ysql_dump must generate correct/original  CREATE TABLE statement.

**Comment by jaki** [comment]
Commits b14485a5fdd8220a23e4f685d84b44e501b3bb15 and 96beb9e77e5d6e4032106bdbc52fcd15df5f6c05 add generic YSQL backup/restore handling for any partitioning mismatch.  Even if the `SPLIT` clause provided by ysql_dump (or lack thereof) causes partitioning that doesn't match with what's in the backup, these commits add checks to detect that then repartition the live table to match what's in the backup before/during importing.

In theory, this fix should extend to range partitioned tables.  However, since the repartition takes time (and locks on master), it may be worth adding a `SPLIT AT VALUES` clause in ysql_dump to avoid the repartition upon restore (for most, not all cases, for same reasons as in hash partitioning: see issue #8229).

Also, @yifanguan, note that the first commit I mention adds a disabled test `YBBackupTest.TestYSQLRangeSplitConstraint`.  Please enable it with your changes.

**Comment by mheer9** [comment]
AS requested schema DDL attached to ticket
https://yugabyte.zendesk.com/agent/tickets/2562

**Comment by m-iancu** [comment]
Closing as this is solved for backups by [3156825](https://github.com/yugabyte/yugabyte-db/commit/3156825304c9ad4b7ea20464bab99a272dba758d). 
However for ysql_dump this is still not solved and should be addressed in a separate issue.
