### ISSUE TITLE
Avoid concurrent LookupTabletById for the same tablet

### ISSUE THREAD

**Issue by spolitov** [yugabyte/yugabyte-db#4969]
Currently, when meta cache decides to refresh tablet leader information it performs `LookupTabletById`.
In the case of old leader failure, different RPCs could find out that leader information should be refreshed and will invoke `LookupTabletById` for the same tablet in parallel.
To decrease the master load we could combine those queries on the client-side.
I.e. only one request should be sent and multiple callers will be notified with its result.

**Comment by hectorgcr** [comment]
Currently we have a mechanism in `LookupTabletByKey`:

```
auto& table_data = tables_[table->id()];
    auto& lookup = table_data.tablet_lookups_by_group[partition_group_start];
    bool was_empty = lookup.empty();
    lookup[partition_start].push_back({std::move(callback), deadline});
    if (!was_empty) {
      VLOG_WITH_FUNC(4) << "Lookups were not empty for partition_group_start: "
                        << Slice(partition_group_start).ToDebugHexString();
      return;
    }
```

Basically, every time we receive a request in `MetaCache::LookupTabletByKey` we enqueue into `table_data.tablet_lookups_by_group[partition_group_start]` which is of type `PartitionToLookupData`:
```
typedef std::unordered_map<std::string, std::vector<LookupData>> PartitionToLookupData;
```
and `LookupData` is just a struct that allows to store the callbacks later when we receive the ONE reply for the rpc request:
```// Used to store callbacks for individual requests looking up tablet by partition key and those
  // requests deadlines, so MetaCache can fire invoke those callbacks inside ProcessTabletLocations
  // after receiving group of tablet locations from master.
  struct LookupData {
    LookupTabletCallback callback;
    CoarseTimePoint deadline;

    std::string ToString() const {
      return Format("{ deadline: $1 }", deadline);
    }
  };
```

So in other words, we only send the RPC for the first call to `LookupTabletByKey`, all the other ones that happen while there is a pending RPC request, get enqueued so that their callbacks can be called when the reply comes back, and the metacache has been updated.

For `LookupTabletById` we can do exactly the same, but instead of having a hash map based on the partition start, we can have one based on the tablet id. Everything else should work the same, we only send the RPC for the first request, and enqueue the callbacks for the rest.

**Comment by robertsami** [comment]
this was covered by https://github.com/YugaByte/yugabyte-db/issues/5059
