### ISSUE TITLE
[Platform] Enhance yb-platform-backup script 

### ISSUE THREAD

**Issue by ajcaldera1** [yugabyte/yugabyte-db#5120]
The following enhancements are needed in the yb-platform-backup script

- Better argument error checking
- Detection of docker ( replicated ) vs. non-docker environments
- Prometheus export should be done via prometheus snapshot api
- Exclude packages/software directory in non-docker environments

Aha! Link: https://yugabyte-test.aha.io/features/PLATFORM-131

**Comment by iSignal** [comment]
Currently, there are two separate scripts for platform backup - one for replicated environments and one for standalone YW installation.

1. For prometheus backup, the script currently copies files over from a running Prometheus instance - this should instead use the prometheus snapshot API https://prometheus.io/docs/prometheus/latest/querying/api/#snapshot which creates a consistent snapshot that can be restored. 
That said, it is not clear what is the priority since prometheus data only goes back the last 14 days.

2. It would be nice to have a single script that does both docker and standalone YW backup but we can maybe wait for a while until the standalone YW setup is operational for a bit.

3. @ajcaldera1 : can you clarify what you mean by better arg checking?

**Comment by ajcaldera1** [comment]
1. The most common use case for this backup will be to provide DR capability for YW. The customer does not want to lose metrics from YW in the event of a failover. This is very high priority. 
2. That's up to how engineering wants to keep these versions straight between replicated environments and standalone environments. A unified script would be easier to manage.
3. The error checking on script arguments is non-existent. We should do some basic sanity tests on the provided parameters.

**Comment by ajcaldera1** [comment]
The first check in for this issue has a couple of problems in a non-docker environment:

1. The default PROMETHEUS_DATA_DIR is incorrect. There should be a method to detect the storage local path via the web-admin /api/v1/status/flags.
2. The script attempts to do a sudo to root when copying the prometheus data from the snapshot directory. Perhaps it should as the prometheus user.

**Comment by WesleyW** [comment]
Currently in review
