### ISSUE TITLE
Change YW nginx config to proxy master/tserver DNS name addresses

### ISSUE THREAD

**Issue by iSignal** [yugabyte/yugabyte-db#5145]

**Comment by rkarthik007** [comment]
This will become an input parameter at the install time of Yugabyte Platform.

@daniel-yb will update the issue with more information (issue, design and usage).

**Comment by daniel-yb** [comment]
The issue is that our current proxy configuration only redirects for IP-based requests based on a regex match. We need to add a location block to the nginx configuration to also match on hostnames so that proxy redirects work for DNS based universes too. This requires adding either:
1. A user-inputted parameter to the replicated installation that is the IP address of the nameserver used to resolve the hostname->IP.
2. A bash script that queries /etc/resolv.conf on the YW machine and adds the nameserver IP found in the file as the proxy resolver in the nginx conf.

**Comment by daniel-yb** [comment]
Final implementation merged went with option #2 specified above.
