### ISSUE TITLE
Abort local tablet bootstrap if the tablet is deleted

### ISSUE THREAD

**Issue by mbautin** [yugabyte/yugabyte-db#5162]

**Comment by hectorgcr** [comment]
It seems that it can very easily fixed:

```
for (const RaftGroupMetadataPtr& meta : metas) {
    scoped_refptr<TransitionInProgressDeleter> deleter;
    RETURN_NOT_OK(StartTabletStateTransition(
        meta->raft_group_id(), "opening tablet", &deleter));

    TabletPeerPtr tablet_peer = VERIFY_RESULT(CreateAndRegisterTabletPeer(meta, NEW_PEER));
    RETURN_NOT_OK(open_tablet_pool_->SubmitFunc(
        std::bind(&TSTabletManager::OpenTablet, this, meta, deleter)));
  }
```


Basically, what we want to do is to check `meta->tablet_data_state()`, and if it’s tombstoned we skip the OpenTablet. We still want to register it regardless of the state because that means that we still heartbeat the tablet to the master, so when a table gets deleted, we don’t leave data behind

**Comment by hectorgcr** [comment]
We actually already have code to avoid bootstrapping TOMBSTONED tablets. Also, because of the use of tablet transitions, it's not possible to tombstone a tablet while it's being bootstrapped.
