### ISSUE TITLE
[Platform] restore azcopy may need /* at the end of backup location

### ISSUE THREAD

**Issue by rao-vasireddy** [yugabyte/yugabyte-db#5163]
Also, * may need to be encoded.

**Comment by rao-vasireddy** [comment]
Also , do we need to add --recursive to the az download command?

**Comment by ajcaldera1** [comment]
Not for files -- recursive only applies to directories. When we download files we don't need --recursive

**Comment by rao-vasireddy** [comment]
@Alan Caldera <alan@yugabyte.com> , this was needed for multi table
restore. Arnav is looking into it.

**Comment by Arnav15** [comment]
No need for `/*` as the `--recursive` flag takes care of that. @ajcaldera1 this was needed since for multi-table backup, each of the table is a directory as well, and that is what was causing the issue while taking backups. When copying a file, it just ignores the --recursive flag, so that should not cause any issues.
