### ISSUE TITLE
[docdb] Add support for range-partitioned tablets to yb-admin split_tablet 

### ISSUE THREAD

**Issue by stevebang** [yugabyte/yugabyte-db#5166]
Currently, `yb-admin split_tablet` supports splitting only hash-partitioned tablets.

**Comment by bmatican** [comment]
@ramsrivatsa you can reach out to @ttyusupov for more info on this.

High level though, you'll need to try out the `yb-admin split_tablet <TABLET_UUID>` command, on a table that is range partitioned, and see the behavior of that vs on a hash partitioned table. Ideally, this should work in both.

**Comment by nspiegelberg** [comment]
Spent a day looking at this task.  A good starting point is `CatalogManager::SplitTablet`.  Manual splits are currently logical ((a + b) / 2) and automatic splits are load based (`Tablet::GetEncodedMiddleSplitKey`).  This means we could go 2 ways with this task:

1. **Add Manual Logical Split for RangePartitioned Tables**.  The current manual split code assumes HashPartitioning and needs support for RangePartitioning (`PartitionSchema::IsHashPartitioning`).  The main implementation for this task should be to add logical split support for range partitioned DocKeys.  

2. (optional) **Add Load Based Split Support for `yb-admin split_tablet`**.  A less common but additionally useful CLI tool is to give an option to trigger a load based split on the TServer with this command as well.  It would require adding some info to the Tablet Metadata on the Master that the TServer could pickup on Heartbeat to trigger that path.  It would also require some way of forcing that path to operate instead of being optimized out on the incremental report.

**Comment by bmatican** [comment]
@mikhpolitov feel free to reach out to @ttyusupov for tablet splitting related questions and maybe @nspiegelberg or @robertsami for `yb-admin` questions.

**Comment by arybochkin** [comment]
Can be closed:
1) Run `./bin/ysqlsh` and execute:
```
=# CREATE TABLE test_table (k INT, i0 INT, t0 TEXT, PRIMARY KEY(k ASC));
=# INSERT INTO test_table SELECT i, i, i::text FROM (SELECT generate_series(1, 1000) i) t2;
```
2) Open master's UI and make sure the table is range partitioned:
55c24061a99b43c1a9c4a6b437141dec	range: [<start>, <end>)
3) Open tserver's UI and make sure there is a single tablet for the table
`yugabyte	test_table	000033e5000030008000000000004106	55c24061a99b43c1a9c4a6b437141dec	range: [<start>, <end>)	RUNNING`
3) Run manual flush for the tablet and wait for some time (may want to look at tserver's UI to make sure SST appeared):
`> ./bin/yb-ts-cli flush_tablet 55c24061a99b43c1a9c4a6b437141dec`
4) Run manual tablet splitting for the tablet and wait for the splitting completed:
`> ./bin/yb-admin split_tablet -master_addresses localhost:7100 55c24061a99b43c1a9c4a6b437141dec`
5) Open tserver's UI and make sure there are two tablets for the table:
```
yugabyte	test_table	000033e5000030008000000000004106	b31af28f7fcf4252841b62f277449936	range: [<start>, DocKey([], [510]))	RUNNING
yugabyte	test_table	000033e5000030008000000000004106	6ad340e5f9ec4284958ab4c56fd191ab	range: [DocKey([], [510]), <end>)	RUNNING
```
6) Run `./bin/ysqlsh` and execute:
```
=# SELECT COUNT(*) FROM test_table;
 count 
-------
  1000
(1 row)
```

**Comment by ttyusupov** [comment]
Manual splitting of range-based sharded table was enabled by this commit:
[[https://github.com/yugabyte/yugabyte-db/commit/f9c8d2ff443c06d41074c7115b85d128779c4597#diff-0ba0805e8f4b95723324d78[…]ee55f0806c43e43fc646d762R2447](https://github.com/yugabyte/yugabyte-db/commit/f9c8d2ff443c06d41074c7115b85d128779c4597#diff-0ba0805e8f4b95723324d7862ebd1144f917008cee55f0806c43e43fc646d762R2447)
](https://github.com/yugabyte/yugabyte-db/commit/f9c8d2ff443c06d41074c7115b85d128779c4597#diff-0ba0805e8f4b95723324d7862ebd1144f917008cee55f0806c43e43fc646d762R2447)

This commit updated `split-tablet` yb-admin command handling to use the same functionality which is used by automated tablet splitting and already supports both hash-based and range-based sharded tables. Before this commit, the was a custom handling for `split-tablet` command at master side which only supported hash-based sharded tablets.
