### ISSUE TITLE
[ysql] add support for ysql in the kubernetes-statefulset.yaml

### ISSUE THREAD

**Issue by schoudhury** [YugaByte/yugabyte-db#517]
currently the https://raw.githubusercontent.com/YugaByte/yugabyte-db/master/cloud/kubernetes/yugabyte-statefulset.yaml does instantiate the yb-postgres container. this should be enhanced so that the yb-postgres service can be instantiated with 1 statefulset pod to begin with.

**Comment by ravimurthy** [comment]
Fixed by https://github.com/YugaByte/yugabyte-db/pull/643

To enable postgres support :- 
(1) uncomment the following lines in statefulset yaml :-
 
# To support postgres functionality, uncomment the following flags.
         #  - "--start_pgsql_proxy"
         #  - "--pgsql_proxy_bind_address=$(POD_IP):5433"

(2) install: kubectl apply -f yugabyte-statefulset.yaml
(3) run initdb: kubectl exec -it yb-tserver-0 bash -- -c "YB_ENABLED_IN_POSTGRES=1 FLAGS_pggate_master_addresses=yb-master-0.yb-masters.default.svc.cluster.local:7100,yb-master-1.yb-masters.default.svc.cluster.local:7100,yb-master-2.yb-masters.default.svc.cluster.local:7100 /home/yugabyte/postgres/bin/initdb -D /tmp/yb_pg_initdb_tmp_data_dir -U postgres"
connect: kubectl exec -it yb-tserver-0 /home/yugabyte/postgres/bin/psql -- -U postgres -d postgres -h yb-tserver-0 -p 5433

More details at :- https://docs.yugabyte.com/latest/quick-start/test-postgresql/#kubernetes
