### ISSUE TITLE
[ysql] add ysql support in yugabyte db's helm chart

### ISSUE THREAD

**Issue by schoudhury** [YugaByte/yugabyte-db#518]
currently the yugabyte db helm chart (documented here: https://docs.yugabyte.com/latest/deploy/kubernetes/helm-chart/) does not instantiate the yb-postgres service with 1 statefulset pod. this should be enhanced.

**Comment by ravimurthy** [comment]
Fixed by https://github.com/YugaByte/yugabyte-db/pull/643

To enable postgres support using helm :- 

(1) install yugabyte :- 
helm install yugabyte --wait --namespace yb-demo --name yb-demo --set "enablePostgres=true"
(2) initialize postgres :- 
kubectl exec -it -n yb-demo yb-tserver-0 bash -- -c "YB_ENABLED_IN_POSTGRES=1 FLAGS_pggate_master_addresses=yb-master-0.yb-masters.yb-demo.svc.cluster.local:7100,yb-master-1.yb-masters.yb-demo.svc.cluster.local:7100,yb-master-2.yb-masters.yb-demo.svc.cluster.local:7100 /home/yugabyte/postgres/bin/initdb -D /tmp/yb_pg_initdb_tmp_data_dir -U postgres"

More details at :- https://docs.yugabyte.com/latest/deploy/kubernetes/helm-chart/
