### ISSUE TITLE
[docdb] new master leader should not try to balance load before it hears from all tservers

### ISSUE THREAD

**Issue by rao-vasireddy** [yugabyte/yugabyte-db#5186]
If there's a network partition and a new master leader is elected, load balancer should not try to move tablets around if it hasn't received heartbeats from all tservers. 
Does the new leader have prior master leader's heartbeat info in terms of any dead nodes and live nodes?

**Comment by bmatican** [comment]
@rao-vasireddy we're already tracking this here: https://github.com/yugabyte/yugabyte-db/issues/4691 and @rahuldesirazu has a fix out for it, just ironing out test failures.

I'll leave this around though, until it gets fixed, as while the root cause is the same, the way this is observed is slightly different.
