### ISSUE TITLE
[YSQL] YB ysql_hba_conf flag does not work as expected

### ISSUE THREAD

**Issue by yb-andrew** [yugabyte/yugabyte-db#5370]
Setting the `ysql_hba_conf` flag does not work as expected. When creating a universe, the hba_conf flag was set to `0.0.0.0/0 md5` and `::0/0 md5` by default, so we added three entries (two to reject and override the public IP's and one to set a non-existent IP to see if it would block access from my laptop. Result is it did not block access and I was able to access with a db role I had set previously.

HBA config file for reference
![Screen Shot 2020-08-11 at 12 56 20 AM](https://user-images.githubusercontent.com/50115930/89935463-0fe71a00-dbc7-11ea-8729-f45c8bef94dc.png)

**Comment by ndeodhar** [comment]
@yb-andrew This is expected behavior - hba conf entries are processed in the order in which they are defined. In this case, since the first entry allows connections from any host to any database, you are able to connect.

If you want to restrict to certain connections, you just need to have those rules in your config. So, in the example above, you might want to just have lines 6 and 7 and not the ones above them.

**Comment by m-iancu** [comment]
Root cause here was that both flags `ysql_hba_conf` and `ysql_enable_auth` were used. 
But in general these are alternatives, and only one should be used depending on the use case:
1.  `ysql_hba_conf` sets custom (fine-grained) hba rules that the cluster will respect (same as in Postgres) -- for advanced usage.
2. `ysql_enable_auth` is a convenience flag that sets a common hba rules setup (i.e. setting auth to md5) -- for common/local use-case. See:  https://docs.yugabyte.com/latest/reference/configuration/yb-tserver/#ysql-enable-auth

If we use both, both two configs (rule-sets) will be set so the behaviour might not be the intended one.
