### ISSUE TITLE
[ysql] Allow multiple small tables to live inside the same tablet (use case: PostgreSQL metadata tables)

### ISSUE THREAD

**Issue by mbautin** [YugaByte/yugabyte-db#542]
The use case is PostgreSQL system tables. We don't want to create 100 tablets in an empty cluster.

One possible design:
- The tables share the same RocksDB in each replica.
- If such a table is dropped, we can drop the RocksDB data on compaction.
- The table id (or the postgres OID of the postgres system catalog table) could take the place of the "hash component". No real hash component would be necessary for the tables themselves as there is only one tablet each request can go to.

**Comment by kmuthukk** [comment]
@mbautin : Is the plan to share the same design as co-partitioned tables here?

**Comment by mbautin** [comment]
@kmuthukk: for co-partitioned tables it is more efficient to use multiple pairs of RocksDB instances per tablet (separate pair of (regular_rocksdb, provisional_rocksdb) instances for each table). This way SSTable files belonging to other table won't interfere with the read performance of a table we're reading. But that design is more complicated to implement (it has local bootstrap implications, separate flushed OpId "frontier" values to track, flush timings, etc.) so we decided to go with the simplified single-RocksDB design for PostgreSQL integration. Also it will likely be more efficient when storing on the order of 100 system catalog tables in the master, most of which will be really small.

**Comment by kmuthukk** [comment]
@mbautin 

<<<This way SSTable files belonging to other table won't interfere with the read performance of a table we're reading>>

I think read interference will be minimal since the sections of each table's data in a SSTable file will fall in distinct regions (different blocks). So the simpler single-RocksDB instance (or two if you counts the intents DB) might be a pretty good choice in terms of a practical tradeoff-- i.e. gets us much of the benefits at much lower implementation complexity.

**Comment by robertpang** [comment]
This is implemented in commit [091b469](https://github.com/YugaByte/yugabyte-db/commit/091b469a7c1eeb80828d8ebb032931cab0d13011).
