### ISSUE TITLE
[YSQL] DELETE support in PostgreSQL

### ISSUE THREAD

**Issue by mbautin** [YugaByte/yugabyte-db#552]

**Comment by mbautin** [comment]
Moved UPDATE support to its own issue: https://github.com/YugaByte/yugabyte-db/issues/565

**Comment by mbautin** [comment]
Pending questions:
- Should we use the foreign data wrapper API or the non-FDW API as we doing for INSERT currently in `nodeModifyTable.c`?
- When should we implement the optimization of skipping read-modify-write for deleting a fully-specified primary key?
- How does postgres_fdw handle this? Does it do a read-modify-write?

**Comment by nocaway** [comment]
Regarding the questions @mbautin posted.

1. Should we use the foreign data wrapper API?
We don't use foreign data wrapper for DML (INSERT, UPDATE, DELETE).  FDW API prepared the statements and then execute it with a set of bind variables, but PostgreSQL engine already does this work for us. We'll just need to implement the DML execution nodes to call YugaByte via PgGate.

2. When should we implement the optimization of skipping read-modify-write?
The optimization for avoiding read-modify-write as well as any other optimizations will be postponed till much later.  At the moment, we want support the functionalities of all PostgreSQL execution nodes and expression operators first and then optimize them.

3. How does postgres_fdw handle this? Does it do a read-modify-write?
The FDW does read-modify-write.  The native PostgreSQL support also runs through the same query plan of execution nodes.

**Comment by nocaway** [comment]
YugaByte's approach on DELETE support.

DELETE FROM <table> WHERE <delete_cond>

Conceptually, PostgreSQL query plan breaks the above DELETE into two steps in one transaction.
Step 1- SELECT <tuple ID> FROM <table> WHERE <delete_cond>
Step 2- DELETE FROM <table> WHERE <tuple ID> = ?

To support the above query plan, we introduce a new system column in YugaByte, **ybctid**.
- During step 1, YugaByte returns **ybctid**
- During step 2, YugaByte delete the row that is identified by **ybctid**

**YBCTID** column
- This column is of datatype BYTEA (binary)
- Currently, it contains the KEY that identifies one row.

NOTE for future consideration: We might optimize our DELETE execution by returning a YBCTID key that identifies a SET of ROWS for BULK deletion instead of just ONE ROW.

**Comment by nocaway** [comment]
This work has been completed by two commits. The first commit provide support for YBCTID, the second, actual deletion.

(1) commit 117de1d4044f5e09618b90d8a26320a6ab21076a
Author: Neil Le <neil@yugabyte.com>
Date:   Tue Nov 27 18:37:59 2018 -0800
    Support for System Columns

(2) commit f78748c999815a1de5b12e5ee939b8ef57ad8bdd
Author: Neil Le <neil@yugabyte.com>
Date:   Thu Dec 6 01:50:25 2018 -0800
    #552: DELETE statement support in PostgreSQL
