### ISSUE TITLE
[platform] Global tasks tab does not show universe context information for create/delete backup jobs

### ISSUE THREAD

**Issue by streddy-yb** [yugabyte/yugabyte-db#5806]
Currently global tasks tab shows the table name(s) that is being backed up -or- deleted but not the universe context. 

![image](https://user-images.githubusercontent.com/68868569/94179230-11a42e80-fe51-11ea-9744-aafcccfa88a9.png)

@chirag-yb

**Comment by mjoshi0923** [comment]
@streddy-yb get tasks api  `api/customers/<CustomerUUID>/tasks` does not provide information ( universe name ) to which the backup task belongs to. I tied implementing lookup in UI, but in case universe has been deleted for that back tasks. in that case universe lookup fails.

We need to have universe name on the task (backup or all) so that we cab show proper context.

@Arnav15 what do you suggest?

**Comment by Arnav15** [comment]
@mjoshi0923 I think that is a good point, but that is in general an issue, that we don't keep references to the backed up universes once they get deleted. So for now I think we can just show it as orphaned or deleted universe, and then actually address it moving forward. Since even if we introduce the new field, it will still have issues in displaying that information for backups that were taken before the fix went in.

**Comment by mjoshi0923** [comment]
@streddy-yb  Right now title attribute has universe name and UI is displaying it. in case of deleted universe task is missing universe name and looks like dangling task. either we will need to do clean up for deleted task or we will have to preserve context on task it self if we want it to be displayed on tasks list UI.

**Comment by mjoshi0923** [comment]
@streddy-yb @chirag-yb This is not an issue anymore, the issue was for the tasks created in past, we had no migration for the past tasks that created this issue. now all backup task has hard coded universe name  so this is not an issues anymore.
