### ISSUE TITLE
[platform][UI] Global tasks page says "There is no data to display" while loading the tasks data

### ISSUE THREAD

**Issue by streddy-yb** [yugabyte/yugabyte-db#5876]
The current message ("_There is no data to display_") is misleading. At the minimum, this message should be changed to something like "Fetching the data, please wait". Ideally the implementation should be changed to improving the data load behavior.

![image](https://user-images.githubusercontent.com/68868569/94621979-25430100-0266-11eb-9916-194963718238.png)

**Comment by rajaSahil** [comment]
Hi, @streddy-yb I would like to take up this as my first contribution. Can you please give me some more insights on how and from where should I start?

**Comment by streddy-yb** [comment]
hi @rajaSahil - sorry for the delay. If you want to simply the change the label, see the previous update. If you want to fix the data loading behavior, it is more involved fix. 

hi @yb-andrew - can you chime in on fixing the data loading behavior?

**Comment by yb-andrew** [comment]
@rajaSahil Right now there's no indication in Redux store that the task list is being fetched. You'll have to add the promise state functions (we use helper functions from `PromiseUtils.js`) to `reducer_tasks.js` for the `FETCH_CUSTOMER_TASKS` case. Then update all instances in the code where we use the `customerTaskList` redux state variable because the data structure will have changed. Finally, you can add a promise check on the inside the `TaskListTable.js`, where the table is rendered, to determine what string. Use the `noDataText` property on the `<BootstrapTable>` to show the correct string: http://allenfang.github.io/react-bootstrap-table/docs.html#noDataText

**Comment by Tigojiang** [comment]
@streddy-yb  Hello! I am a first contributor here. Does the issue still need help? I can definitely go with it. Thank you!

**Comment by streddy-yb** [comment]
hi @Tigojiang - Thanks for offering help. This behavior is being addressed as part of #6214.
