### ISSUE TITLE
Explore restarting writes for kAborted if no data has been sent to the user.

### ISSUE THREAD

**Issue by psudheer21** [yugabyte/yugabyte-db#5931]
Jira Link: [DB-2277](https://yugabyte.atlassian.net/browse/DB-2277)
As of 2nd October, we restart writes on a transaction conflict when we get a `kConflict` error and there is no data being sent to the user. This was fine for most of the cases. However, in presence of multiple writes due to the same operation we can get the kAborted error {like in the case of writes due to triggers}, we don't restart the writes.

Explore fixing this by performing the restarts even for `kAborted` failures if no data has been sent to the user.

**Comment by pkj415** [comment]
Restarting kAborts will not be required once [Wait-on-Conflict concurrency control](https://docs.yugabyte.com/preview/architecture/transactions/concurrency-control/#wait-on-conflict) becomes the default. this is because, in this mode, transactions holding locks can't be aborted by higher priority transactions (which happens in Fail-on-Conflict concurrency control). Instead, there is no concept of priority, and a transaction will wait for other conflicting transactions to finish. If non-resolvable conflicts still persist once the waiting is done, a kConflict is thrown instead of a kAbort. So, a kAbort will only be thrown in other rare failure situations, not due to contention and conflicts between transactions.
