### ISSUE TITLE
[k8s] Standard quay image needs to include "which" executable

### ISSUE THREAD

**Issue by ajcaldera1** [yugabyte/yugabyte-db#6013]
The new post_install -e option depends on the presence of the which command to be installed in the container otherwise it fails silently. The which command is used to locate the path for ldd. We should update our quay image to include this as part of the distribution image.

**Comment by svarnau** [comment]
The which command would be only the first missing thing, since the postgis libraries and all its dependencies also would not be in the standard image, correct?

This is indicative of the larger missing feature to support user modified images (e.g., user-installed postgres extensions). Have discussed this in past with @bmatican

**Comment by ajcaldera1** [comment]
I've come up with a way to bring in the proper docker image as part of an initContainer in the helm chart. I plan to copy the necessary control and libraries from the docker image to the permanent filesystem at startup and then move them to the proper location during the postStart hook for the yb-tserver container. Also at that time the post_install -e will be run. The customer will be responsible for the `CREATE EXTENSION postgis` step.

**Comment by svarnau** [comment]
Good sounds like all the pieces are there. I will look at updating the standard dockerfile for "which" command.

**Comment by svarnau** [comment]
Future docker images for master branch will include the 'which' package.
