### ISSUE TITLE
[YBASE] Crash loop when changing tablet split size in the middle of tablet split operation in progress

### ISSUE THREAD

**Issue by nmantrav2** [yugabyte/yugabyte-db#6104]
Enabled tablet splitting on PF-3 universe (http://portal.dev.yugabyte.com/universes/e3b1d178-39c5-4539-aa72-2cdef2af3549). It is  an existing universe that was running YCQL CassandraBatchTimeseries sample app for some days.

Initially the split size was set to 256MB which was leading to too many splits. Perhaps as discussed in the design meetings, a flag to set upper limit on the splits is needed. After some time decided to change the split size to 5GB. Looks like changing split size in the middle of tablets being split led to tserver crash loop.  Perhaps we should not allow changing split size change when tablet splitting is in progress.

**Comment by bmatican** [comment]
After #8039, we now have flags for size thresholds at which to start splitting, as well as number of tablets per server.

Using these, I was able to setup a universe with a large amount of data (hundreds of GB) with
- a low size threshold (some number of MB), so we start splitting very early
- a low tablet count threshold (10 initially), so we also stop at a small number of tablets and let them grow really big

After each tablet was in the 20GB size, I did a number of rolling restarts, changing the count threshold from 10 to 20/40/80/160 to see if there's any cluster instability caused by this. Observed no more crashes.
