### ISSUE TITLE
[YSQL] Downgrade permission check for data directory to warning

### ISSUE THREAD

**Issue by tedyu** [yugabyte/yugabyte-db#6131]
Currently if the permission on pg_data is unexpected, we would get a fatal message:
```
2020-10-21 16:17:22.453 UTC [60148] FATAL: data directory "/mnt/disk0/pg_data" has invalid permissions
2020-10-21 16:17:22.453 UTC [60148] DETAIL: Permissions should be u=rwx (0700) or u=rwx,g=rx (0750).
```
Edit:
Kannan provided better summary:

The pg_data is a sub-directory that sits under the provided -fs_data_dirs (where transaction logs, database files, table and tablet metadata, etc. also live). We recommend that the entire directory structure under --fs_data_dirs be secured appropriately. Rather than FATAL/crash on specific sub-directories' permission settings, the check has been converted to a WARNING.

**Comment by tylarb** [comment]
`pg_data` contains the decidedly not-minor thing which is `pg_hba.conf` 

The acceptance of this PR means that we trade a currently more secure design for a less secure one - one that allows a user who is not root and not the database owner to set permissions to allow access to the database.

I do not see what problem this PR is trying to solve and I see no reason to make this change which can allow the database to run in a less secure way.

**Comment by kmuthukk** [comment]
@tylarb 

Yes - the description in the commit isn't accurate `Since pg_data stores minor things, we can downgrade the check to warning.`, and shouldn't have been worded that way.
----

Additional notes:

The pg_data is a sub-directory that sits under the provide `-fs_data_dirs` (where transaction logs, database files, table and tablet metadata, etc. sit). We recommend that the entire directory structure under `--fs_data_dirs` be secured appropriately. Rather than FATAL/crash on specific sub-directories permission settings, the check has been converted to a WARNING.
