### ISSUE TITLE
Invalid detection of range operation.

### ISSUE THREAD

**Issue by spolitov** [YugaByte/yugabyte-db#617]
When table has range key we could execute range operation when only part of range key is specified or only hash key is specified.
For instance if we have table (h,r1,r2,v), where h - hash key and r1,r2 - range keys.
The following operation is range operation:
delete where h=XXX and r1=YYY
But because of bug in `IsRangeOperation` we mark operation as range operation only when it does not have range key at all.

**Comment by kmuthukk** [comment]
<<But because of bug in `IsRangeOperation` we mark operation as range operation only when it does not have range key at all.>>

hi @spolitov : From an application point of view, what is the implication of this bug? Does this cause a perf issue or correctness issue or execution failure?

It will be helpful if you can clarify what test case will hit this issue and what the observed end-user behavior will be? That in turn will be useful for us to know in case a user runs into this issue on a older release?

Thanks!

**Comment by spolitov** [comment]
Mentioned delete operation did not work, before the fix.

**Comment by kmuthukk** [comment]
Ok. Can you also clarify the did not work part? Meaning- for example-
doesn't delete any rows or deletes too many rows?

**Comment by spolitov** [comment]
It does NOT delete any rows.

**Comment by spolitov** [comment]
It does not affect our CQL interface, because this codepath is not yet used for the case when we delete by partially specified range key.

**Comment by kmuthukk** [comment]
OK - so given that currently this doesn't affect externally visible functionality - marking this as an internal "enhancement", rather than a bug.
