### ISSUE TITLE
[Platform] Fix health check blocking indefinitely

### ISSUE THREAD

**Issue by daniel-yb** [yugabyte/yugabyte-db#6301]
Each universe health check blocks indefinitely. This can cause the rest of the health checks to not run + cause downstream issues. Possible solutions are:
1. Implement a timeout for the blocking task (the cluster_health script).
2. Implement an Akka actor that receives a message for each universe and runs the health check for them separately.
3. Add a timeout for each individual SSH check that the health check script performs

**Comment by tylarb** [comment]
I've now hit this issue, with this scenario. 

The df command fails, due to NFS mount being unavailable. 

While I think it's a good start - and probably also good - to fail the check globally, I think there's a lot of help to make sure we know _what_ is failed by timing out each command, or a subset of them. 

In the above example, a failed `df` command probably means that there's a bad disk.

**Comment by daniel-yb** [comment]
Agreed it's better to have the timeout at the individual check level. I think a combination of option (2) and (3) is what I'm going to do
