### ISSUE TITLE
[k8s] TServer UI not exposed via OSS deployments.

### ISSUE THREAD

**Issue by Arnav15** [yugabyte/yugabyte-db#6303]
Currently, our helm charts or our statefulsets do not provide a way to expose the UI of the tserver pods. We can enable this by deploying an ingress controller that allows the URL re-writes to redirect to the correct page as well as get access to the UIs themself.

**Comment by iSignal** [comment]
If we have a enableIngress option similar to the enableLoadBalancer option, we could (a) expose our regular client/master UI ports through it and also (b) set up URL rewrites to make @Arnav15 's suggestion above possible.

Nginx ingress might work (as described at https://stackoverflow.com/questions/55394823/hosting-webapp-with-relative-urls-behind-kubernetes-nginx-ingress-controller) because it supports annotations that allow us to rewrite URLs in the returned HTML. Doesn't look like Ambassador supports this.
