### ISSUE TITLE
Go lang support

### ISSUE THREAD

**Issue by arafath-mk** [yugabyte/yugabyte-db#6306]
Jira Link: [DB-2153](https://yugabyte.atlassian.net/browse/DB-2153)
**gocql**

The last update to this repo was on 3rd June 2020 and it is 16 commits behind the original repo.

**pg**
In the case of PostgreSQL library, Yugabyte recommends to use the `https://github.com/lib/pq`. Where as the authors of this library recommends to use `https://github.com/jackc/pgx`.

Hope, you would add professional ongoing support for Go language.

**Comment by ddorian** [comment]
Hi @arafath-mk 

> In the case of PostgreSQL library, Yugabyte recommends to use the https://github.com/lib/pq. Where as the authors of this library recommends to use https://github.com/jackc/pgx.

We recommend the same library that's recommended for standard PostgreSQL. In this case we will update the documentation to point to the new one.

> It seems like a quick and dirty support is provided for the Go language. The yugabyte/gocql library is an old fork from the original gocql library. Since it is just a forked repository, there is no issue tracker available. The last update to this repo was on 3rd June 2020 and it is 16 commits behind the original repo.

When there's a need,bug,feature-request we rebase to the latest version. Are you having any trouble with our library ? If yes, can you open an issue regarding this ?

**Comment by arafath-mk** [comment]
Hi @ddorian 

I was about to evaluate the YB through Go language. Since I found such finding as I mentioned earlier, I dropped the idea of using YB.   

Rather than asking issues to a new comer, please go through the original gocql's issue list and find out whether there are  any issues fixed which are relevant to your `yugabyte/gocql` library too.

**Comment by ddorian** [comment]
@arafath-mk  You opened an issue. And you have 2 issues.

1 is about the PostgreSQL layer that we recommend a different library than what they do. 
I will fix the documentation about this. Does this fix your concern ?

> Rather than asking issues to a new comer, please go through the original gocql's issue list and find out whether there are any issues fixed which are relevant to your yugabyte/gocql library too.

We will. I was still asking if you had any particular issues beside it's 16 commits behind ?

**Comment by arafath-mk** [comment]
Thanks @ddorian. I am planning to tryout YB using the new `pgx` package through `database/sql`.  

If I get time, I will go through the `yugabyte/gocql` library and do a pull request to incorporate latest changes from the original repository.

One of the things software architects do while selecting a new open source technology is to *check the repository activity*. It definitely indicates either the work force availability within the company, or company's interest for giving ongoing support.

Hope, you would add professional ongoing support for Go language.

**Comment by ddorian** [comment]
I think you are looking at this from a perfectionist point of view. As an example: 

We have forked the Python Driver too. It is behind upstream.
We have users using it. Yesterday a user was upgrading to Python 3.8. Quick patch and works again in 3.8. 
Still behind upstream but it's "good enough" to be used on production.

**Comment by rkarthik007** [comment]
Hi @arafath-mk,

We do take client drivers very seriously as a company and are building out a team to focus on this specifically (which will take some time). So we are indeed planning to add support for Go (and other languages).

Pulling any critical fixes/features, upgrading versions and qualifying where relevant is something we do based on end user request (examples: [here](https://github.com/yugabyte/yugabyte-db/issues/4390) and [here](https://github.com/yugabyte/yugabyte-db/issues/611)). Note that we do not play to stay driver version compatible with gocql/other languages, because we have added features that are not present in CQL (example: JSON support) and we expect things to diverge at some point. 

Also, please consider helping us out where you see an area of improvement (as an example, filing this issue counts too - so thanks!). Additionally, if you could share what you find as a result of your evaluation, that would help immensely as well.

cc @kmuthukk @streddy-yb

**Comment by arafath-mk** [comment]
Thanks @rkarthik007. Thanks for your crystal clear explanation. I will definitely try YB. 

Sincerely,
Arafath M

**Comment by ashetkar** [comment]
Closing the ticket since we've since updated the gocql fork with upstream and also added [PGX Smart driver](https://docs.yugabyte.com/preview/drivers-orms/go/yb-pgx/).
