### ISSUE TITLE
DB Write fails

### ISSUE THREAD

**Issue by VishalGupta04** [YugaByte/yugabyte-db#635]
While writing data to Yugabyte cluster using lua-cassandra driver (https://github.com/thibaultcha/lua-cassandra version 1.3.3) with following setup:
- 6 node cluster (1 Leader, 2 Followers)
- Table to insert to was having Primary and Secondary indexes
- Started with empty table and was trying to insert a batch of 1000 records

I observed this error and no records were inserted:
![image](https://user-images.githubusercontent.com/45633837/49526846-ae619a80-f87e-11e8-9913-5cde5c17f11e.png)

Also ran some more DB write test using same Lua-Cassandra driver and observed following on Yugabyte server:
![image](https://user-images.githubusercontent.com/45633837/49527171-4fe8ec00-f87f-11e8-88b6-0e715a1bbbd9.png)

**Comment by kmuthukk** [comment]
@VishalGupta04 : 

My guess is the three issues might be related, and the perhaps the cluster had an hiccup because of the full table scans. That's usually not recommended on very large tables in a OLTP style database. 

Please check if your yb-tserver processes are still running... you may need to restart the yb-tserver processes on all nodes first.

The full table scans (the SELECT * FROM T) on very large tables is a resource intensive (and we need perhaps need an additional safety check to time out the internal operation also, when the top-level operation times out). We have an issue to address this here: https://github.com/YugaByte/yugabyte-db/issues/569 to internal abort stray queries from continuing to run or use up all memory.

**Comment by VishalGupta04** [comment]
I re-ran these test today (without a full table scan) and still see some of the requests (~7%) fail and here is what i see in driver log:
![image](https://user-images.githubusercontent.com/45633837/49560726-940cd880-f8e1-11e8-93b4-c88fc292c07c.png)

![image](https://user-images.githubusercontent.com/45633837/49560748-a424b800-f8e1-11e8-9180-203d27f954bf.png)

**Comment by kmuthukk** [comment]
Hi @VishalGupta04 

a) Can you confirm that all the "yb-tserver" processes (on the N nodes) and "yb-master" processes (on the RF (e.g., 3) nodes) are up?

b) The TServer health can also be verified from HTTP UI: http://<master-ip>:7000/tablet-servers

If not, we can coordinate a time to look at the server side logs with you to investigate further (if that works for you).

regards,
Kannan

**Comment by kmuthukk** [comment]
@VishalGupta04 -- not sure if this issue is still applicable. Closing it for now. Feel free to re-open if the issue still persists or if you are able to repro.
