### ISSUE TITLE
Document how to analyze queries with examples: pg_stat_activity

### ISSUE THREAD

**Issue by rkarthik007** [yugabyte/yugabyte-db#6519]
It would be good to add a section here: https://docs.yugabyte.com/latest/develop/

The ask is to add the following:

* Location: Develop -> Query Performance ->  View Live Queries
* Content: Add information about `pg_stat_activity` with functional examples
* Examples: https://www.tutorialdba.com/2018/03/postgresql-pgstatactivity.html, https://www.alibabacloud.com/help/doc-detail/171076.htm

**Comment by fbsolo** [comment]
I'll take this issue.

**Comment by fbsolo** [comment]
I'd like to take this issue.

**Comment by rkarthik007** [comment]
Thanks @fbsolo!

**Comment by fbsolo** [comment]
**PG_STAT_ACTIVITY**

**Synopsis**

The **PG_STAT_ACTIVITY** view returns analysis and diagnostic information about active Yugabyte server processes and queries.

**Columns**

At a Yugabyte prompt, this query

**yugabyte**=# \d pg_stat_activity

returns the **PG_STAT_ACTIVITY** view columns:

Column | Type | Collation | Nullable | Default
-- | -- | -- | -- | --
datid | oid |   |   |  
datname | name |   |   |  
pid | integer |   |   |  
usesysid | oid |   |   |  
usename | name |   |   |  
application_name | text |   |   |  
client_addr | inet |   |   |  
client_hostname | text |   |   |  
client_port | integer |   |   |  
backend_start | timestamp with time zone |   |   |  
xact_start | timestamp with time zone |   |   |  
query_start | timestamp with time zone |   |   |  
state_change | timestamp with time zone |   |   |  
wait_event_type | text |   |   |  
wait_event | text |   |   |  
state | text |   |   |  
backend_xid | xid |   |   |  
backend_xmin | xid |   |   |  
query | text |   |   |  
backend_type | text |   |   |  

**Examples**

**A basic query**

This query returns basic information about active Yugabyte processes.

**yugabyte=#** SELECT datname, pid, application_name, state, query FROM pg_stat_activity;

datname | pid | application_name | state | query
-- | -- | -- | -- | --
backend_xid | 240 | worker2 | active | SELECT datname, pid, application_name, client_addr, query FROM   pg_stat_activity;

**datname**:			the database connected to this process
**pid**:				the ID value of the specific process
**application_name**:	the application connected to this process
**state**:				the operational condition of the process 

		•	active
		•	idle
		•	idle in transaction
		•	idle in transaction (aborted)
		•	fastpath function call
		•	disabled

**query**:			for this process, the latest query executed

**Identify an open transaction**

This example focuses on sample Yugabyte data resources available [here](https://download.yugabyte.com/#docker).

Often enough, we need to identify long-running queries, because these queries could indicate deeper problems. The **pg_stat_activity** view can help identify these issues. In our examples, we'll focus on the **users** table in the sample **yb_demo** database.

This query shows columns from a row in the **users** table:

**yugabyte=#** SELECT id, name, state FROM users WHERE id = 212;

Id | Name | state
-- | -- | --
212 | Jacinthe Rowe | CO

We might want to update the state column value of this role with a transaction, as shown in this query:

**yugabyte=#** BEGIN TRANSACTION; UPDATE users SET state = 'IA' WHERE id = 212; 

However, we forgot to add **END;** at the end of the query, to close the transaction. This query will return

BEGIN
UPDATE 1

but because the transaction never ended, it will waste resources as an open process. In another Docker window running Yugabyte, we can find information about this idle transaction with **pg_stat_activity**, as shown here:

**yugabyte=#** SELECT datname, pid, application_name, state, query FROM pg_stat_activity;

The query will return these rows:

datname | pid | application_name | state | query
-- | -- | -- | -- | --
yb_demo | 378 | ysqlsh | active | SELECT datname, pid, application_name, state, query FROM   pg_stat_activity;
yb_demo | 582 | ysqlsh | idle in transaction | UPDATE users SET state = 'IA' WHERE id = 212;

In the second row, the **state** column value shows the idle transaction. The process has a **pid** value of 582. We can terminate it with the **pg_terminate_backend** function, as shown in this query:

**yugabyte=#** SELECT pg_terminate_backend(582); 

 pg_terminate_backend
\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
t
(1 row)

The **pg_terminate_backend** function returns "t" when it succeeds, and "f" if it fails. When we again query **pg_stat_activity** in the second window, we see that the idle process ended:

**yugabyte=#** SELECT datname, pid, application_name, state, query FROM pg_stat_activity;

datname | pid | application_name | state | query
-- | -- | -- | -- | --
yb_demo | 378 | ysqlsh | active | SELECT datname, pid, application_name, state, query FROM   pg_stat_activity;

**Comment by polarweasel** [comment]
Best to put this in Explore > Query Optimization.

**Comment by polarweasel** [comment]
@m-iancu can you please review this? I'll get it into a PR once you give it the thumbs-up.

**Comment by m-iancu** [comment]
Looks great, I'd add a couple of useful query patterns that maybe can be added after `Identify an open transaction` and before terminate to actually help a long running txn (particularly useful if there are _a lot_ of open connections on that node).

#### Get list of processes ordered by current txn duration:
```
SELECT datname, pid, application_name, state, query, now() - xact_start AS txn_duration 
          FROM pg_stat_activity ORDER BY xact_start desc;
```

#### Alternatively, get list of processes where current txn has taken more than `1 minute`:
```
SELECT datname, pid, application_name, state, query, xact_start 
    FROM pg_stat_activity WHERE now() - xact_start > '1 min';
```

**Comment by tedyu** [comment]
There seems to be a typo in the first query above. I guess you meant:

yugabyte=# SELECT datname, pid, application_name, state, query, now() - xact_start AS txn_duration
          FROM pg_stat_activity ORDER BY txn_duration desc;

**Comment by m-iancu** [comment]
@tedyu You're right, thanks for catching this -- edited the query in the msg above.

**Comment by polarweasel** [comment]
@tedyu and @aishwarya24 thanks for your work on this one! The PR is now merged.
