### ISSUE TITLE
TwoDCTest.AlterUniverseReplicationMasters/1 sometimes fails AlterUniverseReplication having no error assertion 

### ISSUE THREAD

**Issue by tedyu** [yugabyte/yugabyte-db#6895]
From https://jenkins.dev.yugabyte.com/job/github-yugabyte-db-centos-master-clang-tsan/1633/artifact/build/tsan-clang-dynamic-ninja/yb-test-logs/tests-integration-tests__twodc-test/TwoDCTestParams__TwoDCTest_AlterUniverseReplicationMasters__1.log 
```
I0111 23:49:12.396755 29640 raft_consensus.cc:1015] Sending NO_OP at op { term: 1 index: 66 }
W0111 23:49:12.402693 29640 replica_state.cc:804] T 00000000000000000000000000000000 P b0e80aeba7f843a7a9ef28b5c8e967c5 [term 3 LEADER]: Can't advance the committed index across term boundaries until operations from the current term are replicated. Last committed operation was: { term: 1 index: 66 }, New majority replicated is: { term: 1 index: 66 }, Current term is: 3
I0111 23:49:12.404572 29281 raft_consensus.cc:1578] T 00000000000000000000000000000000 P 1d196b82e8c040c08f2e45a74cf5c539 [term 3 FOLLOWER]: Refusing update from remote peer b0e80aeba7f843a7a9ef28b5c8e967c5: Log matching property violated. Preceding OpId in replica: 1.67. Preceding OpId from leader: 3.67. (term mismatch)
I0111 23:49:12.404619 29618 raft_consensus.cc:1578] T 00000000000000000000000000000000 P 6302278c38c74aa18008ca562beebde7 [term 3 FOLLOWER]: Refusing update from remote peer b0e80aeba7f843a7a9ef28b5c8e967c5: Log matching property violated. Preceding OpId in replica: 1.66. Preceding OpId from leader: 3.67. (index mismatch)
I0111 23:49:12.404846 29281 replica_state.cc:564] T 00000000000000000000000000000000 P 1d196b82e8c040c08f2e45a74cf5c539 [term 3 FOLLOWER]: Aborting all operations after (but not including): 66. Current State: Replica: 1d196b82e8c040c08f2e45a74cf5c539, State: 1, Role: FOLLOWER, Watermarks: {Received: 1.67 Committed: 1.66} Leader: 0.0
I0111 23:49:12.404925 29618 raft_consensus.cc:1808] T 00000000000000000000000000000000 P 6302278c38c74aa18008ca562beebde7 [term 3 FOLLOWER]: Returning from UpdateConsensus because of error: error { code: PRECEDING_ENTRY_DIDNT_MATCH status { code: ILLEGAL_STATE message: "Log matching property violated. Preceding OpId in replica: 1.66. Preceding OpId from leader: 3.67. (index mismatch)" source_file: "../../src/yb/consensus/raft_consensus.cc" source_line: 1576 errors: "\000" } }
I0111 23:49:12.405160 29281 replica_state.cc:596] T 00000000000000000000000000000000 P 1d196b82e8c040c08f2e45a74cf5c539 [term 3 FOLLOWER]: Aborting uncommitted operation due to leader change: 1.67, committed: { term: 1 index: 66 }
I0111 23:49:12.406085 29281 raft_consensus.cc:1808] T 00000000000000000000000000000000 P 1d196b82e8c040c08f2e45a74cf5c539 [term 3 FOLLOWER]: Returning from UpdateConsensus because of error: error { code: PRECEDING_ENTRY_DIDNT_MATCH status { code: ILLEGAL_STATE message: "Log matching property violated. Preceding OpId in replica: 1.67. Preceding OpId from leader: 3.67. (term mismatch)" source_file: "../../src/yb/consensus/raft_consensus.cc" source_line: 1576 errors: "\000" } }
W0111 23:49:12.406268 29274 catalog_manager-internal.h:121] Aborted (yb/consensus/replica_state.cc:593): An error occurred while inserting universe replication info into sys-catalog: Operation aborted by new leader
I0111 23:49:12.407102 29232 consensus_queue.cc:1165] T 00000000000000000000000000000000 P b0e80aeba7f843a7a9ef28b5c8e967c5 [LEADER]: Connected to new peer: { peer: 6302278c38c74aa18008ca562beebde7 is_new: 0 last_received: 1.66 next_index: 67 last_known_committed_idx: 66 is_last_exchange_successful: 0 needs_remote_bootstrap: 0 member_type: VOTER num_sst_files: 0 last_applied: 1.66 }
I0111 23:49:12.408645 29234 consensus_queue.cc:1165] T 00000000000000000000000000000000 P b0e80aeba7f843a7a9ef28b5c8e967c5 [LEADER]: Connected to new peer: { peer: 1d196b82e8c040c08f2e45a74cf5c539 is_new: 0 last_received: 1.66 next_index: 67 last_known_committed_idx: 66 is_last_exchange_successful: 0 needs_remote_bootstrap: 0 member_type: VOTER num_sst_files: 0 last_applied: 1.66 }
../../ent/src/yb/integration-tests/twodc-test.cc:1161: Failure
Value of: alter_resp.has_error()
  Actual: true
Expected: false
```
From the preceding log snippet, it seems universe replication info wasn't inserted into sys-catalog.

**Comment by ns-joep** [comment]
Seems similar but this is single DC universe.

Tserver Information Log-
I0307 04:24:20.283365 2406334 raft_consensus.cc:1692] T ccd317ec4f39414d936eb0650ea440e3 P 48b43ae7a42a4529a6bbad35f8bc8b41 [term 16 FOLLOWER]: Refusing update from remote peer 35a1de2cd5ba40f1ba1a56ce87256dcd: Log matching property violated. Preceding OpId in replica: 16.7081578. Preceding OpId from leader: 16.7081581. (index mismatch)
I0307 04:24:20.283538 2406334 raft_consensus.cc:1922] T ccd317ec4f39414d936eb0650ea440e3 P 48b43ae7a42a4529a6bbad35f8bc8b41 [term 16 FOLLOWER]: Returning from UpdateConsensus because of error: error { code: PRECEDING_ENTRY_DIDNT_MATCH status { code: ILLEGAL_STATE message: "Log matching property violated. Preceding OpId in replica: 16.7081578. Preceding OpId from leader: 16.7081581. (index mismatch)" source_file: "../../src/yb/consensus/raft_consensus.cc" source_line: 1690 errors: "\000" } }

Tserver Error log-
Running duration (h:mm:ss): 52:23:01
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
E0307 04:24:33.229626 2406545 [log.cc:1088](http://log.cc:1088/)] T 9ac488f3a9f344fc823c3bc5f6e9086e P 48b43ae7a42a4529a6bbad35f8bc8b41: Appender stack: Runtime error (yb/util/debug-util.cc:579): Thread did not respond: maybe it is blocking signals
E0307 04:24:33.231597 2406545 [log.cc:1089](http://log.cc:1089/)] T 9ac488f3a9f344fc823c3bc5f6e9086e P 48b43ae7a42a4529a6bbad35f8bc8b41: Long wait for safe op id: 20.146065857, current: 20.146065855, last appended: 20.146065856, last submitted: 20.146065857, appender: { queue: { type: 1 state: 2 max_op_id: -1.-1 }
{ type: 1 state: 2 max_op_id: 20.146065857 }
run_state: kComplete stopped: 0 stop_requested: 0 }, passed: 16.000s
E0307 04:24:34.229770 1945112 [log.cc:1088](http://log.cc:1088/)] T b95b6104a77c4ce78315525b7acb7b38 P 48b43ae7a42a4529a6bbad35f8bc8b41: Appender stack: Runtime error (yb/util/debug-util.cc:579): Thread did not respond: maybe it is blocking signals
E0307 04:24:34.229831 1945112 [log.cc:1089](http://log.cc:1089/)] T b95b6104a77c4ce78315525b7acb7b38 P 48b43ae7a42a4529a6bbad35f8bc8b41: Long wait for safe op id: 15.145810372, current: 15.145810370, last appended: 15.145810371, last submitted: 15.145810372, appender: { queue: { type: 1 state: 2 max_op_id: -1.-1 }
{ type: 1 state: 2 max_op_id: 15.145810372 }
