### ISSUE TITLE
[Platform] [Cert Rotation] Task Progress shows as Done although the task is still in progress

### ISSUE THREAD

**Issue by streddy-yb** [yugabyte/yugabyte-db#6917]
When rotating custom certificates, Task Progress shows as Done although the task is still in progress.

![image](https://user-images.githubusercontent.com/68868569/105002886-cd7fff80-59e6-11eb-8025-85e747300509.png)

cc @Arnav15 @sshev

**Comment by sshev** [comment]
@streddy-yb the root cause for the behavior above is that the task progress bar and tasks history table are updated from different sources. The progress bar appears when some task is active only and it polls that individual task status via a separate API call. The tasks history table updates from the all tasks list by filtering the current universe's tasks only.
Due to that progress bar has the most up-to-date status as polling individual task status happens much faster than fetching all tasks and also there's a known issue with that API as well.
The issue should be gone once tasks API will support pagination (#6214)

**Comment by streddy-yb** [comment]
Thanks @sshev , closing this issue for now.
