### ISSUE TITLE
[docs] Tablet auto splitting is still marked as BETA

### ISSUE THREAD

**Issue by ddorian** [yugabyte/yugabyte-db#6977]
Tablet autosplitting is GA but is still marked as BETA in https://docs.yugabyte.com/latest/architecture/docdb-sharding/tablet-splitting/#automatic-tablet-splitting-beta and https://docs.yugabyte.com/latest/reference/configuration/yb-master/#tablet-split-size-threshold-bytes

**Comment by lizayugabyte** [comment]
@ddorian  Just to make sure I understand: auto tablet splitting is GA and manual is Beta, correct?

**Comment by lizayugabyte** [comment]
@ddorian  Have any of the following items been resolved in 2.4 and can be removed from the limitations list?    * Presplit tablets remain in the system forever and are not deleted from the disk.
* There is no upper bound on the number of tablets for the table when automatic tablet splitting is enabled.
* During tablet splitting, client applications can get an error from the driver and need to retry the request.
* If tablet splitting occurs during an ongoing distributed transaction, it could be aborted and need to be retried.
* Because splitting of tablets that are not completely compacted is not yet implemented, tablets created by tablet splitting might be split after they reach the specified size threshold.
* Colocated tables cannot be split.

**Comment by ddorian** [comment]
@mikhpolitov @robertsami @ttyusupov have committed on the feature: https://github.com/yugabyte/yugabyte-db/issues/1004 so they can confirm::

> auto tablet splitting is GA and manual is Beta, correct?

I'm assuming manual-split is also GA @mbautin 

>     There is no upper bound on the number of tablets for the table when automatic tablet splitting is enabled.
This is done in https://github.com/yugabyte/yugabyte-db/commit/e028f70763b9eb6c286b1e3fc0978fd89a7bef98
>     During tablet splitting, client applications can get an error from the driver and need to retry the request.
This is true https://github.com/yugabyte/yugabyte-db/issues/5854
>     If tablet splitting occurs during an ongoing distributed transaction, it could be aborted and need to be retried.
This is true https://github.com/yugabyte/yugabyte-db/issues/5854
>     Because splitting of tablets that are not completely compacted is not yet implemented, tablets created by tablet splitting might be split after they reach the specified size threshold.
Fixed in https://github.com/yugabyte/yugabyte-db/issues/5523 @robertsami ?
>     Colocated tables cannot be split.
This should be true, the same as "pull out colocated tables", tracked here: https://github.com/yugabyte/yugabyte-db/issues/5239

**Comment by lizayugabyte** [comment]
@ddorian  What about "Presplit tablets remain in the system forever and are not deleted from the disk" ?

**Comment by ddorian** [comment]
> What about "Presplit tablets remain in the system forever and are not deleted from the disk" ?

I think it's done in https://github.com/yugabyte/yugabyte-db/issues/4929 cc @ttyusupov ?

**Comment by ttyusupov** [comment]
I've updated related docs. Feel free to close this issue if you think https://github.com/yugabyte/yugabyte-db/pull/7004 resolved it.

**Comment by lizayugabyte** [comment]
@ddorian @ttyusupov  Okay, thanks, I'll leave the following 3 limitations that are listed in the updated architecture doc. Please confirm that I can close the ticket.
* During tablet splitting, client applications may get an error from the driver and need to retry the request.
* If tablet splitting occurs during an ongoing distributed transaction, it could be aborted and need to be retried.
* Since splitting of tablets that are not completely compacted is not yet implemented, tablets created by tablet splitting might be split after they reach the specified size threshold.
