### ISSUE TITLE
[Platform][Bug] Unable to edit number of nodes in Availability Zones section

### ISSUE THREAD

**Issue by sshev** [yugabyte/yugabyte-db#7024]
STR:
- open AWS portal or run platform UI with API pointed to AWS portal
- open any existing universe for editing
- try to increase nodes number in the Availability Zones section
- observe UI app crashed in browser with js error in console `Uncaught TypeError: Cannot read property 'replicationFactor' of null`
![image](https://user-images.githubusercontent.com/11736711/106225500-1f204b00-619a-11eb-8ea9-a7a8458d88ad.png)

Bug above was introduced in https://github.com/yugabyte/yugabyte-db/commit/ad3a72ae2f48f5f9641305bc565e1345169903a1 commit.

cc @streddy-yb @chirag-yb

**Comment by chirag-yb** [comment]
@sshev Which releases are impacted by this bug? Has this made into 2.4 by any chance?

**Comment by gaurav061** [comment]
@chirag-yb  No this was not backported so it is not in 2.4

**Comment by gaurav061** [comment]
PR: https://github.com/yugabyte/yugabyte-db/pull/7029

**Comment by gaurav061** [comment]
@sshev This issue was due to null currentPlacementStatus prop. Earlier we were not getting the AZ info on the initial load it was only coming if you refresh the page or make any changes which result to call the cluster_resources and cluster_configure API's and thus setting the above prop to a valid data.

**Comment by gaurav061** [comment]
Fixed PR: https://github.com/yugabyte/yugabyte-db/pull/7029
