### ISSUE TITLE
Document Triggers in Explorer Section

### ISSUE THREAD

**Issue by ameyb** [yugabyte/yugabyte-db#7177]
Create a page explaining Triggers (Regular and Event Triggers)

@rkarthik007 / @m-iancu to add starter doc for this section

**Comment by lizayugabyte** [comment]
@rkarthik007  @m-iancu I wrote the following Intro section. Now I just need a list of what we support (I could't find any info), and I'll take it from there.
-------------------------

In YSQL, a function invoked automatically when an event associated with a table occurs is called a trigger. The event is typically caused by data manipulation during `INSERT`, `UPDATE`, and `DELETE`.

You create a trigger by defining a function and then attaching this trigger function to a table. You can create a trigger at a row level or a statement level, depending on the number of times the trigger is to be invoked and when. For example, when executing an `UPDATE` statement that affects five rows, the row-level trigger is invoked five times, whereas the statement-level trigger is invoked only once. In addition, you can enable the trigger to be invoked before or after an event: when the trigger is invoked before an event, it may skip the operation for the current row or modify the row itself; if the trigger is invoked after the event, the trigger has access to all the changes.

When YugabyteDB is being used by different applications, triggers allow you to keep the cross-functional behavior within the database that is performed automatically every time the table data is modified. In addition, triggers let you maintain data integrity rules that can only be implemented at the database level. 

When using triggers, it is important to be aware of their existence and understand their logic. Otherwise, it is difficult to predict the timing and effects of data changes.

While YSQL implements SQL standard, YSQL triggers have the following features that are YSQL-specific:

**Comment by bllewell** [comment]
These examples were tested in YB-2.4.0.0 (the most-recent "stable" at the time of writing).

Here's an example of a regular table trigger. It works when you sign on as any ordinary user. I left out all the `drop` commands (or, if you prefer, `create or replace`) to reduce the clutter.

```
create table t(k int primary key, v text);
insert into t(k, v) values(1, 'dog');

drop function if exists t_trg_f() cascade;
create function t_trg_f()
  returns trigger 
  language plpgsql
as $body$
begin
  raise info 'In t_trg_f()';
  return new;
end;
$body$;

create trigger raw_paths_trg
  after truncate on t
  for each statement
execute function t_trg_f();

truncate table t;
```

Sure enough, the `raise info` message is shown when `truncate table` is issued. I chose the special case of `truncate table` because only statement-level triggers are allowed here. Triggers that are specified to fire on ordinary data-changing statements (`INSERT`, `UPDATE`, and `DELETE`) allow both statement-level and row-level flavors.

Here's an example of an event trigger. (Again, prparatory clean-up is omitted.) Realism is added by having the function record some facts in a table. The user who does this must have `Superuser`.

```
\c demo u1

create table ddl_history(
  id serial primary key,
  ddl_date timestamptz,
  ddl_tag text,
  object_name text);

create function log_ddl()
  returns event_trigger
  language plpgsql
as $body$
declare
  r record;
begin
  for r in select * from pg_event_trigger_ddl_commands() loop
    insert into u1.ddl_history
      (ddl_date, ddl_tag, object_name)
    values
      (statement_timestamp(), tg_tag, r.object_identity);
  end loop;
end;
$body$;

create event trigger log_ddl_info
  on ddl_command_end
execute procedure log_ddl();

create table t(k int primary key, v text);

select ddl_date, ddl_tag, object_name from ddl_history order by id;
```

Here is the result. (The values depend on when you run the `create table`.)

```
           ddl_date           |   ddl_tag    | object_name 
------------------------------+--------------+-------------
 2021-02-10 15:34:01.84568-08 | CREATE TABLE | u1.t
 2021-02-10 15:34:01.84568-08 | CREATE TABLE | u1.t_pkey
```
