### ISSUE TITLE
YSQL slow update when index is added

### ISSUE THREAD

**Issue by drakoto** [yugabyte/yugabyte-db#7229]
Jira Link: [DB-2032](https://yugabyte.atlassian.net/browse/DB-2032)
This could be related to the issue #7208 . It can be reproduced using the same sample.
This time, we see a slowdown of an update when an index is added to the tbl2  :

Tables
```sql
CREATE TABLE tbl1(
tblKey UUID DEFAULT uuid_generate_v4 (),
itemName VARCHAR(255),
col1 INT,
CONSTRAINT pk_tbl1 PRIMARY KEY(tblKey)
);
 
CREATE TABLE tbl2(
tblid UUID,
itemname VARCHAR(255),
refKey UUID,
status CHAR DEFAULT 'u' CHECK (status IN ('c', 'd', 'm', 'u')),
col2 UUID,
CONSTRAINT pk_tbl2 PRIMARY KEY(itemname, tblid),
CONSTRAINT fk_tbl1 FOREIGN KEY(refKey) REFERENCES tbl1(tblKey) DEFERRABLE INITIALLY DEFERRED
);
```
1.Load data into TBL1 (1000 rows):
```sql
do $$
declare
n int := 0;
begin
loop
n := n + 1;
exit when n > 1000;
INSERT INTO tbl1 (itemName, col1) values ('Item ' || n, n);
end loop;
end; $$
```
2.Load data into TBL2 (foreign keys to TBL1):
```sql
insert into TBL2 (tblid, itemname, refKey, status)
select '00000000-0000-0000-0000-000000000000',itemname, tblKey, 'c' FROM tbl1
```
3.create the index on TBL2
```sql
CREATE INDEX idx_tbl2_tblid ON tbl2(tblid);
```
4.The update
```sql
  UPDATE tbl2 SET status = 'u', col2 = refKey WHERE tblid = '00000000-0000-0000-0000-000000000000';
```

When sending the update with the index
```
  Update on tbl2  (cost=0.00..5.22 rows=10 width=1200) (actual time=756.205..756.205 rows=0 loops=1)"
  ->  Index Scan using idx_tbl2_tblid on tbl2  (cost=0.00..5.22 rows=10 width=1200) (actual time=19.985..25.239 rows=1000 loops=1)"
        Index Cond: (tblid = '00000000-0000-0000-0000-000000000000'::uuid)"
Planning Time: 0.055 ms
Execution Time: 789.938 ms
```

When sending the update without the index (dropped the index) 
```
Update on tbl2  (cost=0.00..102.50 rows=1000 width=1200) (actual time=67.965..67.965 rows=0 loops=1)
  ->  Seq Scan on tbl2  (cost=0.00..102.50 rows=1000 width=1200) (actual time=8.739..10.057 rows=1000 loops=1)
        Filter: (tblid = '00000000-0000-0000-0000-000000000000'::uuid)
Planning Time: 13.187 ms
Execution Time: 101.970
```
Not sure what is going on, may be we are missing something here ? This is the measured time for 1000 rows, but in reality we have millions of rows where we could see some significant slowdown.
Thank you.

**Comment by ddorian** [comment]
Hi @drakoto 

This because of the architecture of the system. 
1. Sharding results in data being split in multiple tablets and spread over the cluster. Running multi-tablet transactions result in distributed transactions, which are slower.
2. Indexing also splits, resulting in same thing as 1. Combining them together, goes even further.
3. This also results in cross network rpc calls compared to function-calls or shared-memory that you can in single node postgresql scenario.
4. Adding synchronous replication on top, results on more overhead.
5. Because all production deployments will run with ^^ in mind, we haven't prioritized single node performance compared to cross shard transactions, multi region replication etc.
6. There's also the difference in plan picking here. The query is scanning the index, then finding the rows in the main table, which may also fall in different servers.

Example: in a production environment with 3 nodes of 8+ cores, the query above would make a distributed transaction over 16 leader-tablets and replicating to other 16*2 follower tablets. Deleting 2000 rows and inserting 2000 new rows over those 16 * 3 tablets in a single distributed transaction.

Therefore simple queries & single node PostgreSQL wins, because we haven't optimized yet. 
The goal is to have PostgreSQL-level speed in single-node transactions though.

**Comment by drakoto** [comment]
Thanks you so much for the quick answer. We are going to check the performance on multi node.

**Comment by ddorian** [comment]
Closing as no update from user. The performance of the system has become better since this post was created.
