### ISSUE TITLE
Create Universe enables password authentication and PermitRootLogin in VMs

### ISSUE THREAD

**Issue by RunningJon** [yugabyte/yugabyte-db#7415]
VMs deployed for Universe have the /etc/ssh/sshd_config file updated by Ansible as noted in the updated first line of the file. The updates allow for password authentication and allows root to login.

This creates a security problem and also conflicts with many organizations authentication policies that get overridden by Platform.

I created a Universe just now and within a few minutes, I already got someone trying to hack the cluster because of the sshd_config changs.

Mar  1 11:24:32 ip-172-31-21-48 sshd[28610]: Invalid user admin from 5.188.62.240 port 33118
Mar  1 11:24:32 ip-172-31-21-48 sshd[28610]: input_userauth_request: invalid user admin [preauth]
Mar  1 11:24:32 ip-172-31-21-48 sshd[28610]: pam_unix(sshd:auth): check pass; user unknown
Mar  1 11:24:32 ip-172-31-21-48 sshd[28610]: pam_unix(sshd:auth): authentication failure; logname= uid=0 euid=0 tty=ssh ruser= rhost=5.188.62.240
Mar  1 11:24:34 ip-172-31-21-48 sshd[28610]: Failed password for invalid user admin from 5.188.62.240 port 33118 ssh2

This example appears to be from Russia and scanning AWS VMs for vulnerabilities.

**Comment by RunningJon** [comment]
I really think you should reconsider reopening this. Any customer using their own image or even a publicly available one in a cloud marketplace, will expect the sshd_config to not get updated by the installation of our software. It might be the default for the operating system, but it is not the default for cloud marketplaces. AWS, for example, does not allow an AMI to be published in their marketplace with password authentication or root login enabled. 

We have Ansible updating the sshd_config file when it is not needed. The fix is easy. Don't update the file.

**Comment by rtsisyk** [comment]
I agree with you, Jon. I also didn't like that, but this implementation was here before my patch. 

In the current code base we use a special Ansible role to install `sshd` on a custom port. Under the hood, this role efficiently overwrites the entire `/etc/ssh/sshd_config` and changes the port of the system's `sshd`. I see that  this role is only used if `custom_ssh_port` is enabled, but I haven't found an option to disable it. 

I can rework to remove this harmful Ansible role and to patch `sshd_config` instead. This is a different problem which requires extra more work. I can open a new ticket if you think that this problem is important.

**Comment by rtsisyk** [comment]
BTW, this custom Ansible role also causes #7315 you have reported recently.

**Comment by RunningJon** [comment]
I think this is an important issue. I think spending time on this to fix this now is a better choice rather than waiting for a customer to complain and second guess our commitment to security.

**Comment by rtsisyk** [comment]
I created a new issue for this problem.

**Comment by RunningJon** [comment]
Thank you!
