### ISSUE TITLE
[Docs] Add ability to search a specific version of the documentation

### ISSUE THREAD

**Issue by ssung-yugabyte** [yugabyte/yugabyte-db#7636]
Currently, keyword search from the search box always return the latest release. 
It will be very helpful to have keyword search returns the results with the version specified in the version drop down.
For example, 
1) I picked 2.4 from the version drop down list.
2) I search scram 256 in search box
3) The return page flips back to 2.5.

**Comment by polarweasel** [comment]
The current search behaviour is due to Algolia only indexing the docs under /latest, to avoid a pile of duplicate content being indexed and returned in searches. _Older docs are not currently indexed._

Thinking about ways to address this. Options include a separate "archived-documentation" site, an advanced-search page that would let you specify a version and/or query all indices, and running our own Algolia instance so we can control exactly what it indexes.

Meanwhile, perhaps a related improvement could be for us to put a note at the top of https://docs.yugabyte.com/search/ that indicates that all results point to the latest docs?

**Comment by polarweasel** [comment]
Longer-term idea: Postgres (and other doc sets in various industries) identify the _product versions to which a given page applies_. We don't currently have the infrastructure to do that without an enormous amount of manual work, but it's something to keep in mind for future docs-redesign project.

**Comment by polarweasel** [comment]
We are working on version-based search. Closing this as I can't link the PR, which is in another (private) repo.
