### ISSUE TITLE
[Platform] Backup to S3 fails using Yugaware instance's IAM role

### ISSUE THREAD

**Issue by tvesely** [yugabyte/yugabyte-db#7704]
When Yugaware is configured to use the instance's IAM role, `yb_backup.py` obtains the credentials from the `http://169.254.169.254/latest/meta-data/iam/security-credentials/<role>` API endpoint. This endpoint includes an `access_key`, a `secret_key`, and a `security_token`.

```
{
  "Code" : "Success",
  "LastUpdated" : "2012-04-26T16:39:16Z",
  "Type" : "AWS-HMAC",
  "AccessKeyId" : "ASIAIOSFODNN7EXAMPLE",
  "SecretAccessKey" : "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY",
  "Token" : "<token>",
  "Expiration" : "2017-05-17T15:09:54Z"
}
```

It then uses these credentials to create a `cloud_cfg` file for `s3cmd`, that includes all three of these credentials.

https://github.com/yugabyte/yugabyte-db/blob/8d001b06e376c2c3d7686302b0bfd1d5c2c61279/managed/devops/bin/yb_backup.py#L756-L762

When the backup is complete, `yb_backup.py` uses these credentials to upload the backup to s3 using `s3cmd put`. When this occurs `s3cmd put` prefers to use the `access_key` and `secret_key` to upload the files to `s3`, over the `security_token`. These credentials are actually invalid, and the upload fails with `ERROR: S3 error: 403 (InvalidAccessKeyId): The AWS Access Key Id you provided does not exist in our records.`.

```
ubuntu@ip-10-9-1-211:~$ s3cmd --config=/tmp/cloud_cfg put /tmp/example_put_file s3://example-bucket
upload: '/tmp/example_put_file' -> 's3://example-bucket/example_put_file'  [1 of 1]
 0 of 0     0% in    0s     0.00 B/s  done
upload: '/tmp/example_put_file' -> 's3://example-bucket/example_put_file'  [1 of 1]
 0 of 0     0% in    0s     0.00 B/s  done
ERROR: S3 error: 403 (InvalidAccessKeyId): The AWS Access Key Id you provided does not exist in our records.
```

When the `access_key` and `secret_key` are omitted, it uses the `security_token` instead, and the upload succeeds. In my test environment removing L760-L761 allows the backups to succeed, but I'm not entirely convinced that this is the best solution.

**Comment by streddy-yb** [comment]
This issue is still reproducible in the latest builds.

**Comment by mjoshi0923** [comment]
Checking

**Comment by vpatibandla-yb** [comment]
Based on the RCA, the failure on the http://portal2.4.dev.yugabyte.com/ portal is because the s3 backup directory provided did not have the required PUT permissions. When the same backup was tried using a different s3 directory, the action succeeded. 

The above-specified permission issue basically meant that any AWS user whose name is not "aws-portal" will not be able to do the PUT operation on the directories "backups.yugabyte.com/portal/*", "backups.yugabyte.com/portal-2/*". This was the cause of the failure from the portal. Trying the same backup operation by using a different S3 location resulted in a successful backup upload. Hence, the changes made for this fix worked the way they were supposed to and there is no need for additional changes. 

In the future, to not face these issues we have to do some prechecks on the S3 backup config such as GET, PUT, DELETE, LIST operations. This ensures that once a backup config is provided, future operations on the backup config can be guaranteed to a large extent. There is a GitHub issue that is also present and can be used for tracking purposes: https://github.com/yugabyte/yugabyte-db/issues/6857. 

PS: There is access deny policies on other directories also such as "backups.yugabyte.com/gcp-portal/*", "backups.yugabyte.com/k8s-portal/*". I do not know the context behind having these policies in place. Hence, did not remove them. Someone with more context should look at these policies and decide whether they are needed or not.

**Comment by vpatibandla-yb** [comment]
There is a need to do prechecks for the GCP and Azure configs also. The GitHub issues for them are present here: https://github.com/yugabyte/yugabyte-db/issues/6860,  https://github.com/yugabyte/yugabyte-db/issues/6859.
