### ISSUE TITLE
[docdb] Make WritableFileWriter buffer gflag controllable

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#7804]
@rahuldesirazu noticed this as part of the investigation in #6676

> buf_.AllocateNewBuffer(65536);

We should turn this into a gflag. Maybe we can also increase this exponentially up to a certain size, as needed? cc @kmuthukk

**Comment by rahuldesirazu** [comment]
@bmatican The memory allocation increases exponentially until 1MB.

**Comment by rahuldesirazu** [comment]
New flag `rocksdb_file_starting_buffer_size` with default value 8192.

Before: 2 x 70k allocation per tablet

![image](https://user-images.githubusercontent.com/7719567/113357571-0991e380-92f9-11eb-832e-d44762746ade.png)

After: 2 x 13k allocation per tablet

![image](https://user-images.githubusercontent.com/7719567/113357582-0c8cd400-92f9-11eb-9ff5-6985de00723d.png)

So that's about a 114k decrease in allocation per tablet.
