### ISSUE TITLE
Why is there a limit to 6TB per node?

### ISSUE THREAD

**Issue by hiqbn** [YugaByte/yugabyte-db#785]
Why is there a limit to 6TB per node?

**Comment by kmuthukk** [comment]
Hi @hiqbn 

There isn't any hard limit of 6TB per node. If you find that somewhere in our docs mentioned as a hard limit, would appreciate if you can point us to it, so that we can correct it.

The data size limits are primarily  based on workload characteristics, and YugaByte should be able to support much larger data densities as well. In our current tests, we have only gone up to about 6.5TB per node, primarily because we were using i3.8xlarge machines which have about 7.6TB (4 x 1.9TB drives).

*Some highlights from that round of testing*

* Setup: 4-nodes / AWS i3.8xlarge instances/ Replication Factor 3
* Density: 26 TB across 4 nodes (6.5 TB / node)
* 30 billion records (300 byte KVs)
* Cluster expanded from 4 to 5 nodes in 8 hours; deliberately rate limited at 200 MB/sec.
* Induced one node failure in 5 node cluster. Cluster rebalanced back to 4 nodes in 2 hrs 10 minutes!

Also note: This is compressed, on-disk size. In many real world workloads, the compression benefit will be about 3-4x. So the logical data set per node is potentially much larger.

*Architectural Reasons*

Some of the key architectural/design reasons YugaByte is able to support much larger data sets gracefully are:

* C++ implementation (no GC pauses, Java GC tuning requirements etc.)
* RocksDB enhancements to blockify/page meta-data in SSTable files: RocksDB index & bloom filter sections are also broken up into blocks and can be demand paged in.
* Strongly consistent replication design means that when a new node needs to be added, we can copy compressed files from the corresponding leader and do not have do a logical quorum scan of the data across replicas (like in eventually consistent databases).
* Data model aware bloom filters and range predicate hints on each SSTable to minimize number of seeks into SSTables for read workloads.
* Eliminating WAL (transaction log) in RocksDB and using the RAFT WAL as the source of truth to cut write amplification/disk overhead in the write path.

There's a lot more. Please see here for more details: https://docs.yugabyte.com/latest/architecture/concepts/persistence/

**Comment by hiqbn** [comment]
https://www.yugabyte.com/community-edition/

search Multi-TB Density

Store up to 6TB per node

**Comment by kmuthukk** [comment]
Thx for link @hiqbn. Will update/clarify.

**Comment by kmuthukk** [comment]
Updated the info now. Thanks again @hiqbn.

**Comment by hiqbn** [comment]
Store 10s of TBs per node
is there a limit per node?
