### ISSUE TITLE
MemTrackers shows BlockBasedTable instances for deleted tablets

### ISSUE THREAD

**Issue by ttyusupov** [yugabyte/yugabyte-db#7940]
Steps to reproduce:
```
./bin/yb-ctl --rf=1 create
java -jar ~/code/yb-sample-apps/target/yb-sample-apps.jar --workload SqlSecondaryIndex --nodes 127.0.0.1:5433 --num_threads_read 2 --num_threads_write 2 --num_unique_keys 10000000 --nouuid
```

Then after some SST files have been flushed:
```
./bin/ysqlsh
\c postgres;
drop table sqlsecondaryindex;
```

`drop table` statement succeeds and there are no more tablets in master UI, but in tserver memtrackers UI I still can see `RegularDB` and `IntentsDB` for deleted tablets.

**Comment by ttyusupov** [comment]
Was using https://github.com/yugabyte/yugabyte-db/commit/67a117170b7ef9fb1da63b56971d51fc037cb348.

**Comment by ttyusupov** [comment]
Tried another scenario with YCQL:
```
java -jar ~/code/yb-sample-apps/target/yb-sample-apps.jar --workload CassandraBatchTimeseries --nodes 127.0.0.1:9042 --num_threads_read 4 --num_threads_write 4 --nouuid --min_metrics_count 10000 --max_metrics_count 20000 --num_unique_keys 1000000000
```

Then after some SST files have been flushed:
```
./bin/ycqsh

drop table ybdemo_keyspace.batch_ts_metrics_raw;
```

RegularDB instances are still in tserver memtracker UI: http://127.0.0.1:9000/mem-trackers, although tablets are no longer in http://127.0.0.1:9001/tablets

**Comment by jmeehan16** [comment]
This seems to be happening due to the BlockBasedTable memtrackers not being deregistered from their parents.  Here are screenshots demonstrating the fix:
Before table drop (SQL scenario):
<img width="896" alt="BlockBasedTable-memtrackers-before" src="https://user-images.githubusercontent.com/2799714/116920130-46b30380-ac20-11eb-888e-d2b4e5d5d4fd.png">

After table drop:
<img width="900" alt="BlockBasedTable-memtrackers-after" src="https://user-images.githubusercontent.com/2799714/116920164-4e72a800-ac20-11eb-9aed-db0b5c2831ff.png">
