### ISSUE TITLE
[Platform] Huge responses for provider and region endpoints

### ISSUE THREAD

**Issue by sshev** [yugabyte/yugabyte-db#7958]
AWS portal `/providers` and `/regions` endpoints return enormously huge responses - 1.3Mb and 13.4Mb respectively:

![image](https://user-images.githubusercontent.com/11736711/113946700-df8b6600-97bd-11eb-937a-c93d0fc72f42.png)

Both endpoints return suspiciously large `instanceTypes` and `priceComponents` provider records.

**Comment by hkandala** [comment]
I realized it is because of the newly added properties (instanceTypes and priceComponents) in Provider.java. This was added as to provide bidirectional relationship (@OneToMany) to access all instanceTypes and priceComponents of a given provider. There are two possible fixes:
1. Add @JsonIgnore on these two properties to ignore them when converting to json. As the default FetchType is Lazy, all those values will not be queried too.
2. Remove the properties as currently there are no usages for them and it was added just for easier access in future use cases.
