### ISSUE TITLE
[Jepsen] Concurrent create-table calls can result in "Table Not Found"

### ISSUE THREAD

**Issue by aphyr** [YugaByte/yugabyte-db#798]
On Yugabyte 1.1.10.0, when two or more threads create a keyspace, create a table in that keyspace, then insert a record into that table concurrently, inserts can throw `Table Not Found` errors, even though the call to create that table completed successfully just prior. For instance, this code from the Jepsen bank test reliably throws when creating accounts, unless execution is restricted to a single thread at a time:

```clj
      (cql/create-keyspace conn keyspace
                           (if-not-exists)
                           (with
                             {:replication          
                              {"class"              "SimpleStrategy"
                               "replication_factor" 3}}))
      (info "Creating table") 
      (cassandra/execute conn (str "CREATE TABLE IF NOT EXISTS " keyspace "." table-name                           
                                   " (id INT PRIMARY KEY, balance BIGINT)"
                                   " WITH transactions = { 'enabled' : true }"))
      (dotimes [i n]
        (info "Creating account" i)
        (cql/insert-with-ks conn keyspace table-name {:id i :balance starting-balance}))))
```

@kmuthukk suggests that this might be a case where a concurrent call to create-table observes another create-table in process, and returns immediately, without blocking for the table to be completely ready.

**Comment by hectorgcr** [comment]
With the YugaByte cassandra java driver (https://github.com/YugaByte/cassandra-java-driver) this issue doesn't happen. Before an insert, our driver issues an RPC to the master to get all the tablet location along with the key ranges they serve so that it can send the request to the yb-tserver that is the leader of the tablet that contains the key for our insert statement. If one of the tablets is not ready yet, the master returns an error. Our driver then does a retry in a few seconds. In other words, even though the `CREATE TABLE IF NOT EXISTS` returns before the tablets are ready for writes, the master will not return the list of tablet servers until all the tablets are ready, so the `INSERT` will be delayed until then.

Here is part of the log immediately after an insert statement and before the tablets are ready:
```
W0213 00:54:00.757200 145428480 table-internal.cc:169] Error getting table locations: Service unavailable (yb/master/catalog_manager.cc:6245): Tablet not running, retrying.
2019-02-13 00:54:01,793 (cluster1-reconnection-0) [ERROR - com.datastax.driver.core.ControlConnection$1.onConnectionException(ControlConnection.java:176)] [Control connection] Cannot connect to any host, scheduling retry in 8000 milliseconds```

**Comment by aphyr** [comment]
I can observe this reliably with com.yugabyte/cassandra-driver-core, version 3.2.0-yb-19, via Yugabyte's fork of Cassaforte. Is it possible that there's a different version of Yugabyte's cassandra java driver which works differently? Or that Cassaforte is bypassing some safety code you've added?

**Comment by hectorgcr** [comment]
@aphyr never mind. It was a timing issue. I've been able to reproduce it in a unit test. I'll be submitting a fix soon.

**Comment by aphyr** [comment]
Glad to hear it! :)
