### ISSUE TITLE
[Docs] HTAP capabilities

### ISSUE THREAD

**Issue by hackintoshrao** [YugaByte/yugabyte-db#815]
It would be great to understand the nature and limitations of HTAP workloads for YB DB through documentation and example applications. This will give a better understanding of the set of HTAP workloads for which YB would be suitable. This will immensely help system architects when YB is also part of the application stack.

**Comment by rkarthik007** [comment]
Hi @hackintoshrao,

We have since made a lots of progress - but overwhelming request from users has been for OLTP. However, YCQL works well with Spark Streaming, Kafka, Presto, etc.

We have added a write up on the trade-offs of YugaByte DB when compared with various general areas: https://docs.yugabyte.com/latest/introduction/#what-are-the-trade-offs-involved-in-using-yugabyte-db

I am closing this issue, please feel free to open another issue if you have other questions. Also, please join our Slack Community since some of these are very relevant discussions: https://www.yugabyte.com/slack
