### ISSUE TITLE
Unable to start master after killed during first start

### ISSUE THREAD

**Issue by goranc** [YugaByte/yugabyte-db#832]
I'm working on POC for cluster with 4 nodes on bare-metal servers with Centos 7 OS.
When start single master for the first time after install, service is up and running.
If I kill process I'm not able to start service again, but with error and automatic shutdown.
I'm not adding any new instances just one master node. 
```
I0128 16:45:19.049883 68949 master_main.cc:93] Starting Master server...
I0128 16:45:19.051587 68949 webserver.cc:147] Starting webserver on 0.0.0.0:7000
I0128 16:45:19.051601 68949 webserver.cc:152] Document root: /opt/yugabyte/yugabyte-1.1.9.0/www
I0128 16:45:19.051887 68949 webserver.cc:239] Webserver started. Bound to: http://0.0.0.0:7000/
I0128 16:45:19.052076 68949 rpc_server.cc:167] RPC server started. Bound to: 0.0.0.0:7100
I0128 16:45:19.054144 68977 sys_catalog.cc:198] Trying to load previous SysCatalogTable data from disk
E0128 16:45:19.055213 68977 master.cc:222] Master@0.0.0.0:7100: Unable to init master catalog manager: Not found (yb/util/env_posix.cc:1011): Unable to initialize catalog manager: Failed to initialize sys tables async: Unable to load consensus metadata for tablet 00000000000000000000000000000000: /data05/yb-data/master/consensus-meta/00000000000000000000000000000000: No such file or directory (error 2)
E0128 16:45:19.055485 68949 main_util.cc:22] Not found (yb/util/env_posix.cc:1011): Unable to initialize catalog manager: Failed to initialize sys tables async: Unable to load consensus metadata for tablet 00000000000000000000000000000000: /data05/yb-data/master/consensus-meta/00000000000000000000000000000000: No such file or directory (error 2)
I0128 16:45:19.055583 68949 master.cc:265] Master@0.0.0.0:7100 shutting down...
I0128 16:45:19.067188 68949 master.cc:269] Master@0.0.0.0:7100 shutdown complete.
```
g.c.

**Comment by kmuthukk** [comment]
Hi @goranc 

I presume you are trying to start a 4-node cluster, with the default/recommended replication_factor (RF=3). Looks like the master is binding to the 0.0.0.0 address. In this setup, you would need to start yb-master on 3 servers (because RF=3), and yb-tservers on all the nodes (in your case 4).

See this section as an example:

https://docs.yugabyte.com/latest/deploy/manual-deployment/start-masters/

Each master should now about the other masters via the `master_addresses` argument

--master_addresses=172.151.17.130:7100,172.151.17.220:7100,172.151.17.140:7100

Once the 3 masters are started, the cluster is formed. At which point, you can then start the 4 yb-tserver processes.

Feel free to share the full command line for the yb-master and yb-tserver that you are trying to create the cluster with.

If you need to wipe out an old cluster (that was not created successfully), you can simply delete everything under the /data05/yb-data directory you are using for storage under all the nodes.

**Comment by goranc** [comment]
Thanks for explanation, 
it is as I expected that will be the reason, that we have to setup functional cluster with all nodes needed for specific replication factor (in this case is 3 as you noted)

I'm still expecting that startup script will take care of leaving node in workable state even the cluster is not functional, at least to clean itself if the boot-strapping cluster process is not finished, or have specific command to initiate cleanup of the node.
Ok, we can have documented steps how to do that manually and that will also be acceptable.

I'm also missing systemd yugabyte.service script for manual installation on linux servers, so we can have standard service for on-premise cluster, yes it is easy to write but just nice to have.

About binding to specific address (not all interfaces as with 0.0.0.0) I suppose that we need to specify address for all or some of parameters :
--rpc_bind_addresses
--server_broadcast_addresses
--webserver_interface

g.c.

**Comment by kmuthukk** [comment]
Let's say your 3 masters are set in this environment variable:
```
export MASTER_RPC_ADDRS="$MASTER1:7100,$MASTER2:7100,$MASTER3:7100"
```

Then, for each yb-master please pass these. Here $IP is the IP of *that* master.
```
     --master_addresses=$MASTER_RPC_ADDRS
     --fs_data_dirs=$DATA_DIRS
     --rpc_bind_addresses=$IP:7100
     --webserver_interface=$IP 
```
And for yb-tserver please pass these, 
```
      --tserver_master_addrs=$MASTER_RPC_ADDRS
      --fs_data_dirs=$DATA_DIRS
      --rpc_bind_addresses=$IP:9100
      --cql_proxy_bind_address=$IP:9042
      --redis_proxy_bind_address=$IP:6379
      --webserver_interface=$IP
```

**Comment by bmatican** [comment]
@goranc wanted to follow-up on this, as we've since finalized #1575, which should guarantee a clean slate across potentially failed master startups.

As for a systemd unit file, we are undergoing work for #1019 and would expect to have those as part of those installers automatically!

Closing this for now, feel free to re-open if you still have any open questions.
