### ISSUE TITLE
[Platform][UI] Create Universe should auto-populate dropdown for provider and region

### ISSUE THREAD

**Issue by kc-yb** [yugabyte/yugabyte-db#8517]
The Create Universe screen needs enhancement when showing dropdown list for provider and region. For example, if there is only one provider with one region, the drop down list is still unfilled - it should be auto populated with some provider/region - based on some criteria - for ex: alphabetically.

Or an advanced feature - like default config provider and default region (like shopping apps - where you can have multiple addresses and one can be your default) - it helps reduce the number of clicks required to create the universe.

**Comment by kc-yb** [comment]
[
![Region-Screenshot](https://user-images.githubusercontent.com/18676881/118761687-76a20e00-b892-11eb-8e14-9573202d6ef3.png)
![Provider-screenshot](https://user-images.githubusercontent.com/18676881/118761692-786bd180-b892-11eb-8dd3-a28ad710796b.png)

](url)

**Comment by rajmaddy89** [comment]
Can you please assign this issue to me ?

**Comment by rajmaddy89** [comment]
In case of In Region Dropdown for issue 8517, its a little bit tricky to auto-populate. Here is the reason

It is multi select type and uses React-Select component,

when you assign the value prop it points to a default value but it will not change at all. This is because when we try to hardcode it say like universeRegionList[0], we do an anti-pattern in React

This is because you've tied the value prop directly to universeRegionList[0], which doesn't change. Better to tie it to a state variable that you default to the option, and have your onChange update the state variable.

React is intended to have an unmount happen from a parent to child relationship. Now if you want a child to unmount itself, you can simulate this with a state change in the parent that is triggered by the child. let me show you in code. So the value must be tied to state variable and can be re-rendered by the parent component and this is how React default value works.

This is the reason why I have tied the value prop to state variable

**Comment by rajmaddy89** [comment]
Reference to PR: https://github.com/yugabyte/yugabyte-db/pull/10028
