### ISSUE TITLE
Monitoring UPSERT using gocql

### ISSUE THREAD

**Issue by ahmedsaifreza** [YugaByte/yugabyte-db#857]
Trying to determine whether the UPDATE is actually updating any record or INSERT as new record. In cqlsh I get the `[applied]` column returned `true` or `false` when I use `IF EXISTS`. But the following code in go gives me the error `gocql: not enough columns to scan into` which means `[applied]` column is not being returned after the Query Execution. 

`err := session.Query(UPDATE ybdemo.employee SET name = ?, age = ?, language = ? WHERE id = ? IF EXISTS, employee.Name, employee.Age, employee.Language, employee.Id).Scan(&flag)`

**Comment by kmuthukk** [comment]
hi @ahmedsaifreza 

See this example:

https://github.com/gocql/gocql/blob/c53c3654dc8acfc0ace976e1535cb0b8abb027a4/cassandra_test.go#L348

Can you try the ScanCAS() method of Scan() and it seems to return a 2-tuple with applied & error status. [The CAS (stands for compare-and-swap)... because these operations like IF EXISTS or IF NOT EXISTS do an atomic check.]

Unlike Apache Cassandra, these CAS operations (like IF EXISTS, IF NOT EXISTS) are done in YugaByte using a single Raft operation rather than 4 network roundtrips.

**Comment by ahmedsaifreza** [comment]
@kmuthukk  ScanCAS worked ! 

```
var flag string = ""
if applied, err := session.Query(`UPDATE ybdemo.employee SET name = ?, age = ?, language = ? WHERE id = ? IF EXISTS`,
        employee.Name, employee.Age, employee.Language, employee.Id).ScanCAS(&flag); err != nil {
            fmt.Println(err)
	} else if applied {
        fmt.Println(flag)
		
    }

```

**Comment by kmuthukk** [comment]
Thx for confirming, and providing an example @ahmedsaifreza .
