### ISSUE TITLE
Tablet server should be able to evict block cache entries dynamically if the memory on the system is running low

### ISSUE THREAD

**Issue by mbautin** [YugaByte/yugabyte-db#860]
Sometimes other processes might consume a lot of memory on the node. In these situations, to avoid the OOM killer stepping in, the tablet server should proactively evict block cache entries. Alerting the administrator should happen separately using healthcheck scripts running on the machine.

**Comment by spolitov** [comment]
@kmuthukk, could you please clarify your opinion about this feature.

**Comment by kmuthukk** [comment]
@spolitov - 

IMO, we can defer this for later. Each component should stay within its safety limit. If something is causing an OOM, then that's more a symptom of:

* a memory leak in the system, or 
* some sub-component not respecting its quota, or
* rate limiting (based on memory thresholds) not working correctly

So would rather prioritize the above, rather than pro-actively evicting memory from another component. Doing so can potentially mask a genuine issue. Longer term we can consider doing this-- but for now, in terms of prioritization, I think we can defer this work for now, as it also needs a fair bit of extra testing cycles.

**Comment by spolitov** [comment]
Implemented as part of #1795
