### ISSUE TITLE
[docdb] Group tservers by availability zone in the master leader tablet servers page

### ISSUE THREAD

**Issue by rao-vasireddy** [yugabyte/yugabyte-db#8770]
At the moment the tservers are listed randomly in the tablet servers page in the master leader UI. 
Its nice to have them grouped by availability zone to find the nodes easily on large clusters.

**Comment by Tigojiang** [comment]
@rao-vasireddy Hello! I am a first-time contributor, and may I pick up this task? Would you mind me pointing out the files that need changes and the files that I should refer to? Thank you!

**Comment by bmatican** [comment]
welcome to the Yugabyte repo @Tigojiang !

the main file you'd need to change is `src/yb/master/master-path-handlers.cc`

in order to test this, you would need different availability zones on your tablet servers, see https://docs.yugabyte.com/latest/explore/linear-scalability/scaling-transactions/ as an example of how to pass master and tserver flags -- you will need to pass different tserver flags, for placement_cloud / placement_region / placement_zone, to see the potential different groupping

cc @hulien22 @rahuldesirazu if you can help on any followup input / PR review

**Comment by Tigojiang** [comment]
@hulien22 @rahuldesirazu 
Hello! Upon looking at the source code, the tablet server comparator actually compares the zone. So I am wondering about what does grouping them by availability zone stand for? Thank you for that information!
<img width="629" alt="截屏2021-06-25 下午5 41 31" src="https://user-images.githubusercontent.com/54599335/123405632-97215e80-d5dc-11eb-8a98-d89d32de4e64.png">

In the following test, there are different servers from different zone. As we can see, they are first grouped by cloud, then region, then zone. Do we need to group them firstly by zone and then others? Thank you!
<img width="1173" alt="截屏2021-06-25 下午5 39 21" src="https://user-images.githubusercontent.com/54599335/123405435-67725680-d5dc-11eb-9ec3-cfc05f9de9ef.png">
<img width="1142" alt="截屏2021-06-25 下午5 39 27" src="https://user-images.githubusercontent.com/54599335/123405458-6e00ce00-d5dc-11eb-88bf-ebb27b5bdcf5.png">

**Comment by bmatican** [comment]
@Tigojiang oh interesting, perhaps this was done as part of some previous usability work, sorry about that

cc @rao-vasireddy do you know if this is already done and we just didn't attach the right

**Comment by Tigojiang** [comment]
@bmatican Sure, thank you! If this is done, then we can close it. And may I pick another one to start?
