### ISSUE TITLE
[YSQL] Backups break if there are tables with the same name across different schemas

### ISSUE THREAD

**Issue by tsmull-11** [yugabyte/yugabyte-db#8804]
If a user creates multiple schemas and then within each of those schemas they create tables that the same name as in other schemas backups will break with the following error. 

`2021-06-07 20:40:04,122 [INFO] from com.yugabyte.yw.common.ShellProcessHandler in TaskPool-MultiTableBackup(f7c62287-0f46-4fdf-a793-831ec5b498b0)-1 - 2021-06-07 20:39:58,084 ERROR: Failed to run command [[ ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i /opt/yugabyte/yugaware/data/keys/ba2f894b-29b0-4561-8314-ddfd3c1d59ed/yb-cloud-keepworks-key.pem -p 54422 -q yugabyte@10.5.12.4 'cd / &&  bash -c '"'"'/home/yugabyte/master/bin/yb-admin --master_addresses 10.5.12.3:7100,10.5.12.4:7100,10.5.12.5:7100 --certs_dir_name /home/yugabyte/yugabyte-tls-config/ list_tablets ysql.yugabyte schema_migrations 0'"'"'' ]]: code=1 output=Error: Invalid argument (yb/tools/yb-admin_client.cc:375): Namespace 'ysql.yugabyte' has multiple tables named 'schema_migrations', specify table id instead`

**Comment by OlegLoginov** [comment]
YSQL tables with the same name across different schemas" are not supported now. It's not a bug, it was never supported due to the current backup implementation limits.
We need a mapping 'OLD TABLE UUID' -> 'NEW TABLE UUID' for all restored tables.
Now the mapping is created via searching by table name in CatalogManager internal maps. But the info does not have the YSQL Schema name. So, in such case the searcing returned 2 tables (DB is the same, name is the same, schema is not available & so ignored).
There are several ways how to resolve it:
Add the 'YSQL schema' name into the Table Entry in the SysCatalog (in CatalogManager).
In YSQLDump after every CREATE TABLE - print old OID (hardcoded), print the new table OID (via an additional SELECT to a PG sys table). Parse the OIDs in yb_backup, convert it into UUID - so we can create the needed 'OLD TABLE UUID' -> 'NEW TABLE UUID' mapping.
CC: @mihnea @bogdan

**Comment by jpiscitella** [comment]
different message but same concept on restoring snapshots

Import snapshot : 56155114-4d6f-42ea-a4f4-866340e69cc6
$yb-admin import_snapshot ${YSNAPSHOT_LOCATION}/${YSNAPSHOT}.snapshot database > ${YSNAPSHOT_FILE}

Error running import_snapshot: Invalid argument
(yb/master/catalog_manager_ent.cc:1159): Unable to import snapshot meta file
/mnt/data/yugabyte/snapshots//56155114-4d6f-42ea-a4f4-866340e69cc6/56155114-4d6f-42ea-a4f4-866340e69cc6.snapshot:
Found 2 YSQL tables with the same name: test -
0000400700003000800000000000407f, 00004007000030008000000000004085:
SNAPSHOT_FAILED (master error 23)

**Comment by kkg-yb** [comment]
@m-iancu  is there any modifications needed on the platfrom side to complete this? If so could you details this out please?

**Comment by jaki** [comment]
This is done.  Reopen if not, @OlegLoginov.
