### ISSUE TITLE
[YSQL]: Support of ALTER TABLE ALTER COLUMN type VARCHAR

### ISSUE THREAD

**Issue by p-null** [yugabyte/yugabyte-db#8902]
Jira Link: [DB-2223](https://yugabyte.atlassian.net/browse/DB-2223)
I was trying to convert a column from type `character(64)` to `varchar(64)`  

yb version: `yugabytedb/yugabyte:2.5.3.1-b10`

Running the query in ysql:

```
alter table public.collection alter column answer type varchar;
ERROR:  This ALTER TABLE command is not yet supported.
```

**Comment by jaki** [comment]
I didn't look at the code, but I tested both non-pk and pk, and sst_dump shows that the on-disk format is the same between the two types, so this should be straightforward.

**Comment by jaki** [comment]
It's strange that char and varchar seem to be stored the same variable-length way.  It's probably too late to change that to match https://www.postgresql.org/docs/current/datatype-character.html.

@p-null, if your only goal is to potentially reduce disk space with this alter, I don't think that will happen.  However, it is possible that processing will be different in the pggate/postgres layer.

**Comment by p-null** [comment]
Hi @jaki , thanks for following up.
> the on-disk format is the same between the two types, so this should be straightforward.

Can you expand more on this? What is straightforward?

> It's strange that char and varchar seem to be stored the same variable-length way.

That's just an example, I am not able to convert `char` to `varchar` with a different length neither.

> However, it is possible that processing will be different in the pggate/postgres layer.

If I understand correctly, it's implying that the type conversation in yugabyte is implemented at a different layer than postgres. And that's what leads to this behavior?


Actually there are other types of conversation are not supported, e.g.
```
ALTER TABLE "public"."entity_aggregation" ALTER COLUMN "entity_type" TYPE int2;
ERROR:  This ALTER TABLE command is not yet supported.
```
`entity_type` was `int` before.

**Comment by jaki** [comment]
@p-null, I was mostly speaking to myself and whoever will pick this up.

> What is straightforward?

A fix for this should be straightforward.

> it's implying that the type conversation in yugabyte is implemented at a different layer than postgres.

Yes, there's another layer: DocDB types.  char and varchar map to the same DocDB (variable-length) string.  int4 and int2 map to the same DocDB int32 (see issue #7971).  So you're being stopped from doing these alters by checks at a higher level (pggate/postgres), and those checks can just be relaxed to support these.

However, doing these changes further entrenches us into these potentially bad storage layouts so that fixing them might be more difficult in the future.
