### ISSUE TITLE
[docdb] Improve master load balancer state presentation.

### ISSUE THREAD

**Issue by tylarb** [yugabyte/yugabyte-db#8979]
It's a common point of confusion that the "is load balanced" check box in the master tablet http endpoint doesn't actually mean that the system is load balanced - it only indicates the state of the load balanced.

This can be improved in several ways 

1. Change the syntax of this specific check to "load balancer running"
![image](https://user-images.githubusercontent.com/20615828/122591771-716ee500-d031-11eb-88c1-32b08d51b41d.png)

2. if possible, make the "is load balanced" check mean what it is says (i.e. is the load actually balanced - this can be greyed out as "unknown" if the load balancer is disabled) 

3. Add a "is load balancer enabled" check

**Comment by bmatican** [comment]
@tylarb what's the difference between 2) and 3) ? do you envision it as just having 3 states? not enabled / enabled and balanced / enabled and busy?

**Comment by tylarb** [comment]
I think definitely a separate "load balancer enabled" flag. Make sure its accurately turned on.

Then maybe a second field , "load balancer state" could be
-  "running" or "working" or "balancing" 
- "balanced"
- "unknown" (because the balancer is off in the first check, presumably) 

Is there another state? Unbalanced but the load balancer is on but isn't working or moving for some reason?

**Comment by tylarb** [comment]
Maybe it helps on what I'd like to communicate - which is simply:

Is load balancer on?  [ Yes or no ] 

If yes, is my cluster already balanced or is it working to get there? 

Bonus points for "how long will it take to become balanced" I think, or "balancing at a rate of 3 tablets/min" so I can calculate how many hours it might take to complete or something.

**Comment by bmatican** [comment]
Hey @es1024 , I think this would get you familiar a bit with the load balancer (LB) side of the master, as well as some gflag usage.

There is a flag to enable/disable the LB + some RPC way to turn it on off, so ideally we already expose this as state from the LB itself and can use that for the on/off logic.

If on, we should already have logic for LB being active or not, through some Idle mechanic. To exercise that, you could try out a local cluster + a create table + adding a new server, in order to see the LB moving tablets around.

Feel free to reach out to @hulien22 or @sanketkedia for more input.

The bonus points of information about the LB rate of progress might be a bit trickier, as we currently have too many knobs to control that. I think Sanket wanted to setup a somewhat more involved page for displaying more debug info from the LB.

**Comment by es1024** [comment]
Load balancer state presentation has been split into "is load balancing enabled?" and "is everything load balanced?" in 189a3a4.
