### ISSUE TITLE
Metrics endpoint for determining server loadedness

### ISSUE THREAD

**Issue by larry1234567** [yugabyte/yugabyte-db#9063]
We would like to have a metrics endpoint so that clients can determine how loaded the servers are and throttle/backoff requests accordingly. Currently, the `/prometheus-metrics` endpoint returns too many metrics, most of which are irrelevant to our use case. Ideally, we want a way to only obtain the metrics that we care about, which are rpcs_in_queue, rpc_{in,out}bound_calls_alive, and possibly some other metrics on client latency and cpu time.

Possible ways to do this are to:
- Expose a new endpoint that exposes just loadedness metrics in a data format like json.
- Allow HTTP parameters on the `/prometheus-metrics` endpoint so that clients can filter the specific metrics that they need.

**Comment by danielmh0** [comment]
For completeness, including the maximum RPC queue size (as specified in flag/config) would be nice.

**Comment by kmuthukk** [comment]
* One option would be to allow specifying a list of metrics of interest (rather than getting all the metrics)
* While doing this, we should also add ability to control/limit the max number of metrics exported (and exclude less relevant metrics if the number of metrics exported are too many). This mainly is an issue for table level metrics when the number of tables is very large.

**Comment by amitanandaiyer** [comment]
Looks like we have this for /metrics but not for /prometheus-metrics

https://github.com/yugabyte/yugabyte-db/blob/d1a81c33fadbc5f4a3d3f2c5618ceeb53693236c/src/yb/server/default-path-handlers.cc#L243

you'd query this as 

http://<node>:9000/metrics?metrics=mem_tracker_Reg

**Comment by bmatican** [comment]
@amitanandaiyer oh nice, this must have been part of the work that Raju ported over from Kudu as part of the metrics level framework!

Thoughts on how easy it would be to extend further to the prometheus side? I suspect the problem there is the aggregation?

**Comment by amitanandaiyer** [comment]
I think this is there from the start. Raju added a http param for specifying level=?? the other params are there since the initial port.

Should be straighforward to do the similar filtering at the prometheus level. But that will be a code change. If/when we are doing that, probably also worth adding more params to just query for specific tables?

**Comment by amitanandaiyer** [comment]
committed https://github.com/yugabyte/yugabyte-db/commit/f7438c2cc5e119c3f6851b72472f2a742fa9be30
