### ISSUE TITLE
Check if the leader is still valid immediately before replying to a leader-only RPC request or queuing a Raft record for replication

### ISSUE THREAD

**Issue by mbautin** [YugaByte/yugabyte-db#915]
Theoretically, a YugaByte DB leader could read the current clock, pause, then wake up and serve requests, believing its lease were still valid. This is unlikely to happen in practice. However, we would still like to have an additional safety net of checking the leader lease validity not just in the beginning of the request, but also at the latest possible point in the request.

**Comment by aphyr** [comment]
I'm not sure if this would necessarily pose a problem, so long as you check the clock *after* receiving the request--because the time window that the request was outstanding would cover a time when that leader *was* valid, and an older read *would* therefore be linearizable, not stale. What do you think?

**Comment by mbautin** [comment]
OK, in the scenario described here, the response will still be recent enough for the reader, because it would reflect the latest state as of when the read request started, so I'll close this issue.
