### ISSUE TITLE
[YCQL] KeySpace Names - compatibility

### ISSUE THREAD

**Issue by barum** [YugaByte/yugabyte-db#916]
FYI:
in Cassandra  i can name a Keyspace "static" or "references".
However in YCQL I can not create a Keyspace called "static" or "references".

This is a compatibility issue.

**Comment by kmuthukk** [comment]
@nocaway 

Would the work for this be similar to what's needed for what you are doing right now for:
 https://github.com/YugaByte/yugabyte-db/issues/835?

**Comment by barum** [comment]
Yes but for Keyspace Name.

**Comment by nocaway** [comment]
@kmuthukk : For keywords, we'll go through them on case-by-case basics.
- YugaByte reserves more keywords than Apache CQL because we planned to extend the language to support more features. Some of the keywords will be make unreserved, but not others.
- In this case, "STATIC" will be made unreserved keyword as specified by Apache CQL.
- REFERENCES will be removed from keyword list as its associated feature will not be added to the language.

'cc @barum

**Comment by nocaway** [comment]
This has been fixed by commit https://github.com/YugaByte/yugabyte-db/commit/d281ca04097474ffaf69dcf4c12bbecc3b8b710e

'cc @barum

**Comment by kmuthukk** [comment]
Thanks @nocaway for taking care of this quickly!
