### ISSUE TITLE
[YSQL] Support a way to read from local partitions first

### ISSUE THREAD

**Issue by rkarthik007** [yugabyte/yugabyte-db#9178]
In a geo-partitioned scenario where a particular row key is pinned to only one partition, we need a way to query by the primary key (without specifying the partition column value in the where clause) from the local region. This should be achievable by querying the parent table (without having to hit the partition table directly).

**Comment by deeps1991** [comment]
@rkarthik007 Please can you provide more details about this requirement?
Is this an ask for:
1) Uniqueness across all partitions (something we do not support today) (OR)
2) If partition key is not specified in a query, always look in the local partition first. But here we would also need some way of knowing that this key is unique across all partitions (else we would not know that once we find one row in the local partition, we can stop looking). (OR)
3) Is all that this needed just a shortcut to query the local partition? 
something like: SELECT * FROM parent_partitioned_table LOCAL; 
(which will compute which partition is the local partition and only return keys from there)

**Comment by m-iancu** [comment]
@deeps1991 -- @rkarthik007 can confirm, but from what we discussed, I think some variant of option 3 (i.e. syntax to be determined) should be sufficient for now.

**Comment by rkarthik007** [comment]
Yes, some variant of option 3 should be good - but can we make the retry transparent? Meaning:
* Read from the local partition first, if there is a response then we're done
* If not, read from remote partitions to check if we get a response
Otherwise, the user needs to do the second step above.

Eventually, the ask will be to support 1, so we can truly read from local partition first and check.

**Comment by deeps1991** [comment]
Since this is an urgent requirement, I think we could do the following:
1) Create a new yb function that can return the local partition name, so their queries might look something like:
SELECT * from yb_local_partition(test_partitioned_table);
2) For the longer term fix, first ensure that the executor runs the query on the local partition first. Maybe this could even be generic behavior? (cc @m-iancu )
3) Add syntax support that specifies that the required results are present in a single partition (this means that if the executor finds any results in any partition, it does not need to look at the other partitions)

@rkarthik007 Any rules on what is constituted as the local partition?
I thought we could look for partitions associated with a tablespace in the following order.
If the node is in zone us-west-1a, the local partition will be the one associated with the tablespace that:
i) constrains all replicas to zone us-west-1a
ii) If not present, find partition that has at least one replica in zone us-west-1a (and is constrained within region us-west-1)
iii) If not present, the partition constrained to the region us-west-1
iv) If not present, return error.

**Comment by deeps1991** [comment]
Closing this in favor of https://github.com/yugabyte/yugabyte-db/issues/10477 which also tracks future improvements in this area
