### ISSUE TITLE
The lock is not released after program exit

### ISSUE THREAD

**Issue by jenny-cheung** [yugabyte/yugabyte-db#9324]
Dear developers:
               First, thank you for your checking!  The lock pthread_mutex_lock(&init_mutex); is not released if the pthread_create fails to create the thread. The fix is to insert `pthread_mutex_unlock(&init_mutex);` before exit(1).

https://github.com/yugabyte/yugabyte-db/blob/d28d82e8c48bb068b538a3ea0e5165525e46838d/src/postgres/src/test/thread/thread_test.c#L143

```
int
main(int argc, char *argv[])
{
	/* Hold lock until we are ready for the child threads to exit. */
	pthread_mutex_lock(&init_mutex);

	rc = pthread_create(&thread1, NULL, (void *(*) (void *)) func_call_1, NULL);
	if (rc != 0)
	{
		fprintf(stderr, "Failed to create thread 1: %s **\nexiting\n",
				strerror(errno));
		exit(1); // end without releasing the lock &init_mutex
	}
	rc = pthread_create(&thread2, NULL, (void *(*) (void *)) func_call_2, NULL);
	if (rc != 0)
	{
		/*
		 * strerror() might not be thread-safe, and we already spawned thread
		 * 1 that uses it, so avoid using it.
		 */
		fprintf(stderr, "Failed to create thread 2 **\nexiting\n");
		exit(1); // end without releasing the lock &init_mutex
	}
}
```

Best,

**Comment by tedyu** [comment]
@jenny-cheung 
Do you want to send a pull request ?

Thanks

**Comment by jenny-cheung** [comment]
@tedyu Sure. I will send a pull request soon.

**Comment by d-uspenskiy** [comment]
Hello @jenny-cheung could you please describe the impact of the issue? What is going wrong without your fix?
As you know YugaByte uses postgres fork and this code belong to postgres native code. Latest version of postgres sources has same code now. There is no mutex unlocking before exit

**Comment by jenny-cheung** [comment]
@d-uspenskiy Hi, the impact is that the lock is not correctly released before exit. It is not a very harmful bug( e.g., resource leak, deadlock) since the program exits and all of the program resources will be cleaned up by some common OS. However, other OS systems (e.g., embedded systems) do not automatically free some resources at the exit. It is a good manner for resource management. Adding the unlock statement adds symmetry, so the code looks better. Also, the debugger would not warn this case : )

**Comment by jaki** [comment]
Note, upstream postgres commit 8a2121185b26d7eb439860c7a96a08c0aa3c8508 moved the code location:

```
 {src/test/thread => config}/thread_test.c | 30 ++++--------------------------
```

**Comment by d-uspenskiy** [comment]
Hi @jenny-cheung it looks like there is no error which should be fixed due to the following:
1. The `init_mutex` is local mutex (i.e. non shared among different processes. Please check `pthread_mutexattr_setpshared` or `PTHREAD_PROCESS_SHARED` for details). In case any thread calls `exit(...)` current process will be terminated. As a result there are no parties who can use/access `init_mutex` after calling of `exit(...)` by any thread.
2. The `pthread_mutex_unlock` function doesn't free the `init_mutex` resource. For the purpose of freeing mutex the  `pthread_mutex_destroy` function is designed. But this function is not used here as the `init_mutex` is the static variable. Memory will be released automatically on any OS, and it is the only thing that should be done for proper resource management here.

I think it is enough reason to close the issue without any changes in code.

**Comment by jenny-cheung** [comment]
@d-uspenskiy OK. Thank you for your detailed reply.
