### ISSUE TITLE
[YSQL] Avoid explicit row locking on index tuples in index scan in SERIALIZABLE

### ISSUE THREAD

**Issue by pkj415** [yugabyte/yugabyte-db#9543]
Jira Link: [DB-2138](https://yugabyte.atlassian.net/browse/DB-2138)

```
CREATE TABLE test (k int PRIMARY KEY, v1 int, v2 int);
CREATE INDEX idx ON test (v1) INCLUDE (k);
INSERT INTO test VALUES (1, 4, 1);
SET yb_debug_log_docdb_requests TO on;
BEGIN ISOLATION LEVEL SERIALIZABLE;
SELECT k, v1 FROM test WHERE v1=4 FOR UPDATE;
```

Expected:
Lock on the "User table" only, as defined in the :7000/tables dashboard.

Result:
Locks are taken on both the "User table" and an "Index table". They look like this: `row_mark_type: ROW_MARK_EXCLUSIVE wait_policy: WAIT_BLOCK` in the postgresql log file.

Notes:
Previously, this bug occurred in other isolation levels, but on the master branch I've only been able to make it happen in isolation level SERIALIZABLE. The fix for the non-serializable cases was in c9fcd931c6fdb022ad32e06a5d2ce3024acb11ee.

There is a related issue: #19036.

[DB-2138]: https://yugabyte.atlassian.net/browse/DB-2138?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by foucher** [comment]
First off, the code has changed. In order to have locks taken in an isolation level other than SERIALIZABLE, you have to have one or more rows to lock. Add that to the repro steps. For example:
```
insert into test values (1,4,1);
```

Still, I'm unable to reproduce the issue using the repro steps. I see locks taken only on the main table. It's possible the directly-referenced issue was fixed by c9fcd931c6fdb022ad32e06a5d2ce3024acb11ee.

I talked to Piyush about this issue. He suggested to check what happens at isolation level SERIALIZABLE, and sure enough, SERIALIZABLE does exhibit this issue. I will work on fixing that issue. Index scans for SERIALIZABLE should not add row marks or wait policy if they aren't on the main table.

**Comment by foucher** [comment]
I verified the original repro steps (on a row that exists) were fixed by c9fcd931c6fdb022ad32e06a5d2ce3024acb11ee.

**Comment by foucher** [comment]
I rewrote the issue description.

**Comment by pkj415** [comment]
This seems like a non-issue to me: locks need to be taken on both the index and the main table in serializable isolation. Refer #7522 for more details.
