### ISSUE TITLE
percpu_rwlock assert sched_getcpu() within the range of visible CPUs is broken on OpenVZ

### ISSUE THREAD

**Issue by FranckPachot** [yugabyte/yugabyte-db#9619]
Jira Link: [DB-1453](https://yugabyte.atlassian.net/browse/DB-1453)
In https://github.com/yugabyte/yugabyte-db/blob/master/src/yb/util/locks.h#L201 we have the following assert: `CHECK_LT(cpu, n_cpus_);` that checks that the processor we are scheduled on is within the range visible from `/sys/devices/system/cpu/present`

This, on some hypervisors like OpenVZ, fails because sched_getcpu() maps all host processors, but /sys exposes only the visible range. All details here: https://dev.to/yugabyte/visible-number-of-cpu-on-openvz-2h7d

**Comment by bmatican** [comment]
I believe we've seen something like this in robin.io as well, but I think the checks are in place because the locks implementation rely on being able to explicitly use a range of cpus.

I think some of this functionality is ported over from chromium, not sure if there's something upstream we could bring in to cover for this here.
