### ISSUE TITLE
[xCluster] : Min Replicated Index not set on restart

### ISSUE THREAD

**Issue by nspiegelberg** [yugabyte/yugabyte-db#9656]
Discovered while debugging an xCluster configuration.  From @tvesely :

> A tablet was bootstrapped (I think due to load balancing) to a new node. When it did, it set the cdc_min_replicated_index to `9223372036854775807`. it looks like during bootstrapping this value may not be initialized yet?

```
17:00 - Created and populated tables
17:20 - Ran yb-admin bootstrap_cdc_producer
17:30 - started backup of PRODUCER data
17:47 - Google restarted/preempted the instance of one of my nodes- during the tserver restart, 
             dozens of tablets had the cdc checkpointed WAL garbage collected
17:50 - Started inserting new data into the backed up tables
23:00 - Finished restore of bootstrap data to the CONSUMER
23:12 - enabled universe replication

```

@nspiegelberg Commentary : We should look for a couple things. 

> [1] Is grabbing the min replicated index + caching it + persisting it thread safe?
> [2] Is `bootstrap_cdc_producer` synchronous?  We should not return from this command until all tablets have persisted their cdc_min_replicated_index in the SysCatalog.
> [3] Is there a race on startup between setting the initial value of cdc_min_replicated_index on a tablet in memory and loading it from disk.  Unlikely, because I believe we persist it on the TabletMetadataPB directly.

**Comment by rahuldesirazu** [comment]
The current BootstrapProducer logic doesn't update cdc_min_replicated_index. And because we only run the background thread (which updates this on each peer every 60s) when the service receives its first call to GetChanges, we don't actually update this until the setup_universe_replication step, by which time the WAL may have already been GC'ed. The fix is to make sure we update each tablet peer synchronously during BootstrapProducer itself.
