### ISSUE TITLE
[docdb] Ensure read restarts work as intended with savepoints

### ISSUE THREAD

**Issue by robertsami** [yugabyte/yugabyte-db#9799]
Note that ybDataSent is not properly accounted for in the lifecycle of subtransactions, so we may improperly allow a read restart even when we have externalized data to the user

**Comment by pkj415** [comment]
Adding example and details to expose the bug -
`
start transaction isolation level repeatable read;
savepoint a; // PushTransaction - ybDataSent of parent txn=0 ybDataSent of current txn=0
select * from test;
savepoint b; // PushTransaction - ybDataSent of parent txn=1 ybDataSent of current txn=0
select * from test; // If a read restart occurs here, we will transparently retry the txn even though data has been sent to the client. This is because ybDataSent is not inherited from the parent txn.
`

**Comment by robertsami** [comment]
@pkj415 if we externalize data in some subtransaction, and then rollback that subtransaction, should we still behave as if we have externalized data in all cases?

if so, as for implementation detail, it might be best to remove ybDataSent state from `CurrentTransactionState` entirely

**Comment by robertsami** [comment]
note these fields which we do not currently update on push:
```
	char	   *name;			/* savepoint name, if any */
	MemoryContext curTransactionContext;	/* my xact-lifetime context */
	ResourceOwner curTransactionOwner;	/* my query resources */
	TransactionId *childXids;	/* subcommitted child XIDs, in XID order */
	int			nChildXids;		/* # of subcommitted child XIDs */
	int			maxChildXids;	/* allocated size of childXids[] */
	bool		startedInRecovery;	/* did we start in recovery? */
	bool		didLogXid;		/* has xid been included in WAL record? */
	bool		ybDataSent; /* Whether some tuples have been transmitted to
				             * frontend as part of this execution */
	bool		isYBTxnWithPostgresRel; /* does the current transaction
				                         * operate on a postgres table? */
	List		*YBPostponedDdlOps; /* We postpone execution of non-revertable
				                     * DocDB operations (e.g. drop table/index)
				                     * until the rest of the txn succeeds */
```

**Comment by pkj415** [comment]
`should we still behave as if we have externalized data in all cases (e.g. regardless of isolation level)`
Yes, that should be the case regardless of the isolation level. Reason being - postgres would trivially behave that way. Trivially because Postgres doesn't worry about retrying internally when possible (say for kConflict errors) and doesn't even face read restarts. So, Postgres never faces this question/ design choice except for in #9587.

And given they made the choice to behave as if data is externalized in #9587, we should extrapolate the same design to these new problems specific to YB.

`note these fields which we do not currently update on push:`
Oh nice - we should scan this list and ponder to check if not updating on push/pop can result in bugs. We should ask some ppl who know in detail about these fields.

**Comment by robertsami** [comment]
Looked into the following fields, which were yb-specific fields added to CurrentTransactionState as top-level transaction state:

```
	bool		ybDataSent; /* Whether some tuples have been transmitted to
				             * frontend as part of this execution */
	bool		isYBTxnWithPostgresRel; /* does the current transaction
				                         * operate on a postgres table? */
	List		*YBPostponedDdlOps; /* We postpone execution of non-revertable
				                     * DocDB operations (e.g. drop table/index)
				                     * until the rest of the txn succeeds */
```

`ybDataSent` is managed appropriately as described in the comment above

`isYBTxnWithPostgresRel` is updated during the parsing of each statement, before any other codepaths which depend on reading from it

`YBPostponedDdlOps` is DDL specific and should not interact with savepoints at all

closing this issue, since we've added tests to ensure the correct behavior w.r.t read restarts and savepoints
