### ISSUE TITLE
[docdb] Geo-partitioning support for the transaction status table

### ISSUE THREAD

**Issue by mbautin** [yugabyte/yugabyte-db#9980]
Jira Link: [[DB-359]](https://yugabyte.atlassian.net/browse/DB-359)
### Phase 1 -- Done
Proof of concept for this work. User should be able to create txn tables manually, control local vs global behavior via a session variable and get appropriate errors when trying to do global work against local transaction tables.

✅ Ability to create new transaction tables with custom placement (#10157)
✅ Ability for a TS to use a local vs global transaction table (#10158)
✅ Session variable to control local vs global transaction table usage (#10159)

### Phase 2 -- Done
Improve usability, by automatically creating tables for the user, by piggybacking on tablespaces, as the means to configure this feature in YSQL. New, local txn tables, will be created on the first table added to a tablespace, either via CREATE TABLE or via ALTER TABLE SET TABLESPACE.

✅ Create txn table on first table in a tablespace (#10783)
✅ Create txn table on first use of ALTER TABLE SET TABLESPACE (#11353)

### Phase 3 -- 2.13
Further improve usability by also removing the local vs global error for the user, allowing them to start in a local context and be able to execute global queries, without receiving an error, by transparently promoting their transaction to a global one.

✅ Automatically promote from local to global transactions when necessary (#10537)

### Future work
⬜️ Support for ALTER TABLESPACE (#11075)
⬜️ Support for deleting local txn tables (#11123)

[DB-359]: https://yugabyte.atlassian.net/browse/DB-359?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by mbautin** [comment]
There are two possible approaches:
1. Specify different placement for different tablets of the transaction status table. Specifying placement per-tablet is a new feature we will need to add.
2. Allow creating multiple transaction status tables. We can already specify placement per table. We will just need to learn to select the status tablet to use out of all the available transaction status tables.

From a discussion with @spolitov, the second approach (multiple status tablets) seems easier. This will involve periodically refreshing the information about the complete set of transaction status tables/tablets on each transaction client (YBClient).

**Comment by bmatican** [comment]
existing limitations
- we cannot create new txn status tablets

notes from meeting on the topic
- preferable to go with option 2, as we already have per-table placement, but also because we currently cannot add new tablets to the txn table, so this would allow us a clean way of generating new txn tablets
- PG should have some mechanism (session var / gflag), to select if a txn should use an in-region txn status tablet, or a globally distributed one
    - introduce new retriable error (eg: like the txn conflict ones), that we can bubble up to the user, in case a txn starts off as region local, but then touches global tablets
- we will also need to flow the placement information of these tables, from master to tserver, in order to be able to distinguish which tablets are region local vs which are global
- there's also some code where we cache the txn tablets, as we currently expect them to be a fixed set, so this will also have to change

@mbautin @kgupta-yb in case I missed anything

**Comment by bmatican** [comment]
Followup clarification from Sergei, on how any queries to the txn status tablet would be handled, after a txn is started (eg: conflict resolution)
> each transaction has assigned status tablet. and it is stored in transaction metadata, so when we find intent we always know what status tablet should be queried
